package soc

import _ "unsafe"

const EFUSE_WRITE_OP_CODE = 0x5a5a
const EFUSE_READ_OP_CODE = 0x5aa5
const EFUSE_PKG_VERSION_ESP32C3 = 0
const EFUSE_PKG_VERSION_ESP8685 = 1
const EFUSE_PKG_VERSION_ESP32C3AZ = 2
const EFUSE_PKG_VERSION_ESP8686 = 3
