package soc

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

const I_D_SRAM_SEGMENT_SIZE = 0x20000
const I_D_SPLIT_LINE_SHIFT = 0x9
const I_D_FAULT_ADDR_SHIFT = 0x2
const DRAM_SRAM_START = 0x3FC7C000
const IRAM0_VIOLATE_STATUS_ADDR_OFFSET = 0x40000000
const DRAM0_VIOLATE_STATUS_ADDR_OFFSET = 0x3C000000
const SENSITIVE_CORE_X_IRAM0_PMS_CONSTRAIN_SRAM_WORLD_X_R = 0x1
const SENSITIVE_CORE_X_IRAM0_PMS_CONSTRAIN_SRAM_WORLD_X_W = 0x2
const SENSITIVE_CORE_X_IRAM0_PMS_CONSTRAIN_SRAM_WORLD_X_F = 0x4
const SENSITIVE_CORE_X_DRAM0_PMS_CONSTRAIN_SRAM_WORLD_X_R = 0x1
const SENSITIVE_CORE_X_DRAM0_PMS_CONSTRAIN_SRAM_WORLD_X_W = 0x2
const SENSITIVE_CORE_0_PIF_PMS_CONSTRAIN_RTCFAST_WORLD_X_W = 0x1
const SENSITIVE_CORE_0_PIF_PMS_CONSTRAIN_RTCFAST_WORLD_X_R = 0x2
const SENSITIVE_CORE_0_PIF_PMS_CONSTRAIN_RTCFAST_WORLD_X_F = 0x4
const AREA_LOW = 0
const AREA_HIGH = 1

type ConstrainRegFieldsT struct {
	Val c.Uint32T
}
