package esp_pm

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

const CONFIG_SOC_BROWNOUT_RESET_SUPPORTED = "Not determined"
const CONFIG_SOC_TWAI_BRP_DIV_SUPPORTED = "Not determined"
const CONFIG_SOC_DPORT_WORKAROUND = "Not determined"
const CONFIG_SOC_CAPS_ECO_VER_MAX = 301
const CONFIG_SOC_ADC_SUPPORTED = 1
const CONFIG_SOC_DAC_SUPPORTED = 1
const CONFIG_SOC_UART_SUPPORTED = 1
const CONFIG_SOC_MCPWM_SUPPORTED = 1
const CONFIG_SOC_GPTIMER_SUPPORTED = 1
const CONFIG_SOC_SDMMC_HOST_SUPPORTED = 1
const CONFIG_SOC_BT_SUPPORTED = 1
const CONFIG_SOC_PCNT_SUPPORTED = 1
const CONFIG_SOC_PHY_SUPPORTED = 1
const CONFIG_SOC_WIFI_SUPPORTED = 1
const CONFIG_SOC_SDIO_SLAVE_SUPPORTED = 1
const CONFIG_SOC_TWAI_SUPPORTED = 1
const CONFIG_SOC_EFUSE_SUPPORTED = 1
const CONFIG_SOC_EMAC_SUPPORTED = 1
const CONFIG_SOC_ULP_SUPPORTED = 1
const CONFIG_SOC_CCOMP_TIMER_SUPPORTED = 1
const CONFIG_SOC_RTC_FAST_MEM_SUPPORTED = 1
const CONFIG_SOC_RTC_SLOW_MEM_SUPPORTED = 1
const CONFIG_SOC_RTC_MEM_SUPPORTED = 1
const CONFIG_SOC_I2S_SUPPORTED = 1
const CONFIG_SOC_RMT_SUPPORTED = 1
const CONFIG_SOC_SDM_SUPPORTED = 1
const CONFIG_SOC_GPSPI_SUPPORTED = 1
const CONFIG_SOC_LEDC_SUPPORTED = 1
const CONFIG_SOC_I2C_SUPPORTED = 1
const CONFIG_SOC_SUPPORT_COEXISTENCE = 1
const CONFIG_SOC_AES_SUPPORTED = 1
const CONFIG_SOC_MPI_SUPPORTED = 1
const CONFIG_SOC_SHA_SUPPORTED = 1
const CONFIG_SOC_FLASH_ENC_SUPPORTED = 1
const CONFIG_SOC_SECURE_BOOT_SUPPORTED = 1
const CONFIG_SOC_TOUCH_SENSOR_SUPPORTED = 1
const CONFIG_SOC_BOD_SUPPORTED = 1
const CONFIG_SOC_ULP_FSM_SUPPORTED = 1
const CONFIG_SOC_CLK_TREE_SUPPORTED = 1
const CONFIG_SOC_MPU_SUPPORTED = 1
const CONFIG_SOC_WDT_SUPPORTED = 1
const CONFIG_SOC_SPI_FLASH_SUPPORTED = 1
const CONFIG_SOC_RNG_SUPPORTED = 1
const CONFIG_SOC_LIGHT_SLEEP_SUPPORTED = 1
const CONFIG_SOC_DEEP_SLEEP_SUPPORTED = 1
const CONFIG_SOC_LP_PERIPH_SHARE_INTERRUPT = 1
const CONFIG_SOC_PM_SUPPORTED = 1
const CONFIG_SOC_DPORT_WORKAROUND_DIS_INTERRUPT_LVL = 5
const CONFIG_SOC_XTAL_SUPPORT_26M = 1
const CONFIG_SOC_XTAL_SUPPORT_40M = 1
const CONFIG_SOC_XTAL_SUPPORT_AUTO_DETECT = 1
const CONFIG_SOC_ADC_RTC_CTRL_SUPPORTED = 1
const CONFIG_SOC_ADC_DIG_CTRL_SUPPORTED = 1
const CONFIG_SOC_ADC_DMA_SUPPORTED = 1
const CONFIG_SOC_ADC_PERIPH_NUM = 2
const CONFIG_SOC_ADC_MAX_CHANNEL_NUM = 10
const CONFIG_SOC_ADC_ATTEN_NUM = 4
const CONFIG_SOC_ADC_DIGI_CONTROLLER_NUM = 2
const CONFIG_SOC_ADC_PATT_LEN_MAX = 16
const CONFIG_SOC_ADC_DIGI_MIN_BITWIDTH = 9
const CONFIG_SOC_ADC_DIGI_MAX_BITWIDTH = 12
const CONFIG_SOC_ADC_DIGI_RESULT_BYTES = 2
const CONFIG_SOC_ADC_DIGI_DATA_BYTES_PER_CONV = 4
const CONFIG_SOC_ADC_DIGI_MONITOR_NUM = 0
const CONFIG_SOC_ADC_SAMPLE_FREQ_THRES_HIGH = 2
const CONFIG_SOC_ADC_SAMPLE_FREQ_THRES_LOW = 20
const CONFIG_SOC_ADC_RTC_MIN_BITWIDTH = 9
const CONFIG_SOC_ADC_RTC_MAX_BITWIDTH = 12
const CONFIG_SOC_ADC_SHARED_POWER = 1
const CONFIG_SOC_SHARED_IDCACHE_SUPPORTED = 1
const CONFIG_SOC_IDCACHE_PER_CORE = 1
const CONFIG_SOC_CPU_CORES_NUM = 2
const CONFIG_SOC_CPU_INTR_NUM = 32
const CONFIG_SOC_CPU_HAS_FPU = 1
const CONFIG_SOC_HP_CPU_HAS_MULTIPLE_CORES = 1
const CONFIG_SOC_CPU_BREAKPOINTS_NUM = 2
const CONFIG_SOC_CPU_WATCHPOINTS_NUM = 2
const CONFIG_SOC_CPU_WATCHPOINT_MAX_REGION_SIZE = 64
const CONFIG_SOC_DAC_CHAN_NUM = 2
const CONFIG_SOC_DAC_RESOLUTION = 8
const CONFIG_SOC_DAC_DMA_16BIT_ALIGN = 1
const CONFIG_SOC_GPIO_PORT = 1
const CONFIG_SOC_GPIO_PIN_COUNT = 40
const CONFIG_SOC_GPIO_VALID_GPIO_MASK = 0xFFFFFFFFFF
const CONFIG_SOC_GPIO_IN_RANGE_MAX = 39
const CONFIG_SOC_GPIO_OUT_RANGE_MAX = 33
const CONFIG_SOC_GPIO_VALID_DIGITAL_IO_PAD_MASK = 0xEF0FEA
const CONFIG_SOC_GPIO_CLOCKOUT_BY_IO_MUX = 1
const CONFIG_SOC_GPIO_CLOCKOUT_CHANNEL_NUM = 3
const CONFIG_SOC_GPIO_SUPPORT_HOLD_IO_IN_DSLP = 1
const CONFIG_SOC_I2C_NUM = 2
const CONFIG_SOC_HP_I2C_NUM = 2
const CONFIG_SOC_I2C_FIFO_LEN = 32
const CONFIG_SOC_I2C_CMD_REG_NUM = 16
const CONFIG_SOC_I2C_SUPPORT_SLAVE = 1
const CONFIG_SOC_I2C_SUPPORT_APB = 1
const CONFIG_SOC_I2C_SUPPORT_10BIT_ADDR = 1
const CONFIG_SOC_I2C_STOP_INDEPENDENT = 1
const CONFIG_SOC_I2S_NUM = 2
const CONFIG_SOC_I2S_HW_VERSION_1 = 1
const CONFIG_SOC_I2S_SUPPORTS_APLL = 1
const CONFIG_SOC_I2S_SUPPORTS_PLL_F160M = 1
const CONFIG_SOC_I2S_SUPPORTS_PDM = 1
const CONFIG_SOC_I2S_SUPPORTS_PDM_TX = 1
const CONFIG_SOC_I2S_PDM_MAX_TX_LINES = 1
const CONFIG_SOC_I2S_SUPPORTS_PDM_RX = 1
const CONFIG_SOC_I2S_PDM_MAX_RX_LINES = 1
const CONFIG_SOC_I2S_SUPPORTS_ADC_DAC = 1
const CONFIG_SOC_I2S_SUPPORTS_ADC = 1
const CONFIG_SOC_I2S_SUPPORTS_DAC = 1
const CONFIG_SOC_I2S_SUPPORTS_LCD_CAMERA = 1
const CONFIG_SOC_I2S_MAX_DATA_WIDTH = 24
const CONFIG_SOC_I2S_TRANS_SIZE_ALIGN_WORD = 1
const CONFIG_SOC_I2S_LCD_I80_VARIANT = 1
const CONFIG_SOC_LCD_I80_SUPPORTED = 1
const CONFIG_SOC_LCD_I80_BUSES = 2
const CONFIG_SOC_LCD_I80_BUS_WIDTH = 24
const CONFIG_SOC_LEDC_HAS_TIMER_SPECIFIC_MUX = 1
const CONFIG_SOC_LEDC_SUPPORT_APB_CLOCK = 1
const CONFIG_SOC_LEDC_SUPPORT_REF_TICK = 1
const CONFIG_SOC_LEDC_SUPPORT_HS_MODE = 1
const CONFIG_SOC_LEDC_TIMER_NUM = 4
const CONFIG_SOC_LEDC_CHANNEL_NUM = 8
const CONFIG_SOC_LEDC_TIMER_BIT_WIDTH = 20
const CONFIG_SOC_MCPWM_GROUPS = 2
const CONFIG_SOC_MCPWM_TIMERS_PER_GROUP = 3
const CONFIG_SOC_MCPWM_OPERATORS_PER_GROUP = 3
const CONFIG_SOC_MCPWM_COMPARATORS_PER_OPERATOR = 2
const CONFIG_SOC_MCPWM_GENERATORS_PER_OPERATOR = 2
const CONFIG_SOC_MCPWM_TRIGGERS_PER_OPERATOR = 2
const CONFIG_SOC_MCPWM_GPIO_FAULTS_PER_GROUP = 3
const CONFIG_SOC_MCPWM_CAPTURE_TIMERS_PER_GROUP = 1
const CONFIG_SOC_MCPWM_CAPTURE_CHANNELS_PER_TIMER = 3
const CONFIG_SOC_MCPWM_GPIO_SYNCHROS_PER_GROUP = 3
const CONFIG_SOC_MMU_PERIPH_NUM = 2
const CONFIG_SOC_MMU_LINEAR_ADDRESS_REGION_NUM = 3
const CONFIG_SOC_MPU_MIN_REGION_SIZE = 0x20000000
const CONFIG_SOC_MPU_REGIONS_MAX_NUM = 8
const CONFIG_SOC_PCNT_GROUPS = 1
const CONFIG_SOC_PCNT_UNITS_PER_GROUP = 8
const CONFIG_SOC_PCNT_CHANNELS_PER_UNIT = 2
const CONFIG_SOC_PCNT_THRES_POINT_PER_UNIT = 2
const CONFIG_SOC_RMT_GROUPS = 1
const CONFIG_SOC_RMT_TX_CANDIDATES_PER_GROUP = 8
const CONFIG_SOC_RMT_RX_CANDIDATES_PER_GROUP = 8
const CONFIG_SOC_RMT_CHANNELS_PER_GROUP = 8
const CONFIG_SOC_RMT_MEM_WORDS_PER_CHANNEL = 64
const CONFIG_SOC_RMT_SUPPORT_REF_TICK = 1
const CONFIG_SOC_RMT_SUPPORT_APB = 1
const CONFIG_SOC_RMT_CHANNEL_CLK_INDEPENDENT = 1
const CONFIG_SOC_RTCIO_PIN_COUNT = 18
const CONFIG_SOC_RTCIO_INPUT_OUTPUT_SUPPORTED = 1
const CONFIG_SOC_RTCIO_HOLD_SUPPORTED = 1
const CONFIG_SOC_RTCIO_WAKE_SUPPORTED = 1
const CONFIG_SOC_SDM_GROUPS = 1
const CONFIG_SOC_SDM_CHANNELS_PER_GROUP = 8
const CONFIG_SOC_SDM_CLK_SUPPORT_APB = 1
const CONFIG_SOC_SPI_HD_BOTH_INOUT_SUPPORTED = 1
const CONFIG_SOC_SPI_AS_CS_SUPPORTED = 1
const CONFIG_SOC_SPI_PERIPH_NUM = 3
const CONFIG_SOC_SPI_DMA_CHAN_NUM = 2
const CONFIG_SOC_SPI_MAX_CS_NUM = 3
const CONFIG_SOC_SPI_SUPPORT_CLK_APB = 1
const CONFIG_SOC_SPI_MAXIMUM_BUFFER_SIZE = 64
const CONFIG_SOC_SPI_MAX_PRE_DIVIDER = 8192
const CONFIG_SOC_MEMSPI_SRC_FREQ_80M_SUPPORTED = 1
const CONFIG_SOC_MEMSPI_SRC_FREQ_40M_SUPPORTED = 1
const CONFIG_SOC_MEMSPI_SRC_FREQ_26M_SUPPORTED = 1
const CONFIG_SOC_MEMSPI_SRC_FREQ_20M_SUPPORTED = 1
const CONFIG_SOC_TIMER_GROUPS = 2
const CONFIG_SOC_TIMER_GROUP_TIMERS_PER_GROUP = 2
const CONFIG_SOC_TIMER_GROUP_COUNTER_BIT_WIDTH = 64
const CONFIG_SOC_TIMER_GROUP_TOTAL_TIMERS = 4
const CONFIG_SOC_TIMER_GROUP_SUPPORT_APB = 1
const CONFIG_SOC_LP_TIMER_BIT_WIDTH_LO = 32
const CONFIG_SOC_LP_TIMER_BIT_WIDTH_HI = 16
const CONFIG_SOC_TOUCH_SENSOR_VERSION = 1
const CONFIG_SOC_TOUCH_SENSOR_NUM = 10
const CONFIG_SOC_TOUCH_SAMPLE_CFG_NUM = 1
const CONFIG_SOC_TWAI_CONTROLLER_NUM = 1
const CONFIG_SOC_TWAI_BRP_MIN = 2
const CONFIG_SOC_TWAI_CLK_SUPPORT_APB = 1
const CONFIG_SOC_TWAI_SUPPORT_MULTI_ADDRESS_LAYOUT = 1
const CONFIG_SOC_UART_NUM = 3
const CONFIG_SOC_UART_HP_NUM = 3
const CONFIG_SOC_UART_SUPPORT_APB_CLK = 1
const CONFIG_SOC_UART_SUPPORT_REF_TICK = 1
const CONFIG_SOC_UART_FIFO_LEN = 128
const CONFIG_SOC_UART_BITRATE_MAX = 5000000
const CONFIG_SOC_SPIRAM_SUPPORTED = 1
const CONFIG_SOC_SPI_MEM_SUPPORT_CONFIG_GPIO_BY_EFUSE = 1
const CONFIG_SOC_SHA_SUPPORT_PARALLEL_ENG = 1
const CONFIG_SOC_SHA_ENDIANNESS_BE = 1
const CONFIG_SOC_SHA_SUPPORT_SHA1 = 1
const CONFIG_SOC_SHA_SUPPORT_SHA256 = 1
const CONFIG_SOC_SHA_SUPPORT_SHA384 = 1
const CONFIG_SOC_SHA_SUPPORT_SHA512 = 1
const CONFIG_SOC_MPI_MEM_BLOCKS_NUM = 4
const CONFIG_SOC_MPI_OPERATIONS_NUM = 1
const CONFIG_SOC_RSA_MAX_BIT_LEN = 4096
const CONFIG_SOC_AES_SUPPORT_AES_128 = 1
const CONFIG_SOC_AES_SUPPORT_AES_192 = 1
const CONFIG_SOC_AES_SUPPORT_AES_256 = 1
const CONFIG_SOC_SECURE_BOOT_V1 = 1
const CONFIG_SOC_EFUSE_SECURE_BOOT_KEY_DIGESTS = 1
const CONFIG_SOC_FLASH_ENCRYPTED_XTS_AES_BLOCK_MAX = 32
const CONFIG_SOC_PHY_DIG_REGS_MEM_SIZE = 21
const CONFIG_SOC_PM_SUPPORT_EXT0_WAKEUP = 1
const CONFIG_SOC_PM_SUPPORT_EXT1_WAKEUP = 1
const CONFIG_SOC_PM_SUPPORT_EXT_WAKEUP = 1
const CONFIG_SOC_PM_SUPPORT_TOUCH_SENSOR_WAKEUP = 1
const CONFIG_SOC_PM_SUPPORT_RTC_PERIPH_PD = 1
const CONFIG_SOC_PM_SUPPORT_RTC_FAST_MEM_PD = 1
const CONFIG_SOC_PM_SUPPORT_RTC_SLOW_MEM_PD = 1
const CONFIG_SOC_PM_SUPPORT_RC_FAST_PD = 1
const CONFIG_SOC_PM_SUPPORT_VDDSDIO_PD = 1
const CONFIG_SOC_PM_SUPPORT_MODEM_PD = 1
const CONFIG_SOC_CONFIGURABLE_VDDSDIO_SUPPORTED = 1
const CONFIG_SOC_PM_MODEM_PD_BY_SW = 1
const CONFIG_SOC_CLK_APLL_SUPPORTED = 1
const CONFIG_SOC_CLK_RC_FAST_D256_SUPPORTED = 1
const CONFIG_SOC_RTC_SLOW_CLK_SUPPORT_RC_FAST_D256 = 1
const CONFIG_SOC_CLK_RC_FAST_SUPPORT_CALIBRATION = 1
const CONFIG_SOC_CLK_XTAL32K_SUPPORTED = 1
const CONFIG_SOC_SDMMC_USE_IOMUX = 1
const CONFIG_SOC_SDMMC_NUM_SLOTS = 2
const CONFIG_SOC_WIFI_WAPI_SUPPORT = 1
const CONFIG_SOC_WIFI_CSI_SUPPORT = 1
const CONFIG_SOC_WIFI_MESH_SUPPORT = 1
const CONFIG_SOC_WIFI_SUPPORT_VARIABLE_BEACON_WINDOW = 1
const CONFIG_SOC_WIFI_NAN_SUPPORT = 1
const CONFIG_SOC_BLE_SUPPORTED = 1
const CONFIG_SOC_BLE_MESH_SUPPORTED = 1
const CONFIG_SOC_BT_CLASSIC_SUPPORTED = 1
const CONFIG_SOC_BLUFI_SUPPORTED = 1
const CONFIG_SOC_BT_H2C_ENC_KEY_CTRL_ENH_VSC_SUPPORTED = 1
const CONFIG_SOC_ULP_HAS_ADC = 1
const CONFIG_SOC_PHY_COMBO_MODULE = 1
const CONFIG_SOC_EMAC_RMII_CLK_OUT_INTERNAL_LOOPBACK = 1
const CONFIG_IDF_CMAKE = 1
const CONFIG_IDF_TOOLCHAIN = "gcc"
const CONFIG_IDF_TOOLCHAIN_GCC = 1
const CONFIG_IDF_TARGET_ARCH_XTENSA = 1
const CONFIG_IDF_TARGET_ARCH = "xtensa"
const CONFIG_IDF_TARGET = "esp32"
const CONFIG_IDF_INIT_VERSION = "5.4.2"
const CONFIG_IDF_TARGET_ESP32 = 1
const CONFIG_IDF_FIRMWARE_CHIP_ID = 0x0000
const CONFIG_APP_BUILD_TYPE_APP_2NDBOOT = 1
const CONFIG_APP_BUILD_GENERATE_BINARIES = 1
const CONFIG_APP_BUILD_BOOTLOADER = 1
const CONFIG_APP_BUILD_USE_FLASH_SECTIONS = 1
const CONFIG_BOOTLOADER_COMPILE_TIME_DATE = 1
const CONFIG_BOOTLOADER_PROJECT_VER = 1
const CONFIG_BOOTLOADER_OFFSET_IN_FLASH = 0x1000
const CONFIG_BOOTLOADER_COMPILER_OPTIMIZATION_SIZE = 1
const CONFIG_BOOTLOADER_LOG_LEVEL_INFO = 1
const CONFIG_BOOTLOADER_LOG_LEVEL = 3
const CONFIG_BOOTLOADER_LOG_TIMESTAMP_SOURCE_CPU_TICKS = 1
const CONFIG_BOOTLOADER_FLASH_XMC_SUPPORT = 1
const CONFIG_BOOTLOADER_VDDSDIO_BOOST_1_9V = 1
const CONFIG_BOOTLOADER_REGION_PROTECTION_ENABLE = 1
const CONFIG_BOOTLOADER_WDT_ENABLE = 1
const CONFIG_BOOTLOADER_WDT_TIME_MS = 9000
const CONFIG_BOOTLOADER_RESERVE_RTC_SIZE = 0x0
const CONFIG_SECURE_BOOT_V1_SUPPORTED = 1
const CONFIG_APP_COMPILE_TIME_DATE = 1
const CONFIG_APP_RETRIEVE_LEN_ELF_SHA = 9
const CONFIG_ESP_ROM_HAS_CRC_LE = 1
const CONFIG_ESP_ROM_HAS_CRC_BE = 1
const CONFIG_ESP_ROM_HAS_MZ_CRC32 = 1
const CONFIG_ESP_ROM_HAS_JPEG_DECODE = 1
const CONFIG_ESP_ROM_HAS_UART_BUF_SWITCH = 1
const CONFIG_ESP_ROM_NEEDS_SWSETUP_WORKAROUND = 1
const CONFIG_ESP_ROM_HAS_NEWLIB = 1
const CONFIG_ESP_ROM_HAS_NEWLIB_NANO_FORMAT = 1
const CONFIG_ESP_ROM_HAS_NEWLIB_32BIT_TIME = 1
const CONFIG_ESP_ROM_HAS_SW_FLOAT = 1
const CONFIG_ESP_ROM_SUPPORT_DEEP_SLEEP_WAKEUP_STUB = 1
const CONFIG_ESP_ROM_HAS_OUTPUT_PUTC_FUNC = 1
const CONFIG_ESPTOOLPY_FLASHMODE_DIO = 1
const CONFIG_ESPTOOLPY_FLASH_SAMPLE_MODE_STR = 1
const CONFIG_ESPTOOLPY_FLASHMODE = "dio"
const CONFIG_ESPTOOLPY_FLASHFREQ_40M = 1
const CONFIG_ESPTOOLPY_FLASHFREQ = "40m"
const CONFIG_ESPTOOLPY_FLASHSIZE_2MB = 1
const CONFIG_ESPTOOLPY_FLASHSIZE = "2MB"
const CONFIG_ESPTOOLPY_BEFORE_RESET = 1
const CONFIG_ESPTOOLPY_BEFORE = "default_reset"
const CONFIG_ESPTOOLPY_AFTER_RESET = 1
const CONFIG_ESPTOOLPY_AFTER = "hard_reset"
const CONFIG_ESPTOOLPY_MONITOR_BAUD = 115200
const CONFIG_PARTITION_TABLE_SINGLE_APP = 1
const CONFIG_PARTITION_TABLE_CUSTOM_FILENAME = "partitions.csv"
const CONFIG_PARTITION_TABLE_FILENAME = "partitions_singleapp.csv"
const CONFIG_PARTITION_TABLE_OFFSET = 0x8000
const CONFIG_PARTITION_TABLE_MD5 = 1
const CONFIG_COMPILER_OPTIMIZATION_DEBUG = 1
const CONFIG_COMPILER_OPTIMIZATION_ASSERTIONS_ENABLE = 1
const CONFIG_COMPILER_ASSERT_NDEBUG_EVALUATE = 1
const CONFIG_COMPILER_FLOAT_LIB_FROM_GCCLIB = 1
const CONFIG_COMPILER_OPTIMIZATION_ASSERTION_LEVEL = 2
const CONFIG_COMPILER_HIDE_PATHS_MACROS = 1
const CONFIG_COMPILER_STACK_CHECK_MODE_NONE = 1
const CONFIG_COMPILER_DISABLE_DEFAULT_ERRORS = 1
const CONFIG_COMPILER_RT_LIB_GCCLIB = 1
const CONFIG_COMPILER_RT_LIB_NAME = "gcc"
const CONFIG_COMPILER_ORPHAN_SECTIONS_WARNING = 1
const CONFIG_APPTRACE_DEST_NONE = 1
const CONFIG_APPTRACE_DEST_UART_NONE = 1
const CONFIG_APPTRACE_UART_TASK_PRIO = 1
const CONFIG_APPTRACE_LOCK_ENABLE = 1
const CONFIG_TWAI_ERRATA_FIX_BUS_OFF_REC = 1
const CONFIG_TWAI_ERRATA_FIX_TX_INTR_LOST = 1
const CONFIG_TWAI_ERRATA_FIX_RX_FRAME_INVALID = 1
const CONFIG_TWAI_ERRATA_FIX_RX_FIFO_CORRUPT = 1
const CONFIG_TWAI_ERRATA_FIX_LISTEN_ONLY_DOM = 1
const CONFIG_ADC_DISABLE_DAC = 1
const CONFIG_ADC_CAL_EFUSE_TP_ENABLE = 1
const CONFIG_ADC_CAL_EFUSE_VREF_ENABLE = 1
const CONFIG_ADC_CAL_LUT_ENABLE = 1
const CONFIG_EFUSE_CODE_SCHEME_COMPAT_3_4 = 1
const CONFIG_EFUSE_MAX_BLK_LEN = 192
const CONFIG_ESP_TLS_USING_MBEDTLS = 1
const CONFIG_ADC_CALI_EFUSE_TP_ENABLE = 1
const CONFIG_ADC_CALI_EFUSE_VREF_ENABLE = 1
const CONFIG_ADC_CALI_LUT_ENABLE = 1
const CONFIG_ADC_DISABLE_DAC_OUTPUT = 1
const CONFIG_ESP_COEX_ENABLED = 1
const CONFIG_ESP_ERR_TO_NAME_LOOKUP = 1
const CONFIG_DAC_DMA_AUTO_16BIT_ALIGN = 1
const CONFIG_GPTIMER_ISR_HANDLER_IN_IRAM = 1
const CONFIG_GPTIMER_OBJ_CACHE_SAFE = 1
const CONFIG_SPI_MASTER_ISR_IN_IRAM = 1
const CONFIG_SPI_SLAVE_ISR_IN_IRAM = 1
const CONFIG_ETH_ENABLED = 1
const CONFIG_ETH_USE_ESP32_EMAC = 1
const CONFIG_ETH_PHY_INTERFACE_RMII = 1
const CONFIG_ETH_RMII_CLK_INPUT = 1
const CONFIG_ETH_RMII_CLK_IN_GPIO = 0
const CONFIG_ETH_DMA_BUFFER_SIZE = 512
const CONFIG_ETH_DMA_RX_BUFFER_NUM = 10
const CONFIG_ETH_DMA_TX_BUFFER_NUM = 10
const CONFIG_ETH_USE_SPI_ETHERNET = 1
const CONFIG_ESP_EVENT_POST_FROM_ISR = 1
const CONFIG_ESP_EVENT_POST_FROM_IRAM_ISR = 1
const CONFIG_ESP_GDBSTUB_ENABLED = 1
const CONFIG_ESP_GDBSTUB_SUPPORT_TASKS = 1
const CONFIG_ESP_GDBSTUB_MAX_TASKS = 32
const CONFIG_ESPHID_TASK_SIZE_BT = 2048
const CONFIG_ESPHID_TASK_SIZE_BLE = 4096
const CONFIG_ESP_HTTP_CLIENT_ENABLE_HTTPS = 1
const CONFIG_ESP_HTTP_CLIENT_EVENT_POST_TIMEOUT = 2000
const CONFIG_HTTPD_MAX_REQ_HDR_LEN = 512
const CONFIG_HTTPD_MAX_URI_LEN = 512
const CONFIG_HTTPD_ERR_RESP_NO_DELAY = 1
const CONFIG_HTTPD_PURGE_BUF_LEN = 32
const CONFIG_HTTPD_SERVER_EVENT_POST_TIMEOUT = 2000
const CONFIG_ESP_HTTPS_OTA_EVENT_POST_TIMEOUT = 2000
const CONFIG_ESP_HTTPS_SERVER_EVENT_POST_TIMEOUT = 2000
const CONFIG_ESP32_REV_MIN_0 = 1
const CONFIG_ESP32_REV_MIN = 0
const CONFIG_ESP32_REV_MIN_FULL = 0
const CONFIG_ESP_REV_MIN_FULL = 0
const CONFIG_ESP32_REV_MAX_FULL = 399
const CONFIG_ESP_REV_MAX_FULL = 399
const CONFIG_ESP_EFUSE_BLOCK_REV_MIN_FULL = 0
const CONFIG_ESP_EFUSE_BLOCK_REV_MAX_FULL = 99
const CONFIG_ESP_MAC_ADDR_UNIVERSE_WIFI_STA = 1
const CONFIG_ESP_MAC_ADDR_UNIVERSE_WIFI_AP = 1
const CONFIG_ESP_MAC_ADDR_UNIVERSE_BT = 1
const CONFIG_ESP_MAC_ADDR_UNIVERSE_ETH = 1
const CONFIG_ESP_MAC_UNIVERSAL_MAC_ADDRESSES_FOUR = 1
const CONFIG_ESP_MAC_UNIVERSAL_MAC_ADDRESSES = 4
const CONFIG_ESP32_UNIVERSAL_MAC_ADDRESSES_FOUR = 1
const CONFIG_ESP32_UNIVERSAL_MAC_ADDRESSES = 4
const CONFIG_ESP_SLEEP_FLASH_LEAKAGE_WORKAROUND = 1
const CONFIG_ESP_SLEEP_RTC_BUS_ISO_WORKAROUND = 1
const CONFIG_ESP_SLEEP_WAIT_FLASH_READY_EXTRA_DELAY = 2000
const CONFIG_ESP_SLEEP_GPIO_ENABLE_INTERNAL_RESISTORS = 1
const CONFIG_RTC_CLK_SRC_INT_RC = 1
const CONFIG_RTC_CLK_CAL_CYCLES = 1024
const CONFIG_XTAL_FREQ_40 = 1
const CONFIG_XTAL_FREQ = 40
const CONFIG_ESP_SPI_BUS_LOCK_ISR_FUNCS_IN_IRAM = 1
const CONFIG_ESP_NETIF_IP_LOST_TIMER_INTERVAL = 120
const CONFIG_ESP_NETIF_TCPIP_LWIP = 1
const CONFIG_ESP_NETIF_USES_TCPIP_WITH_BSD_API = 1
const CONFIG_ESP_NETIF_REPORT_DATA_TRAFFIC = 1
const CONFIG_ESP_PHY_ENABLED = 1
const CONFIG_ESP_PHY_CALIBRATION_AND_DATA_STORAGE = 1
const CONFIG_ESP_PHY_MAX_WIFI_TX_POWER = 20
const CONFIG_ESP_PHY_MAX_TX_POWER = 20
const CONFIG_ESP_PHY_RF_CAL_PARTIAL = 1
const CONFIG_ESP_PHY_CALIBRATION_MODE = 0
const CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ_160 = 1
const CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ = 160
const CONFIG_ESP32_TRACEMEM_RESERVE_DRAM = 0x0
const CONFIG_ESP_SYSTEM_PANIC_PRINT_REBOOT = 1
const CONFIG_ESP_SYSTEM_PANIC_REBOOT_DELAY_SECONDS = 0
const CONFIG_ESP_SYSTEM_EVENT_QUEUE_SIZE = 32
const CONFIG_ESP_SYSTEM_EVENT_TASK_STACK_SIZE = 2304
const CONFIG_ESP_MAIN_TASK_STACK_SIZE = 3584
const CONFIG_ESP_MAIN_TASK_AFFINITY_CPU0 = 1
const CONFIG_ESP_MAIN_TASK_AFFINITY = 0x0
const CONFIG_ESP_MINIMAL_SHARED_STACK_SIZE = 2048
const CONFIG_ESP_CONSOLE_UART_DEFAULT = 1
const CONFIG_ESP_CONSOLE_UART = 1
const CONFIG_ESP_CONSOLE_UART_NUM = 0
const CONFIG_ESP_CONSOLE_ROM_SERIAL_PORT_NUM = 0
const CONFIG_ESP_CONSOLE_UART_BAUDRATE = 115200
const CONFIG_ESP_INT_WDT = 1
const CONFIG_ESP_INT_WDT_TIMEOUT_MS = 300
const CONFIG_ESP_INT_WDT_CHECK_CPU1 = 1
const CONFIG_ESP_TASK_WDT_EN = 1
const CONFIG_ESP_TASK_WDT_INIT = 1
const CONFIG_ESP_TASK_WDT_TIMEOUT_S = 5
const CONFIG_ESP_TASK_WDT_CHECK_IDLE_TASK_CPU0 = 1
const CONFIG_ESP_TASK_WDT_CHECK_IDLE_TASK_CPU1 = 1
const CONFIG_ESP_DEBUG_OCDAWARE = 1
const CONFIG_ESP_SYSTEM_CHECK_INT_LEVEL_4 = 1
const CONFIG_ESP_BROWNOUT_DET = 1
const CONFIG_ESP_BROWNOUT_DET_LVL_SEL_0 = 1
const CONFIG_ESP_BROWNOUT_DET_LVL = 0
const CONFIG_ESP_SYSTEM_BROWNOUT_INTR = 1
const CONFIG_ESP_IPC_TASK_STACK_SIZE = 1024
const CONFIG_ESP_IPC_USES_CALLERS_PRIORITY = 1
const CONFIG_ESP_IPC_ISR_ENABLE = 1
const CONFIG_ESP_TIME_FUNCS_USE_RTC_TIMER = 1
const CONFIG_ESP_TIME_FUNCS_USE_ESP_TIMER = 1
const CONFIG_ESP_TIMER_TASK_STACK_SIZE = 3584
const CONFIG_ESP_TIMER_INTERRUPT_LEVEL = 1
const CONFIG_ESP_TIMER_TASK_AFFINITY = 0x0
const CONFIG_ESP_TIMER_TASK_AFFINITY_CPU0 = 1
const CONFIG_ESP_TIMER_ISR_AFFINITY_CPU0 = 1
const CONFIG_ESP_TIMER_IMPL_TG0_LAC = 1
const CONFIG_ESP_WIFI_ENABLED = 1
const CONFIG_ESP_WIFI_STATIC_RX_BUFFER_NUM = 10
const CONFIG_ESP_WIFI_DYNAMIC_RX_BUFFER_NUM = 32
const CONFIG_ESP_WIFI_DYNAMIC_TX_BUFFER = 1
const CONFIG_ESP_WIFI_TX_BUFFER_TYPE = 1
const CONFIG_ESP_WIFI_DYNAMIC_TX_BUFFER_NUM = 32
const CONFIG_ESP_WIFI_STATIC_RX_MGMT_BUFFER = 1
const CONFIG_ESP_WIFI_DYNAMIC_RX_MGMT_BUF = 0
const CONFIG_ESP_WIFI_RX_MGMT_BUF_NUM_DEF = 5
const CONFIG_ESP_WIFI_AMPDU_TX_ENABLED = 1
const CONFIG_ESP_WIFI_TX_BA_WIN = 6
const CONFIG_ESP_WIFI_AMPDU_RX_ENABLED = 1
const CONFIG_ESP_WIFI_RX_BA_WIN = 6
const CONFIG_ESP_WIFI_NVS_ENABLED = 1
const CONFIG_ESP_WIFI_TASK_PINNED_TO_CORE_0 = 1
const CONFIG_ESP_WIFI_SOFTAP_BEACON_MAX_LEN = 752
const CONFIG_ESP_WIFI_MGMT_SBUF_NUM = 32
const CONFIG_ESP_WIFI_IRAM_OPT = 1
const CONFIG_ESP_WIFI_RX_IRAM_OPT = 1
const CONFIG_ESP_WIFI_ENABLE_WPA3_SAE = 1
const CONFIG_ESP_WIFI_ENABLE_SAE_PK = 1
const CONFIG_ESP_WIFI_SOFTAP_SAE_SUPPORT = 1
const CONFIG_ESP_WIFI_ENABLE_WPA3_OWE_STA = 1
const CONFIG_ESP_WIFI_SLP_DEFAULT_MIN_ACTIVE_TIME = 50
const CONFIG_ESP_WIFI_SLP_DEFAULT_MAX_ACTIVE_TIME = 10
const CONFIG_ESP_WIFI_SLP_DEFAULT_WAIT_BROADCAST_DATA_TIME = 15
const CONFIG_ESP_WIFI_STA_DISCONNECTED_PM_ENABLE = 1
const CONFIG_ESP_WIFI_GMAC_SUPPORT = 1
const CONFIG_ESP_WIFI_SOFTAP_SUPPORT = 1
const CONFIG_ESP_WIFI_ESPNOW_MAX_ENCRYPT_NUM = 7
const CONFIG_ESP_WIFI_MBEDTLS_CRYPTO = 1
const CONFIG_ESP_WIFI_MBEDTLS_TLS_CLIENT = 1
const CONFIG_ESP_WIFI_ENTERPRISE_SUPPORT = 1
const CONFIG_ESP_COREDUMP_ENABLE_TO_NONE = 1
const CONFIG_FATFS_VOLUME_COUNT = 2
const CONFIG_FATFS_LFN_NONE = 1
const CONFIG_FATFS_SECTOR_4096 = 1
const CONFIG_FATFS_CODEPAGE_437 = 1
const CONFIG_FATFS_CODEPAGE = 437
const CONFIG_FATFS_FS_LOCK = 0
const CONFIG_FATFS_TIMEOUT_MS = 10000
const CONFIG_FATFS_PER_FILE_CACHE = 1
const CONFIG_FATFS_USE_STRFUNC_NONE = 1
const CONFIG_FATFS_VFS_FSTAT_BLKSIZE = 0
const CONFIG_FATFS_LINK_LOCK = 1
const CONFIG_FATFS_DONT_TRUST_FREE_CLUSTER_CNT = 0
const CONFIG_FATFS_DONT_TRUST_LAST_ALLOC = 0
const CONFIG_FREERTOS_HZ = 100
const CONFIG_FREERTOS_CHECK_STACKOVERFLOW_CANARY = 1
const CONFIG_FREERTOS_THREAD_LOCAL_STORAGE_POINTERS = 1
const CONFIG_FREERTOS_IDLE_TASK_STACKSIZE = 1536
const CONFIG_FREERTOS_MAX_TASK_NAME_LEN = 16
const CONFIG_FREERTOS_USE_TIMERS = 1
const CONFIG_FREERTOS_TIMER_SERVICE_TASK_NAME = "Tmr Svc"
const CONFIG_FREERTOS_TIMER_TASK_NO_AFFINITY = 1
const CONFIG_FREERTOS_TIMER_SERVICE_TASK_CORE_AFFINITY = 0x7FFFFFFF
const CONFIG_FREERTOS_TIMER_TASK_PRIORITY = 1
const CONFIG_FREERTOS_TIMER_TASK_STACK_DEPTH = 2048
const CONFIG_FREERTOS_TIMER_QUEUE_LENGTH = 10
const CONFIG_FREERTOS_QUEUE_REGISTRY_SIZE = 0
const CONFIG_FREERTOS_TASK_NOTIFICATION_ARRAY_ENTRIES = 1
const CONFIG_FREERTOS_TASK_FUNCTION_WRAPPER = 1
const CONFIG_FREERTOS_TLSP_DELETION_CALLBACKS = 1
const CONFIG_FREERTOS_CHECK_MUTEX_GIVEN_BY_OWNER = 1
const CONFIG_FREERTOS_ISR_STACKSIZE = 1536
const CONFIG_FREERTOS_INTERRUPT_BACKTRACE = 1
const CONFIG_FREERTOS_TICK_SUPPORT_CORETIMER = 1
const CONFIG_FREERTOS_CORETIMER_0 = 1
const CONFIG_FREERTOS_SYSTICK_USES_CCOUNT = 1
const CONFIG_FREERTOS_PORT = 1
const CONFIG_FREERTOS_NO_AFFINITY = 0x7FFFFFFF
const CONFIG_FREERTOS_SUPPORT_STATIC_ALLOCATION = 1
const CONFIG_FREERTOS_DEBUG_OCDAWARE = 1
const CONFIG_FREERTOS_ENABLE_TASK_SNAPSHOT = 1
const CONFIG_FREERTOS_PLACE_SNAPSHOT_FUNS_INTO_FLASH = 1
const CONFIG_FREERTOS_NUMBER_OF_CORES = 2
const CONFIG_HAL_ASSERTION_EQUALS_SYSTEM = 1
const CONFIG_HAL_DEFAULT_ASSERTION_LEVEL = 2
const CONFIG_HAL_SPI_MASTER_FUNC_IN_IRAM = 1
const CONFIG_HAL_SPI_SLAVE_FUNC_IN_IRAM = 1
const CONFIG_HEAP_POISONING_DISABLED = 1
const CONFIG_HEAP_TRACING_OFF = 1
const CONFIG_LOG_DEFAULT_LEVEL_INFO = 1
const CONFIG_LOG_DEFAULT_LEVEL = 3
const CONFIG_LOG_MAXIMUM_EQUALS_DEFAULT = 1
const CONFIG_LOG_MAXIMUM_LEVEL = 3
const CONFIG_LOG_DYNAMIC_LEVEL_CONTROL = 1
const CONFIG_LOG_TAG_LEVEL_IMPL_CACHE_AND_LINKED_LIST = 1
const CONFIG_LOG_TAG_LEVEL_CACHE_BINARY_MIN_HEAP = 1
const CONFIG_LOG_TAG_LEVEL_IMPL_CACHE_SIZE = 31
const CONFIG_LOG_TIMESTAMP_SOURCE_RTOS = 1
const CONFIG_LWIP_ENABLE = 1
const CONFIG_LWIP_LOCAL_HOSTNAME = "espressif"
const CONFIG_LWIP_TCPIP_TASK_PRIO = 18
const CONFIG_LWIP_DNS_SUPPORT_MDNS_QUERIES = 1
const CONFIG_LWIP_TIMERS_ONDEMAND = 1
const CONFIG_LWIP_ND6 = 1
const CONFIG_LWIP_MAX_SOCKETS = 10
const CONFIG_LWIP_SO_REUSE = 1
const CONFIG_LWIP_SO_REUSE_RXTOALL = 1
const CONFIG_LWIP_IP_DEFAULT_TTL = 64
const CONFIG_LWIP_IP4_FRAG = 1
const CONFIG_LWIP_IP6_FRAG = 1
const CONFIG_LWIP_IP_REASS_MAX_PBUFS = 10
const CONFIG_LWIP_ESP_GRATUITOUS_ARP = 1
const CONFIG_LWIP_GARP_TMR_INTERVAL = 60
const CONFIG_LWIP_ESP_MLDV6_REPORT = 1
const CONFIG_LWIP_MLDV6_TMR_INTERVAL = 40
const CONFIG_LWIP_TCPIP_RECVMBOX_SIZE = 32
const CONFIG_LWIP_DHCP_DOES_ARP_CHECK = 1
const CONFIG_LWIP_DHCP_DISABLE_VENDOR_CLASS_ID = 1
const CONFIG_LWIP_DHCP_OPTIONS_LEN = 68
const CONFIG_LWIP_NUM_NETIF_CLIENT_DATA = 0
const CONFIG_LWIP_DHCP_COARSE_TIMER_SECS = 1
const CONFIG_LWIP_DHCPS = 1
const CONFIG_LWIP_DHCPS_LEASE_UNIT = 60
const CONFIG_LWIP_DHCPS_MAX_STATION_NUM = 8
const CONFIG_LWIP_DHCPS_STATIC_ENTRIES = 1
const CONFIG_LWIP_DHCPS_ADD_DNS = 1
const CONFIG_LWIP_IPV4 = 1
const CONFIG_LWIP_IPV6 = 1
const CONFIG_LWIP_IPV6_NUM_ADDRESSES = 3
const CONFIG_LWIP_NETIF_LOOPBACK = 1
const CONFIG_LWIP_LOOPBACK_MAX_PBUFS = 8
const CONFIG_LWIP_MAX_ACTIVE_TCP = 16
const CONFIG_LWIP_MAX_LISTENING_TCP = 16
const CONFIG_LWIP_TCP_HIGH_SPEED_RETRANSMISSION = 1
const CONFIG_LWIP_TCP_MAXRTX = 12
const CONFIG_LWIP_TCP_SYNMAXRTX = 12
const CONFIG_LWIP_TCP_MSS = 1440
const CONFIG_LWIP_TCP_TMR_INTERVAL = 250
const CONFIG_LWIP_TCP_MSL = 60000
const CONFIG_LWIP_TCP_FIN_WAIT_TIMEOUT = 20000
const CONFIG_LWIP_TCP_SND_BUF_DEFAULT = 5760
const CONFIG_LWIP_TCP_WND_DEFAULT = 5760
const CONFIG_LWIP_TCP_RECVMBOX_SIZE = 6
const CONFIG_LWIP_TCP_ACCEPTMBOX_SIZE = 6
const CONFIG_LWIP_TCP_QUEUE_OOSEQ = 1
const CONFIG_LWIP_TCP_OOSEQ_TIMEOUT = 6
const CONFIG_LWIP_TCP_OOSEQ_MAX_PBUFS = 4
const CONFIG_LWIP_TCP_OVERSIZE_MSS = 1
const CONFIG_LWIP_TCP_RTO_TIME = 1500
const CONFIG_LWIP_MAX_UDP_PCBS = 16
const CONFIG_LWIP_UDP_RECVMBOX_SIZE = 6
const CONFIG_LWIP_CHECKSUM_CHECK_ICMP = 1
const CONFIG_LWIP_TCPIP_TASK_STACK_SIZE = 3072
const CONFIG_LWIP_TCPIP_TASK_AFFINITY_NO_AFFINITY = 1
const CONFIG_LWIP_TCPIP_TASK_AFFINITY = 0x7FFFFFFF
const CONFIG_LWIP_IPV6_MEMP_NUM_ND6_QUEUE = 3
const CONFIG_LWIP_IPV6_ND6_NUM_NEIGHBORS = 5
const CONFIG_LWIP_IPV6_ND6_NUM_PREFIXES = 5
const CONFIG_LWIP_IPV6_ND6_NUM_ROUTERS = 3
const CONFIG_LWIP_IPV6_ND6_NUM_DESTINATIONS = 10
const CONFIG_LWIP_ICMP = 1
const CONFIG_LWIP_MAX_RAW_PCBS = 16
const CONFIG_LWIP_SNTP_MAX_SERVERS = 1
const CONFIG_LWIP_SNTP_UPDATE_DELAY = 3600000
const CONFIG_LWIP_SNTP_STARTUP_DELAY = 1
const CONFIG_LWIP_SNTP_MAXIMUM_STARTUP_DELAY = 5000
const CONFIG_LWIP_DNS_MAX_HOST_IP = 1
const CONFIG_LWIP_DNS_MAX_SERVERS = 3
const CONFIG_LWIP_BRIDGEIF_MAX_PORTS = 7
const CONFIG_LWIP_ESP_LWIP_ASSERT = 1
const CONFIG_LWIP_HOOK_TCP_ISN_DEFAULT = 1
const CONFIG_LWIP_HOOK_IP6_ROUTE_NONE = 1
const CONFIG_LWIP_HOOK_ND6_GET_GW_NONE = 1
const CONFIG_LWIP_HOOK_IP6_SELECT_SRC_ADDR_NONE = 1
const CONFIG_LWIP_HOOK_NETCONN_EXT_RESOLVE_NONE = 1
const CONFIG_LWIP_HOOK_DNS_EXT_RESOLVE_NONE = 1
const CONFIG_LWIP_HOOK_IP6_INPUT_DEFAULT = 1
const CONFIG_MBEDTLS_INTERNAL_MEM_ALLOC = 1
const CONFIG_MBEDTLS_ASYMMETRIC_CONTENT_LEN = 1
const CONFIG_MBEDTLS_SSL_IN_CONTENT_LEN = 16384
const CONFIG_MBEDTLS_SSL_OUT_CONTENT_LEN = 4096
const CONFIG_MBEDTLS_SSL_KEEP_PEER_CERTIFICATE = 1
const CONFIG_MBEDTLS_PKCS7_C = 1
const CONFIG_MBEDTLS_CERTIFICATE_BUNDLE = 1
const CONFIG_MBEDTLS_CERTIFICATE_BUNDLE_DEFAULT_FULL = 1
const CONFIG_MBEDTLS_CERTIFICATE_BUNDLE_MAX_CERTS = 200
const CONFIG_MBEDTLS_CMAC_C = 1
const CONFIG_MBEDTLS_HARDWARE_AES = 1
const CONFIG_MBEDTLS_GCM_SUPPORT_NON_AES_CIPHER = 1
const CONFIG_MBEDTLS_HARDWARE_MPI = 1
const CONFIG_MBEDTLS_HARDWARE_SHA = 1
const CONFIG_MBEDTLS_ROM_MD5 = 1
const CONFIG_MBEDTLS_HAVE_TIME = 1
const CONFIG_MBEDTLS_ECDSA_DETERMINISTIC = 1
const CONFIG_MBEDTLS_SHA1_C = 1
const CONFIG_MBEDTLS_SHA512_C = 1
const CONFIG_MBEDTLS_TLS_SERVER_AND_CLIENT = 1
const CONFIG_MBEDTLS_TLS_SERVER = 1
const CONFIG_MBEDTLS_TLS_CLIENT = 1
const CONFIG_MBEDTLS_TLS_ENABLED = 1
const CONFIG_MBEDTLS_KEY_EXCHANGE_RSA = 1
const CONFIG_MBEDTLS_KEY_EXCHANGE_ELLIPTIC_CURVE = 1
const CONFIG_MBEDTLS_KEY_EXCHANGE_ECDHE_RSA = 1
const CONFIG_MBEDTLS_KEY_EXCHANGE_ECDHE_ECDSA = 1
const CONFIG_MBEDTLS_KEY_EXCHANGE_ECDH_ECDSA = 1
const CONFIG_MBEDTLS_KEY_EXCHANGE_ECDH_RSA = 1
const CONFIG_MBEDTLS_SSL_RENEGOTIATION = 1
const CONFIG_MBEDTLS_SSL_PROTO_TLS1_2 = 1
const CONFIG_MBEDTLS_SSL_ALPN = 1
const CONFIG_MBEDTLS_CLIENT_SSL_SESSION_TICKETS = 1
const CONFIG_MBEDTLS_SERVER_SSL_SESSION_TICKETS = 1
const CONFIG_MBEDTLS_AES_C = 1
const CONFIG_MBEDTLS_CCM_C = 1
const CONFIG_MBEDTLS_GCM_C = 1
const CONFIG_MBEDTLS_PEM_PARSE_C = 1
const CONFIG_MBEDTLS_PEM_WRITE_C = 1
const CONFIG_MBEDTLS_X509_CRL_PARSE_C = 1
const CONFIG_MBEDTLS_X509_CSR_PARSE_C = 1
const CONFIG_MBEDTLS_ECP_C = 1
const CONFIG_MBEDTLS_PK_PARSE_EC_EXTENDED = 1
const CONFIG_MBEDTLS_PK_PARSE_EC_COMPRESSED = 1
const CONFIG_MBEDTLS_ECDH_C = 1
const CONFIG_MBEDTLS_ECDSA_C = 1
const CONFIG_MBEDTLS_ECP_DP_SECP192R1_ENABLED = 1
const CONFIG_MBEDTLS_ECP_DP_SECP224R1_ENABLED = 1
const CONFIG_MBEDTLS_ECP_DP_SECP256R1_ENABLED = 1
const CONFIG_MBEDTLS_ECP_DP_SECP384R1_ENABLED = 1
const CONFIG_MBEDTLS_ECP_DP_SECP521R1_ENABLED = 1
const CONFIG_MBEDTLS_ECP_DP_SECP192K1_ENABLED = 1
const CONFIG_MBEDTLS_ECP_DP_SECP224K1_ENABLED = 1
const CONFIG_MBEDTLS_ECP_DP_SECP256K1_ENABLED = 1
const CONFIG_MBEDTLS_ECP_DP_BP256R1_ENABLED = 1
const CONFIG_MBEDTLS_ECP_DP_BP384R1_ENABLED = 1
const CONFIG_MBEDTLS_ECP_DP_BP512R1_ENABLED = 1
const CONFIG_MBEDTLS_ECP_DP_CURVE25519_ENABLED = 1
const CONFIG_MBEDTLS_ECP_NIST_OPTIM = 1
const CONFIG_MBEDTLS_ERROR_STRINGS = 1
const CONFIG_MBEDTLS_FS_IO = 1
const CONFIG_MQTT_PROTOCOL_311 = 1
const CONFIG_MQTT_TRANSPORT_SSL = 1
const CONFIG_MQTT_TRANSPORT_WEBSOCKET = 1
const CONFIG_MQTT_TRANSPORT_WEBSOCKET_SECURE = 1
const CONFIG_NEWLIB_STDOUT_LINE_ENDING_CRLF = 1
const CONFIG_NEWLIB_STDIN_LINE_ENDING_CR = 1
const CONFIG_NEWLIB_TIME_SYSCALL_USE_RTC_HRT = 1
const CONFIG_ESP_PROTOCOMM_SUPPORT_SECURITY_VERSION_0 = 1
const CONFIG_ESP_PROTOCOMM_SUPPORT_SECURITY_VERSION_1 = 1
const CONFIG_ESP_PROTOCOMM_SUPPORT_SECURITY_VERSION_2 = 1
const CONFIG_ESP_PROTOCOMM_SUPPORT_SECURITY_PATCH_VERSION = 1
const CONFIG_PTHREAD_TASK_PRIO_DEFAULT = 5
const CONFIG_PTHREAD_TASK_STACK_SIZE_DEFAULT = 3072
const CONFIG_PTHREAD_STACK_MIN = 768
const CONFIG_PTHREAD_DEFAULT_CORE_NO_AFFINITY = 1
const CONFIG_PTHREAD_TASK_NAME_DEFAULT = "pthread"
const CONFIG_MMU_PAGE_SIZE_64KB = 1
const CONFIG_MMU_PAGE_MODE = "64KB"
const CONFIG_MMU_PAGE_SIZE = 0x10000
const CONFIG_SPI_FLASH_BROWNOUT_RESET_XMC = 1
const CONFIG_SPI_FLASH_BROWNOUT_RESET = 1
const CONFIG_SPI_FLASH_SUSPEND_TSUS_VAL_US = 50
const CONFIG_SPI_FLASH_ROM_DRIVER_PATCH = 1
const CONFIG_SPI_FLASH_DANGEROUS_WRITE_ABORTS = 1
const CONFIG_SPI_FLASH_YIELD_DURING_ERASE = 1
const CONFIG_SPI_FLASH_ERASE_YIELD_DURATION_MS = 20
const CONFIG_SPI_FLASH_ERASE_YIELD_TICKS = 1
const CONFIG_SPI_FLASH_WRITE_CHUNK_SIZE = 8192
const CONFIG_SPI_FLASH_VENDOR_XMC_SUPPORTED = 1
const CONFIG_SPI_FLASH_VENDOR_GD_SUPPORTED = 1
const CONFIG_SPI_FLASH_VENDOR_ISSI_SUPPORTED = 1
const CONFIG_SPI_FLASH_VENDOR_MXIC_SUPPORTED = 1
const CONFIG_SPI_FLASH_VENDOR_WINBOND_SUPPORTED = 1
const CONFIG_SPI_FLASH_SUPPORT_ISSI_CHIP = 1
const CONFIG_SPI_FLASH_SUPPORT_MXIC_CHIP = 1
const CONFIG_SPI_FLASH_SUPPORT_GD_CHIP = 1
const CONFIG_SPI_FLASH_SUPPORT_WINBOND_CHIP = 1
const CONFIG_SPI_FLASH_ENABLE_ENCRYPTED_READ_WRITE = 1
const CONFIG_SPIFFS_MAX_PARTITIONS = 3
const CONFIG_SPIFFS_CACHE = 1
const CONFIG_SPIFFS_CACHE_WR = 1
const CONFIG_SPIFFS_PAGE_CHECK = 1
const CONFIG_SPIFFS_GC_MAX_RUNS = 10
const CONFIG_SPIFFS_PAGE_SIZE = 256
const CONFIG_SPIFFS_OBJ_NAME_LEN = 32
const CONFIG_SPIFFS_USE_MAGIC = 1
const CONFIG_SPIFFS_USE_MAGIC_LENGTH = 1
const CONFIG_SPIFFS_META_LENGTH = 4
const CONFIG_SPIFFS_USE_MTIME = 1
const CONFIG_WS_TRANSPORT = 1
const CONFIG_WS_BUFFER_SIZE = 1024
const CONFIG_UNITY_ENABLE_FLOAT = 1
const CONFIG_UNITY_ENABLE_DOUBLE = 1
const CONFIG_UNITY_ENABLE_IDF_TEST_RUNNER = 1
const CONFIG_VFS_SUPPORT_IO = 1
const CONFIG_VFS_SUPPORT_DIR = 1
const CONFIG_VFS_SUPPORT_SELECT = 1
const CONFIG_VFS_SUPPRESS_SELECT_DEBUG_OUTPUT = 1
const CONFIG_VFS_SUPPORT_TERMIOS = 1
const CONFIG_VFS_MAX_COUNT = 8
const CONFIG_VFS_SEMIHOSTFS_MAX_MOUNT_POINTS = 1
const CONFIG_VFS_INITIALIZE_DEV_NULL = 1
const CONFIG_WL_SECTOR_SIZE_4096 = 1
const CONFIG_WL_SECTOR_SIZE = 4096
const CONFIG_WIFI_PROV_SCAN_MAX_ENTRIES = 16
const CONFIG_WIFI_PROV_AUTOSTOP_TIMEOUT = 30
const CONFIG_WIFI_PROV_STA_ALL_CHANNEL_SCAN = 1
const X_NEWLIB_VERSION_H__ = 1
const X_NEWLIB_VERSION = "4.3.0"
const X__NEWLIB__ = 4
const X__NEWLIB_MINOR__ = 3
const X__NEWLIB_PATCHLEVEL__ = 0
const X_ATFILE_SOURCE = 1
const X_DEFAULT_SOURCE = 1
const X_ISOC99_SOURCE = 1
const X_ISOC11_SOURCE = 1
const X_POSIX_SOURCE = 1
const X_XOPEN_SOURCE = 700
const X_XOPEN_SOURCE_EXTENDED = 1
const X__ATFILE_VISIBLE = 1
const X__BSD_VISIBLE = 1
const X__GNU_VISIBLE = 1
const X__ISO_C_VISIBLE = 2011
const X__LARGEFILE_VISIBLE = 1
const X__MISC_VISIBLE = 1
const X__POSIX_VISIBLE = 200809
const X__SVID_VISIBLE = 1
const X__XSI_VISIBLE = 700
const X__SSP_FORTIFY_LEVEL = 0
const X_POSIX_THREADS = 1
const X_POSIX_TIMEOUTS = 1
const X_POSIX_TIMERS = 1
const X_UNIX98_THREAD_MUTEX_ATTRIBUTES = 1
const X__have_longlong64 = 1
const X__have_long32 = 1
const X___int8_t_defined = 1
const X___int16_t_defined = 1
const X___int32_t_defined = 1
const X___int64_t_defined = 1
const X___int_least8_t_defined = 1
const X___int_least16_t_defined = 1
const X___int_least32_t_defined = 1
const X___int_least64_t_defined = 1
const X__INT8 = "hh"
const X__INT16 = "h"
const X__INT64 = "ll"
const X__FAST8 = "hh"
const X__FAST16 = "h"
const X__FAST64 = "ll"
const X__LEAST8 = "hh"
const X__LEAST16 = "h"
const X__LEAST64 = "ll"
const X__int8_t_defined = 1
const X__int16_t_defined = 1
const X__int32_t_defined = 1
const X__int64_t_defined = 1
const X__int_least8_t_defined = 1
const X__int_least16_t_defined = 1
const X__int_least32_t_defined = 1
const X__int_least64_t_defined = 1
const X__int_fast8_t_defined = 1
const X__int_fast16_t_defined = 1
const X__int_fast32_t_defined = 1
const X__int_fast64_t_defined = 1
const X__bool_true_false_are_defined = 1
const True = 1
const False = 0
const X__NEWLIB_H__ = 1
const X_ATEXIT_DYNAMIC_ALLOC = 1
const X_FSEEK_OPTIMIZATION = 1
const X_FVWRITE_IN_STREAMIO = 1
const X_HAVE_INITFINI_ARRAY = 1
const X_HAVE_LONG_DOUBLE = 1
const X_ICONV_ENABLED = 1
const X_LDBL_EQ_DBL = 1
const X_MB_LEN_MAX = 1
const X_NANO_MALLOC = 1
const X_REENT_CHECK_VERIFY = 1
const X_RETARGETABLE_LOCKING = 1
const X_UNBUF_STREAM_OPT = 1
const X_WANT_IO_C99_FORMATS = 1
const X_WANT_IO_LONG_LONG = 1
const X_WANT_IO_POS_ARGS = 1
const X_WANT_REENT_BACKWARD_BINARY_COMPAT = 1
const X_WANT_REENT_SMALL = 1
const X_WANT_USE_GDTOA = 1
const X__OBSOLETE_MATH_DEFAULT = 1
const X__BUFSIZ__ = 128
const X__RAND_MAX = 0x7fffffff
const X__GNUCLIKE_ASM = 3
const X__GNUCLIKE___TYPEOF = 1
const X__GNUCLIKE___SECTION = 1
const X__GNUCLIKE_CTOR_SECTION_HANDLING = 1
const X__GNUCLIKE_BUILTIN_CONSTANT_P = 1
const X__GNUCLIKE_BUILTIN_VARARGS = 1
const X__GNUCLIKE_BUILTIN_STDARG = 1
const X__GNUCLIKE_BUILTIN_VAALIST = 1
const X__GNUC_VA_LIST_COMPATIBILITY = 1
const X__GNUCLIKE_BUILTIN_NEXT_ARG = 1
const X__GNUCLIKE_BUILTIN_MEMCPY = 1
const X__CC_SUPPORTS_INLINE = 1
const X__CC_SUPPORTS___INLINE = 1
const X__CC_SUPPORTS___INLINE__ = 1
const X__CC_SUPPORTS___FUNC__ = 1
const X__CC_SUPPORTS_WARNING = 1
const X__CC_SUPPORTS_VARADIC_XXX = 1
const X__CC_SUPPORTS_DYNAMIC_ARRAY_INIT = 1
const X_NULL = 0
const X_ATEXIT_SIZE = 32
const X_REENT_EMERGENCY_SIZE = 25
const X_REENT_ASCTIME_SIZE = 26
const X_REENT_SIGNAL_SIZE = 24
const EXIT_FAILURE = 1
const EXIT_SUCCESS = 0
const X__SLBF = 0x0001
const X__SNBF = 0x0002
const X__SRD = 0x0004
const X__SWR = 0x0008
const X__SRW = 0x0010
const X__SEOF = 0x0020
const X__SERR = 0x0040
const X__SMBF = 0x0080
const X__SAPP = 0x0100
const X__SSTR = 0x0200
const X__SOPT = 0x0400
const X__SNPT = 0x0800
const X__SOFF = 0x1000
const X__SORD = 0x2000
const X__SL64 = 0x8000
const X__SNLK = 0x0001
const X__SWID = 0x2000
const X_IOFBF = 0
const X_IOLBF = 1
const X_IONBF = 2
const FOPEN_MAX = 20
const FILENAME_MAX = 1024
const P_tmpdir = "/tmp"
const SEEK_SET = 0
const SEEK_CUR = 1
const SEEK_END = 2
const TMP_MAX = 26
const L_cuserid = 9
const L_ctermid = 16
const ESP_OK = 0
const ESP_ERR_NO_MEM = 0x101
const ESP_ERR_INVALID_ARG = 0x102
const ESP_ERR_INVALID_STATE = 0x103
const ESP_ERR_INVALID_SIZE = 0x104
const ESP_ERR_NOT_FOUND = 0x105
const ESP_ERR_NOT_SUPPORTED = 0x106
const ESP_ERR_TIMEOUT = 0x107
const ESP_ERR_INVALID_RESPONSE = 0x108
const ESP_ERR_INVALID_CRC = 0x109
const ESP_ERR_INVALID_VERSION = 0x10A
const ESP_ERR_INVALID_MAC = 0x10B
const ESP_ERR_NOT_FINISHED = 0x10C
const ESP_ERR_NOT_ALLOWED = 0x10D
const ESP_ERR_WIFI_BASE = 0x3000
const ESP_ERR_MESH_BASE = 0x4000
const ESP_ERR_FLASH_BASE = 0x6000
const ESP_ERR_HW_CRYPTO_BASE = 0xc000
const ESP_ERR_MEMPROT_BASE = 0xd000
const SOC_CAPS_ECO_VER_MAX = 301
const SOC_ADC_SUPPORTED = 1
const SOC_DAC_SUPPORTED = 1
const SOC_UART_SUPPORTED = 1
const SOC_MCPWM_SUPPORTED = 1
const SOC_GPTIMER_SUPPORTED = 1
const SOC_SDMMC_HOST_SUPPORTED = 1
const SOC_BT_SUPPORTED = 1
const SOC_PCNT_SUPPORTED = 1
const SOC_PHY_SUPPORTED = 1
const SOC_WIFI_SUPPORTED = 1
const SOC_SDIO_SLAVE_SUPPORTED = 1
const SOC_TWAI_SUPPORTED = 1
const SOC_EFUSE_SUPPORTED = 1
const SOC_EMAC_SUPPORTED = 1
const SOC_ULP_SUPPORTED = 1
const SOC_CCOMP_TIMER_SUPPORTED = 1
const SOC_RTC_FAST_MEM_SUPPORTED = 1
const SOC_RTC_SLOW_MEM_SUPPORTED = 1
const SOC_RTC_MEM_SUPPORTED = 1
const SOC_I2S_SUPPORTED = 1
const SOC_RMT_SUPPORTED = 1
const SOC_SDM_SUPPORTED = 1
const SOC_GPSPI_SUPPORTED = 1
const SOC_LEDC_SUPPORTED = 1
const SOC_I2C_SUPPORTED = 1
const SOC_SUPPORT_COEXISTENCE = 1
const SOC_AES_SUPPORTED = 1
const SOC_MPI_SUPPORTED = 1
const SOC_SHA_SUPPORTED = 1
const SOC_FLASH_ENC_SUPPORTED = 1
const SOC_SECURE_BOOT_SUPPORTED = 1
const SOC_TOUCH_SENSOR_SUPPORTED = 1
const SOC_BOD_SUPPORTED = 1
const SOC_ULP_FSM_SUPPORTED = 1
const SOC_CLK_TREE_SUPPORTED = 1
const SOC_MPU_SUPPORTED = 1
const SOC_WDT_SUPPORTED = 1
const SOC_SPI_FLASH_SUPPORTED = 1
const SOC_RNG_SUPPORTED = 1
const SOC_LIGHT_SLEEP_SUPPORTED = 1
const SOC_DEEP_SLEEP_SUPPORTED = 1
const SOC_LP_PERIPH_SHARE_INTERRUPT = 1
const SOC_PM_SUPPORTED = 1
const SOC_DPORT_WORKAROUND = 1
const SOC_XTAL_SUPPORT_26M = 1
const SOC_XTAL_SUPPORT_40M = 1
const SOC_XTAL_SUPPORT_AUTO_DETECT = 1
const SOC_ADC_RTC_CTRL_SUPPORTED = 1
const SOC_ADC_DIG_CTRL_SUPPORTED = 1
const SOC_ADC_DMA_SUPPORTED = 1
const SOC_ADC_SHARED_POWER = 1
const SOC_SHARED_IDCACHE_SUPPORTED = 1
const SOC_IDCACHE_PER_CORE = 1
const SOC_CPU_CORES_NUM = 2
const SOC_CPU_INTR_NUM = 32
const SOC_CPU_HAS_FPU = 1
const SOC_HP_CPU_HAS_MULTIPLE_CORES = 1
const SOC_CPU_BREAKPOINTS_NUM = 2
const SOC_CPU_WATCHPOINTS_NUM = 2
const SOC_CPU_WATCHPOINT_MAX_REGION_SIZE = 64
const SOC_DAC_CHAN_NUM = 2
const SOC_DAC_RESOLUTION = 8
const SOC_DAC_DMA_16BIT_ALIGN = 1
const SOC_GPIO_PIN_COUNT = 40
const SOC_GPIO_IN_RANGE_MAX = 39
const SOC_GPIO_OUT_RANGE_MAX = 33
const SOC_MMU_PERIPH_NUM = 2
const SOC_MMU_LINEAR_ADDRESS_REGION_NUM = 3
const SOC_MPU_CONFIGURABLE_REGIONS_SUPPORTED = 0
const SOC_MPU_REGIONS_MAX_NUM = 8
const SOC_MPU_REGION_RO_SUPPORTED = 0
const SOC_MPU_REGION_WO_SUPPORTED = 0
const SOC_RMT_TX_CANDIDATES_PER_GROUP = 8
const SOC_RMT_RX_CANDIDATES_PER_GROUP = 8
const SOC_RMT_CHANNELS_PER_GROUP = 8
const SOC_RMT_MEM_WORDS_PER_CHANNEL = 64
const SOC_RMT_SUPPORT_REF_TICK = 1
const SOC_RMT_SUPPORT_APB = 1
const SOC_RMT_CHANNEL_CLK_INDEPENDENT = 1
const SOC_RTCIO_PIN_COUNT = 18
const SOC_RTCIO_INPUT_OUTPUT_SUPPORTED = 1
const SOC_RTCIO_HOLD_SUPPORTED = 1
const SOC_RTCIO_WAKE_SUPPORTED = 1
const SOC_SDM_CHANNELS_PER_GROUP = 8
const SOC_SDM_CLK_SUPPORT_APB = 1
const SOC_SPI_HD_BOTH_INOUT_SUPPORTED = 1
const SOC_SPI_AS_CS_SUPPORTED = 1
const SOC_SPI_PERIPH_NUM = 3
const SOC_SPI_DMA_CHAN_NUM = 2
const SOC_SPI_MAX_CS_NUM = 3
const SOC_SPI_SUPPORT_CLK_APB = 1
const SOC_SPI_MAXIMUM_BUFFER_SIZE = 64
const SOC_SPI_MAX_PRE_DIVIDER = 8192
const SOC_MEMSPI_SRC_FREQ_80M_SUPPORTED = 1
const SOC_MEMSPI_SRC_FREQ_40M_SUPPORTED = 1
const SOC_MEMSPI_SRC_FREQ_26M_SUPPORTED = 1
const SOC_MEMSPI_SRC_FREQ_20M_SUPPORTED = 1
const SOC_LP_TIMER_BIT_WIDTH_LO = 32
const SOC_LP_TIMER_BIT_WIDTH_HI = 16
const SOC_TWAI_BRP_MIN = 2
const SOC_TWAI_BRP_MAX = 128
const SOC_TWAI_CLK_SUPPORT_APB = 1
const SOC_TWAI_SUPPORT_MULTI_ADDRESS_LAYOUT = 1
const SOC_SPIRAM_SUPPORTED = 1
const SOC_SECURE_BOOT_V1 = 1
const SOC_EFUSE_SECURE_BOOT_KEY_DIGESTS = 1
const SOC_SDMMC_USE_IOMUX = 1
const SOC_SDMMC_NUM_SLOTS = 2
const BIT31 = 0x80000000
const BIT30 = 0x40000000
const BIT29 = 0x20000000
const BIT28 = 0x10000000
const BIT27 = 0x08000000
const BIT26 = 0x04000000
const BIT25 = 0x02000000
const BIT24 = 0x01000000
const BIT23 = 0x00800000
const BIT22 = 0x00400000
const BIT21 = 0x00200000
const BIT20 = 0x00100000
const BIT19 = 0x00080000
const BIT18 = 0x00040000
const BIT17 = 0x00020000
const BIT16 = 0x00010000
const BIT15 = 0x00008000
const BIT14 = 0x00004000
const BIT13 = 0x00002000
const BIT12 = 0x00001000
const BIT11 = 0x00000800
const BIT10 = 0x00000400
const BIT9 = 0x00000200
const BIT8 = 0x00000100
const BIT7 = 0x00000080
const BIT6 = 0x00000040
const BIT5 = 0x00000020
const BIT4 = 0x00000010
const BIT3 = 0x00000008
const BIT2 = 0x00000004
const BIT1 = 0x00000002
const BIT0 = 0x00000001
const DR_REG_DPORT_BASE = 0x3ff00000
const DR_REG_AES_BASE = 0x3ff01000
const DR_REG_RSA_BASE = 0x3ff02000
const DR_REG_SHA_BASE = 0x3ff03000
const DR_REG_FLASH_MMU_TABLE_PRO = 0x3ff10000
const DR_REG_FLASH_MMU_TABLE_APP = 0x3ff12000
const DR_REG_DPORT_END = 0x3ff13FFC
const DR_REG_UART_BASE = 0x3ff40000
const DR_REG_SPI1_BASE = 0x3ff42000
const DR_REG_SPI0_BASE = 0x3ff43000
const DR_REG_GPIO_BASE = 0x3ff44000
const DR_REG_GPIO_SD_BASE = 0x3ff44f00
const DR_REG_FE2_BASE = 0x3ff45000
const DR_REG_FE_BASE = 0x3ff46000
const DR_REG_FRC_TIMER_BASE = 0x3ff47000
const DR_REG_RTCCNTL_BASE = 0x3ff48000
const DR_REG_RTCIO_BASE = 0x3ff48400
const DR_REG_SENS_BASE = 0x3ff48800
const DR_REG_RTC_I2C_BASE = 0x3ff48C00
const DR_REG_IO_MUX_BASE = 0x3ff49000
const DR_REG_HINF_BASE = 0x3ff4B000
const DR_REG_UHCI1_BASE = 0x3ff4C000
const DR_REG_I2S_BASE = 0x3ff4F000
const DR_REG_UART1_BASE = 0x3ff50000
const DR_REG_BT_BASE = 0x3ff51000
const DR_REG_I2C_EXT_BASE = 0x3ff53000
const DR_REG_UHCI0_BASE = 0x3ff54000
const DR_REG_SLCHOST_BASE = 0x3ff55000
const DR_REG_RMT_BASE = 0x3ff56000
const DR_REG_PCNT_BASE = 0x3ff57000
const DR_REG_SLC_BASE = 0x3ff58000
const DR_REG_LEDC_BASE = 0x3ff59000
const DR_REG_EFUSE_BASE = 0x3ff5A000
const DR_REG_SPI_ENCRYPT_BASE = 0x3ff5B000
const DR_REG_NRX_BASE = 0x3ff5CC00
const DR_REG_BB_BASE = 0x3ff5D000
const DR_REG_PWM0_BASE = 0x3ff5E000
const DR_REG_TIMERGROUP0_BASE = 0x3ff5F000
const DR_REG_TIMERGROUP1_BASE = 0x3ff60000
const DR_REG_RTCMEM0_BASE = 0x3ff61000
const DR_REG_RTCMEM1_BASE = 0x3ff62000
const DR_REG_RTCMEM2_BASE = 0x3ff63000
const DR_REG_SPI2_BASE = 0x3ff64000
const DR_REG_SPI3_BASE = 0x3ff65000
const DR_REG_SYSCON_BASE = 0x3ff66000
const DR_REG_APB_CTRL_BASE = 0x3ff66000
const DR_REG_I2C1_EXT_BASE = 0x3ff67000
const DR_REG_SDMMC_BASE = 0x3ff68000
const DR_REG_EMAC_BASE = 0x3ff69000
const DR_REG_CAN_BASE = 0x3ff6B000
const DR_REG_PWM1_BASE = 0x3ff6C000
const DR_REG_I2S1_BASE = 0x3ff6D000
const DR_REG_UART2_BASE = 0x3ff6E000
const SOC_MAX_CONTIGUOUS_RAM_SIZE = 0x400000
const SPI_CLK_DIV = 4
const TICKS_PER_US_ROM = 26
const SOC_DROM_LOW = 0x3F400000
const SOC_DROM_HIGH = 0x3F800000
const SOC_DRAM_LOW = 0x3FFAE000
const SOC_DRAM_HIGH = 0x40000000
const SOC_IROM_LOW = 0x400D0000
const SOC_IROM_HIGH = 0x40400000
const SOC_IROM_MASK_LOW = 0x40000000
const SOC_IROM_MASK_HIGH = 0x40070000
const SOC_CACHE_PRO_LOW = 0x40070000
const SOC_CACHE_PRO_HIGH = 0x40078000
const SOC_CACHE_APP_LOW = 0x40078000
const SOC_CACHE_APP_HIGH = 0x40080000
const SOC_IRAM_LOW = 0x40080000
const SOC_IRAM_HIGH = 0x400AA000
const SOC_RTC_IRAM_LOW = 0x400C0000
const SOC_RTC_IRAM_HIGH = 0x400C2000
const SOC_RTC_DRAM_LOW = 0x3FF80000
const SOC_RTC_DRAM_HIGH = 0x3FF82000
const SOC_RTC_DATA_LOW = 0x50000000
const SOC_RTC_DATA_HIGH = 0x50002000
const SOC_EXTRAM_DATA_LOW = 0x3F800000
const SOC_EXTRAM_DATA_HIGH = 0x3FC00000
const SOC_DIRAM_IRAM_LOW = 0x400A0000
const SOC_DIRAM_IRAM_HIGH = 0x400C0000
const SOC_DIRAM_DRAM_LOW = 0x3FFE0000
const SOC_DIRAM_DRAM_HIGH = 0x40000000
const SOC_DIRAM_INVERTED = 1
const SOC_DMA_LOW = 0x3FFAE000
const SOC_DMA_HIGH = 0x40000000
const SOC_BYTE_ACCESSIBLE_LOW = 0x3FF90000
const SOC_BYTE_ACCESSIBLE_HIGH = 0x40000000
const SOC_MEM_INTERNAL_LOW = 0x3FF90000
const SOC_MEM_INTERNAL_HIGH = 0x400C2000
const SOC_ROM_STACK_START = 0x3ffe3f20
const ETS_WMAC_INUM = 0
const ETS_BT_HOST_INUM = 1
const ETS_WBB_INUM = 4
const ETS_T1_WDT_INUM = 24
const ETS_MEMACCESS_ERR_INUM = 25
const ETS_IPC_ISR_INUM = 28
const ETS_SLC_INUM = 1
const ETS_UART0_INUM = 5
const ETS_UART1_INUM = 5
const ETS_INVALID_INUM = 6
const RTCIO_GPIO36_CHANNEL = 0
const RTCIO_CHANNEL_0_GPIO_NUM = 36
const RTCIO_GPIO37_CHANNEL = 1
const RTCIO_CHANNEL_1_GPIO_NUM = 37
const RTCIO_GPIO38_CHANNEL = 2
const RTCIO_CHANNEL_2_GPIO_NUM = 38
const RTCIO_GPIO39_CHANNEL = 3
const RTCIO_CHANNEL_3_GPIO_NUM = 39
const RTCIO_GPIO34_CHANNEL = 4
const RTCIO_CHANNEL_4_GPIO_NUM = 34
const RTCIO_GPIO35_CHANNEL = 5
const RTCIO_CHANNEL_5_GPIO_NUM = 35
const RTCIO_GPIO25_CHANNEL = 6
const RTCIO_CHANNEL_6_GPIO_NUM = 25
const RTCIO_GPIO26_CHANNEL = 7
const RTCIO_CHANNEL_7_GPIO_NUM = 26
const RTCIO_GPIO33_CHANNEL = 8
const RTCIO_CHANNEL_8_GPIO_NUM = 33
const RTCIO_GPIO32_CHANNEL = 9
const RTCIO_CHANNEL_9_GPIO_NUM = 32
const RTCIO_GPIO4_CHANNEL = 10
const RTCIO_CHANNEL_10_GPIO_NUM = 4
const RTCIO_GPIO0_CHANNEL = 11
const RTCIO_CHANNEL_11_GPIO_NUM = 0
const RTCIO_GPIO2_CHANNEL = 12
const RTCIO_CHANNEL_12_GPIO_NUM = 2
const RTCIO_GPIO15_CHANNEL = 13
const RTCIO_CHANNEL_13_GPIO_NUM = 15
const RTCIO_GPIO13_CHANNEL = 14
const RTCIO_CHANNEL_14_GPIO_NUM = 13
const RTCIO_GPIO12_CHANNEL = 15
const RTCIO_CHANNEL_15_GPIO_NUM = 12
const RTCIO_GPIO14_CHANNEL = 16
const RTCIO_CHANNEL_16_GPIO_NUM = 14
const RTCIO_GPIO27_CHANNEL = 17
const RTCIO_CHANNEL_17_GPIO_NUM = 27
const SLP_OE_V = 1
const SLP_OE_S = 0
const SLP_SEL_V = 1
const SLP_SEL_S = 1
const SLP_PD_V = 1
const SLP_PD_S = 2
const SLP_PU_V = 1
const SLP_PU_S = 3
const SLP_IE_V = 1
const SLP_IE_S = 4
const SLP_DRV = 0x3
const SLP_DRV_V = 0x3
const SLP_DRV_S = 5
const FUN_PD_V = 1
const FUN_PD_S = 7
const FUN_PU_V = 1
const FUN_PU_S = 8
const FUN_IE_V = 1
const FUN_IE_S = 9
const FUN_DRV = 0x3
const FUN_DRV_V = 0x3
const FUN_DRV_S = 10
const MCU_SEL = 0x7
const MCU_SEL_V = 0x7
const MCU_SEL_S = 12
const PIN_FUNC_GPIO = 2
const SPI_CLK_GPIO_NUM = 6
const SPI_CS0_GPIO_NUM = 11
const SPI_Q_GPIO_NUM = 7
const SPI_D_GPIO_NUM = 8
const SPI_WP_GPIO_NUM = 10
const SPI_HD_GPIO_NUM = 9
const XTAL32K_P_GPIO_NUM = 32
const XTAL32K_N_GPIO_NUM = 33
const CLK_OUT3 = 0xf
const CLK_OUT3_S = 8
const CLK_OUT2 = 0xf
const CLK_OUT2_S = 4
const CLK_OUT1 = 0xf
const CLK_OUT1_S = 0
const FUNC_GPIO0_EMAC_TX_CLK = 5
const FUNC_GPIO0_GPIO0 = 2
const FUNC_GPIO0_CLK_OUT1 = 1
const FUNC_GPIO0_GPIO0_0 = 0
const FUNC_U0TXD_EMAC_RXD2 = 5
const FUNC_U0TXD_GPIO1 = 2
const FUNC_U0TXD_CLK_OUT3 = 1
const FUNC_U0TXD_U0TXD = 0
const FUNC_GPIO2_SD_DATA0 = 4
const FUNC_GPIO2_HS2_DATA0 = 3
const FUNC_GPIO2_GPIO2 = 2
const FUNC_GPIO2_HSPIWP = 1
const FUNC_GPIO2_GPIO2_0 = 0
const FUNC_U0RXD_GPIO3 = 2
const FUNC_U0RXD_CLK_OUT2 = 1
const FUNC_U0RXD_U0RXD = 0
const FUNC_GPIO4_EMAC_TX_ER = 5
const FUNC_GPIO4_SD_DATA1 = 4
const FUNC_GPIO4_HS2_DATA1 = 3
const FUNC_GPIO4_GPIO4 = 2
const FUNC_GPIO4_HSPIHD = 1
const FUNC_GPIO4_GPIO4_0 = 0
const FUNC_GPIO5_EMAC_RX_CLK = 5
const FUNC_GPIO5_HS1_DATA6 = 3
const FUNC_GPIO5_GPIO5 = 2
const FUNC_GPIO5_VSPICS0 = 1
const FUNC_GPIO5_GPIO5_0 = 0
const FUNC_SD_CLK_U1CTS = 4
const FUNC_SD_CLK_HS1_CLK = 3
const FUNC_SD_CLK_GPIO6 = 2
const FUNC_SD_CLK_SPICLK = 1
const FUNC_SD_CLK_SD_CLK = 0
const FUNC_SD_DATA0_U2RTS = 4
const FUNC_SD_DATA0_HS1_DATA0 = 3
const FUNC_SD_DATA0_GPIO7 = 2
const FUNC_SD_DATA0_SPIQ = 1
const FUNC_SD_DATA0_SD_DATA0 = 0
const FUNC_SD_DATA1_U2CTS = 4
const FUNC_SD_DATA1_HS1_DATA1 = 3
const FUNC_SD_DATA1_GPIO8 = 2
const FUNC_SD_DATA1_SPID = 1
const FUNC_SD_DATA1_SD_DATA1 = 0
const FUNC_SD_DATA2_U1RXD = 4
const FUNC_SD_DATA2_HS1_DATA2 = 3
const FUNC_SD_DATA2_GPIO9 = 2
const FUNC_SD_DATA2_SPIHD = 1
const FUNC_SD_DATA2_SD_DATA2 = 0
const FUNC_SD_DATA3_U1TXD = 4
const FUNC_SD_DATA3_HS1_DATA3 = 3
const FUNC_SD_DATA3_GPIO10 = 2
const FUNC_SD_DATA3_SPIWP = 1
const FUNC_SD_DATA3_SD_DATA3 = 0
const FUNC_SD_CMD_U1RTS = 4
const FUNC_SD_CMD_HS1_CMD = 3
const FUNC_SD_CMD_GPIO11 = 2
const FUNC_SD_CMD_SPICS0 = 1
const FUNC_SD_CMD_SD_CMD = 0
const FUNC_MTDI_EMAC_TXD3 = 5
const FUNC_MTDI_SD_DATA2 = 4
const FUNC_MTDI_HS2_DATA2 = 3
const FUNC_MTDI_GPIO12 = 2
const FUNC_MTDI_HSPIQ = 1
const FUNC_MTDI_MTDI = 0
const FUNC_MTCK_EMAC_RX_ER = 5
const FUNC_MTCK_SD_DATA3 = 4
const FUNC_MTCK_HS2_DATA3 = 3
const FUNC_MTCK_GPIO13 = 2
const FUNC_MTCK_HSPID = 1
const FUNC_MTCK_MTCK = 0
const FUNC_MTMS_EMAC_TXD2 = 5
const FUNC_MTMS_SD_CLK = 4
const FUNC_MTMS_HS2_CLK = 3
const FUNC_MTMS_GPIO14 = 2
const FUNC_MTMS_HSPICLK = 1
const FUNC_MTMS_MTMS = 0
const FUNC_MTDO_EMAC_RXD3 = 5
const FUNC_MTDO_SD_CMD = 4
const FUNC_MTDO_HS2_CMD = 3
const FUNC_MTDO_GPIO15 = 2
const FUNC_MTDO_HSPICS0 = 1
const FUNC_MTDO_MTDO = 0
const FUNC_GPIO16_EMAC_CLK_OUT = 5
const FUNC_GPIO16_U2RXD = 4
const FUNC_GPIO16_HS1_DATA4 = 3
const FUNC_GPIO16_GPIO16 = 2
const FUNC_GPIO16_GPIO16_0 = 0
const FUNC_GPIO17_EMAC_CLK_OUT_180 = 5
const FUNC_GPIO17_U2TXD = 4
const FUNC_GPIO17_HS1_DATA5 = 3
const FUNC_GPIO17_GPIO17 = 2
const FUNC_GPIO17_GPIO17_0 = 0
const FUNC_GPIO18_HS1_DATA7 = 3
const FUNC_GPIO18_GPIO18 = 2
const FUNC_GPIO18_VSPICLK = 1
const FUNC_GPIO18_GPIO18_0 = 0
const FUNC_GPIO19_EMAC_TXD0 = 5
const FUNC_GPIO19_U0CTS = 3
const FUNC_GPIO19_GPIO19 = 2
const FUNC_GPIO19_VSPIQ = 1
const FUNC_GPIO19_GPIO19_0 = 0
const FUNC_GPIO20_GPIO20 = 2
const FUNC_GPIO20_GPIO20_0 = 0
const FUNC_GPIO21_EMAC_TX_EN = 5
const FUNC_GPIO21_GPIO21 = 2
const FUNC_GPIO21_VSPIHD = 1
const FUNC_GPIO21_GPIO21_0 = 0
const FUNC_GPIO22_EMAC_TXD1 = 5
const FUNC_GPIO22_U0RTS = 3
const FUNC_GPIO22_GPIO22 = 2
const FUNC_GPIO22_VSPIWP = 1
const FUNC_GPIO22_GPIO22_0 = 0
const FUNC_GPIO23_HS1_STROBE = 3
const FUNC_GPIO23_GPIO23 = 2
const FUNC_GPIO23_VSPID = 1
const FUNC_GPIO23_GPIO23_0 = 0
const FUNC_GPIO24_GPIO24 = 2
const FUNC_GPIO24_GPIO24_0 = 0
const FUNC_GPIO25_EMAC_RXD0 = 5
const FUNC_GPIO25_GPIO25 = 2
const FUNC_GPIO25_GPIO25_0 = 0
const FUNC_GPIO26_EMAC_RXD1 = 5
const FUNC_GPIO26_GPIO26 = 2
const FUNC_GPIO26_GPIO26_0 = 0
const FUNC_GPIO27_EMAC_RX_DV = 5
const FUNC_GPIO27_GPIO27 = 2
const FUNC_GPIO27_GPIO27_0 = 0
const FUNC_GPIO32_GPIO32 = 2
const FUNC_GPIO32_GPIO32_0 = 0
const FUNC_GPIO33_GPIO33 = 2
const FUNC_GPIO33_GPIO33_0 = 0
const FUNC_GPIO34_GPIO34 = 2
const FUNC_GPIO34_GPIO34_0 = 0
const FUNC_GPIO35_GPIO35 = 2
const FUNC_GPIO35_GPIO35_0 = 0
const FUNC_GPIO36_GPIO36 = 2
const FUNC_GPIO36_GPIO36_0 = 0
const FUNC_GPIO37_GPIO37 = 2
const FUNC_GPIO37_GPIO37_0 = 0
const FUNC_GPIO38_GPIO38 = 2
const FUNC_GPIO38_GPIO38_0 = 0
const FUNC_GPIO39_GPIO39 = 2
const FUNC_GPIO39_GPIO39_0 = 0
const RTC_CNTL_SW_SYS_RST_V = 0x1
const RTC_CNTL_SW_SYS_RST_S = 31
const RTC_CNTL_DG_WRAP_FORCE_NORST_V = 0x1
const RTC_CNTL_DG_WRAP_FORCE_NORST_S = 30
const RTC_CNTL_DG_WRAP_FORCE_RST_V = 0x1
const RTC_CNTL_DG_WRAP_FORCE_RST_S = 29
const RTC_CNTL_ANALOG_FORCE_NOISO_V = 0x1
const RTC_CNTL_ANALOG_FORCE_NOISO_S = 28
const RTC_CNTL_PLL_FORCE_NOISO_V = 0x1
const RTC_CNTL_PLL_FORCE_NOISO_S = 27
const RTC_CNTL_XTL_FORCE_NOISO_V = 0x1
const RTC_CNTL_XTL_FORCE_NOISO_S = 26
const RTC_CNTL_ANALOG_FORCE_ISO_V = 0x1
const RTC_CNTL_ANALOG_FORCE_ISO_S = 25
const RTC_CNTL_PLL_FORCE_ISO_V = 0x1
const RTC_CNTL_PLL_FORCE_ISO_S = 24
const RTC_CNTL_XTL_FORCE_ISO_V = 0x1
const RTC_CNTL_XTL_FORCE_ISO_S = 23
const RTC_CNTL_BIAS_CORE_FORCE_PU_V = 0x1
const RTC_CNTL_BIAS_CORE_FORCE_PU_S = 22
const RTC_CNTL_BIAS_CORE_FORCE_PD_V = 0x1
const RTC_CNTL_BIAS_CORE_FORCE_PD_S = 21
const RTC_CNTL_BIAS_CORE_FOLW_8M_V = 0x1
const RTC_CNTL_BIAS_CORE_FOLW_8M_S = 20
const RTC_CNTL_BIAS_I2C_FORCE_PU_V = 0x1
const RTC_CNTL_BIAS_I2C_FORCE_PU_S = 19
const RTC_CNTL_BIAS_I2C_FORCE_PD_V = 0x1
const RTC_CNTL_BIAS_I2C_FORCE_PD_S = 18
const RTC_CNTL_BIAS_I2C_FOLW_8M_V = 0x1
const RTC_CNTL_BIAS_I2C_FOLW_8M_S = 17
const RTC_CNTL_BIAS_FORCE_NOSLEEP_V = 0x1
const RTC_CNTL_BIAS_FORCE_NOSLEEP_S = 16
const RTC_CNTL_BIAS_FORCE_SLEEP_V = 0x1
const RTC_CNTL_BIAS_FORCE_SLEEP_S = 15
const RTC_CNTL_BIAS_SLEEP_FOLW_8M_V = 0x1
const RTC_CNTL_BIAS_SLEEP_FOLW_8M_S = 14
const RTC_CNTL_XTL_FORCE_PU_V = 0x1
const RTC_CNTL_XTL_FORCE_PU_S = 13
const RTC_CNTL_XTL_FORCE_PD_V = 0x1
const RTC_CNTL_XTL_FORCE_PD_S = 12
const RTC_CNTL_BBPLL_FORCE_PU_V = 0x1
const RTC_CNTL_BBPLL_FORCE_PU_S = 11
const RTC_CNTL_BBPLL_FORCE_PD_V = 0x1
const RTC_CNTL_BBPLL_FORCE_PD_S = 10
const RTC_CNTL_BBPLL_I2C_FORCE_PU_V = 0x1
const RTC_CNTL_BBPLL_I2C_FORCE_PU_S = 9
const RTC_CNTL_BBPLL_I2C_FORCE_PD_V = 0x1
const RTC_CNTL_BBPLL_I2C_FORCE_PD_S = 8
const RTC_CNTL_BB_I2C_FORCE_PU_V = 0x1
const RTC_CNTL_BB_I2C_FORCE_PU_S = 7
const RTC_CNTL_BB_I2C_FORCE_PD_V = 0x1
const RTC_CNTL_BB_I2C_FORCE_PD_S = 6
const RTC_CNTL_SW_PROCPU_RST_V = 0x1
const RTC_CNTL_SW_PROCPU_RST_S = 5
const RTC_CNTL_SW_APPCPU_RST_V = 0x1
const RTC_CNTL_SW_APPCPU_RST_S = 4
const RTC_CNTL_SW_STALL_PROCPU_C0 = 0x00000003
const RTC_CNTL_SW_STALL_PROCPU_C0_V = 0x3
const RTC_CNTL_SW_STALL_PROCPU_C0_S = 2
const RTC_CNTL_SW_STALL_APPCPU_C0 = 0x00000003
const RTC_CNTL_SW_STALL_APPCPU_C0_V = 0x3
const RTC_CNTL_SW_STALL_APPCPU_C0_S = 0
const RTC_CNTL_SLP_VAL_LO = 0xFFFFFFFF
const RTC_CNTL_SLP_VAL_LO_V = 0xFFFFFFFF
const RTC_CNTL_SLP_VAL_LO_S = 0
const RTC_CNTL_MAIN_TIMER_ALARM_EN_V = 0x1
const RTC_CNTL_MAIN_TIMER_ALARM_EN_S = 16
const RTC_CNTL_SLP_VAL_HI = 0x0000FFFF
const RTC_CNTL_SLP_VAL_HI_V = 0xFFFF
const RTC_CNTL_SLP_VAL_HI_S = 0
const RTC_CNTL_TIME_UPDATE_V = 0x1
const RTC_CNTL_TIME_UPDATE_S = 31
const RTC_CNTL_TIME_VALID_V = 0x1
const RTC_CNTL_TIME_VALID_S = 30
const RTC_CNTL_TIME_LO = 0xFFFFFFFF
const RTC_CNTL_TIME_LO_V = 0xFFFFFFFF
const RTC_CNTL_TIME_LO_S = 0
const RTC_CNTL_TIME_HI = 0x0000FFFF
const RTC_CNTL_TIME_HI_V = 0xFFFF
const RTC_CNTL_TIME_HI_S = 0
const RTC_CNTL_SLEEP_EN_V = 0x1
const RTC_CNTL_SLEEP_EN_S = 31
const RTC_CNTL_SLP_REJECT_V = 0x1
const RTC_CNTL_SLP_REJECT_S = 30
const RTC_CNTL_SLP_WAKEUP_V = 0x1
const RTC_CNTL_SLP_WAKEUP_S = 29
const RTC_CNTL_SDIO_ACTIVE_IND_V = 0x1
const RTC_CNTL_SDIO_ACTIVE_IND_S = 28
const RTC_CNTL_ULP_CP_SLP_TIMER_EN_V = 0x1
const RTC_CNTL_ULP_CP_SLP_TIMER_EN_S = 24
const RTC_CNTL_TOUCH_SLP_TIMER_EN_V = 0x1
const RTC_CNTL_TOUCH_SLP_TIMER_EN_S = 23
const RTC_CNTL_APB2RTC_BRIDGE_SEL_V = 0x1
const RTC_CNTL_APB2RTC_BRIDGE_SEL_S = 22
const RTC_CNTL_ULP_CP_WAKEUP_FORCE_EN_V = 0x1
const RTC_CNTL_ULP_CP_WAKEUP_FORCE_EN_S = 21
const RTC_CNTL_TOUCH_WAKEUP_FORCE_EN_V = 0x1
const RTC_CNTL_TOUCH_WAKEUP_FORCE_EN_S = 20
const RTC_CNTL_PLL_BUF_WAIT = 0x000000FF
const RTC_CNTL_PLL_BUF_WAIT_V = 0xFF
const RTC_CNTL_PLL_BUF_WAIT_S = 24
const RTC_CNTL_PLL_BUF_WAIT_DEFAULT = 20
const RTC_CNTL_XTL_BUF_WAIT = 0x000003FF
const RTC_CNTL_XTL_BUF_WAIT_V = 0x3FF
const RTC_CNTL_XTL_BUF_WAIT_S = 14
const RTC_CNTL_XTL_BUF_WAIT_DEFAULT = 20
const RTC_CNTL_CK8M_WAIT = 0x000000FF
const RTC_CNTL_CK8M_WAIT_V = 0xFF
const RTC_CNTL_CK8M_WAIT_S = 6
const RTC_CNTL_CPU_STALL_WAIT = 0x0000001F
const RTC_CNTL_CPU_STALL_WAIT_V = 0x1F
const RTC_CNTL_CPU_STALL_WAIT_S = 1
const RTC_CNTL_CPU_STALL_EN_V = 0x1
const RTC_CNTL_CPU_STALL_EN_S = 0
const RTC_CNTL_MIN_TIME_CK8M_OFF = 0x000000FF
const RTC_CNTL_MIN_TIME_CK8M_OFF_V = 0xFF
const RTC_CNTL_MIN_TIME_CK8M_OFF_S = 24
const RTC_CNTL_ULPCP_TOUCH_START_WAIT = 0x000001FF
const RTC_CNTL_ULPCP_TOUCH_START_WAIT_V = 0x1FF
const RTC_CNTL_ULPCP_TOUCH_START_WAIT_S = 15
const RTC_CNTL_ROM_RAM_POWERUP_TIMER = 0x0000007F
const RTC_CNTL_ROM_RAM_POWERUP_TIMER_V = 0x7F
const RTC_CNTL_ROM_RAM_POWERUP_TIMER_S = 25
const RTC_CNTL_ROM_RAM_WAIT_TIMER = 0x000001FF
const RTC_CNTL_ROM_RAM_WAIT_TIMER_V = 0x1FF
const RTC_CNTL_ROM_RAM_WAIT_TIMER_S = 16
const RTC_CNTL_WIFI_POWERUP_TIMER = 0x0000007F
const RTC_CNTL_WIFI_POWERUP_TIMER_V = 0x7F
const RTC_CNTL_WIFI_POWERUP_TIMER_S = 9
const RTC_CNTL_WIFI_WAIT_TIMER = 0x000001FF
const RTC_CNTL_WIFI_WAIT_TIMER_V = 0x1FF
const RTC_CNTL_WIFI_WAIT_TIMER_S = 0
const RTC_CNTL_DG_WRAP_POWERUP_TIMER = 0x0000007F
const RTC_CNTL_DG_WRAP_POWERUP_TIMER_V = 0x7F
const RTC_CNTL_DG_WRAP_POWERUP_TIMER_S = 25
const RTC_CNTL_DG_WRAP_WAIT_TIMER = 0x000001FF
const RTC_CNTL_DG_WRAP_WAIT_TIMER_V = 0x1FF
const RTC_CNTL_DG_WRAP_WAIT_TIMER_S = 16
const RTC_CNTL_POWERUP_TIMER = 0x0000007F
const RTC_CNTL_POWERUP_TIMER_V = 0x7F
const RTC_CNTL_POWERUP_TIMER_S = 9
const RTC_CNTL_WAIT_TIMER = 0x000001FF
const RTC_CNTL_WAIT_TIMER_V = 0x1FF
const RTC_CNTL_WAIT_TIMER_S = 0
const RTC_CNTL_RTCMEM_POWERUP_TIMER = 0x0000007F
const RTC_CNTL_RTCMEM_POWERUP_TIMER_V = 0x7F
const RTC_CNTL_RTCMEM_POWERUP_TIMER_S = 25
const RTC_CNTL_RTCMEM_WAIT_TIMER = 0x000001FF
const RTC_CNTL_RTCMEM_WAIT_TIMER_V = 0x1FF
const RTC_CNTL_RTCMEM_WAIT_TIMER_S = 16
const RTC_CNTL_MIN_SLP_VAL = 0x000000FF
const RTC_CNTL_MIN_SLP_VAL_V = 0xFF
const RTC_CNTL_MIN_SLP_VAL_S = 8
const RTC_CNTL_ULP_CP_SUBTIMER_PREDIV = 0x000000FF
const RTC_CNTL_ULP_CP_SUBTIMER_PREDIV_V = 0xFF
const RTC_CNTL_ULP_CP_SUBTIMER_PREDIV_S = 0
const RTC_CNTL_PLL_I2C_PU_V = 0x1
const RTC_CNTL_PLL_I2C_PU_S = 31
const RTC_CNTL_CKGEN_I2C_PU_V = 0x1
const RTC_CNTL_CKGEN_I2C_PU_S = 30
const RTC_CNTL_RFRX_PBUS_PU_V = 0x1
const RTC_CNTL_RFRX_PBUS_PU_S = 28
const RTC_CNTL_TXRF_I2C_PU_V = 0x1
const RTC_CNTL_TXRF_I2C_PU_S = 27
const RTC_CNTL_PVTMON_PU_V = 0x1
const RTC_CNTL_PVTMON_PU_S = 26
const RTC_CNTL_BBPLL_CAL_SLP_START_V = 0x1
const RTC_CNTL_BBPLL_CAL_SLP_START_S = 25
const RTC_CNTL_PLLA_FORCE_PU_V = 0x1
const RTC_CNTL_PLLA_FORCE_PU_S = 24
const RTC_CNTL_PLLA_FORCE_PD_V = 0x1
const RTC_CNTL_PLLA_FORCE_PD_S = 23
const RTC_CNTL_PROCPU_STAT_VECTOR_SEL_V = 0x1
const RTC_CNTL_PROCPU_STAT_VECTOR_SEL_S = 13
const RTC_CNTL_APPCPU_STAT_VECTOR_SEL_V = 0x1
const RTC_CNTL_APPCPU_STAT_VECTOR_SEL_S = 12
const RTC_CNTL_RESET_CAUSE_APPCPU = 0x0000003F
const RTC_CNTL_RESET_CAUSE_APPCPU_V = 0x3F
const RTC_CNTL_RESET_CAUSE_APPCPU_S = 6
const RTC_CNTL_RESET_CAUSE_PROCPU = 0x0000003F
const RTC_CNTL_RESET_CAUSE_PROCPU_V = 0x3F
const RTC_CNTL_RESET_CAUSE_PROCPU_S = 0
const RTC_CNTL_GPIO_WAKEUP_FILTER_V = 0x1
const RTC_CNTL_GPIO_WAKEUP_FILTER_S = 22
const RTC_CNTL_WAKEUP_ENA = 0x000007FF
const RTC_CNTL_WAKEUP_ENA_V = 0x7FF
const RTC_CNTL_WAKEUP_ENA_S = 11
const RTC_CNTL_WAKEUP_CAUSE = 0x000007FF
const RTC_CNTL_WAKEUP_CAUSE_V = 0x7FF
const RTC_CNTL_WAKEUP_CAUSE_S = 0
const RTC_CNTL_MAIN_TIMER_INT_ENA_V = 0x1
const RTC_CNTL_MAIN_TIMER_INT_ENA_S = 8
const RTC_CNTL_BROWN_OUT_INT_ENA_V = 0x1
const RTC_CNTL_BROWN_OUT_INT_ENA_S = 7
const RTC_CNTL_TOUCH_INT_ENA_V = 0x1
const RTC_CNTL_TOUCH_INT_ENA_S = 6
const RTC_CNTL_ULP_CP_INT_ENA_V = 0x1
const RTC_CNTL_ULP_CP_INT_ENA_S = 5
const RTC_CNTL_TIME_VALID_INT_ENA_V = 0x1
const RTC_CNTL_TIME_VALID_INT_ENA_S = 4
const RTC_CNTL_WDT_INT_ENA_V = 0x1
const RTC_CNTL_WDT_INT_ENA_S = 3
const RTC_CNTL_SDIO_IDLE_INT_ENA_V = 0x1
const RTC_CNTL_SDIO_IDLE_INT_ENA_S = 2
const RTC_CNTL_SLP_REJECT_INT_ENA_V = 0x1
const RTC_CNTL_SLP_REJECT_INT_ENA_S = 1
const RTC_CNTL_SLP_WAKEUP_INT_ENA_V = 0x1
const RTC_CNTL_SLP_WAKEUP_INT_ENA_S = 0
const RTC_CNTL_MAIN_TIMER_INT_RAW_V = 0x1
const RTC_CNTL_MAIN_TIMER_INT_RAW_S = 8
const RTC_CNTL_BROWN_OUT_INT_RAW_V = 0x1
const RTC_CNTL_BROWN_OUT_INT_RAW_S = 7
const RTC_CNTL_TOUCH_INT_RAW_V = 0x1
const RTC_CNTL_TOUCH_INT_RAW_S = 6
const RTC_CNTL_ULP_CP_INT_RAW_V = 0x1
const RTC_CNTL_ULP_CP_INT_RAW_S = 5
const RTC_CNTL_TIME_VALID_INT_RAW_V = 0x1
const RTC_CNTL_TIME_VALID_INT_RAW_S = 4
const RTC_CNTL_WDT_INT_RAW_V = 0x1
const RTC_CNTL_WDT_INT_RAW_S = 3
const RTC_CNTL_SDIO_IDLE_INT_RAW_V = 0x1
const RTC_CNTL_SDIO_IDLE_INT_RAW_S = 2
const RTC_CNTL_SLP_REJECT_INT_RAW_V = 0x1
const RTC_CNTL_SLP_REJECT_INT_RAW_S = 1
const RTC_CNTL_SLP_WAKEUP_INT_RAW_V = 0x1
const RTC_CNTL_SLP_WAKEUP_INT_RAW_S = 0
const RTC_CNTL_MAIN_TIMER_INT_ST_V = 0x1
const RTC_CNTL_MAIN_TIMER_INT_ST_S = 8
const RTC_CNTL_BROWN_OUT_INT_ST_V = 0x1
const RTC_CNTL_BROWN_OUT_INT_ST_S = 7
const RTC_CNTL_TOUCH_INT_ST_V = 0x1
const RTC_CNTL_TOUCH_INT_ST_S = 6
const RTC_CNTL_SAR_INT_ST_V = 0x1
const RTC_CNTL_SAR_INT_ST_S = 5
const RTC_CNTL_TIME_VALID_INT_ST_V = 0x1
const RTC_CNTL_TIME_VALID_INT_ST_S = 4
const RTC_CNTL_WDT_INT_ST_V = 0x1
const RTC_CNTL_WDT_INT_ST_S = 3
const RTC_CNTL_SDIO_IDLE_INT_ST_V = 0x1
const RTC_CNTL_SDIO_IDLE_INT_ST_S = 2
const RTC_CNTL_SLP_REJECT_INT_ST_V = 0x1
const RTC_CNTL_SLP_REJECT_INT_ST_S = 1
const RTC_CNTL_SLP_WAKEUP_INT_ST_V = 0x1
const RTC_CNTL_SLP_WAKEUP_INT_ST_S = 0
const RTC_CNTL_MAIN_TIMER_INT_CLR_V = 0x1
const RTC_CNTL_MAIN_TIMER_INT_CLR_S = 8
const RTC_CNTL_BROWN_OUT_INT_CLR_V = 0x1
const RTC_CNTL_BROWN_OUT_INT_CLR_S = 7
const RTC_CNTL_TOUCH_INT_CLR_V = 0x1
const RTC_CNTL_TOUCH_INT_CLR_S = 6
const RTC_CNTL_SAR_INT_CLR_V = 0x1
const RTC_CNTL_SAR_INT_CLR_S = 5
const RTC_CNTL_TIME_VALID_INT_CLR_V = 0x1
const RTC_CNTL_TIME_VALID_INT_CLR_S = 4
const RTC_CNTL_WDT_INT_CLR_V = 0x1
const RTC_CNTL_WDT_INT_CLR_S = 3
const RTC_CNTL_SDIO_IDLE_INT_CLR_V = 0x1
const RTC_CNTL_SDIO_IDLE_INT_CLR_S = 2
const RTC_CNTL_SLP_REJECT_INT_CLR_V = 0x1
const RTC_CNTL_SLP_REJECT_INT_CLR_S = 1
const RTC_CNTL_SLP_WAKEUP_INT_CLR_V = 0x1
const RTC_CNTL_SLP_WAKEUP_INT_CLR_S = 0
const RTC_CNTL_SCRATCH0 = 0xFFFFFFFF
const RTC_CNTL_SCRATCH0_V = 0xFFFFFFFF
const RTC_CNTL_SCRATCH0_S = 0
const RTC_CNTL_SCRATCH1 = 0xFFFFFFFF
const RTC_CNTL_SCRATCH1_V = 0xFFFFFFFF
const RTC_CNTL_SCRATCH1_S = 0
const RTC_CNTL_SCRATCH2 = 0xFFFFFFFF
const RTC_CNTL_SCRATCH2_V = 0xFFFFFFFF
const RTC_CNTL_SCRATCH2_S = 0
const RTC_CNTL_SCRATCH3 = 0xFFFFFFFF
const RTC_CNTL_SCRATCH3_V = 0xFFFFFFFF
const RTC_CNTL_SCRATCH3_S = 0
const RTC_CNTL_XTL_EXT_CTR_EN_V = 0x1
const RTC_CNTL_XTL_EXT_CTR_EN_S = 31
const RTC_CNTL_XTL_EXT_CTR_LV_V = 0x1
const RTC_CNTL_XTL_EXT_CTR_LV_S = 30
const RTC_CNTL_EXT_WAKEUP1_LV_V = 0x1
const RTC_CNTL_EXT_WAKEUP1_LV_S = 31
const RTC_CNTL_EXT_WAKEUP0_LV_V = 0x1
const RTC_CNTL_EXT_WAKEUP0_LV_S = 30
const RTC_CNTL_REJECT_CAUSE = 0x0000000F
const RTC_CNTL_REJECT_CAUSE_V = 0xF
const RTC_CNTL_REJECT_CAUSE_S = 28
const RTC_CNTL_DEEP_SLP_REJECT_EN_V = 0x1
const RTC_CNTL_DEEP_SLP_REJECT_EN_S = 27
const RTC_CNTL_LIGHT_SLP_REJECT_EN_V = 0x1
const RTC_CNTL_LIGHT_SLP_REJECT_EN_S = 26
const RTC_CNTL_SDIO_REJECT_EN_V = 0x1
const RTC_CNTL_SDIO_REJECT_EN_S = 25
const RTC_CNTL_GPIO_REJECT_EN_V = 0x1
const RTC_CNTL_GPIO_REJECT_EN_S = 24
const RTC_CNTL_CPUPERIOD_SEL = 0x00000003
const RTC_CNTL_CPUPERIOD_SEL_V = 0x3
const RTC_CNTL_CPUPERIOD_SEL_S = 30
const RTC_CNTL_CPUSEL_CONF_V = 0x1
const RTC_CNTL_CPUSEL_CONF_S = 29
const RTC_CNTL_SDIO_ACT_DNUM = 0x000003FF
const RTC_CNTL_SDIO_ACT_DNUM_V = 0x3FF
const RTC_CNTL_SDIO_ACT_DNUM_S = 22
const RTC_CNTL_ANA_CLK_RTC_SEL = 0x00000003
const RTC_CNTL_ANA_CLK_RTC_SEL_V = 0x3
const RTC_CNTL_ANA_CLK_RTC_SEL_S = 30
const RTC_CNTL_FAST_CLK_RTC_SEL_V = 0x1
const RTC_CNTL_FAST_CLK_RTC_SEL_S = 29
const RTC_CNTL_SOC_CLK_SEL = 0x00000003
const RTC_CNTL_SOC_CLK_SEL_V = 0x3
const RTC_CNTL_SOC_CLK_SEL_S = 27
const RTC_CNTL_CK8M_FORCE_PU_V = 0x1
const RTC_CNTL_CK8M_FORCE_PU_S = 26
const RTC_CNTL_CK8M_FORCE_PD_V = 0x1
const RTC_CNTL_CK8M_FORCE_PD_S = 25
const RTC_CNTL_CK8M_DFREQ = 0x000000FF
const RTC_CNTL_CK8M_DFREQ_V = 0xFF
const RTC_CNTL_CK8M_DFREQ_S = 17
const RTC_CNTL_CK8M_DFREQ_DEFAULT = 172
const RTC_CNTL_CK8M_FORCE_NOGATING_V = 0x1
const RTC_CNTL_CK8M_FORCE_NOGATING_S = 16
const RTC_CNTL_XTAL_FORCE_NOGATING_V = 0x1
const RTC_CNTL_XTAL_FORCE_NOGATING_S = 15
const RTC_CNTL_CK8M_DIV_SEL = 0x00000007
const RTC_CNTL_CK8M_DIV_SEL_V = 0x7
const RTC_CNTL_CK8M_DIV_SEL_S = 12
const RTC_CNTL_CK8M_DFREQ_FORCE_V = 0x1
const RTC_CNTL_CK8M_DFREQ_FORCE_S = 11
const RTC_CNTL_DIG_CLK8M_EN_V = 0x1
const RTC_CNTL_DIG_CLK8M_EN_S = 10
const RTC_CNTL_DIG_CLK8M_D256_EN_V = 0x1
const RTC_CNTL_DIG_CLK8M_D256_EN_S = 9
const RTC_CNTL_DIG_XTAL32K_EN_V = 0x1
const RTC_CNTL_DIG_XTAL32K_EN_S = 8
const RTC_CNTL_ENB_CK8M_DIV_V = 0x1
const RTC_CNTL_ENB_CK8M_DIV_S = 7
const RTC_CNTL_ENB_CK8M_V = 0x1
const RTC_CNTL_ENB_CK8M_S = 6
const RTC_CNTL_CK8M_DIV = 0x00000003
const RTC_CNTL_CK8M_DIV_V = 0x3
const RTC_CNTL_CK8M_DIV_S = 4
const RTC_CNTL_XPD_SDIO_REG_V = 0x1
const RTC_CNTL_XPD_SDIO_REG_S = 31
const RTC_CNTL_DREFH_SDIO = 0x00000003
const RTC_CNTL_DREFH_SDIO_V = 0x3
const RTC_CNTL_DREFH_SDIO_S = 29
const RTC_CNTL_DREFM_SDIO = 0x00000003
const RTC_CNTL_DREFM_SDIO_V = 0x3
const RTC_CNTL_DREFM_SDIO_S = 27
const RTC_CNTL_DREFL_SDIO = 0x00000003
const RTC_CNTL_DREFL_SDIO_V = 0x3
const RTC_CNTL_DREFL_SDIO_S = 25
const RTC_CNTL_REG1P8_READY_V = 0x1
const RTC_CNTL_REG1P8_READY_S = 24
const RTC_CNTL_SDIO_TIEH_V = 0x1
const RTC_CNTL_SDIO_TIEH_S = 23
const RTC_CNTL_SDIO_FORCE_V = 0x1
const RTC_CNTL_SDIO_FORCE_S = 22
const RTC_CNTL_SDIO_PD_EN_V = 0x1
const RTC_CNTL_SDIO_PD_EN_S = 21
const RTC_CNTL_RST_BIAS_I2C_V = 0x1
const RTC_CNTL_RST_BIAS_I2C_S = 31
const RTC_CNTL_DEC_HEARTBEAT_WIDTH_V = 0x1
const RTC_CNTL_DEC_HEARTBEAT_WIDTH_S = 30
const RTC_CNTL_INC_HEARTBEAT_PERIOD_V = 0x1
const RTC_CNTL_INC_HEARTBEAT_PERIOD_S = 29
const RTC_CNTL_DEC_HEARTBEAT_PERIOD_V = 0x1
const RTC_CNTL_DEC_HEARTBEAT_PERIOD_S = 28
const RTC_CNTL_INC_HEARTBEAT_REFRESH_V = 0x1
const RTC_CNTL_INC_HEARTBEAT_REFRESH_S = 27
const RTC_CNTL_ENB_SCK_XTAL_V = 0x1
const RTC_CNTL_ENB_SCK_XTAL_S = 26
const RTC_CNTL_DBG_ATTEN = 0x00000003
const RTC_CNTL_DBG_ATTEN_V = 0x3
const RTC_CNTL_DBG_ATTEN_S = 24
const RTC_CNTL_DBG_ATTEN_DEFAULT = 3
const RTC_CNTL_DBG_ATTEN_NODROP = 0
const RTC_CNTL_FORCE_PU_V = 0x1
const RTC_CNTL_FORCE_PU_S = 31
const RTC_CNTL_FORCE_PD_V = 0x1
const RTC_CNTL_FORCE_PD_S = 30
const RTC_CNTL_DBOOST_FORCE_PU_V = 0x1
const RTC_CNTL_DBOOST_FORCE_PU_S = 29
const RTC_CNTL_DBOOST_FORCE_PD_V = 0x1
const RTC_CNTL_DBOOST_FORCE_PD_S = 28
const RTC_CNTL_DBIAS_WAK = 0x00000007
const RTC_CNTL_DBIAS_WAK_V = 0x7
const RTC_CNTL_DBIAS_WAK_S = 25
const RTC_CNTL_DBIAS_SLP = 0x00000007
const RTC_CNTL_DBIAS_SLP_V = 0x7
const RTC_CNTL_DBIAS_SLP_S = 22
const RTC_CNTL_SCK_DCAP = 0x000000FF
const RTC_CNTL_SCK_DCAP_V = 0xFF
const RTC_CNTL_SCK_DCAP_S = 14
const RTC_CNTL_SCK_DCAP_DEFAULT = 255
const RTC_CNTL_DIG_DBIAS_WAK = 0x00000007
const RTC_CNTL_DIG_DBIAS_WAK_V = 0x7
const RTC_CNTL_DIG_DBIAS_WAK_S = 11
const RTC_CNTL_DIG_DBIAS_SLP = 0x00000007
const RTC_CNTL_DIG_DBIAS_SLP_V = 0x7
const RTC_CNTL_DIG_DBIAS_SLP_S = 8
const RTC_CNTL_SCK_DCAP_FORCE_V = 0x1
const RTC_CNTL_SCK_DCAP_FORCE_S = 7
const RTC_CNTL_DBIAS_0V90 = 0
const RTC_CNTL_DBIAS_0V95 = 1
const RTC_CNTL_DBIAS_1V00 = 2
const RTC_CNTL_DBIAS_1V05 = 3
const RTC_CNTL_DBIAS_1V10 = 4
const RTC_CNTL_DBIAS_1V15 = 5
const RTC_CNTL_DBIAS_1V20 = 6
const RTC_CNTL_DBIAS_1V25 = 7
const RTC_CNTL_PD_EN_V = 0x1
const RTC_CNTL_PD_EN_S = 20
const RTC_CNTL_PWC_FORCE_PU_V = 0x1
const RTC_CNTL_PWC_FORCE_PU_S = 19
const RTC_CNTL_PWC_FORCE_PD_V = 0x1
const RTC_CNTL_PWC_FORCE_PD_S = 18
const RTC_CNTL_SLOWMEM_PD_EN_V = 0x1
const RTC_CNTL_SLOWMEM_PD_EN_S = 17
const RTC_CNTL_SLOWMEM_FORCE_PU_V = 0x1
const RTC_CNTL_SLOWMEM_FORCE_PU_S = 16
const RTC_CNTL_SLOWMEM_FORCE_PD_V = 0x1
const RTC_CNTL_SLOWMEM_FORCE_PD_S = 15
const RTC_CNTL_FASTMEM_PD_EN_V = 0x1
const RTC_CNTL_FASTMEM_PD_EN_S = 14
const RTC_CNTL_FASTMEM_FORCE_PU_V = 0x1
const RTC_CNTL_FASTMEM_FORCE_PU_S = 13
const RTC_CNTL_FASTMEM_FORCE_PD_V = 0x1
const RTC_CNTL_FASTMEM_FORCE_PD_S = 12
const RTC_CNTL_SLOWMEM_FORCE_LPU_V = 0x1
const RTC_CNTL_SLOWMEM_FORCE_LPU_S = 11
const RTC_CNTL_SLOWMEM_FORCE_LPD_V = 0x1
const RTC_CNTL_SLOWMEM_FORCE_LPD_S = 10
const RTC_CNTL_SLOWMEM_FOLW_CPU_V = 0x1
const RTC_CNTL_SLOWMEM_FOLW_CPU_S = 9
const RTC_CNTL_FASTMEM_FORCE_LPU_V = 0x1
const RTC_CNTL_FASTMEM_FORCE_LPU_S = 8
const RTC_CNTL_FASTMEM_FORCE_LPD_V = 0x1
const RTC_CNTL_FASTMEM_FORCE_LPD_S = 7
const RTC_CNTL_FASTMEM_FOLW_CPU_V = 0x1
const RTC_CNTL_FASTMEM_FOLW_CPU_S = 6
const RTC_CNTL_FORCE_NOISO_V = 0x1
const RTC_CNTL_FORCE_NOISO_S = 5
const RTC_CNTL_FORCE_ISO_V = 0x1
const RTC_CNTL_FORCE_ISO_S = 4
const RTC_CNTL_SLOWMEM_FORCE_ISO_V = 0x1
const RTC_CNTL_SLOWMEM_FORCE_ISO_S = 3
const RTC_CNTL_SLOWMEM_FORCE_NOISO_V = 0x1
const RTC_CNTL_SLOWMEM_FORCE_NOISO_S = 2
const RTC_CNTL_FASTMEM_FORCE_ISO_V = 0x1
const RTC_CNTL_FASTMEM_FORCE_ISO_S = 1
const RTC_CNTL_FASTMEM_FORCE_NOISO_V = 0x1
const RTC_CNTL_FASTMEM_FORCE_NOISO_S = 0
const RTC_CNTL_DG_WRAP_PD_EN_V = 0x1
const RTC_CNTL_DG_WRAP_PD_EN_S = 31
const RTC_CNTL_WIFI_PD_EN_V = 0x1
const RTC_CNTL_WIFI_PD_EN_S = 30
const RTC_CNTL_INTER_RAM4_PD_EN_V = 0x1
const RTC_CNTL_INTER_RAM4_PD_EN_S = 29
const RTC_CNTL_INTER_RAM3_PD_EN_V = 0x1
const RTC_CNTL_INTER_RAM3_PD_EN_S = 28
const RTC_CNTL_INTER_RAM2_PD_EN_V = 0x1
const RTC_CNTL_INTER_RAM2_PD_EN_S = 27
const RTC_CNTL_INTER_RAM1_PD_EN_V = 0x1
const RTC_CNTL_INTER_RAM1_PD_EN_S = 26
const RTC_CNTL_INTER_RAM0_PD_EN_V = 0x1
const RTC_CNTL_INTER_RAM0_PD_EN_S = 25
const RTC_CNTL_ROM0_PD_EN_V = 0x1
const RTC_CNTL_ROM0_PD_EN_S = 24
const RTC_CNTL_DG_WRAP_FORCE_PU_V = 0x1
const RTC_CNTL_DG_WRAP_FORCE_PU_S = 20
const RTC_CNTL_DG_WRAP_FORCE_PD_V = 0x1
const RTC_CNTL_DG_WRAP_FORCE_PD_S = 19
const RTC_CNTL_WIFI_FORCE_PU_V = 0x1
const RTC_CNTL_WIFI_FORCE_PU_S = 18
const RTC_CNTL_WIFI_FORCE_PD_V = 0x1
const RTC_CNTL_WIFI_FORCE_PD_S = 17
const RTC_CNTL_INTER_RAM4_FORCE_PU_V = 0x1
const RTC_CNTL_INTER_RAM4_FORCE_PU_S = 16
const RTC_CNTL_INTER_RAM4_FORCE_PD_V = 0x1
const RTC_CNTL_INTER_RAM4_FORCE_PD_S = 15
const RTC_CNTL_INTER_RAM3_FORCE_PU_V = 0x1
const RTC_CNTL_INTER_RAM3_FORCE_PU_S = 14
const RTC_CNTL_INTER_RAM3_FORCE_PD_V = 0x1
const RTC_CNTL_INTER_RAM3_FORCE_PD_S = 13
const RTC_CNTL_INTER_RAM2_FORCE_PU_V = 0x1
const RTC_CNTL_INTER_RAM2_FORCE_PU_S = 12
const RTC_CNTL_INTER_RAM2_FORCE_PD_V = 0x1
const RTC_CNTL_INTER_RAM2_FORCE_PD_S = 11
const RTC_CNTL_INTER_RAM1_FORCE_PU_V = 0x1
const RTC_CNTL_INTER_RAM1_FORCE_PU_S = 10
const RTC_CNTL_INTER_RAM1_FORCE_PD_V = 0x1
const RTC_CNTL_INTER_RAM1_FORCE_PD_S = 9
const RTC_CNTL_INTER_RAM0_FORCE_PU_V = 0x1
const RTC_CNTL_INTER_RAM0_FORCE_PU_S = 8
const RTC_CNTL_INTER_RAM0_FORCE_PD_V = 0x1
const RTC_CNTL_INTER_RAM0_FORCE_PD_S = 7
const RTC_CNTL_ROM0_FORCE_PU_V = 0x1
const RTC_CNTL_ROM0_FORCE_PU_S = 6
const RTC_CNTL_ROM0_FORCE_PD_V = 0x1
const RTC_CNTL_ROM0_FORCE_PD_S = 5
const RTC_CNTL_LSLP_MEM_FORCE_PU_V = 0x1
const RTC_CNTL_LSLP_MEM_FORCE_PU_S = 4
const RTC_CNTL_LSLP_MEM_FORCE_PD_V = 0x1
const RTC_CNTL_LSLP_MEM_FORCE_PD_S = 3
const RTC_CNTL_DG_WRAP_FORCE_NOISO_V = 0x1
const RTC_CNTL_DG_WRAP_FORCE_NOISO_S = 31
const RTC_CNTL_DG_WRAP_FORCE_ISO_V = 0x1
const RTC_CNTL_DG_WRAP_FORCE_ISO_S = 30
const RTC_CNTL_WIFI_FORCE_NOISO_V = 0x1
const RTC_CNTL_WIFI_FORCE_NOISO_S = 29
const RTC_CNTL_WIFI_FORCE_ISO_V = 0x1
const RTC_CNTL_WIFI_FORCE_ISO_S = 28
const RTC_CNTL_INTER_RAM4_FORCE_NOISO_V = 0x1
const RTC_CNTL_INTER_RAM4_FORCE_NOISO_S = 27
const RTC_CNTL_INTER_RAM4_FORCE_ISO_V = 0x1
const RTC_CNTL_INTER_RAM4_FORCE_ISO_S = 26
const RTC_CNTL_INTER_RAM3_FORCE_NOISO_V = 0x1
const RTC_CNTL_INTER_RAM3_FORCE_NOISO_S = 25
const RTC_CNTL_INTER_RAM3_FORCE_ISO_V = 0x1
const RTC_CNTL_INTER_RAM3_FORCE_ISO_S = 24
const RTC_CNTL_INTER_RAM2_FORCE_NOISO_V = 0x1
const RTC_CNTL_INTER_RAM2_FORCE_NOISO_S = 23
const RTC_CNTL_INTER_RAM2_FORCE_ISO_V = 0x1
const RTC_CNTL_INTER_RAM2_FORCE_ISO_S = 22
const RTC_CNTL_INTER_RAM1_FORCE_NOISO_V = 0x1
const RTC_CNTL_INTER_RAM1_FORCE_NOISO_S = 21
const RTC_CNTL_INTER_RAM1_FORCE_ISO_V = 0x1
const RTC_CNTL_INTER_RAM1_FORCE_ISO_S = 20
const RTC_CNTL_INTER_RAM0_FORCE_NOISO_V = 0x1
const RTC_CNTL_INTER_RAM0_FORCE_NOISO_S = 19
const RTC_CNTL_INTER_RAM0_FORCE_ISO_V = 0x1
const RTC_CNTL_INTER_RAM0_FORCE_ISO_S = 18
const RTC_CNTL_ROM0_FORCE_NOISO_V = 0x1
const RTC_CNTL_ROM0_FORCE_NOISO_S = 17
const RTC_CNTL_ROM0_FORCE_ISO_V = 0x1
const RTC_CNTL_ROM0_FORCE_ISO_S = 16
const RTC_CNTL_DG_PAD_FORCE_HOLD_V = 0x1
const RTC_CNTL_DG_PAD_FORCE_HOLD_S = 15
const RTC_CNTL_DG_PAD_FORCE_UNHOLD_V = 0x1
const RTC_CNTL_DG_PAD_FORCE_UNHOLD_S = 14
const RTC_CNTL_DG_PAD_FORCE_ISO_V = 0x1
const RTC_CNTL_DG_PAD_FORCE_ISO_S = 13
const RTC_CNTL_DG_PAD_FORCE_NOISO_V = 0x1
const RTC_CNTL_DG_PAD_FORCE_NOISO_S = 12
const RTC_CNTL_DG_PAD_AUTOHOLD_EN_V = 0x1
const RTC_CNTL_DG_PAD_AUTOHOLD_EN_S = 11
const RTC_CNTL_CLR_DG_PAD_AUTOHOLD_V = 0x1
const RTC_CNTL_CLR_DG_PAD_AUTOHOLD_S = 10
const RTC_CNTL_DG_PAD_AUTOHOLD_V = 0x1
const RTC_CNTL_DG_PAD_AUTOHOLD_S = 9
const RTC_CNTL_DIG_ISO_FORCE_ON_V = 0x1
const RTC_CNTL_DIG_ISO_FORCE_ON_S = 8
const RTC_CNTL_DIG_ISO_FORCE_OFF_V = 0x1
const RTC_CNTL_DIG_ISO_FORCE_OFF_S = 7
const RTC_CNTL_WDT_EN_V = 0x1
const RTC_CNTL_WDT_EN_S = 31
const RTC_CNTL_WDT_STG0 = 0x00000007
const RTC_CNTL_WDT_STG0_V = 0x7
const RTC_CNTL_WDT_STG0_S = 28
const RTC_CNTL_WDT_STG1 = 0x00000007
const RTC_CNTL_WDT_STG1_V = 0x7
const RTC_CNTL_WDT_STG1_S = 25
const RTC_CNTL_WDT_STG2 = 0x00000007
const RTC_CNTL_WDT_STG2_V = 0x7
const RTC_CNTL_WDT_STG2_S = 22
const RTC_CNTL_WDT_STG3 = 0x00000007
const RTC_CNTL_WDT_STG3_V = 0x7
const RTC_CNTL_WDT_STG3_S = 19
const RTC_CNTL_WDT_EDGE_INT_EN_V = 0x1
const RTC_CNTL_WDT_EDGE_INT_EN_S = 18
const RTC_CNTL_WDT_LEVEL_INT_EN_V = 0x1
const RTC_CNTL_WDT_LEVEL_INT_EN_S = 17
const RTC_CNTL_WDT_CPU_RESET_LENGTH = 0x00000007
const RTC_CNTL_WDT_CPU_RESET_LENGTH_V = 0x7
const RTC_CNTL_WDT_CPU_RESET_LENGTH_S = 14
const RTC_CNTL_WDT_SYS_RESET_LENGTH = 0x00000007
const RTC_CNTL_WDT_SYS_RESET_LENGTH_V = 0x7
const RTC_CNTL_WDT_SYS_RESET_LENGTH_S = 11
const RTC_CNTL_WDT_FLASHBOOT_MOD_EN_V = 0x1
const RTC_CNTL_WDT_FLASHBOOT_MOD_EN_S = 10
const RTC_CNTL_WDT_PROCPU_RESET_EN_V = 0x1
const RTC_CNTL_WDT_PROCPU_RESET_EN_S = 9
const RTC_CNTL_WDT_APPCPU_RESET_EN_V = 0x1
const RTC_CNTL_WDT_APPCPU_RESET_EN_S = 8
const RTC_CNTL_WDT_PAUSE_IN_SLP_V = 0x1
const RTC_CNTL_WDT_PAUSE_IN_SLP_S = 7
const RTC_WDT_STG_SEL_OFF = 0
const RTC_WDT_STG_SEL_INT = 1
const RTC_WDT_STG_SEL_RESET_CPU = 2
const RTC_WDT_STG_SEL_RESET_SYSTEM = 3
const RTC_WDT_STG_SEL_RESET_RTC = 4
const RTC_CNTL_WDT_STG0_HOLD = 0xFFFFFFFF
const RTC_CNTL_WDT_STG0_HOLD_V = 0xFFFFFFFF
const RTC_CNTL_WDT_STG0_HOLD_S = 0
const RTC_CNTL_WDT_STG1_HOLD = 0xFFFFFFFF
const RTC_CNTL_WDT_STG1_HOLD_V = 0xFFFFFFFF
const RTC_CNTL_WDT_STG1_HOLD_S = 0
const RTC_CNTL_WDT_STG2_HOLD = 0xFFFFFFFF
const RTC_CNTL_WDT_STG2_HOLD_V = 0xFFFFFFFF
const RTC_CNTL_WDT_STG2_HOLD_S = 0
const RTC_CNTL_WDT_STG3_HOLD = 0xFFFFFFFF
const RTC_CNTL_WDT_STG3_HOLD_V = 0xFFFFFFFF
const RTC_CNTL_WDT_STG3_HOLD_S = 0
const RTC_CNTL_WDT_FEED_V = 0x1
const RTC_CNTL_WDT_FEED_S = 31
const RTC_CNTL_WDT_WKEY = 0xFFFFFFFF
const RTC_CNTL_WDT_WKEY_V = 0xFFFFFFFF
const RTC_CNTL_WDT_WKEY_S = 0
const RTC_CNTL_DTEST_RTC = 0x00000003
const RTC_CNTL_DTEST_RTC_V = 0x3
const RTC_CNTL_DTEST_RTC_S = 30
const RTC_CNTL_ENT_RTC_V = 0x1
const RTC_CNTL_ENT_RTC_S = 29
const RTC_CNTL_SW_STALL_PROCPU_C1 = 0x0000003F
const RTC_CNTL_SW_STALL_PROCPU_C1_V = 0x3F
const RTC_CNTL_SW_STALL_PROCPU_C1_S = 26
const RTC_CNTL_SW_STALL_APPCPU_C1 = 0x0000003F
const RTC_CNTL_SW_STALL_APPCPU_C1_V = 0x3F
const RTC_CNTL_SW_STALL_APPCPU_C1_S = 20
const RTC_CNTL_SCRATCH4 = 0xFFFFFFFF
const RTC_CNTL_SCRATCH4_V = 0xFFFFFFFF
const RTC_CNTL_SCRATCH4_S = 0
const RTC_CNTL_SCRATCH5 = 0xFFFFFFFF
const RTC_CNTL_SCRATCH5_V = 0xFFFFFFFF
const RTC_CNTL_SCRATCH5_S = 0
const RTC_CNTL_SCRATCH6 = 0xFFFFFFFF
const RTC_CNTL_SCRATCH6_V = 0xFFFFFFFF
const RTC_CNTL_SCRATCH6_S = 0
const RTC_CNTL_SCRATCH7 = 0xFFFFFFFF
const RTC_CNTL_SCRATCH7_V = 0xFFFFFFFF
const RTC_CNTL_SCRATCH7_S = 0
const RTC_CNTL_RDY_FOR_WAKEUP_V = 0x1
const RTC_CNTL_RDY_FOR_WAKEUP_S = 19
const RTC_CNTL_LOW_POWER_DIAG0 = 0xFFFFFFFF
const RTC_CNTL_LOW_POWER_DIAG0_V = 0xFFFFFFFF
const RTC_CNTL_LOW_POWER_DIAG0_S = 0
const RTC_CNTL_LOW_POWER_DIAG1 = 0xFFFFFFFF
const RTC_CNTL_LOW_POWER_DIAG1_V = 0xFFFFFFFF
const RTC_CNTL_LOW_POWER_DIAG1_S = 0
const RTC_CNTL_X32N_HOLD_FORCE_V = 0x1
const RTC_CNTL_X32N_HOLD_FORCE_S = 17
const RTC_CNTL_X32P_HOLD_FORCE_V = 0x1
const RTC_CNTL_X32P_HOLD_FORCE_S = 16
const RTC_CNTL_TOUCH_PAD7_HOLD_FORCE_V = 0x1
const RTC_CNTL_TOUCH_PAD7_HOLD_FORCE_S = 15
const RTC_CNTL_TOUCH_PAD6_HOLD_FORCE_V = 0x1
const RTC_CNTL_TOUCH_PAD6_HOLD_FORCE_S = 14
const RTC_CNTL_TOUCH_PAD5_HOLD_FORCE_V = 0x1
const RTC_CNTL_TOUCH_PAD5_HOLD_FORCE_S = 13
const RTC_CNTL_TOUCH_PAD4_HOLD_FORCE_V = 0x1
const RTC_CNTL_TOUCH_PAD4_HOLD_FORCE_S = 12
const RTC_CNTL_TOUCH_PAD3_HOLD_FORCE_V = 0x1
const RTC_CNTL_TOUCH_PAD3_HOLD_FORCE_S = 11
const RTC_CNTL_TOUCH_PAD2_HOLD_FORCE_V = 0x1
const RTC_CNTL_TOUCH_PAD2_HOLD_FORCE_S = 10
const RTC_CNTL_TOUCH_PAD1_HOLD_FORCE_V = 0x1
const RTC_CNTL_TOUCH_PAD1_HOLD_FORCE_S = 9
const RTC_CNTL_TOUCH_PAD0_HOLD_FORCE_V = 0x1
const RTC_CNTL_TOUCH_PAD0_HOLD_FORCE_S = 8
const RTC_CNTL_SENSE4_HOLD_FORCE_V = 0x1
const RTC_CNTL_SENSE4_HOLD_FORCE_S = 7
const RTC_CNTL_SENSE3_HOLD_FORCE_V = 0x1
const RTC_CNTL_SENSE3_HOLD_FORCE_S = 6
const RTC_CNTL_SENSE2_HOLD_FORCE_V = 0x1
const RTC_CNTL_SENSE2_HOLD_FORCE_S = 5
const RTC_CNTL_SENSE1_HOLD_FORCE_V = 0x1
const RTC_CNTL_SENSE1_HOLD_FORCE_S = 4
const RTC_CNTL_PDAC2_HOLD_FORCE_V = 0x1
const RTC_CNTL_PDAC2_HOLD_FORCE_S = 3
const RTC_CNTL_PDAC1_HOLD_FORCE_V = 0x1
const RTC_CNTL_PDAC1_HOLD_FORCE_S = 2
const RTC_CNTL_ADC2_HOLD_FORCE_V = 0x1
const RTC_CNTL_ADC2_HOLD_FORCE_S = 1
const RTC_CNTL_ADC1_HOLD_FORCE_V = 0x1
const RTC_CNTL_ADC1_HOLD_FORCE_S = 0
const RTC_CNTL_EXT_WAKEUP1_STATUS_CLR_V = 0x1
const RTC_CNTL_EXT_WAKEUP1_STATUS_CLR_S = 18
const RTC_CNTL_EXT_WAKEUP1_SEL = 0x0003FFFF
const RTC_CNTL_EXT_WAKEUP1_SEL_V = 0x3FFFF
const RTC_CNTL_EXT_WAKEUP1_SEL_S = 0
const RTC_CNTL_EXT_WAKEUP1_STATUS = 0x0003FFFF
const RTC_CNTL_EXT_WAKEUP1_STATUS_V = 0x3FFFF
const RTC_CNTL_EXT_WAKEUP1_STATUS_S = 0
const RTC_CNTL_BROWN_OUT_DET_V = 0x1
const RTC_CNTL_BROWN_OUT_DET_S = 31
const RTC_CNTL_BROWN_OUT_ENA_V = 0x1
const RTC_CNTL_BROWN_OUT_ENA_S = 30
const RTC_CNTL_DBROWN_OUT_THRES = 0x00000007
const RTC_CNTL_DBROWN_OUT_THRES_V = 0x7
const RTC_CNTL_DBROWN_OUT_THRES_S = 27
const RTC_CNTL_BROWN_OUT_RST_ENA_V = 0x1
const RTC_CNTL_BROWN_OUT_RST_ENA_S = 26
const RTC_CNTL_BROWN_OUT_RST_WAIT = 0x000003FF
const RTC_CNTL_BROWN_OUT_RST_WAIT_V = 0x3FF
const RTC_CNTL_BROWN_OUT_RST_WAIT_S = 16
const RTC_CNTL_BROWN_OUT_PD_RF_ENA_V = 0x1
const RTC_CNTL_BROWN_OUT_PD_RF_ENA_S = 15
const RTC_CNTL_BROWN_OUT_CLOSE_FLASH_ENA_V = 0x1
const RTC_CNTL_BROWN_OUT_CLOSE_FLASH_ENA_S = 14
const RTC_MEM_CRC_FINISH_V = 0x1
const RTC_MEM_CRC_FINISH_S = 31
const RTC_MEM_CRC_LEN_V = 0x7ff
const RTC_MEM_CRC_LEN_S = 20
const RTC_MEM_CRC_ADDR = 0x7ff
const RTC_MEM_CRC_ADDR_V = 0x7ff
const RTC_MEM_CRC_ADDR_S = 9
const RTC_MEM_CRC_START_V = 0x1
const RTC_MEM_CRC_START_S = 8
const RTC_MEM_PID_CONF = 0xff
const RTC_MEM_PID_CONF_M = 0xff
const RTC_MEM_PID_CONF_V = 0xff
const RTC_MEM_PID_CONF_S = 0
const RTC_CNTL_CNTL_DATE = 0x0FFFFFFF
const RTC_CNTL_CNTL_DATE_V = 0xFFFFFFF
const RTC_CNTL_CNTL_DATE_S = 0
const RTC_CNTL_RTC_CNTL_DATE_VERSION = 0x1604280
const SOC_CLK_RC_FAST_FREQ_APPROX = 8500000
const SOC_CLK_RC_SLOW_FREQ_APPROX = 150000
const SOC_CLK_XTAL32K_FREQ_APPROX = 32768
const SOC_DELAY_PLL_DBIAS_RAISE = 3
const SOC_DELAY_PLL_ENABLE_WITH_150K = 80
const SOC_DELAY_PLL_ENABLE_WITH_32K = 160
const SOC_DELAY_RTC_FAST_CLK_SWITCH = 3
const SOC_DELAY_RTC_SLOW_CLK_SWITCH = 300
const SOC_DELAY_RC_FAST_ENABLE = 50
const SOC_DELAY_RC_FAST_DIGI_SWITCH = 5
const RTC_CLK_CAL_FRACT = 19
const RTC_CNTL_CK8M_WAIT_DEFAULT = 20
const RTC_CK8M_ENABLE_WAIT_DEFAULT = 5
const RTC_VDDSDIO_TIEH_1_8V = 0
const RTC_VDDSDIO_TIEH_3_3V = 1

type X__int8T c.Char
type X__uint8T c.Char
type X__int16T int16
type X__uint16T uint16
type X__int32T c.Int
type X__uint32T c.Uint
type X__int64T c.LongLong
type X__uint64T c.UlongLong
type X__intLeast8T c.Char
type X__uintLeast8T c.Char
type X__intLeast16T int16
type X__uintLeast16T uint16
type X__intLeast32T c.Int
type X__uintLeast32T c.Uint
type X__intLeast64T c.LongLong
type X__uintLeast64T c.UlongLong
type X__intmaxT c.LongLong
type X__uintmaxT c.UlongLong
type X__intptrT c.Int
type X__uintptrT c.Uint
type IntLeast8T X__intLeast8T
type UintLeast8T X__uintLeast8T
type IntLeast16T X__intLeast16T
type UintLeast16T X__uintLeast16T
type IntLeast32T X__intLeast32T
type UintLeast32T X__uintLeast32T
type IntLeast64T X__intLeast64T
type UintLeast64T X__uintLeast64T
type IntFast8T c.Char
type UintFast8T c.Char
type IntFast16T int16
type UintFast16T uint16
type IntFast32T c.Int
type UintFast32T c.Uint
type IntFast64T c.LongLong
type UintFast64T c.UlongLong
type PtrdiffT c.Int
type WcharT c.Int

type MaxAlignT struct {
	X__clangMaxAlignNonce1 c.LongLong
	X__clangMaxAlignNonce2 c.Double
}
type X__gnucVaList c.Pointer
type WintT c.Uint
type X__blkcntT c.Long
type X__blksizeT c.Long
type X__fsblkcntT X__uint64T
type X__fsfilcntT X__uint32T
type X_offT c.Long
type X__pidT c.Int
type X__devT int16
type X__uidT uint16
type X__gidT uint16
type X__idT X__uint32T
type X__inoT uint16
type X__modeT X__uint32T
type X_off64T c.LongLong
type X__offT X_offT
type X__loffT X_off64T
type X__keyT c.Long
type X_fposT c.Long
type X__sizeT c.Uint
type X_ssizeT c.Int
type X__ssizeT X_ssizeT

type X_mbstateT struct {
	X__count c.Int
	X__value struct {
		X__wch WintT
	}
}
type X_iconvT c.Pointer
type X__clockT c.Ulong
type X__timeT X__intLeast64T
type X__clockidT c.Ulong
type X__daddrT c.Long
type X__timerT c.Ulong
type X__saFamilyT X__uint8T
type X__socklenT X__uint32T
type X__nlItem c.Int
type X__nlinkT uint16
type X__susecondsT c.Long
type X__usecondsT c.Ulong
type X__vaList c.Pointer
type X__ULong c.Ulong

type X__lock struct {
	Unused [8]uint8
}
type X_LOCKT *X__lock
type X_lockT X_LOCKT
type X_flockT X_LOCKT

type X_reent struct {
	Unused [8]uint8
}

type X__localeT struct {
	Unused [8]uint8
}

type X_Bigint struct {
	X_next   *X_Bigint
	X_k      c.Int
	X_maxwds c.Int
	X_sign   c.Int
	X_wds    c.Int
	X_x      [1]X__ULong
}

type X__tm struct {
	X__tmSec   c.Int
	X__tmMin   c.Int
	X__tmHour  c.Int
	X__tmMday  c.Int
	X__tmMon   c.Int
	X__tmYear  c.Int
	X__tmWday  c.Int
	X__tmYday  c.Int
	X__tmIsdst c.Int
}

type X_onExitArgs struct {
	X_fnargs    [32]c.Pointer
	X_dsoHandle [32]c.Pointer
	X_fntypes   X__ULong
	X_isCxa     X__ULong
}

type X_atexit struct {
	X_next          *X_atexit
	X_ind           c.Int
	X_fns           [32]c.Pointer
	X_onExitArgsPtr *X_onExitArgs
}

type X__sbuf struct {
	X_base *c.Char
	X_size c.Int
}

type X__sFILE struct {
	X_p       *c.Char
	X_r       c.Int
	X_w       c.Int
	X_flags   int16
	X_file    int16
	X_bf      X__sbuf
	X_lbfsize c.Int
	X_data    *X_reent
	X_cookie  c.Pointer
	X_read    c.Pointer
	X_write   c.Pointer
	X_seek    c.Pointer
	X_close   c.Pointer
	X_ub      X__sbuf
	X_up      *c.Char
	X_ur      c.Int
	X_ubuf    [3]c.Char
	X_nbuf    [1]c.Char
	X_lb      X__sbuf
	X_blksize c.Int
	X_offset  X_offT
	X_lock    X_flockT
	X_mbstate X_mbstateT
	X_flags2  c.Int
}
type X__FILE X__sFILE

type X_glue struct {
	X_next  *X_glue
	X_niobs c.Int
	X_iobs  *X__FILE
}

type X_rand48 struct {
	X_seed     [3]uint16
	X_mult     [3]uint16
	X_add      uint16
	X_randNext c.UlongLong
}

type X_mprec struct {
	X_result   *X_Bigint
	X_resultK  c.Int
	X_p5s      *X_Bigint
	X_freelist **X_Bigint
}

type X_miscReent struct {
	X_strtokLast     *c.Char
	X_mblenState     X_mbstateT
	X_wctombState    X_mbstateT
	X_mbtowcState    X_mbstateT
	X_l64aBuf        [8]c.Char
	X_getdateErr     c.Int
	X_mbrlenState    X_mbstateT
	X_mbrtowcState   X_mbstateT
	X_mbsrtowcsState X_mbstateT
	X_wcrtombState   X_mbstateT
	X_wcsrtombsState X_mbstateT
}

type DivT struct {
	Quot c.Int
	Rem  c.Int
}

type LdivT struct {
	Quot c.Long
	Rem  c.Long
}

type LldivT struct {
	Quot c.LongLong
	Rem  c.LongLong
}

// llgo:type C
type X__comparFnT func(c.Pointer, c.Pointer) c.Int
type FposT X_fposT
type OffT X__offT

// llgo:type C
type CookieReadFunctionT func(c.Pointer, *c.Char, c.SizeT) c.SsizeT

// llgo:type C
type CookieWriteFunctionT func(c.Pointer, *c.Char, c.SizeT) c.SsizeT

// llgo:type C
type CookieSeekFunctionT func(c.Pointer, *OffT, c.Int) c.Int

// llgo:type C
type CookieCloseFunctionT func(c.Pointer) c.Int

type CookieIoFunctionsT struct {
	Read  *CookieReadFunctionT
	Write *CookieWriteFunctionT
	Seek  *CookieSeekFunctionT
	Close *CookieCloseFunctionT
}
type EspErrT c.Int
type PeriphInterrputT c.Int

const (
	ETS_WIFI_MAC_INTR_SOURCE       PeriphInterrputT = 0
	ETS_WIFI_MAC_NMI_SOURCE        PeriphInterrputT = 1
	ETS_WIFI_BB_INTR_SOURCE        PeriphInterrputT = 2
	ETS_BT_MAC_INTR_SOURCE         PeriphInterrputT = 3
	ETS_BT_BB_INTR_SOURCE          PeriphInterrputT = 4
	ETS_BT_BB_NMI_SOURCE           PeriphInterrputT = 5
	ETS_RWBT_INTR_SOURCE           PeriphInterrputT = 6
	ETS_RWBLE_INTR_SOURCE          PeriphInterrputT = 7
	ETS_RWBT_NMI_SOURCE            PeriphInterrputT = 8
	ETS_RWBLE_NMI_SOURCE           PeriphInterrputT = 9
	ETS_SLC0_INTR_SOURCE           PeriphInterrputT = 10
	ETS_SLC1_INTR_SOURCE           PeriphInterrputT = 11
	ETS_UHCI0_INTR_SOURCE          PeriphInterrputT = 12
	ETS_UHCI1_INTR_SOURCE          PeriphInterrputT = 13
	ETS_TG0_T0_LEVEL_INTR_SOURCE   PeriphInterrputT = 14
	ETS_TG0_T1_LEVEL_INTR_SOURCE   PeriphInterrputT = 15
	ETS_TG0_WDT_LEVEL_INTR_SOURCE  PeriphInterrputT = 16
	ETS_TG0_LACT_LEVEL_INTR_SOURCE PeriphInterrputT = 17
	ETS_TG1_T0_LEVEL_INTR_SOURCE   PeriphInterrputT = 18
	ETS_TG1_T1_LEVEL_INTR_SOURCE   PeriphInterrputT = 19
	ETS_TG1_WDT_LEVEL_INTR_SOURCE  PeriphInterrputT = 20
	ETS_TG1_LACT_LEVEL_INTR_SOURCE PeriphInterrputT = 21
	ETS_GPIO_INTR_SOURCE           PeriphInterrputT = 22
	ETS_GPIO_NMI_SOURCE            PeriphInterrputT = 23
	ETS_FROM_CPU_INTR0_SOURCE      PeriphInterrputT = 24
	ETS_FROM_CPU_INTR1_SOURCE      PeriphInterrputT = 25
	ETS_FROM_CPU_INTR2_SOURCE      PeriphInterrputT = 26
	ETS_FROM_CPU_INTR3_SOURCE      PeriphInterrputT = 27
	ETS_SPI0_INTR_SOURCE           PeriphInterrputT = 28
	ETS_SPI1_INTR_SOURCE           PeriphInterrputT = 29
	ETS_SPI2_INTR_SOURCE           PeriphInterrputT = 30
	ETS_SPI3_INTR_SOURCE           PeriphInterrputT = 31
	ETS_I2S0_INTR_SOURCE           PeriphInterrputT = 32
	ETS_I2S1_INTR_SOURCE           PeriphInterrputT = 33
	ETS_UART0_INTR_SOURCE          PeriphInterrputT = 34
	ETS_UART1_INTR_SOURCE          PeriphInterrputT = 35
	ETS_UART2_INTR_SOURCE          PeriphInterrputT = 36
	ETS_SDIO_HOST_INTR_SOURCE      PeriphInterrputT = 37
	ETS_ETH_MAC_INTR_SOURCE        PeriphInterrputT = 38
	ETS_PWM0_INTR_SOURCE           PeriphInterrputT = 39
	ETS_PWM1_INTR_SOURCE           PeriphInterrputT = 40
	ETS_LEDC_INTR_SOURCE           PeriphInterrputT = 43
	ETS_EFUSE_INTR_SOURCE          PeriphInterrputT = 44
	ETS_TWAI_INTR_SOURCE           PeriphInterrputT = 45
	ETS_RTC_CORE_INTR_SOURCE       PeriphInterrputT = 46
	ETS_RMT_INTR_SOURCE            PeriphInterrputT = 47
	ETS_PCNT_INTR_SOURCE           PeriphInterrputT = 48
	ETS_I2C_EXT0_INTR_SOURCE       PeriphInterrputT = 49
	ETS_I2C_EXT1_INTR_SOURCE       PeriphInterrputT = 50
	ETS_RSA_INTR_SOURCE            PeriphInterrputT = 51
	ETS_SPI1_DMA_INTR_SOURCE       PeriphInterrputT = 52
	ETS_SPI2_DMA_INTR_SOURCE       PeriphInterrputT = 53
	ETS_SPI3_DMA_INTR_SOURCE       PeriphInterrputT = 54
	ETS_WDT_INTR_SOURCE            PeriphInterrputT = 55
	ETS_TIMER1_INTR_SOURCE         PeriphInterrputT = 56
	ETS_TIMER2_INTR_SOURCE         PeriphInterrputT = 57
	ETS_TG0_T0_EDGE_INTR_SOURCE    PeriphInterrputT = 58
	ETS_TG0_T1_EDGE_INTR_SOURCE    PeriphInterrputT = 59
	ETS_TG0_WDT_EDGE_INTR_SOURCE   PeriphInterrputT = 60
	ETS_TG0_LACT_EDGE_INTR_SOURCE  PeriphInterrputT = 61
	ETS_TG1_T0_EDGE_INTR_SOURCE    PeriphInterrputT = 62
	ETS_TG1_T1_EDGE_INTR_SOURCE    PeriphInterrputT = 63
	ETS_TG1_WDT_EDGE_INTR_SOURCE   PeriphInterrputT = 64
	ETS_TG1_LACT_EDGE_INTR_SOURCE  PeriphInterrputT = 65
	ETS_MMU_IA_INTR_SOURCE         PeriphInterrputT = 66
	ETS_MPU_IA_INTR_SOURCE         PeriphInterrputT = 67
	ETS_CACHE_IA_INTR_SOURCE       PeriphInterrputT = 68
	ETS_MAX_INTR_SOURCE            PeriphInterrputT = 69
)

/**
 * @brief Pin function information for a single RTCIO pad's.
 *
 * This is an internal function of the driver, and is not usually useful
 * for external use.
 */

type RtcIoDescT struct {
	Reg       c.Uint32T
	Mux       c.Uint32T
	Func      c.Uint32T
	Ie        c.Uint32T
	Pullup    c.Uint32T
	Pulldown  c.Uint32T
	Slpsel    c.Uint32T
	Slpie     c.Uint32T
	Slpoe     c.Uint32T
	Hold      c.Uint32T
	HoldForce c.Uint32T
	DrvV      c.Uint32T
	DrvS      c.Uint32T
	RtcNum    c.Int
}

type RtcCntlDevS struct {
	Options0 struct {
		Val c.Uint32T
	}
	SlpTimer0 c.Uint32T
	SlpTimer1 struct {
		Val c.Uint32T
	}
	TimeUpdate struct {
		Val c.Uint32T
	}
	Time0 c.Uint32T
	Time1 struct {
		Val c.Uint32T
	}
	State0 struct {
		Val c.Uint32T
	}
	Timer1 struct {
		Val c.Uint32T
	}
	Timer2 struct {
		Val c.Uint32T
	}
	Timer3 struct {
		Val c.Uint32T
	}
	Timer4 struct {
		Val c.Uint32T
	}
	Timer5 struct {
		Val c.Uint32T
	}
	AnaConf struct {
		Val c.Uint32T
	}
	ResetState struct {
		Val c.Uint32T
	}
	WakeupState struct {
		Val c.Uint32T
	}
	IntEna struct {
		Val c.Uint32T
	}
	IntRaw struct {
		Val c.Uint32T
	}
	IntSt struct {
		Val c.Uint32T
	}
	IntClr struct {
		Val c.Uint32T
	}
	RtcStore0  c.Uint32T
	RtcStore1  c.Uint32T
	RtcStore2  c.Uint32T
	RtcStore3  c.Uint32T
	ExtXtlConf struct {
		Val c.Uint32T
	}
	ExtWakeupConf struct {
		Val c.Uint32T
	}
	SlpRejectConf struct {
		Val c.Uint32T
	}
	CpuPeriodConf struct {
		Val c.Uint32T
	}
	SdioActConf struct {
		Val c.Uint32T
	}
	ClkConf struct {
		Val c.Uint32T
	}
	SdioConf struct {
		Val c.Uint32T
	}
	BiasConf struct {
		Val c.Uint32T
	}
	Rtc struct {
		Val c.Uint32T
	}
	RtcPwc struct {
		Val c.Uint32T
	}
	DigPwc struct {
		Val c.Uint32T
	}
	DigIso struct {
		Val c.Uint32T
	}
	WdtConfig0 struct {
		Val c.Uint32T
	}
	WdtConfig1 c.Uint32T
	WdtConfig2 c.Uint32T
	WdtConfig3 c.Uint32T
	WdtConfig4 c.Uint32T
	WdtFeed    struct {
		Val c.Uint32T
	}
	WdtWprotect c.Uint32T
	TestMux     struct {
		Val c.Uint32T
	}
	SwCpuStall struct {
		Val c.Uint32T
	}
	Store4    c.Uint32T
	Store5    c.Uint32T
	Store6    c.Uint32T
	Store7    c.Uint32T
	Diag0     c.Uint32T
	Diag1     c.Uint32T
	HoldForce struct {
		Val c.Uint32T
	}
	ExtWakeup1 struct {
		Val c.Uint32T
	}
	ExtWakeup1Status struct {
		Val c.Uint32T
	}
	BrownOut struct {
		Val c.Uint32T
	}
	Reserved39 c.Uint32T
	Reserved3d c.Uint32T
	Reserved41 c.Uint32T
	Reserved45 c.Uint32T
	Reserved49 c.Uint32T
	Reserved4d c.Uint32T
	Date       struct {
		Val c.Uint32T
	}
}
type RtcCntlDevT RtcCntlDevS
type SocRootClkT c.Int

const (
	SOC_ROOT_CLK_INT_RC_FAST SocRootClkT = 0
	SOC_ROOT_CLK_INT_RC_SLOW SocRootClkT = 1
	SOC_ROOT_CLK_EXT_XTAL    SocRootClkT = 2
	SOC_ROOT_CLK_EXT_XTAL32K SocRootClkT = 3
)

type SocCpuClkSrcT c.Int

const (
	SOC_CPU_CLK_SRC_XTAL    SocCpuClkSrcT = 0
	SOC_CPU_CLK_SRC_PLL     SocCpuClkSrcT = 1
	SOC_CPU_CLK_SRC_RC_FAST SocCpuClkSrcT = 2
	SOC_CPU_CLK_SRC_APLL    SocCpuClkSrcT = 3
	SOC_CPU_CLK_SRC_INVALID SocCpuClkSrcT = 4
)

type SocRtcSlowClkSrcT c.Int

const (
	SOC_RTC_SLOW_CLK_SRC_RC_SLOW      SocRtcSlowClkSrcT = 0
	SOC_RTC_SLOW_CLK_SRC_XTAL32K      SocRtcSlowClkSrcT = 1
	SOC_RTC_SLOW_CLK_SRC_RC_FAST_D256 SocRtcSlowClkSrcT = 2
	SOC_RTC_SLOW_CLK_SRC_INVALID      SocRtcSlowClkSrcT = 3
)

type SocRtcFastClkSrcT c.Int

const (
	SOC_RTC_FAST_CLK_SRC_XTAL_D4  SocRtcFastClkSrcT = 0
	SOC_RTC_FAST_CLK_SRC_XTAL_DIV SocRtcFastClkSrcT = 0
	SOC_RTC_FAST_CLK_SRC_RC_FAST  SocRtcFastClkSrcT = 1
	SOC_RTC_FAST_CLK_SRC_INVALID  SocRtcFastClkSrcT = 2
)

type SocXtalFreqT c.Int

const (
	SOC_XTAL_FREQ_AUTO SocXtalFreqT = 0
	SOC_XTAL_FREQ_24M  SocXtalFreqT = 24
	SOC_XTAL_FREQ_26M  SocXtalFreqT = 26
	SOC_XTAL_FREQ_40M  SocXtalFreqT = 40
)

type SocModuleClkT c.Int

const (
	SOC_MOD_CLK_CPU          SocModuleClkT = 1
	SOC_MOD_CLK_RTC_FAST     SocModuleClkT = 2
	SOC_MOD_CLK_RTC_SLOW     SocModuleClkT = 3
	SOC_MOD_CLK_APB          SocModuleClkT = 4
	SOC_MOD_CLK_PLL_D2       SocModuleClkT = 5
	SOC_MOD_CLK_PLL_F160M    SocModuleClkT = 6
	SOC_MOD_CLK_XTAL32K      SocModuleClkT = 7
	SOC_MOD_CLK_RC_FAST      SocModuleClkT = 8
	SOC_MOD_CLK_RC_FAST_D256 SocModuleClkT = 9
	SOC_MOD_CLK_XTAL         SocModuleClkT = 10
	SOC_MOD_CLK_REF_TICK     SocModuleClkT = 11
	SOC_MOD_CLK_APLL         SocModuleClkT = 12
	SOC_MOD_CLK_INVALID      SocModuleClkT = 13
)

type SocPeriphSystimerClkSrcT c.Int

const (
	SYSTIMER_CLK_SRC_XTAL    SocPeriphSystimerClkSrcT = 10
	SYSTIMER_CLK_SRC_DEFAULT SocPeriphSystimerClkSrcT = 10
)

type SocPeriphGptimerClkSrcT c.Int

const (
	GPTIMER_CLK_SRC_APB     SocPeriphGptimerClkSrcT = 4
	GPTIMER_CLK_SRC_DEFAULT SocPeriphGptimerClkSrcT = 4
)

type SocPeriphTgClkSrcLegacyT c.Int

const (
	TIMER_SRC_CLK_APB     SocPeriphTgClkSrcLegacyT = 4
	TIMER_SRC_CLK_DEFAULT SocPeriphTgClkSrcLegacyT = 4
)

type SocPeriphLcdClkSrcT c.Int

const (
	LCD_CLK_SRC_PLL160M SocPeriphLcdClkSrcT = 6
	LCD_CLK_SRC_DEFAULT SocPeriphLcdClkSrcT = 6
)

type SocPeriphRmtClkSrcT c.Int

const (
	RMT_CLK_SRC_APB      SocPeriphRmtClkSrcT = 4
	RMT_CLK_SRC_REF_TICK SocPeriphRmtClkSrcT = 11
	RMT_CLK_SRC_DEFAULT  SocPeriphRmtClkSrcT = 4
)

type SocPeriphRmtClkSrcLegacyT c.Int

const (
	RMT_BASECLK_APB     SocPeriphRmtClkSrcLegacyT = 4
	RMT_BASECLK_REF     SocPeriphRmtClkSrcLegacyT = 11
	RMT_BASECLK_DEFAULT SocPeriphRmtClkSrcLegacyT = 4
)

type SocPeriphUartClkSrcLegacyT c.Int

const (
	UART_SCLK_APB      SocPeriphUartClkSrcLegacyT = 4
	UART_SCLK_REF_TICK SocPeriphUartClkSrcLegacyT = 11
	UART_SCLK_DEFAULT  SocPeriphUartClkSrcLegacyT = 4
)

type SocPeriphMcpwmTimerClkSrcT c.Int

const (
	MCPWM_TIMER_CLK_SRC_PLL160M SocPeriphMcpwmTimerClkSrcT = 6
	MCPWM_TIMER_CLK_SRC_DEFAULT SocPeriphMcpwmTimerClkSrcT = 6
)

type SocPeriphMcpwmCaptureClkSrcT c.Int

const (
	MCPWM_CAPTURE_CLK_SRC_APB     SocPeriphMcpwmCaptureClkSrcT = 4
	MCPWM_CAPTURE_CLK_SRC_DEFAULT SocPeriphMcpwmCaptureClkSrcT = 4
)

type SocPeriphMcpwmCarrierClkSrcT c.Int

const (
	MCPWM_CARRIER_CLK_SRC_PLL160M SocPeriphMcpwmCarrierClkSrcT = 6
	MCPWM_CARRIER_CLK_SRC_DEFAULT SocPeriphMcpwmCarrierClkSrcT = 6
)

type SocPeriphI2sClkSrcT c.Int

const (
	I2S_CLK_SRC_DEFAULT  SocPeriphI2sClkSrcT = 6
	I2S_CLK_SRC_PLL_160M SocPeriphI2sClkSrcT = 6
	I2S_CLK_SRC_APLL     SocPeriphI2sClkSrcT = 12
)

type SocPeriphI2cClkSrcT c.Int

const (
	I2C_CLK_SRC_APB     SocPeriphI2cClkSrcT = 4
	I2C_CLK_SRC_DEFAULT SocPeriphI2cClkSrcT = 4
)

type SocPeriphSpiClkSrcT c.Int

const (
	SPI_CLK_SRC_DEFAULT SocPeriphSpiClkSrcT = 4
	SPI_CLK_SRC_APB     SocPeriphSpiClkSrcT = 4
)

type SocPeriphSdmClkSrcT c.Int

const (
	SDM_CLK_SRC_APB     SocPeriphSdmClkSrcT = 4
	SDM_CLK_SRC_DEFAULT SocPeriphSdmClkSrcT = 4
)

type SocPeriphDacDigiClkSrcT c.Int

const (
	DAC_DIGI_CLK_SRC_PLLD2   SocPeriphDacDigiClkSrcT = 5
	DAC_DIGI_CLK_SRC_APLL    SocPeriphDacDigiClkSrcT = 12
	DAC_DIGI_CLK_SRC_DEFAULT SocPeriphDacDigiClkSrcT = 5
)

type SocPeriphDacCosineClkSrcT c.Int

const (
	DAC_COSINE_CLK_SRC_RTC_FAST SocPeriphDacCosineClkSrcT = 2
	DAC_COSINE_CLK_SRC_DEFAULT  SocPeriphDacCosineClkSrcT = 2
)

type SocPeriphTwaiClkSrcT c.Int

const (
	TWAI_CLK_SRC_APB     SocPeriphTwaiClkSrcT = 4
	TWAI_CLK_SRC_DEFAULT SocPeriphTwaiClkSrcT = 4
)

type SocPeriphAdcDigiClkSrcT c.Int

const (
	ADC_DIGI_CLK_SRC_PLL_F160M SocPeriphAdcDigiClkSrcT = 6
	ADC_DIGI_CLK_SRC_APLL      SocPeriphAdcDigiClkSrcT = 12
	ADC_DIGI_CLK_SRC_DEFAULT   SocPeriphAdcDigiClkSrcT = 6
)

type SocPeriphAdcRtcClkSrcT c.Int

const (
	ADC_RTC_CLK_SRC_RC_FAST SocPeriphAdcRtcClkSrcT = 8
	ADC_RTC_CLK_SRC_DEFAULT SocPeriphAdcRtcClkSrcT = 8
)

type SocPeriphMwdtClkSrcT c.Int

const (
	MWDT_CLK_SRC_APB     SocPeriphMwdtClkSrcT = 4
	MWDT_CLK_SRC_DEFAULT SocPeriphMwdtClkSrcT = 4
)

type SocPeriphLedcClkSrcLegacyT c.Int

const (
	LEDC_AUTO_CLK        SocPeriphLedcClkSrcLegacyT = 0
	LEDC_USE_APB_CLK     SocPeriphLedcClkSrcLegacyT = 4
	LEDC_USE_RC_FAST_CLK SocPeriphLedcClkSrcLegacyT = 8
	LEDC_USE_REF_TICK    SocPeriphLedcClkSrcLegacyT = 11
	LEDC_USE_RTC8M_CLK   SocPeriphLedcClkSrcLegacyT = 8
)

type SocPeriphSdmmcClkSrcT c.Int

const (
	SDMMC_CLK_SRC_DEFAULT SocPeriphSdmmcClkSrcT = 6
	SDMMC_CLK_SRC_PLL160M SocPeriphSdmmcClkSrcT = 6
)

type SocClkoutSigIdT c.Int

const (
	CLKOUT_SIG_I2S0     SocClkoutSigIdT = 0
	CLKOUT_SIG_PLL      SocClkoutSigIdT = 1
	CLKOUT_SIG_RC_SLOW  SocClkoutSigIdT = 4
	CLKOUT_SIG_XTAL     SocClkoutSigIdT = 5
	CLKOUT_SIG_APLL     SocClkoutSigIdT = 6
	CLKOUT_SIG_REF_TICK SocClkoutSigIdT = 12
	CLKOUT_SIG_PLL_F80M SocClkoutSigIdT = 13
	CLKOUT_SIG_RC_FAST  SocClkoutSigIdT = 14
	CLKOUT_SIG_I2S1     SocClkoutSigIdT = 15
	CLKOUT_SIG_INVALID  SocClkoutSigIdT = 255
)

/**
 * @brief CPU clock configuration structure
 */

type RtcCpuFreqConfigS struct {
	Source        SocCpuClkSrcT
	SourceFreqMhz c.Uint32T
	Div           c.Uint32T
	FreqMhz       c.Uint32T
}
type RtcCpuFreqConfigT RtcCpuFreqConfigS
type RtcCalSelT c.Int

const (
	RTC_CAL_RTC_MUX  RtcCalSelT = 0
	RTC_CAL_8MD256   RtcCalSelT = 1
	RTC_CAL_32K_XTAL RtcCalSelT = 2
)

/**
 * Initialization parameters for rtc_clk_init
 */

type RtcClkConfigS struct {
	XtalFreq    SocXtalFreqT
	CpuFreqMhz  c.Uint32T
	FastClkSrc  SocRtcFastClkSrcT
	SlowClkSrc  SocRtcSlowClkSrcT
	Clk8mDiv    c.Uint32T
	SlowClkDcap c.Uint32T
	Clk8mDfreq  c.Uint32T
}
type RtcClkConfigT RtcClkConfigS

/**
 * @brief sleep configuration for rtc_sleep_init function
 */

type RtcSleepConfigS struct {
	LslpMemInfFpu      c.Uint32T
	RtcMemInfFpu       c.Uint32T
	RtcMemInfFollowCpu c.Uint32T
	RtcFastmemPdEn     c.Uint32T
	RtcSlowmemPdEn     c.Uint32T
	RtcPeriPdEn        c.Uint32T
	ModemPdEn          c.Uint32T
	Int8mPdEn          c.Uint32T
	RomMemPdEn         c.Uint32T
	DeepSlp            c.Uint32T
	WdtFlashbootModEn  c.Uint32T
	DigDbiasWak        c.Uint32T
	DigDbiasSlp        c.Uint32T
	RtcDbiasWak        c.Uint32T
	RtcDbiasSlp        c.Uint32T
	LslpMeminfPd       c.Uint32T
	VddsdioPdEn        c.Uint32T
	XtalFpu            c.Uint32T
	DeepSlpReject      c.Uint32T
	LightSlpReject     c.Uint32T
	DbgAttenSlp        c.Uint32T
}
type RtcSleepConfigT RtcSleepConfigS

/**
 * RTC power and clock control initialization settings
 */

type RtcConfigS struct {
	Ck8mWait     c.Uint32T
	XtalWait     c.Uint32T
	PllWait      c.Uint32T
	ClkctlInit   c.Uint32T
	PwrctlInit   c.Uint32T
	RtcDboostFpd c.Uint32T
}
type RtcConfigT RtcConfigS

/**
 * Structure describing vddsdio configuration
 */

type RtcVddsdioConfigS struct {
	Force  c.Uint32T
	Enable c.Uint32T
	Tieh   c.Uint32T
	Drefh  c.Uint32T
	Drefm  c.Uint32T
	Drefl  c.Uint32T
}
type RtcVddsdioConfigT RtcVddsdioConfigS
type RtcCpuFreqSrcT SocCpuClkSrcT
type RtcSlowFreqT SocRtcSlowClkSrcT
type RtcFastFreqT SocRtcFastClkSrcT
type RtcXtalFreqT SocXtalFreqT

type EspEtmChannelT struct {
	Unused [8]uint8
}
type EspEtmChannelHandleT *EspEtmChannelT

type EspEtmEventT struct {
	Unused [8]uint8
}
type EspEtmEventHandleT *EspEtmEventT

type EspEtmTaskT struct {
	Unused [8]uint8
}
type EspEtmTaskHandleT *EspEtmTaskT

/**
 * @brief ETM channel configuration
 */

type EspEtmChannelConfigT struct {
	Flags EtmChanFlags
}

type EtmChanFlags struct {
	Unused [8]uint8
}

type EspTimer struct {
	Unused [8]uint8
}
type EspTimerHandleT *EspTimer

// llgo:type C
type EspTimerCbT func(c.Pointer)
type EspTimerDispatchT c.Int

const (
	ESP_TIMER_TASK EspTimerDispatchT = 0
	ESP_TIMER_MAX  EspTimerDispatchT = 1
)

/**
 * @brief Timer configuration passed to esp_timer_create()
 */

type EspTimerCreateArgsT struct {
	Callback            EspTimerCbT
	Arg                 c.Pointer
	DispatchMethod      EspTimerDispatchT
	Name                *c.Char
	SkipUnhandledEvents bool
}
