package riscv

import _ "unsafe"

const ESP_SEMIHOSTING_SYS_APPTRACE_INIT = 0x101
const ESP_SEMIHOSTING_SYS_DBG_STUBS_INIT = 0x102
const ESP_SEMIHOSTING_SYS_BREAKPOINT_SET = 0x103
const ESP_SEMIHOSTING_SYS_WATCHPOINT_SET = 0x104
