package soc

import _ "unsafe"

const DPORT_RECORD_PDEBUGINST_SZ_V = 0xFF
const DPORT_RECORD_PDEBUGINST_SZ_S = 0
const DPORT_RECORD_PDEBUGINST_ISRC_V = 0x07
const DPORT_RECORD_PDEBUGINST_ISRC_S = 12
const DPORT_RECORD_PDEBUGINST_CINTL_V = 0x0F
const DPORT_RECORD_PDEBUGINST_CINTL_S = 24
const DPORT_RECORD_PDEBUGSTATUS_BBCAUSE_V = 0x3F
const DPORT_RECORD_PDEBUGSTATUS_BBCAUSE_S = 0
const DPORT_RECORD_PDEBUGSTATUS_BBCAUSE_PSO = 0x00
const DPORT_RECORD_PDEBUGSTATUS_BBCAUSE_DEP = 0x02
const DPORT_RECORD_PDEBUGSTATUS_BBCAUSE_CTL = 0x04
const DPORT_RECORD_PDEBUGSTATUS_BBCAUSE_ICM = 0x08
const DPORT_RECORD_PDEBUGSTATUS_BBCAUSE_DCM = 0x0C
const DPORT_RECORD_PDEBUGSTATUS_BBCAUSE_EXC0 = 0x10
const DPORT_RECORD_PDEBUGSTATUS_BBCAUSE_EXC1 = 0x11
const DPORT_RECORD_PDEBUGSTATUS_BBCAUSE_RPL = 0x14
const DPORT_RECORD_PDEBUGSTATUS_BBCAUSE_ITLB = 0x18
const DPORT_RECORD_PDEBUGSTATUS_BBCAUSE_ITLBM = 0x1A
const DPORT_RECORD_PDEBUGSTATUS_BBCAUSE_DTLB = 0x1C
const DPORT_RECORD_PDEBUGSTATUS_BBCAUSE_DTLBM = 0x1E
const DPORT_RECORD_PDEBUGSTATUS_BBCAUSE_STALL = 0x20
const DPORT_RECORD_PDEBUGSTATUS_BBCAUSE_HWMEC = 0x24
const DPORT_RECORD_PDEBUGSTATUS_BBCAUSE_WAITI = 0x28
const DPORT_RECORD_PDEBUGSTATUS_BBCAUSE_OTHER = 0x3C
const DPORT_RECORD_PDEBUGSTATUS_INSNTYPE_V = 0x3F
const DPORT_RECORD_PDEBUGSTATUS_INSNTYPE_S = 0
const DPORT_RECORD_PDEBUGSTATUS_INSNTYPE_JX = 0x00
const DPORT_RECORD_PDEBUGSTATUS_INSNTYPE_CALLX = 0x04
const DPORT_RECORD_PDEBUGSTATUS_INSNTYPE_CRET = 0x08
const DPORT_RECORD_PDEBUGSTATUS_INSNTYPE_ERET = 0x0C
const DPORT_RECORD_PDEBUGSTATUS_INSNTYPE_B = 0x10
const DPORT_RECORD_PDEBUGSTATUS_INSNTYPE_J = 0x14
const DPORT_RECORD_PDEBUGSTATUS_INSNTYPE_CALL = 0x18
const DPORT_RECORD_PDEBUGSTATUS_INSNTYPE_BN = 0x1C
const DPORT_RECORD_PDEBUGSTATUS_INSNTYPE_LOOP = 0x20
const DPORT_RECORD_PDEBUGSTATUS_INSNTYPE_S32C1I = 0x24
const DPORT_RECORD_PDEBUGSTATUS_INSNTYPE_WXSR2LB = 0x28
const DPORT_RECORD_PDEBUGSTATUS_INSNTYPE_WSR2MMID = 0x2C
const DPORT_RECORD_PDEBUGSTATUS_INSNTYPE_RWXSR = 0x30
const DPORT_RECORD_PDEBUGSTATUS_INSNTYPE_RWER = 0x34
const DPORT_RECORD_PDEBUGSTATUS_INSNTYPE_DEF = 0x3C
