package soc

import _ "unsafe"

const ECDSA_DATE_S = 0
const ECDSA_WORK_MODE_S = 0
const ECDSA_DETERMINISTIC_K_S = 5
const ECDSA_CLK_GATE_FORCE_ON_S = 0
const ECDSA_PREP_DONE_INT_RAW_S = 0
const ECDSA_PROC_DONE_INT_RAW_S = 1
const ECDSA_POST_DONE_INT_RAW_S = 2
const ECDSA_PREP_DONE_INT_ST_S = 0
const ECDSA_PROC_DONE_INT_ST_S = 1
const ECDSA_POST_DONE_INT_ST_S = 2
const ECDSA_PREP_DONE_INT_ENA_S = 0
const ECDSA_PROC_DONE_INT_ENA_S = 1
const ECDSA_POST_DONE_INT_ENA_S = 2
const ECDSA_PREP_DONE_INT_CLR_S = 0
const ECDSA_PROC_DONE_INT_CLR_S = 1
const ECDSA_POST_DONE_INT_CLR_S = 2
const ECDSA_START_S = 0
const ECDSA_LOAD_DONE_S = 1
const ECDSA_GET_DONE_S = 2
const ECDSA_BUSY_S = 0
const ECDSA_OPERATION_RESULT_S = 0
const ECDSA_SHA_MODE_S = 0
const ECDSA_SHA_START_S = 0
const ECDSA_SHA_CONTINUE_S = 0
const ECDSA_SHA_BUSY_S = 0
const ECDSA_MESSAGE_MEM_SIZE_BYTES = 32
const ECDSA_R_MEM_SIZE_BYTES = 32
const ECDSA_S_MEM_SIZE_BYTES = 32
const ECDSA_Z_MEM_SIZE_BYTES = 32
const ECDSA_QAX_MEM_SIZE_BYTES = 32
const ECDSA_QAY_MEM_SIZE_BYTES = 32
