package soc

import _ "unsafe"

const LP_APM_REGION_FILTER_EN_S = 0
const LP_APM_REGION0_ADDR_START_S = 0
const LP_APM_REGION0_ADDR_END_S = 0
const LP_APM_REGION0_R0_PMS_X_S = 0
const LP_APM_REGION0_R0_PMS_W_S = 1
const LP_APM_REGION0_R0_PMS_R_S = 2
const LP_APM_REGION0_R1_PMS_X_S = 4
const LP_APM_REGION0_R1_PMS_W_S = 5
const LP_APM_REGION0_R1_PMS_R_S = 6
const LP_APM_REGION0_R2_PMS_X_S = 8
const LP_APM_REGION0_R2_PMS_W_S = 9
const LP_APM_REGION0_R2_PMS_R_S = 10
const LP_APM_REGION1_ADDR_START_S = 0
const LP_APM_REGION1_ADDR_END_S = 0
const LP_APM_REGION1_R0_PMS_X_S = 0
const LP_APM_REGION1_R0_PMS_W_S = 1
const LP_APM_REGION1_R0_PMS_R_S = 2
const LP_APM_REGION1_R1_PMS_X_S = 4
const LP_APM_REGION1_R1_PMS_W_S = 5
const LP_APM_REGION1_R1_PMS_R_S = 6
const LP_APM_REGION1_R2_PMS_X_S = 8
const LP_APM_REGION1_R2_PMS_W_S = 9
const LP_APM_REGION1_R2_PMS_R_S = 10
const LP_APM_M0_PMS_FUNC_EN_S = 0
const LP_APM_M0_EXCEPTION_STATUS_S = 0
const LP_APM_M0_REGION_STATUS_CLR_S = 0
const LP_APM_M0_EXCEPTION_REGION_S = 0
const LP_APM_M0_EXCEPTION_MODE_S = 16
const LP_APM_M0_EXCEPTION_ID_S = 18
const LP_APM_M0_EXCEPTION_ADDR_S = 0
const LP_APM_M0_APM_INT_EN_S = 0
const LP_APM_CLK_EN_S = 0
const LP_APM_DATE_S = 0
