package soc

import _ "unsafe"

const LP_WDT_WDT_PAUSE_IN_SLP_S = 9
const LP_WDT_WDT_APPCPU_RESET_EN_S = 10
const LP_WDT_WDT_PROCPU_RESET_EN_S = 11
const LP_WDT_WDT_FLASHBOOT_MOD_EN_S = 12
const LP_WDT_WDT_SYS_RESET_LENGTH_S = 13
const LP_WDT_WDT_CPU_RESET_LENGTH_S = 16
const LP_WDT_WDT_STG3_S = 19
const LP_WDT_WDT_STG2_S = 22
const LP_WDT_WDT_STG1_S = 25
const LP_WDT_WDT_STG0_S = 28
const LP_WDT_WDT_EN_S = 31
const LP_WDT_WDT_STG0_HOLD_S = 0
const LP_WDT_WDT_STG1_HOLD_S = 0
const LP_WDT_WDT_STG2_HOLD_S = 0
const LP_WDT_WDT_STG3_HOLD_S = 0
const LP_WDT_CHIP_RESET_TARGET_S = 0
const LP_WDT_CHIP_RESET_EN_S = 8
const LP_WDT_CHIP_RESET_KEY_S = 9
const LP_WDT_RTC_WDT_FEED_S = 31
const LP_WDT_WDT_WKEY_S = 0
const LP_WDT_SWD_RESET_FLAG_S = 0
const LP_WDT_SWD_AUTO_FEED_EN_S = 18
const LP_WDT_SWD_RST_FLAG_CLR_S = 19
const LP_WDT_SWD_SIGNAL_WIDTH_S = 20
const LP_WDT_SWD_DISABLE_S = 30
const LP_WDT_SWD_FEED_S = 31
const LP_WDT_SWD_WKEY_S = 0
const LP_WDT_SUPER_WDT_INT_RAW_S = 30
const LP_WDT_LP_WDT_INT_RAW_S = 31
const LP_WDT_SUPER_WDT_INT_ST_S = 30
const LP_WDT_LP_WDT_INT_ST_S = 31
const LP_WDT_SUPER_WDT_INT_ENA_S = 30
const LP_WDT_LP_WDT_INT_ENA_S = 31
const LP_WDT_SUPER_WDT_INT_CLR_S = 30
const LP_WDT_LP_WDT_INT_CLR_S = 31
const LP_WDT_LP_WDT_DATE_S = 0
const LP_WDT_CLK_EN_S = 31
