package soc

import _ "unsafe"

const MODEM_LPCON_CLK_EN_S = 0
const MODEM_LPCON_CLK_COEX_LP_SEL_OSC_SLOW_S = 0
const MODEM_LPCON_CLK_COEX_LP_SEL_OSC_FAST_S = 1
const MODEM_LPCON_CLK_COEX_LP_SEL_XTAL_S = 2
const MODEM_LPCON_CLK_COEX_LP_SEL_XTAL32K_S = 3
const MODEM_LPCON_CLK_COEX_LP_DIV_NUM_S = 4
const MODEM_LPCON_CLK_COEX_EN_S = 1
const MODEM_LPCON_CLK_I2C_MST_EN_S = 2
const MODEM_LPCON_CLK_FE_MEM_EN_S = 5
const MODEM_LPCON_CLK_COEX_FO_S = 1
const MODEM_LPCON_CLK_I2C_MST_FO_S = 2
const MODEM_LPCON_CLK_FE_MEM_FO_S = 5
const MODEM_LPCON_PWR_TICK_TARGET_S = 0
const MODEM_LPCON_RST_COEX_S = 1
const MODEM_LPCON_RST_I2C_MST_S = 2
const MODEM_LPCON_AGC_MEM_FORCE_PU_S = 2
const MODEM_LPCON_AGC_MEM_FORCE_PD_S = 3
const MODEM_LPCON_PBUS_MEM_FORCE_PU_S = 4
const MODEM_LPCON_PBUS_MEM_FORCE_PD_S = 5
const MODEM_LPCON_I2C_MST_MEM_FORCE_PU_S = 8
const MODEM_LPCON_I2C_MST_MEM_FORCE_PD_S = 9
const MODEM_LPCON_CHAN_FREQ_MEM_FORCE_PU_S = 10
const MODEM_LPCON_CHAN_FREQ_MEM_FORCE_PD_S = 11
const MODEM_LPCON_MODEM_PWR_MEM_WP_S = 12
const MODEM_LPCON_MODEM_PWR_MEM_WA_S = 15
const MODEM_LPCON_MODEM_PWR_MEM_RA_S = 18
const MODEM_LPCON_MODEM_PWR_MEM_RM_S = 20
const MODEM_LPCON_DATE_S = 0
