package soc

import _ "unsafe"

const MODEM_SYSCON_CLK_EN_S = 0
const MODEM_SYSCON_CLK_ETM_EN_S = 21
const MODEM_SYSCON_CLK_ZB_APB_EN_S = 22
const MODEM_SYSCON_CLK_ZB_MAC_EN_S = 23
const MODEM_SYSCON_CLK_MODEM_SEC_ECB_EN_S = 24
const MODEM_SYSCON_CLK_MODEM_SEC_CCM_EN_S = 25
const MODEM_SYSCON_CLK_MODEM_SEC_BAH_EN_S = 26
const MODEM_SYSCON_CLK_MODEM_SEC_APB_EN_S = 27
const MODEM_SYSCON_CLK_MODEM_SEC_EN_S = 28
const MODEM_SYSCON_CLK_BLE_TIMER_APB_EN_S = 29
const MODEM_SYSCON_CLK_BLE_TIMER_EN_S = 30
const MODEM_SYSCON_CLK_DATA_DUMP_EN_S = 31
const MODEM_SYSCON_CLK_ETM_FO_S = 22
const MODEM_SYSCON_CLK_ZB_FO_S = 24
const MODEM_SYSCON_CLK_MODEM_SEC_FO_S = 29
const MODEM_SYSCON_CLK_BLE_TIMER_FO_S = 30
const MODEM_SYSCON_CLK_DATA_DUMP_FO_S = 31
const MODEM_SYSCON_RST_FE_S = 14
const MODEM_SYSCON_RST_BTMAC_APB_S = 15
const MODEM_SYSCON_RST_BTMAC_S = 16
const MODEM_SYSCON_RST_BTBB_APB_S = 17
const MODEM_SYSCON_RST_BTBB_S = 18
const MODEM_SYSCON_RST_ETM_S = 22
const MODEM_SYSCON_RST_ZBMAC_S = 24
const MODEM_SYSCON_RST_MODEM_ECB_S = 25
const MODEM_SYSCON_RST_MODEM_CCM_S = 26
const MODEM_SYSCON_RST_MODEM_BAH_S = 27
const MODEM_SYSCON_RST_MODEM_SEC_S = 29
const MODEM_SYSCON_RST_BLE_TIMER_S = 30
const MODEM_SYSCON_RST_DATA_DUMP_S = 31
const MODEM_SYSCON_CLK_FE_16M_EN_S = 12
const MODEM_SYSCON_CLK_FE_32M_EN_S = 13
const MODEM_SYSCON_CLK_FE_SDM_EN_S = 14
const MODEM_SYSCON_CLK_FE_ADC_EN_S = 15
const MODEM_SYSCON_CLK_FE_APB_EN_S = 16
const MODEM_SYSCON_CLK_BT_APB_EN_S = 17
const MODEM_SYSCON_CLK_BT_EN_S = 18
const MODEM_SYSCON_CLK_FE_FO_S = 16
const MODEM_SYSCON_CLK_BT_FO_S = 18
const MODEM_SYSCON_MODEM_MEM_WP_S = 0
const MODEM_SYSCON_MODEM_MEM_WA_S = 3
const MODEM_SYSCON_MODEM_MEM_RA_S = 6
const MODEM_SYSCON_DATE_S = 0
