package soc

import _ "unsafe"

const I2C_PMU = 0x6d
const I2C_PMU_HOSTID = 0
const I2C_PMU_EN_I2C_RTC_DREG = 8
const I2C_PMU_EN_I2C_RTC_DREG_MSB = 0
const I2C_PMU_EN_I2C_RTC_DREG_LSB = 0
const I2C_PMU_EN_I2C_DIG_DREG = 8
const I2C_PMU_EN_I2C_DIG_DREG_MSB = 1
const I2C_PMU_EN_I2C_DIG_DREG_LSB = 1
const I2C_PMU_EN_I2C_RTC_DREG_SLP = 8
const I2C_PMU_EN_I2C_RTC_DREG_SLP_MSB = 2
const I2C_PMU_EN_I2C_RTC_DREG_SLP_LSB = 2
const I2C_PMU_EN_I2C_DIG_DREG_SLP = 8
const I2C_PMU_EN_I2C_DIG_DREG_SLP_MSB = 3
const I2C_PMU_EN_I2C_DIG_DREG_SLP_LSB = 3
const I2C_PMU_OR_XPD_RTC_REG = 9
const I2C_PMU_OR_XPD_RTC_REG_MSB = 4
const I2C_PMU_OR_XPD_RTC_REG_LSB = 4
const I2C_PMU_OR_XPD_DIG_REG = 9
const I2C_PMU_OR_XPD_DIG_REG_MSB = 5
const I2C_PMU_OR_XPD_DIG_REG_LSB = 5
const I2C_PMU_OC_SCK_DCAP = 14
const I2C_PMU_OC_SCK_DCAP_MSB = 7
const I2C_PMU_OC_SCK_DCAP_LSB = 0
const I2C_PMU_OR_XPD_TRX = 15
const I2C_PMU_OR_XPD_TRX_MSB = 2
const I2C_PMU_OR_XPD_TRX_LSB = 2
const I2C_PMU_SEL_PLL8M_REF = 21
const I2C_PMU_SEL_PLL8M_REF_MSB = 6
const I2C_PMU_SEL_PLL8M_REF_LSB = 6
