package soc

import _ "unsafe"

const I2C_SAR_ADC = 0x69
const I2C_SAR_ADC_HOSTID = 0
const ADC_SAR1_SAMPLE_CYCLE_ADDR = 0x2
const ADC_SAR1_SAMPLE_CYCLE_ADDR_MSB = 0x2
const ADC_SAR1_SAMPLE_CYCLE_ADDR_LSB = 0x0
const ADC_SAR1_DREF_ADDR = 0x2
const ADC_SAR1_DREF_ADDR_MSB = 0x6
const ADC_SAR1_DREF_ADDR_LSB = 0x4
const ADC_SAR2_DREF_ADDR = 0x5
const ADC_SAR2_DREF_ADDR_MSB = 0x6
const ADC_SAR2_DREF_ADDR_LSB = 0x4
const ADC_SAR1_INITIAL_CODE_HIGH_ADDR = 0x1
const ADC_SAR1_INITIAL_CODE_HIGH_ADDR_MSB = 0x3
const ADC_SAR1_INITIAL_CODE_HIGH_ADDR_LSB = 0x0
const ADC_SAR1_INITIAL_CODE_LOW_ADDR = 0x0
const ADC_SAR1_INITIAL_CODE_LOW_ADDR_MSB = 0x7
const ADC_SAR1_INITIAL_CODE_LOW_ADDR_LSB = 0x0
const I2C_SARADC_TSENS_DAC = 0x6
const I2C_SARADC_TSENS_DAC_MSB = 3
const I2C_SARADC_TSENS_DAC_LSB = 0
const I2C_SARADC_DTEST = 7
const I2C_SARADC_DTEST_MSB = 1
const I2C_SARADC_DTEST_LSB = 0
const I2C_SARADC_ENT_SAR = 7
const I2C_SARADC_ENT_SAR_MSB = 3
const I2C_SARADC_ENT_SAR_LSB = 1
const I2C_SARADC_EN_TOUT_SAR1_BUS = 7
const I2C_SARADC_EN_TOUT_SAR1_BUS_MSB = 5
const I2C_SARADC_EN_TOUT_SAR1_BUS_LSB = 5
const I2C_SARADC_SAR1_INIT_CODE_LSB = 0
const I2C_SARADC_SAR1_INIT_CODE_LSB_MSB = 7
const I2C_SARADC_SAR1_INIT_CODE_LSB_LSB = 0
const I2C_SARADC_SAR1_INIT_CODE_MSB = 1
const I2C_SARADC_SAR1_INIT_CODE_MSB_MSB = 3
const I2C_SARADC_SAR1_INIT_CODE_MSB_LSB = 0
const I2C_SARADC_SAR2_INIT_CODE_LSB = 3
const I2C_SARADC_SAR2_INIT_CODE_LSB_MSB = 7
const I2C_SARADC_SAR2_INIT_CODE_LSB_LSB = 0
const I2C_SARADC_SAR2_INIT_CODE_MSB = 4
const I2C_SARADC_SAR2_INIT_CODE_MSB_MSB = 3
const I2C_SARADC_SAR2_INIT_CODE_MSB_LSB = 0
const ADC_SAR1_ENCAL_GND_ADDR = 0x8
const ADC_SAR1_ENCAL_GND_ADDR_MSB = 0x1
const ADC_SAR1_ENCAL_GND_ADDR_LSB = 0x1
