package soc

import _ "unsafe"

const I2C_PMU_OR_DREFL_VBAT = 17
const I2C_PMU_OR_DREFL_VBAT_MSB = 4
const I2C_PMU_OR_DREFL_VBAT_LSB = 2
const I2C_PMU_OR_DREFH_VBAT = 17
const I2C_PMU_OR_DREFH_VBAT_MSB = 7
const I2C_PMU_OR_DREFH_VBAT_LSB = 5
const I2C_PMU_OR_XPD_DIGDET = 18
const I2C_PMU_OR_XPD_DIGDET_MSB = 0
const I2C_PMU_OR_DREFL_DIGDET = 18
const I2C_PMU_OR_DREFL_DIGDET_MSB = 4
const I2C_PMU_OR_DREFL_DIGDET_LSB = 2
const I2C_PMU_OR_DREFH_DIGDET = 18
const I2C_PMU_OR_DREFH_DIGDET_MSB = 7
const I2C_PMU_OR_DREFH_DIGDET_LSB = 5
const I2C_PMU_OR_DREFL_VDDA = 19
const I2C_PMU_OR_DREFL_VDDA_MSB = 4
const I2C_PMU_OR_DREFL_VDDA_LSB = 2
const I2C_PMU_OR_DREFH_VDDA = 19
const I2C_PMU_OR_DREFH_VDDA_MSB = 7
const I2C_PMU_OR_DREFH_VDDA_LSB = 5
