package soc

import _ "unsafe"

const I2C_BBPLL = 0x66
const I2C_BBPLL_HOSTID = 0
const I2C_BBPLL_OC_REF_DIV = 2
const I2C_BBPLL_OC_REF_DIV_MSB = 3
const I2C_BBPLL_OC_REF_DIV_LSB = 0
const I2C_BBPLL_OC_DIV = 3
const I2C_BBPLL_OC_DIV_MSB = 5
const I2C_BBPLL_OC_DIV_LSB = 0
const I2C_BBPLL_OC_DHREF_SEL = 5
const I2C_BBPLL_OC_DHREF_SEL_MSB = 5
const I2C_BBPLL_OC_DHREF_SEL_LSB = 4
const I2C_BBPLL_OC_DLREF_SEL = 5
const I2C_BBPLL_OC_DLREF_SEL_MSB = 7
const I2C_BBPLL_OC_DLREF_SEL_LSB = 6
