package soc

import _ "unsafe"

const RTCIO_GPIO7_CHANNEL = 0
const RTCIO_CHANNEL_0_GPIO_NUM = 7
const RTCIO_GPIO8_CHANNEL = 1
const RTCIO_CHANNEL_1_GPIO_NUM = 8
const RTCIO_GPIO9_CHANNEL = 2
const RTCIO_CHANNEL_2_GPIO_NUM = 9
const RTCIO_GPIO10_CHANNEL = 3
const RTCIO_CHANNEL_3_GPIO_NUM = 10
const RTCIO_GPIO11_CHANNEL = 4
const RTCIO_CHANNEL_4_GPIO_NUM = 11
const RTCIO_GPIO12_CHANNEL = 5
const RTCIO_CHANNEL_5_GPIO_NUM = 12
const RTCIO_GPIO13_CHANNEL = 6
const RTCIO_CHANNEL_6_GPIO_NUM = 13
const RTCIO_GPIO14_CHANNEL = 7
const RTCIO_CHANNEL_7_GPIO_NUM = 14
