package soc

import _ "unsafe"

const MSPI_FUNC_NUM = 0
const MSPI_IOMUX_PIN_NUM_HD = 18
const MSPI_IOMUX_PIN_NUM_WP = 17
const MSPI_IOMUX_PIN_NUM_CS0 = 15
const MSPI_IOMUX_PIN_NUM_CLK = 19
const MSPI_IOMUX_PIN_NUM_MOSI = 20
const MSPI_IOMUX_PIN_NUM_MISO = 16
const SPI2_FUNC_NUM = 2
const SPI2_IOMUX_PIN_NUM_MISO = 0
const SPI2_IOMUX_PIN_NUM_HD = 3
const SPI2_IOMUX_PIN_NUM_WP = 2
const SPI2_IOMUX_PIN_NUM_CLK = 4
const SPI2_IOMUX_PIN_NUM_MOSI = 5
const SPI2_IOMUX_PIN_NUM_CS = 1
