package soc

import _ "unsafe"

const XTS_AES_PLAIN = 0xFFFFFFFF
const XTS_AES_PLAIN_V = 0xFFFFFFFF
const XTS_AES_PLAIN_S = 0
const XTS_AES_LINESIZE = 0x00000003
const XTS_AES_LINESIZE_V = 0x3
const XTS_AES_LINESIZE_S = 0
const XTS_AES_DESTINATION_V = 0x1
const XTS_AES_DESTINATION_S = 0
const XTS_AES_PHYSICAL_ADDRESS = 0x03FFFFFF
const XTS_AES_PHYSICAL_ADDRESS_V = 0x3FFFFFF
const XTS_AES_PHYSICAL_ADDRESS_S = 0
const XTS_AES_TRIGGER_V = 0x1
const XTS_AES_TRIGGER_S = 0
const XTS_AES_RELEASE_V = 0x1
const XTS_AES_RELEASE_S = 0
const XTS_AES_DESTROY_V = 0x1
const XTS_AES_DESTROY_S = 0
const XTS_AES_STATE = 0x00000003
const XTS_AES_STATE_V = 0x3
const XTS_AES_STATE_S = 0
const XTS_AES_DATE = 0x3FFFFFFF
const XTS_AES_DATE_V = 0x3FFFFFFF
const XTS_AES_DATE_S = 0
const XTS_AES_CRYPT_DPA_SELECT_REGISTER_V = 0x1
const XTS_AES_CRYPT_DPA_SELECT_REGISTER_S = 4
const XTS_AES_CRYPT_CALC_D_DPA_EN_V = 0x1
const XTS_AES_CRYPT_CALC_D_DPA_EN_S = 3
const XTS_AES_CRYPT_SECURITY_LEVEL = 0x00000007
const XTS_AES_CRYPT_SECURITY_LEVEL_V = 0x7
const XTS_AES_CRYPT_SECURITY_LEVEL_S = 0
const XTS_AES_MODE_PSEUDO_S = 0
const XTS_AES_PSEUDO_RNG_CNT_S = 2
const XTS_AES_PSEUDO_BASE_S = 5
const XTS_AES_PSEUDO_INC_S = 9
