package hal

import _ "unsafe"

const GDMA_LL_CHANNEL_MAX_PRIORITY = 5
const GDMA_LL_AHB_GROUP_START_ID = 0
const GDMA_LL_AHB_NUM_GROUPS = 1
const GDMA_LL_AHB_PAIRS_PER_GROUP = 3
const GDMA_LL_AHB_TX_RX_SHARE_INTERRUPT = 1
const GDMA_LL_AHB_DESC_ALIGNMENT = 4
const GDMA_LL_AHB_RX_BURST_NEEDS_ALIGNMENT = 1
