package esp_rom

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

const EFUSE_SPICONFIG_SPI_DEFAULTS = 0
const EFUSE_SPICONFIG_HSPI_DEFAULTS = 1
const EFUSE_SPICONFIG_RET_SPICLK_MASK = 0x3f
const EFUSE_SPICONFIG_RET_SPICLK_SHIFT = 0
const EFUSE_SPICONFIG_RET_SPIQ_MASK = 0x3f
const EFUSE_SPICONFIG_RET_SPIQ_SHIFT = 6
const EFUSE_SPICONFIG_RET_SPID_MASK = 0x3f
const EFUSE_SPICONFIG_RET_SPID_SHIFT = 12
const EFUSE_SPICONFIG_RET_SPICS0_MASK = 0x3f
const EFUSE_SPICONFIG_RET_SPICS0_SHIFT = 18
const EFUSE_SPICONFIG_RET_SPIHD_MASK = 0x3f
const EFUSE_SPICONFIG_RET_SPIHD_SHIFT = 24

type EtsEfusePurposeT c.Int

const ETS_EFUSE_KEY_PURPOSE_INVALID EtsEfusePurposeT = -1

type EtsEfuseBlockT c.Int

const (
	ETS_EFUSE_BLOCK0          EtsEfuseBlockT = 0
	ETS_EFUSE_BLOCK_SYS_DATA1 EtsEfuseBlockT = 1
	ETS_EFUSE_BLOCK_SYS_DATA2 EtsEfuseBlockT = 2
	ETS_EFUSE_BLOCK_KEY0      EtsEfuseBlockT = 3
	ETS_EFUSE_BLOCK_MAX       EtsEfuseBlockT = 4
)
