package esp_rom

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

type SLEEPMODE c.Int

const (
	AWAKE       SLEEPMODE = 0
	LIGHT_SLEEP SLEEPMODE = 1
	DEEP_SLEEP  SLEEPMODE = 2
)

type RESETREASON c.Int

const (
	NO_MEAN                RESETREASON = 0
	POWERON_RESET          RESETREASON = 1
	RTC_SW_SYS_RESET       RESETREASON = 3
	DEEPSLEEP_RESET        RESETREASON = 5
	TG0WDT_SYS_RESET       RESETREASON = 7
	RTCWDT_SYS_RESET       RESETREASON = 9
	INTRUSION_RESET        RESETREASON = 10
	TG0WDT_CPU_RESET       RESETREASON = 11
	RTC_SW_CPU_RESET       RESETREASON = 12
	RTCWDT_CPU_RESET       RESETREASON = 13
	RTCWDT_BROWN_OUT_RESET RESETREASON = 15
	RTCWDT_RTC_RESET       RESETREASON = 16
	SUPER_WDT_RESET        RESETREASON = 18
	GLITCH_RTC_RESET       RESETREASON = 19
	EFUSE_RESET            RESETREASON = 20
	JTAG_RESET             RESETREASON = 24
)

type WAKEUPREASON c.Int

const (
	NO_SLEEP        WAKEUPREASON = 0
	EXT_EVENT0_TRIG WAKEUPREASON = 1
	EXT_EVENT1_TRIG WAKEUPREASON = 2
	GPIO_TRIG       WAKEUPREASON = 4
	TIMER_EXPIRE    WAKEUPREASON = 8
	SDIO_TRIG       WAKEUPREASON = 16
	MAC_TRIG        WAKEUPREASON = 32
	UART0_TRIG      WAKEUPREASON = 64
	UART1_TRIG      WAKEUPREASON = 128
	SAR_TRIG        WAKEUPREASON = 512
	BT_TRIG         WAKEUPREASON = 1024
	RISCV_TRIG      WAKEUPREASON = 2048
	XTAL_DEAD_TRIG  WAKEUPREASON = 4096
	RISCV_TRAP_TRIG WAKEUPREASON = 8192
)

type WAKEUPENABLE c.Int

const (
	DISEN_WAKEUP       WAKEUPENABLE = 0
	EXT_EVENT0_TRIG_EN WAKEUPENABLE = 1
	EXT_EVENT1_TRIG_EN WAKEUPENABLE = 2
	GPIO_TRIG_EN       WAKEUPENABLE = 4
	TIMER_EXPIRE_EN    WAKEUPENABLE = 8
	SDIO_TRIG_EN       WAKEUPENABLE = 16
	MAC_TRIG_EN        WAKEUPENABLE = 32
	UART0_TRIG_EN      WAKEUPENABLE = 64
	UART1_TRIG_EN      WAKEUPENABLE = 128
	SAR_TRIG_EN        WAKEUPENABLE = 512
	BT_TRIG_EN         WAKEUPENABLE = 1024
	RISCV_TRIG_EN      WAKEUPENABLE = 2048
	XTAL_DEAD_TRIG_EN  WAKEUPENABLE = 4096
	RISCV_TRAP_TRIG_EN WAKEUPENABLE = 8192
)
