package soc

import _ "unsafe"

const HP_SYSTEM_ENABLE_SPI_MANUAL_ENCRYPT_S = 0
const HP_SYSTEM_ENABLE_DOWNLOAD_DB_ENCRYPT_S = 1
const HP_SYSTEM_ENABLE_DOWNLOAD_G0CB_DECRYPT_S = 2
const HP_SYSTEM_ENABLE_DOWNLOAD_MANUAL_ENCRYPT_S = 3
const HP_SYSTEM_CACHE_USAGE_S = 0
const HP_SYSTEM_SRAM_USAGE_S = 8
const HP_SYSTEM_MAC_DUMP_ALLOC_S = 16
const HP_SYSTEM_SEC_DPA_LEVEL_S = 0
const HP_SYSTEM_SEC_DPA_CFG_SEL_S = 2
const HP_SYSTEM_CPU_PERI_TIMEOUT_THRES_S = 0
const HP_SYSTEM_CPU_PERI_TIMEOUT_INT_CLEAR_S = 16
const HP_SYSTEM_CPU_PERI_TIMEOUT_PROTECT_EN_S = 17
const HP_SYSTEM_CPU_PERI_TIMEOUT_ADDR_S = 0
const HP_SYSTEM_CPU_PERI_TIMEOUT_UID_S = 0
const HP_SYSTEM_HP_PERI_TIMEOUT_THRES_S = 0
const HP_SYSTEM_HP_PERI_TIMEOUT_INT_CLEAR_S = 16
const HP_SYSTEM_HP_PERI_TIMEOUT_PROTECT_EN_S = 17
const HP_SYSTEM_HP_PERI_TIMEOUT_ADDR_S = 0
const HP_SYSTEM_HP_PERI_TIMEOUT_UID_S = 0
const HP_SYSTEM_MODEM_PERI_TIMEOUT_THRES_S = 0
const HP_SYSTEM_MODEM_PERI_TIMEOUT_INT_CLEAR_S = 16
const HP_SYSTEM_MODEM_PERI_TIMEOUT_PROTECT_EN_S = 17
const HP_SYSTEM_MODEM_PERI_TIMEOUT_ADDR_S = 0
const HP_SYSTEM_MODEM_PERI_TIMEOUT_UID_S = 0
const HP_SYSTEM_DIS_SDIO_PROB_S = 0
const HP_SYSTEM_SDIO_WIN_ACCESS_EN_S = 1
const HP_SYSTEM_RETENTION_DISABLE_S = 0
const HP_SYSTEM_ROM_TABLE_LOCK_S = 0
const HP_SYSTEM_ROM_TABLE_S = 0
const HP_SYSTEM_CORE_DEBUG_RUNSTALL_ENABLE_S = 0
const HP_SYSTEM_HP_MEM_WPULSE_S = 0
const HP_SYSTEM_HP_MEM_WA_S = 3
const HP_SYSTEM_HP_MEM_RA_S = 6
const HP_SYSTEM_REDCY_ENA_S = 0
const HP_SYSTEM_REDCY_RESULT_S = 1
const HP_SYSTEM_REDCY_LOW_S = 0
const HP_SYSTEM_REDCY_HIGH_S = 0
const HP_SYSTEM_CLK_EN_S = 0
const HP_SYSTEM_DATE_S = 0
