package soc

import _ "unsafe"

const TRACE_MEM_STAET_ADDR_S = 0
const TRACE_MEM_END_ADDR_S = 0
const TRACE_MEM_CURRENT_ADDR_S = 0
const TRACE_MEM_CURRENT_ADDR_UPDATE_S = 0
const TRACE_FIFO_EMPTY_S = 0
const TRACE_WORK_STATUS_S = 1
const TRACE_FIFO_OVERFLOW_INTR_ENA_S = 0
const TRACE_MEM_FULL_INTR_ENA_S = 1
const TRACE_FIFO_OVERFLOW_INTR_RAW_S = 0
const TRACE_MEM_FULL_INTR_RAW_S = 1
const TRACE_FIFO_OVERFLOW_INTR_CLR_S = 0
const TRACE_MEM_FULL_INTR_CLR_S = 1
const TRACE_TRIGGER_ON_S = 0
const TRACE_TRIGGER_OFF_S = 1
const TRACE_MEM_LOOP_S = 2
const TRACE_RESTART_ENA_S = 3
const TRACE_RESYNC_PROLONGED_S = 0
const TRACE_RESYNC_MODE_S = 24
const TRACE_CLK_EN_S = 0
const TRACE_DATE_S = 0
