package soc

import _ "unsafe"

const TOUCH_PAD_NUM0_GPIO_NUM = 4
const TOUCH_PAD_NUM1_GPIO_NUM = 0
const TOUCH_PAD_NUM2_GPIO_NUM = 2
const TOUCH_PAD_NUM3_GPIO_NUM = 15
const TOUCH_PAD_NUM4_GPIO_NUM = 13
const TOUCH_PAD_NUM5_GPIO_NUM = 12
const TOUCH_PAD_NUM6_GPIO_NUM = 14
const TOUCH_PAD_NUM7_GPIO_NUM = 27
const TOUCH_PAD_NUM8_GPIO_NUM = 33
const TOUCH_PAD_NUM9_GPIO_NUM = 32
