package soc

import _ "unsafe"

const MSPI_FUNC_NUM = 0
const MSPI_IOMUX_PIN_NUM_HD = 12
const MSPI_IOMUX_PIN_NUM_WP = 13
const MSPI_IOMUX_PIN_NUM_CS0 = 14
const MSPI_IOMUX_PIN_NUM_CLK = 15
const MSPI_IOMUX_PIN_NUM_MOSI = 16
const MSPI_IOMUX_PIN_NUM_MISO = 17
const SPI2_FUNC_NUM = 2
const SPI2_IOMUX_PIN_NUM_MISO = 2
const SPI2_IOMUX_PIN_NUM_HD = 4
const SPI2_IOMUX_PIN_NUM_WP = 5
const SPI2_IOMUX_PIN_NUM_CLK = 6
const SPI2_IOMUX_PIN_NUM_MOSI = 7
const SPI2_IOMUX_PIN_NUM_CS = 10
