package soc

import _ "unsafe"

const ASSIST_DEBUG_CORE_0_SP_SPILL_MIN_ENA_S = 0
const ASSIST_DEBUG_CORE_0_SP_SPILL_MAX_ENA_S = 1
const ASSIST_DEBUG_CORE_0_SP_SPILL_MIN_RAW_S = 0
const ASSIST_DEBUG_CORE_0_SP_SPILL_MAX_RAW_S = 1
const ASSIST_DEBUG_CORE_0_SP_SPILL_MIN_RLS_S = 0
const ASSIST_DEBUG_CORE_0_SP_SPILL_MAX_RLS_S = 1
const ASSIST_DEBUG_CORE_0_SP_SPILL_MIN_CLR_S = 0
const ASSIST_DEBUG_CORE_0_SP_SPILL_MAX_CLR_S = 1
const ASSIST_DEBUG_CORE_0_SP_MIN_S = 0
const ASSIST_DEBUG_CORE_0_SP_MAX_S = 0
const ASSIST_DEBUG_CORE_0_SP_PC_S = 0
const ASSIST_DEBUG_CORE_0_RCD_RECORDEN_S = 0
const ASSIST_DEBUG_CORE_0_RCD_PDEBUGEN_S = 1
const ASSIST_DEBUG_CORE_0_RCD_PDEBUGPC_S = 0
const ASSIST_DEBUG_CORE_0_RCD_PDEBUGSP_S = 0
const ASSIST_DEBUG_CORE_0_LASTPC_BEFORE_EXC_S = 0
const ASSIST_DEBUG_CORE_0_DEBUG_MODE_S = 0
const ASSIST_DEBUG_CORE_0_DEBUG_MODULE_ACTIVE_S = 1
const ASSIST_DEBUG_CLK_EN_S = 0
const ASSIST_DEBUG_DATE_S = 0
