package soc

import _ "unsafe"

const MODEM_CLKRST_CLK_EN_V = 0x1
const MODEM_CLKRST_CLK_EN_S = 0
const MODEM_CLKRST_LP_TIMER_CLK_DIV_NUM = 0x000000FF
const MODEM_CLKRST_LP_TIMER_CLK_DIV_NUM_V = 0xFF
const MODEM_CLKRST_LP_TIMER_CLK_DIV_NUM_S = 4
const MODEM_CLKRST_LP_TIMER_SEL_XTAL32K_V = 0x1
const MODEM_CLKRST_LP_TIMER_SEL_XTAL32K_S = 3
const MODEM_CLKRST_LP_TIMER_SEL_XTAL_V = 0x1
const MODEM_CLKRST_LP_TIMER_SEL_XTAL_S = 2
const MODEM_CLKRST_LP_TIMER_SEL_8M_V = 0x1
const MODEM_CLKRST_LP_TIMER_SEL_8M_S = 1
const MODEM_CLKRST_LP_TIMER_SEL_RTC_SLOW_V = 0x1
const MODEM_CLKRST_LP_TIMER_SEL_RTC_SLOW_S = 0
const MODEM_CLKRST_COEX_LPCLK_DIV_NUM = 0x000000FF
const MODEM_CLKRST_COEX_LPCLK_DIV_NUM_V = 0xFF
const MODEM_CLKRST_COEX_LPCLK_DIV_NUM_S = 4
const MODEM_CLKRST_COEX_LPCLK_SEL_XTAL32K_V = 0x1
const MODEM_CLKRST_COEX_LPCLK_SEL_XTAL32K_S = 3
const MODEM_CLKRST_COEX_LPCLK_SEL_XTAL_V = 0x1
const MODEM_CLKRST_COEX_LPCLK_SEL_XTAL_S = 2
const MODEM_CLKRST_COEX_LPCLK_SEL_8M_V = 0x1
const MODEM_CLKRST_COEX_LPCLK_SEL_8M_S = 1
const MODEM_CLKRST_COEX_LPCLK_SEL_RTC_SLOW_V = 0x1
const MODEM_CLKRST_COEX_LPCLK_SEL_RTC_SLOW_S = 0
const MODEM_CLKRST_BLETIMER_CLK_IS_ACTIVE_V = 0x1
const MODEM_CLKRST_BLETIMER_CLK_IS_ACTIVE_S = 1
const MODEM_CLKRST_BLETIMER_USE_XTAL_V = 0x1
const MODEM_CLKRST_BLETIMER_USE_XTAL_S = 0
const MODEM_CLKRST_ETM_CLK_ACTIVE_V = 0x1
const MODEM_CLKRST_ETM_CLK_ACTIVE_S = 1
const MODEM_CLKRST_ETM_CLK_SEL_V = 0x1
const MODEM_CLKRST_ETM_CLK_SEL_S = 0
const MODEM_CLKRST_DATE = 0x0FFFFFFF
const MODEM_CLKRST_DATE_V = 0xFFFFFFF
const MODEM_CLKRST_DATE_S = 0
