package soc

import _ "unsafe"

const SENSITIVE_ROM_TABLE_LOCK_S = 0
const SENSITIVE_ROM_TABLE_S = 0
const SENSITIVE_APB_PERIPHERAL_ACCESS_LOCK_S = 0
const SENSITIVE_APB_PERIPHERAL_ACCESS_SPLIT_BURST_S = 0
const SENSITIVE_INTERNAL_SRAM_USAGE_LOCK_S = 0
const SENSITIVE_INTERNAL_SRAM_USAGE_CPU_CACHE_S = 0
const SENSITIVE_INTERNAL_SRAM_USAGE_CPU_SRAM_S = 1
const SENSITIVE_INTERNAL_SRAM_USAGE_MAC_DUMP_SRAM_S = 0
const SENSITIVE_INTERNAL_SRAM_ALLOC_MAC_DUMP_S = 3
const SENSITIVE_CACHE_TAG_ACCESS_LOCK_S = 0
const SENSITIVE_PRO_I_TAG_RD_ACS_S = 0
const SENSITIVE_PRO_I_TAG_WR_ACS_S = 1
const SENSITIVE_PRO_D_TAG_RD_ACS_S = 2
const SENSITIVE_PRO_D_TAG_WR_ACS_S = 3
const SENSITIVE_CACHE_MMU_ACCESS_LOCK_S = 0
const SENSITIVE_PRO_MMU_RD_ACS_S = 0
const SENSITIVE_PRO_MMU_WR_ACS_S = 1
const SENSITIVE_PIF_ACCESS_MONITOR_LOCK_S = 0
const SENSITIVE_PIF_ACCESS_MONITOR_NONWORD_VIOLATE_CLR_S = 0
const SENSITIVE_PIF_ACCESS_MONITOR_NONWORD_VIOLATE_EN_S = 1
const SENSITIVE_PIF_ACCESS_MONITOR_NONWORD_VIOLATE_INTR_S = 0
const SENSITIVE_PIF_ACCESS_MONITOR_NONWORD_VIOLATE_STATUS_HSIZE_S = 1
const SENSITIVE_PIF_ACCESS_MONITOR_NONWORD_VIOLATE_STATUS_HADDR_S = 0
const SENSITIVE_XTS_AES_KEY_UPDATE_S = 0
const SENSITIVE_CLK_EN_S = 0
const SENSITIVE_SENSITIVE_REG_DATE_S = 0
