package hal

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

const CLK_LL_BBPLL_IR_CAL_DELAY_VAL = 0x18
const CLK_LL_BBPLL_IR_CAL_EXT_CAP_VAL = 0x20
const CLK_LL_BBPLL_OC_ENB_FCAL_VAL = 0x9a
const CLK_LL_BBPLL_OC_ENB_VCON_VAL = 0x00
const CLK_LL_BBPLL_BBADC_CAL_7_0_VAL = 0x00
const CLK_LL_BBPLL_ENDIV5_VAL_320M = 0x43
const CLK_LL_BBPLL_BBADC_DSMP_VAL_320M = 0x84
const CLK_LL_BBPLL_ENDIV5_VAL_480M = 0xc3
const CLK_LL_BBPLL_BBADC_DSMP_VAL_480M = 0x74
const CLK_LL_APLL_SDM_STOP_VAL_1 = 0x09
const CLK_LL_APLL_SDM_STOP_VAL_2_REV0 = 0x69
const CLK_LL_APLL_SDM_STOP_VAL_2_REV1 = 0x49
const CLK_LL_APLL_CAL_DELAY_1 = 0x0f
const CLK_LL_APLL_CAL_DELAY_2 = 0x3f
const CLK_LL_APLL_CAL_DELAY_3 = 0x1f
const CLK_LL_XTAL_32K_DAC_VAL = 1
const CLK_LL_XTAL_32K_DRES_VAL = 3
const CLK_LL_XTAL_32K_DBIAS_VAL = 0
const CLK_LL_XTAL_32K_EXT_DAC_VAL = 2
const CLK_LL_XTAL_32K_EXT_DRES_VAL = 3
const CLK_LL_XTAL_32K_EXT_DBIAS_VAL = 1
const CLK_LL_XTAL_32K_BOOTSTRAP_DAC_VAL = 3
const CLK_LL_XTAL_32K_BOOTSTRAP_DRES_VAL = 3
const CLK_LL_XTAL_32K_BOOTSTRAP_DBIAS_VAL = 0
const CLK_LL_RC_FAST_WAIT_DEFAULT = 20
const CLK_LL_RC_FAST_ENABLE_WAIT_DEFAULT = 5

type ClkLlXtal32kEnableModeT c.Int

const (
	CLK_LL_XTAL32K_ENABLE_MODE_CRYSTAL   ClkLlXtal32kEnableModeT = 0
	CLK_LL_XTAL32K_ENABLE_MODE_EXTERNAL  ClkLlXtal32kEnableModeT = 1
	CLK_LL_XTAL32K_ENABLE_MODE_BOOTSTRAP ClkLlXtal32kEnableModeT = 2
)
