package hal

import _ "unsafe"

const MWDT_LL_DEFAULT_CLK_PRESCALER = 40000
const TIMG_WDT_STG_SEL_OFF = 0
const TIMG_WDT_STG_SEL_INT = 1
const TIMG_WDT_STG_SEL_RESET_CPU = 2
const TIMG_WDT_STG_SEL_RESET_SYSTEM = 3
const TIMG_WDT_RESET_LENGTH_100_NS = 0
const TIMG_WDT_RESET_LENGTH_200_NS = 1
const TIMG_WDT_RESET_LENGTH_300_NS = 2
const TIMG_WDT_RESET_LENGTH_400_NS = 3
const TIMG_WDT_RESET_LENGTH_500_NS = 4
const TIMG_WDT_RESET_LENGTH_800_NS = 5
const TIMG_WDT_RESET_LENGTH_1600_NS = 6
const TIMG_WDT_RESET_LENGTH_3200_NS = 7
