package hal

import _ "unsafe"

const SHA256_BLOCK_SZ = 64
const SHA256_DIGEST_SZ = 32
const EFUSE_KEY_PURPOSE_HMAC_DOWN_JTAG = 6
const EFUSE_KEY_PURPOSE_HMAC_DOWN_DIGITAL_SIGNATURE = 7
const EFUSE_KEY_PURPOSE_HMAC_UP = 8
const EFUSE_KEY_PURPOSE_HMAC_DOWN_ALL = 5
