package hal

import _ "unsafe"

const LP_WDT_WKEY_VALUE = 0x50D83AA1
const LP_WDT_SWD_WKEY_VALUE = 0x50D83AA1
const LP_WDT_RESET_LENGTH_100_NS = 0
const LP_WDT_RESET_LENGTH_200_NS = 1
const LP_WDT_RESET_LENGTH_300_NS = 2
const LP_WDT_RESET_LENGTH_400_NS = 3
const LP_WDT_RESET_LENGTH_500_NS = 4
const LP_WDT_RESET_LENGTH_800_NS = 5
const LP_WDT_RESET_LENGTH_1600_NS = 6
const LP_WDT_RESET_LENGTH_3200_NS = 7
const LP_WDT_STG_SEL_OFF = 0
const LP_WDT_STG_SEL_INT = 1
const LP_WDT_STG_SEL_RESET_CPU = 2
const LP_WDT_STG_SEL_RESET_SYSTEM = 3
const LP_WDT_STG_SEL_RESET_RTC = 4
