package soc

import _ "unsafe"

const ECC_MULT_CALC_DONE_INT_RAW_S = 0
const ECC_MULT_CALC_DONE_INT_ST_S = 0
const ECC_MULT_CALC_DONE_INT_ENA_S = 0
const ECC_MULT_CALC_DONE_INT_CLR_S = 0
const ECC_MULT_START_S = 0
const ECC_MULT_RESET_S = 1
const ECC_MULT_KEY_LENGTH_S = 2
const ECC_MULT_SECURITY_MODE_S = 3
const ECC_MULT_CLK_EN_S = 4
const ECC_MULT_WORK_MODE_S = 5
const ECC_MULT_VERIFICATION_RESULT_S = 8
const ECC_MULT_MEM_CLOCK_GATE_FORCE_ON_S = 31
const ECC_MULT_DATE_S = 0
const ECC_MULT_K_MEM_SIZE_BYTES = 32
const ECC_MULT_PX_MEM_SIZE_BYTES = 32
const ECC_MULT_PY_MEM_SIZE_BYTES = 32
