package soc

import _ "unsafe"

const HMAC_SET_START_S = 0
const HMAC_PURPOSE_SET_S = 0
const HMAC_KEY_SET_S = 0
const HMAC_SET_PARA_END_S = 0
const HMAC_SET_TEXT_ONE_S = 0
const HMAC_SET_TEXT_ING_S = 0
const HMAC_SET_TEXT_END_S = 0
const HMAC_SET_RESULT_END_S = 0
const HMAC_SET_INVALIDATE_JTAG_S = 0
const HMAC_SET_INVALIDATE_DS_S = 0
const HMAC_QUREY_CHECK_S = 0
const HMAC_BUSY_STATE_S = 0
const HMAC_WR_MESSAGE_MEM_SIZE_BYTES = 64
const HMAC_RD_RESULT_MEM_SIZE_BYTES = 32
const HMAC_SET_TEXT_PAD_S = 0
const HMAC_SET_ONE_BLOCK_S = 0
const HMAC_SOFT_JTAG_CTRL_S = 0
const HMAC_WR_JTAG_S = 0
const HMAC_DATE_S = 0
