package soc

import _ "unsafe"

const LP_I2C_ANA_MST_I2C0_CTRL_S = 0
const LP_I2C_ANA_MST_I2C0_BUSY_S = 25
const LP_I2C_ANA_MST_I2C0_CONF_S = 0
const LP_I2C_ANA_MST_I2C0_STATUS_S = 24
const LP_I2C_ANA_MST_I2C0_RDATA_S = 0
const LP_I2C_ANA_MST_I2C0_CLK_SEL_S = 8
const LP_I2C_ANA_MST_I2C_MST_SEL_S = 11
const LP_I2C_ANA_MST_ANA_CONF1_S = 0
const LP_I2C_ANA_MST_I2C_MST_NOUSE_S = 0
const LP_I2C_ANA_MST_I2C_DEVICE_EN_S = 0
const LP_I2C_ANA_MST_I2C_MAT_DATE_S = 0
const LP_I2C_ANA_MST_I2C_MAT_CLK_EN_S = 28
