package soc

import _ "unsafe"

const LP_TIMER_MAIN_TIMER_TAR_LOW0_S = 0
const LP_TIMER_MAIN_TIMER_TAR_HIGH0_S = 0
const LP_TIMER_MAIN_TIMER_TAR_EN0_S = 31
const LP_TIMER_MAIN_TIMER_TAR_LOW1_S = 0
const LP_TIMER_MAIN_TIMER_TAR_HIGH1_S = 0
const LP_TIMER_MAIN_TIMER_TAR_EN1_S = 31
const LP_TIMER_MAIN_TIMER_UPDATE_S = 28
const LP_TIMER_MAIN_TIMER_XTAL_OFF_S = 29
const LP_TIMER_MAIN_TIMER_SYS_STALL_S = 30
const LP_TIMER_MAIN_TIMER_SYS_RST_S = 31
const LP_TIMER_MAIN_TIMER_BUF0_LOW_S = 0
const LP_TIMER_MAIN_TIMER_BUF0_HIGH_S = 0
const LP_TIMER_MAIN_TIMER_BUF1_LOW_S = 0
const LP_TIMER_MAIN_TIMER_BUF1_HIGH_S = 0
const LP_TIMER_MAIN_TIMER_ALARM_LOAD_S = 31
const LP_TIMER_OVERFLOW_RAW_S = 30
const LP_TIMER_SOC_WAKEUP_INT_RAW_S = 31
const LP_TIMER_OVERFLOW_ST_S = 30
const LP_TIMER_SOC_WAKEUP_INT_ST_S = 31
const LP_TIMER_OVERFLOW_ENA_S = 30
const LP_TIMER_SOC_WAKEUP_INT_ENA_S = 31
const LP_TIMER_OVERFLOW_CLR_S = 30
const LP_TIMER_SOC_WAKEUP_INT_CLR_S = 31
const LP_TIMER_MAIN_TIMER_OVERFLOW_LP_INT_RAW_S = 30
const LP_TIMER_MAIN_TIMER_LP_INT_RAW_S = 31
const LP_TIMER_MAIN_TIMER_OVERFLOW_LP_INT_ST_S = 30
const LP_TIMER_MAIN_TIMER_LP_INT_ST_S = 31
const LP_TIMER_MAIN_TIMER_OVERFLOW_LP_INT_ENA_S = 30
const LP_TIMER_MAIN_TIMER_LP_INT_ENA_S = 31
const LP_TIMER_MAIN_TIMER_OVERFLOW_LP_INT_CLR_S = 30
const LP_TIMER_MAIN_TIMER_LP_INT_CLR_S = 31
const LP_TIMER_DATE_S = 0
const LP_TIMER_CLK_EN_S = 31
