package soc

import _ "unsafe"

const LPPERI_RNG_CK_EN_S = 24
const LPPERI_OTP_DBG_CK_EN_S = 25
const LPPERI_LP_UART_CK_EN_S = 26
const LPPERI_LP_IO_CK_EN_S = 27
const LPPERI_LP_EXT_I2C_CK_EN_S = 28
const LPPERI_LP_ANA_I2C_CK_EN_S = 29
const LPPERI_EFUSE_CK_EN_S = 30
const LPPERI_LP_CPU_CK_EN_S = 31
const LPPERI_BUS_RESET_EN_S = 23
const LPPERI_OTP_DBG_RESET_EN_S = 25
const LPPERI_LP_UART_RESET_EN_S = 26
const LPPERI_LP_IO_RESET_EN_S = 27
const LPPERI_LP_EXT_I2C_RESET_EN_S = 28
const LPPERI_LP_ANA_I2C_RESET_EN_S = 29
const LPPERI_EFUSE_RESET_EN_S = 30
const LPPERI_LP_CPU_RESET_EN_S = 31
const LPPERI_RNG_DATA_S = 0
const LPPERI_LPCORE_DBGM_UNAVALIABLE_S = 31
const LPPERI_LP_PERI_TIMEOUT_THRES_S = 14
const LPPERI_LP_PERI_TIMEOUT_INT_CLEAR_S = 30
const LPPERI_LP_PERI_TIMEOUT_PROTECT_EN_S = 31
const LPPERI_LP_PERI_TIMEOUT_ADDR_S = 0
const LPPERI_LP_PERI_TIMEOUT_UID_S = 0
const LPPERI_UART_WAKEUP_FLAG_CLR_S = 0
const LPPERI_UART_WAKEUP_FLAG_S = 1
const LPPERI_UART_WAKEUP_EN_S = 29
const LPPERI_UART_MEM_FORCE_PD_S = 30
const LPPERI_UART_MEM_FORCE_PU_S = 31
const LPPERI_LP_INTERRUPT_SOURCE_S = 0
const LPPERI_LPPERI_DATE_S = 0
const LPPERI_CLK_EN_S = 31
