package soc

import _ "unsafe"

const MEM_MONITOR_LOG_ENA_S = 0
const MEM_MONITOR_LOG_MODE_S = 3
const MEM_MONITOR_LOG_MEM_LOOP_ENABLE_S = 7
const MEM_MONITOR_LOG_CHECK_DATA_S = 0
const MEM_MONITOR_LOG_DATA_MASK_S = 0
const MEM_MONITOR_LOG_MIN_S = 0
const MEM_MONITOR_LOG_MAX_S = 0
const MEM_MONITOR_LOG_MEM_START_S = 0
const MEM_MONITOR_LOG_MEM_END_S = 0
const MEM_MONITOR_LOG_MEM_CURRENT_ADDR_S = 0
const MEM_MONITOR_LOG_MEM_ADDR_UPDATE_S = 0
const MEM_MONITOR_LOG_MEM_FULL_FLAG_S = 0
const MEM_MONITOR_CLR_LOG_MEM_FULL_FLAG_S = 1
const MEM_MONITOR_CLK_EN_S = 0
const MEM_MONITOR_DATE_S = 0
