package soc

import _ "unsafe"

const PARL_IO_RX_EOF_GEN_SEL_S = 0
const PARL_IO_RX_START_S = 1
const PARL_IO_RX_DATA_BYTELEN_S = 2
const PARL_IO_RX_SW_EN_S = 18
const PARL_IO_RX_PULSE_SUBMODE_SEL_S = 19
const PARL_IO_RX_LEVEL_SUBMODE_SEL_S = 23
const PARL_IO_RX_SMP_MODE_SEL_S = 24
const PARL_IO_RX_CLK_EDGE_SEL_S = 26
const PARL_IO_RX_BIT_PACK_ORDER_S = 27
const PARL_IO_RX_BUS_WID_SEL_S = 28
const PARL_IO_RX_FIFO_SRST_S = 31
const PARL_IO_RX_REG_UPDATE_S = 2
const PARL_IO_RX_TIMEOUT_EN_S = 3
const PARL_IO_RX_EXT_EN_SEL_S = 12
const PARL_IO_RX_TIMEOUT_THRESHOLD_S = 16
const PARL_IO_TX_BYTELEN_S = 2
const PARL_IO_TX_GATING_EN_S = 18
const PARL_IO_TX_START_S = 19
const PARL_IO_TX_HW_VALID_EN_S = 20
const PARL_IO_TX_SMP_EDGE_SEL_S = 25
const PARL_IO_TX_BIT_UNPACK_ORDER_S = 26
const PARL_IO_TX_BUS_WID_SEL_S = 27
const PARL_IO_TX_FIFO_SRST_S = 30
const PARL_IO_TX_IDLE_VALUE_S = 16
const PARL_IO_TX_READY_S = 31
const PARL_IO_TX_FIFO_REMPTY_INT_ENA_S = 0
const PARL_IO_RX_FIFO_WFULL_INT_ENA_S = 1
const PARL_IO_TX_EOF_INT_ENA_S = 2
const PARL_IO_TX_FIFO_REMPTY_INT_RAW_S = 0
const PARL_IO_RX_FIFO_WFULL_INT_RAW_S = 1
const PARL_IO_TX_EOF_INT_RAW_S = 2
const PARL_IO_TX_FIFO_REMPTY_INT_ST_S = 0
const PARL_IO_RX_FIFO_WFULL_INT_ST_S = 1
const PARL_IO_TX_EOF_INT_ST_S = 2
const PARL_IO_TX_FIFO_REMPTY_INT_CLR_S = 0
const PARL_IO_RX_FIFO_WFULL_INT_CLR_S = 1
const PARL_IO_TX_EOF_INT_CLR_S = 2
const PARL_IO_CLK_EN_S = 0
const PARL_IO_DATE_S = 0
