package soc

import _ "unsafe"

const RTCIO_GPIO0_CHANNEL = 0
const RTCIO_CHANNEL_0_GPIO_NUM = 0
const RTCIO_GPIO1_CHANNEL = 1
const RTCIO_CHANNEL_1_GPIO_NUM = 1
const RTCIO_GPIO2_CHANNEL = 2
const RTCIO_CHANNEL_2_GPIO_NUM = 2
const RTCIO_GPIO3_CHANNEL = 3
const RTCIO_CHANNEL_3_GPIO_NUM = 3
const RTCIO_GPIO4_CHANNEL = 4
const RTCIO_CHANNEL_4_GPIO_NUM = 4
const RTCIO_GPIO5_CHANNEL = 5
const RTCIO_CHANNEL_5_GPIO_NUM = 5
const RTCIO_GPIO6_CHANNEL = 6
const RTCIO_CHANNEL_6_GPIO_NUM = 6
const RTCIO_GPIO7_CHANNEL = 7
const RTCIO_CHANNEL_7_GPIO_NUM = 7
