package soc

import _ "unsafe"

const SDIO_SLAVE_SLOT0_IOMUX_PIN_NUM_CMD = 18
const SDIO_SLAVE_SLOT0_IOMUX_PIN_NUM_CLK = 19
const SDIO_SLAVE_SLOT0_IOMUX_PIN_NUM_D0 = 20
const SDIO_SLAVE_SLOT0_IOMUX_PIN_NUM_D1 = 21
const SDIO_SLAVE_SLOT0_IOMUX_PIN_NUM_D2 = 22
const SDIO_SLAVE_SLOT0_IOMUX_PIN_NUM_D3 = 23
const SDIO_SLAVE_SLOT0_FUNC = 0
