package soc

import _ "unsafe"

const MSPI_FUNC_NUM = 0
const MSPI_IOMUX_PIN_NUM_HD = 28
const MSPI_IOMUX_PIN_NUM_WP = 26
const MSPI_IOMUX_PIN_NUM_CS0 = 24
const MSPI_IOMUX_PIN_NUM_CLK = 29
const MSPI_IOMUX_PIN_NUM_MOSI = 30
const MSPI_IOMUX_PIN_NUM_MISO = 25
const SPI2_FUNC_NUM = 2
const SPI2_IOMUX_PIN_NUM_MISO = 2
const SPI2_IOMUX_PIN_NUM_HD = 4
const SPI2_IOMUX_PIN_NUM_WP = 5
const SPI2_IOMUX_PIN_NUM_CLK = 6
const SPI2_IOMUX_PIN_NUM_MOSI = 7
const SPI2_IOMUX_PIN_NUM_CS = 16
