package soc

import _ "unsafe"

const INT_MTX_RETENTION_LINK_LEN = 1
const HP_SYSTEM_RETENTION_LINK_LEN = 1
const TEE_APM_RETENTION_LINK_LEN = 2
const TEE_APM_HIGH_PRI_RETENTION_LINK_LEN = 1
const IOMUX_RETENTION_LINK_LEN = 4
const SPIMEM_RETENTION_LINK_LEN = 8
const SYSTIMER_RETENTION_LINK_LEN = 19
