package esp_rom

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

type SLEEPMODE c.Int

const (
	AWAKE       SLEEPMODE = 0
	LIGHT_SLEEP SLEEPMODE = 1
	DEEP_SLEEP  SLEEPMODE = 2
)

type RESETREASON c.Int

const (
	NO_MEAN                RESETREASON = 0
	POWERON_RESET          RESETREASON = 1
	SW_RESET               RESETREASON = 3
	OWDT_RESET             RESETREASON = 4
	DEEPSLEEP_RESET        RESETREASON = 5
	SDIO_RESET             RESETREASON = 6
	TG0WDT_SYS_RESET       RESETREASON = 7
	TG1WDT_SYS_RESET       RESETREASON = 8
	RTCWDT_SYS_RESET       RESETREASON = 9
	INTRUSION_RESET        RESETREASON = 10
	TGWDT_CPU_RESET        RESETREASON = 11
	SW_CPU_RESET           RESETREASON = 12
	RTCWDT_CPU_RESET       RESETREASON = 13
	EXT_CPU_RESET          RESETREASON = 14
	RTCWDT_BROWN_OUT_RESET RESETREASON = 15
	RTCWDT_RTC_RESET       RESETREASON = 16
)

type WAKEUPREASON c.Int

const (
	NO_SLEEP        WAKEUPREASON = 0
	EXT_EVENT0_TRIG WAKEUPREASON = 1
	EXT_EVENT1_TRIG WAKEUPREASON = 2
	GPIO_TRIG       WAKEUPREASON = 4
	TIMER_EXPIRE    WAKEUPREASON = 8
	SDIO_TRIG       WAKEUPREASON = 16
	MAC_TRIG        WAKEUPREASON = 32
	UART0_TRIG      WAKEUPREASON = 64
	UART1_TRIG      WAKEUPREASON = 128
	TOUCH_TRIG      WAKEUPREASON = 256
	SAR_TRIG        WAKEUPREASON = 512
	BT_TRIG         WAKEUPREASON = 1024
)

type WAKEUPENABLE c.Int

const (
	DISEN_WAKEUP       WAKEUPENABLE = 0
	EXT_EVENT0_TRIG_EN WAKEUPENABLE = 1
	EXT_EVENT1_TRIG_EN WAKEUPENABLE = 2
	GPIO_TRIG_EN       WAKEUPENABLE = 4
	TIMER_EXPIRE_EN    WAKEUPENABLE = 8
	SDIO_TRIG_EN       WAKEUPENABLE = 16
	MAC_TRIG_EN        WAKEUPENABLE = 32
	UART0_TRIG_EN      WAKEUPENABLE = 64
	UART1_TRIG_EN      WAKEUPENABLE = 128
	TOUCH_TRIG_EN      WAKEUPENABLE = 256
	SAR_TRIG_EN        WAKEUPENABLE = 512
	BT_TRIG_EN         WAKEUPENABLE = 1024
)

type RTCINTREASON c.Int

const (
	NO_INT             RTCINTREASON = 0
	WAKEUP_INT         RTCINTREASON = 1
	REJECT_INT         RTCINTREASON = 2
	SDIO_IDLE_INT      RTCINTREASON = 4
	RTC_WDT_INT        RTCINTREASON = 8
	RTC_TIME_VALID_INT RTCINTREASON = 16
)

type RTCINTEN c.Int

const (
	DISEN_INT             RTCINTEN = 0
	WAKEUP_INT_EN         RTCINTEN = 1
	REJECT_INT_EN         RTCINTEN = 2
	SDIO_IDLE_INT_EN      RTCINTEN = 4
	RTC_WDT_INT_EN        RTCINTEN = 8
	RTC_TIME_VALID_INT_EN RTCINTEN = 16
)
