package esp_driver_gpio

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

const X__WORDSIZE = 64
const X__has_safe_buffers = 1
const X__DARWIN_ONLY_64_BIT_INO_T = 1
const X__DARWIN_ONLY_UNIX_CONFORMANCE = 1
const X__DARWIN_ONLY_VERS_1050 = 1
const X__DARWIN_UNIX03 = 1
const X__DARWIN_64_BIT_INO_T = 1
const X__DARWIN_VERS_1050 = 1
const X__DARWIN_NON_CANCELABLE = 0
const X__DARWIN_SUF_EXTSN = "$DARWIN_EXTSN"
const X__STDC_WANT_LIB_EXT1__ = 1
const X__DARWIN_NO_LONG_LONG = 0
const X_DARWIN_FEATURE_64_BIT_INODE = 1
const X_DARWIN_FEATURE_ONLY_64_BIT_INODE = 1
const X_DARWIN_FEATURE_ONLY_VERS_1050 = 1
const X_DARWIN_FEATURE_ONLY_UNIX_CONFORMANCE = 1
const X_DARWIN_FEATURE_UNIX_CONFORMANCE = 3
const X__has_ptrcheck = 0
const X__PTHREAD_SIZE__ = 8176
const X__PTHREAD_ATTR_SIZE__ = 56
const X__PTHREAD_MUTEXATTR_SIZE__ = 8
const X__PTHREAD_MUTEX_SIZE__ = 56
const X__PTHREAD_CONDATTR_SIZE__ = 8
const X__PTHREAD_COND_SIZE__ = 40
const X__PTHREAD_ONCE_SIZE__ = 8
const X__PTHREAD_RWLOCK_SIZE__ = 192
const X__PTHREAD_RWLOCKATTR_SIZE__ = 16
const INT8_MAX = 127
const INT16_MAX = 32767
const INT32_MAX = 2147483647
const UINT8_MAX = 255
const UINT16_MAX = 65535
const X__API_TO_BE_DEPRECATED = 100000
const X__API_TO_BE_DEPRECATED_MACOS = 100000
const X__API_TO_BE_DEPRECATED_IOS = 100000
const X__API_TO_BE_DEPRECATED_MACCATALYST = 100000
const X__API_TO_BE_DEPRECATED_WATCHOS = 100000
const X__API_TO_BE_DEPRECATED_TVOS = 100000
const X__API_TO_BE_DEPRECATED_DRIVERKIT = 100000
const X__API_TO_BE_DEPRECATED_VISIONOS = 100000
const X__MAC_10_0 = 1000
const X__MAC_10_1 = 1010
const X__MAC_10_2 = 1020
const X__MAC_10_3 = 1030
const X__MAC_10_4 = 1040
const X__MAC_10_5 = 1050
const X__MAC_10_6 = 1060
const X__MAC_10_7 = 1070
const X__MAC_10_8 = 1080
const X__MAC_10_9 = 1090
const X__MAC_10_10 = 101000
const X__MAC_10_10_2 = 101002
const X__MAC_10_10_3 = 101003
const X__MAC_10_11 = 101100
const X__MAC_10_11_2 = 101102
const X__MAC_10_11_3 = 101103
const X__MAC_10_11_4 = 101104
const X__MAC_10_12 = 101200
const X__MAC_10_12_1 = 101201
const X__MAC_10_12_2 = 101202
const X__MAC_10_12_4 = 101204
const X__MAC_10_13 = 101300
const X__MAC_10_13_1 = 101301
const X__MAC_10_13_2 = 101302
const X__MAC_10_13_4 = 101304
const X__MAC_10_14 = 101400
const X__MAC_10_14_1 = 101401
const X__MAC_10_14_4 = 101404
const X__MAC_10_14_5 = 101405
const X__MAC_10_14_6 = 101406
const X__MAC_10_15 = 101500
const X__MAC_10_15_1 = 101501
const X__MAC_10_15_4 = 101504
const X__MAC_10_16 = 101600
const X__MAC_11_0 = 110000
const X__MAC_11_1 = 110100
const X__MAC_11_3 = 110300
const X__MAC_11_4 = 110400
const X__MAC_11_5 = 110500
const X__MAC_11_6 = 110600
const X__MAC_12_0 = 120000
const X__MAC_12_1 = 120100
const X__MAC_12_2 = 120200
const X__MAC_12_3 = 120300
const X__MAC_12_4 = 120400
const X__MAC_12_5 = 120500
const X__MAC_12_6 = 120600
const X__MAC_12_7 = 120700
const X__MAC_13_0 = 130000
const X__MAC_13_1 = 130100
const X__MAC_13_2 = 130200
const X__MAC_13_3 = 130300
const X__MAC_13_4 = 130400
const X__MAC_13_5 = 130500
const X__MAC_13_6 = 130600
const X__MAC_14_0 = 140000
const X__MAC_14_1 = 140100
const X__MAC_14_2 = 140200
const X__MAC_14_3 = 140300
const X__MAC_14_4 = 140400
const X__IPHONE_2_0 = 20000
const X__IPHONE_2_1 = 20100
const X__IPHONE_2_2 = 20200
const X__IPHONE_3_0 = 30000
const X__IPHONE_3_1 = 30100
const X__IPHONE_3_2 = 30200
const X__IPHONE_4_0 = 40000
const X__IPHONE_4_1 = 40100
const X__IPHONE_4_2 = 40200
const X__IPHONE_4_3 = 40300
const X__IPHONE_5_0 = 50000
const X__IPHONE_5_1 = 50100
const X__IPHONE_6_0 = 60000
const X__IPHONE_6_1 = 60100
const X__IPHONE_7_0 = 70000
const X__IPHONE_7_1 = 70100
const X__IPHONE_8_0 = 80000
const X__IPHONE_8_1 = 80100
const X__IPHONE_8_2 = 80200
const X__IPHONE_8_3 = 80300
const X__IPHONE_8_4 = 80400
const X__IPHONE_9_0 = 90000
const X__IPHONE_9_1 = 90100
const X__IPHONE_9_2 = 90200
const X__IPHONE_9_3 = 90300
const X__IPHONE_10_0 = 100000
const X__IPHONE_10_1 = 100100
const X__IPHONE_10_2 = 100200
const X__IPHONE_10_3 = 100300
const X__IPHONE_11_0 = 110000
const X__IPHONE_11_1 = 110100
const X__IPHONE_11_2 = 110200
const X__IPHONE_11_3 = 110300
const X__IPHONE_11_4 = 110400
const X__IPHONE_12_0 = 120000
const X__IPHONE_12_1 = 120100
const X__IPHONE_12_2 = 120200
const X__IPHONE_12_3 = 120300
const X__IPHONE_12_4 = 120400
const X__IPHONE_13_0 = 130000
const X__IPHONE_13_1 = 130100
const X__IPHONE_13_2 = 130200
const X__IPHONE_13_3 = 130300
const X__IPHONE_13_4 = 130400
const X__IPHONE_13_5 = 130500
const X__IPHONE_13_6 = 130600
const X__IPHONE_13_7 = 130700
const X__IPHONE_14_0 = 140000
const X__IPHONE_14_1 = 140100
const X__IPHONE_14_2 = 140200
const X__IPHONE_14_3 = 140300
const X__IPHONE_14_5 = 140500
const X__IPHONE_14_4 = 140400
const X__IPHONE_14_6 = 140600
const X__IPHONE_14_7 = 140700
const X__IPHONE_14_8 = 140800
const X__IPHONE_15_0 = 150000
const X__IPHONE_15_1 = 150100
const X__IPHONE_15_2 = 150200
const X__IPHONE_15_3 = 150300
const X__IPHONE_15_4 = 150400
const X__IPHONE_15_5 = 150500
const X__IPHONE_15_6 = 150600
const X__IPHONE_15_7 = 150700
const X__IPHONE_15_8 = 150800
const X__IPHONE_16_0 = 160000
const X__IPHONE_16_1 = 160100
const X__IPHONE_16_2 = 160200
const X__IPHONE_16_3 = 160300
const X__IPHONE_16_4 = 160400
const X__IPHONE_16_5 = 160500
const X__IPHONE_16_6 = 160600
const X__IPHONE_16_7 = 160700
const X__IPHONE_17_0 = 170000
const X__IPHONE_17_1 = 170100
const X__IPHONE_17_2 = 170200
const X__IPHONE_17_3 = 170300
const X__IPHONE_17_4 = 170400
const X__WATCHOS_1_0 = 10000
const X__WATCHOS_2_0 = 20000
const X__WATCHOS_2_1 = 20100
const X__WATCHOS_2_2 = 20200
const X__WATCHOS_3_0 = 30000
const X__WATCHOS_3_1 = 30100
const X__WATCHOS_3_1_1 = 30101
const X__WATCHOS_3_2 = 30200
const X__WATCHOS_4_0 = 40000
const X__WATCHOS_4_1 = 40100
const X__WATCHOS_4_2 = 40200
const X__WATCHOS_4_3 = 40300
const X__WATCHOS_5_0 = 50000
const X__WATCHOS_5_1 = 50100
const X__WATCHOS_5_2 = 50200
const X__WATCHOS_5_3 = 50300
const X__WATCHOS_6_0 = 60000
const X__WATCHOS_6_1 = 60100
const X__WATCHOS_6_2 = 60200
const X__WATCHOS_7_0 = 70000
const X__WATCHOS_7_1 = 70100
const X__WATCHOS_7_2 = 70200
const X__WATCHOS_7_3 = 70300
const X__WATCHOS_7_4 = 70400
const X__WATCHOS_7_5 = 70500
const X__WATCHOS_7_6 = 70600
const X__WATCHOS_8_0 = 80000
const X__WATCHOS_8_1 = 80100
const X__WATCHOS_8_3 = 80300
const X__WATCHOS_8_4 = 80400
const X__WATCHOS_8_5 = 80500
const X__WATCHOS_8_6 = 80600
const X__WATCHOS_8_7 = 80700
const X__WATCHOS_8_8 = 80800
const X__WATCHOS_9_0 = 90000
const X__WATCHOS_9_1 = 90100
const X__WATCHOS_9_2 = 90200
const X__WATCHOS_9_3 = 90300
const X__WATCHOS_9_4 = 90400
const X__WATCHOS_9_5 = 90500
const X__WATCHOS_9_6 = 90600
const X__WATCHOS_10_0 = 100000
const X__WATCHOS_10_1 = 100100
const X__WATCHOS_10_2 = 100200
const X__WATCHOS_10_3 = 100300
const X__WATCHOS_10_4 = 100400
const X__TVOS_9_0 = 90000
const X__TVOS_9_1 = 90100
const X__TVOS_9_2 = 90200
const X__TVOS_10_0 = 100000
const X__TVOS_10_0_1 = 100001
const X__TVOS_10_1 = 100100
const X__TVOS_10_2 = 100200
const X__TVOS_11_0 = 110000
const X__TVOS_11_1 = 110100
const X__TVOS_11_2 = 110200
const X__TVOS_11_3 = 110300
const X__TVOS_11_4 = 110400
const X__TVOS_12_0 = 120000
const X__TVOS_12_1 = 120100
const X__TVOS_12_2 = 120200
const X__TVOS_12_3 = 120300
const X__TVOS_12_4 = 120400
const X__TVOS_13_0 = 130000
const X__TVOS_13_2 = 130200
const X__TVOS_13_3 = 130300
const X__TVOS_13_4 = 130400
const X__TVOS_14_0 = 140000
const X__TVOS_14_1 = 140100
const X__TVOS_14_2 = 140200
const X__TVOS_14_3 = 140300
const X__TVOS_14_5 = 140500
const X__TVOS_14_6 = 140600
const X__TVOS_14_7 = 140700
const X__TVOS_15_0 = 150000
const X__TVOS_15_1 = 150100
const X__TVOS_15_2 = 150200
const X__TVOS_15_3 = 150300
const X__TVOS_15_4 = 150400
const X__TVOS_15_5 = 150500
const X__TVOS_15_6 = 150600
const X__TVOS_16_0 = 160000
const X__TVOS_16_1 = 160100
const X__TVOS_16_2 = 160200
const X__TVOS_16_3 = 160300
const X__TVOS_16_4 = 160400
const X__TVOS_16_5 = 160500
const X__TVOS_16_6 = 160600
const X__TVOS_17_0 = 170000
const X__TVOS_17_1 = 170100
const X__TVOS_17_2 = 170200
const X__TVOS_17_3 = 170300
const X__TVOS_17_4 = 170400
const X__BRIDGEOS_2_0 = 20000
const X__BRIDGEOS_3_0 = 30000
const X__BRIDGEOS_3_1 = 30100
const X__BRIDGEOS_3_4 = 30400
const X__BRIDGEOS_4_0 = 40000
const X__BRIDGEOS_4_1 = 40100
const X__BRIDGEOS_5_0 = 50000
const X__BRIDGEOS_5_1 = 50100
const X__BRIDGEOS_5_3 = 50300
const X__BRIDGEOS_6_0 = 60000
const X__BRIDGEOS_6_2 = 60200
const X__BRIDGEOS_6_4 = 60400
const X__BRIDGEOS_6_5 = 60500
const X__BRIDGEOS_6_6 = 60600
const X__BRIDGEOS_7_0 = 70000
const X__BRIDGEOS_7_1 = 70100
const X__BRIDGEOS_7_2 = 70200
const X__BRIDGEOS_7_3 = 70300
const X__BRIDGEOS_7_4 = 70400
const X__BRIDGEOS_7_6 = 70600
const X__BRIDGEOS_8_0 = 80000
const X__BRIDGEOS_8_1 = 80100
const X__BRIDGEOS_8_2 = 80200
const X__BRIDGEOS_8_3 = 80300
const X__BRIDGEOS_8_4 = 80400
const X__DRIVERKIT_19_0 = 190000
const X__DRIVERKIT_20_0 = 200000
const X__DRIVERKIT_21_0 = 210000
const X__DRIVERKIT_22_0 = 220000
const X__DRIVERKIT_22_4 = 220400
const X__DRIVERKIT_22_5 = 220500
const X__DRIVERKIT_22_6 = 220600
const X__DRIVERKIT_23_0 = 230000
const X__DRIVERKIT_23_1 = 230100
const X__DRIVERKIT_23_2 = 230200
const X__DRIVERKIT_23_3 = 230300
const X__DRIVERKIT_23_4 = 230400
const X__VISIONOS_1_0 = 10000
const X__VISIONOS_1_1 = 10100
const X__ENABLE_LEGACY_MAC_AVAILABILITY = 1
const X_FORTIFY_SOURCE = 2
const RENAME_SECLUDE = 0x00000001
const RENAME_SWAP = 0x00000002
const RENAME_EXCL = 0x00000004
const RENAME_RESERVED1 = 0x00000008
const RENAME_NOFOLLOW_ANY = 0x00000010
const SEEK_SET = 0
const SEEK_CUR = 1
const SEEK_END = 2
const SEEK_HOLE = 3
const SEEK_DATA = 4
const X__SLBF = 0x0001
const X__SNBF = 0x0002
const X__SRD = 0x0004
const X__SWR = 0x0008
const X__SRW = 0x0010
const X__SEOF = 0x0020
const X__SERR = 0x0040
const X__SMBF = 0x0080
const X__SAPP = 0x0100
const X__SSTR = 0x0200
const X__SOPT = 0x0400
const X__SNPT = 0x0800
const X__SOFF = 0x1000
const X__SMOD = 0x2000
const X__SALC = 0x4000
const X__SIGN = 0x8000
const X_IOFBF = 0
const X_IOLBF = 1
const X_IONBF = 2
const BUFSIZ = 1024
const FOPEN_MAX = 20
const FILENAME_MAX = 1024
const P_tmpdir = "/var/tmp/"
const L_tmpnam = 1024
const TMP_MAX = 308915776
const L_ctermid = 1024
const X_USE_FORTIFY_LEVEL = 2
const CONFIG_SOC_MPU_MIN_REGION_SIZE = 0x20000000
const CONFIG_SOC_MPU_REGIONS_MAX_NUM = 8
const CONFIG_SOC_ADC_SUPPORTED = 1
const CONFIG_SOC_UART_SUPPORTED = 1
const CONFIG_SOC_PCNT_SUPPORTED = 1
const CONFIG_SOC_PHY_SUPPORTED = 1
const CONFIG_SOC_WIFI_SUPPORTED = 1
const CONFIG_SOC_TWAI_SUPPORTED = 1
const CONFIG_SOC_GDMA_SUPPORTED = 1
const CONFIG_SOC_AHB_GDMA_SUPPORTED = 1
const CONFIG_SOC_GPTIMER_SUPPORTED = 1
const CONFIG_SOC_LCDCAM_SUPPORTED = 1
const CONFIG_SOC_LCDCAM_I80_LCD_SUPPORTED = 1
const CONFIG_SOC_LCDCAM_RGB_LCD_SUPPORTED = 1
const CONFIG_SOC_MCPWM_SUPPORTED = 1
const CONFIG_SOC_DEDICATED_GPIO_SUPPORTED = 1
const CONFIG_SOC_CACHE_SUPPORT_WRAP = 1
const CONFIG_SOC_ULP_SUPPORTED = 1
const CONFIG_SOC_ULP_FSM_SUPPORTED = 1
const CONFIG_SOC_RISCV_COPROC_SUPPORTED = 1
const CONFIG_SOC_BT_SUPPORTED = 1
const CONFIG_SOC_USB_OTG_SUPPORTED = 1
const CONFIG_SOC_USB_SERIAL_JTAG_SUPPORTED = 1
const CONFIG_SOC_CCOMP_TIMER_SUPPORTED = 1
const CONFIG_SOC_ASYNC_MEMCPY_SUPPORTED = 1
const CONFIG_SOC_SUPPORTS_SECURE_DL_MODE = 1
const CONFIG_SOC_EFUSE_KEY_PURPOSE_FIELD = 1
const CONFIG_SOC_EFUSE_SUPPORTED = 1
const CONFIG_SOC_SDMMC_HOST_SUPPORTED = 1
const CONFIG_SOC_RTC_FAST_MEM_SUPPORTED = 1
const CONFIG_SOC_RTC_SLOW_MEM_SUPPORTED = 1
const CONFIG_SOC_RTC_MEM_SUPPORTED = 1
const CONFIG_SOC_PSRAM_DMA_CAPABLE = 1
const CONFIG_SOC_XT_WDT_SUPPORTED = 1
const CONFIG_SOC_I2S_SUPPORTED = 1
const CONFIG_SOC_RMT_SUPPORTED = 1
const CONFIG_SOC_SDM_SUPPORTED = 1
const CONFIG_SOC_GPSPI_SUPPORTED = 1
const CONFIG_SOC_LEDC_SUPPORTED = 1
const CONFIG_SOC_I2C_SUPPORTED = 1
const CONFIG_SOC_SYSTIMER_SUPPORTED = 1
const CONFIG_SOC_SUPPORT_COEXISTENCE = 1
const CONFIG_SOC_TEMP_SENSOR_SUPPORTED = 1
const CONFIG_SOC_AES_SUPPORTED = 1
const CONFIG_SOC_MPI_SUPPORTED = 1
const CONFIG_SOC_SHA_SUPPORTED = 1
const CONFIG_SOC_HMAC_SUPPORTED = 1
const CONFIG_SOC_DIG_SIGN_SUPPORTED = 1
const CONFIG_SOC_FLASH_ENC_SUPPORTED = 1
const CONFIG_SOC_SECURE_BOOT_SUPPORTED = 1
const CONFIG_SOC_MEMPROT_SUPPORTED = 1
const CONFIG_SOC_TOUCH_SENSOR_SUPPORTED = 1
const CONFIG_SOC_BOD_SUPPORTED = 1
const CONFIG_SOC_CLK_TREE_SUPPORTED = 1
const CONFIG_SOC_MPU_SUPPORTED = 1
const CONFIG_SOC_WDT_SUPPORTED = 1
const CONFIG_SOC_SPI_FLASH_SUPPORTED = 1
const CONFIG_SOC_RNG_SUPPORTED = 1
const CONFIG_SOC_LIGHT_SLEEP_SUPPORTED = 1
const CONFIG_SOC_DEEP_SLEEP_SUPPORTED = 1
const CONFIG_SOC_LP_PERIPH_SHARE_INTERRUPT = 1
const CONFIG_SOC_PM_SUPPORTED = 1
const CONFIG_SOC_SIMD_INSTRUCTION_SUPPORTED = 1
const CONFIG_SOC_XTAL_SUPPORT_40M = 1
const CONFIG_SOC_APPCPU_HAS_CLOCK_GATING_BUG = 1
const CONFIG_SOC_ADC_RTC_CTRL_SUPPORTED = 1
const CONFIG_SOC_ADC_DIG_CTRL_SUPPORTED = 1
const CONFIG_SOC_ADC_ARBITER_SUPPORTED = 1
const CONFIG_SOC_ADC_DIG_IIR_FILTER_SUPPORTED = 1
const CONFIG_SOC_ADC_MONITOR_SUPPORTED = 1
const CONFIG_SOC_ADC_DMA_SUPPORTED = 1
const CONFIG_SOC_ADC_PERIPH_NUM = 2
const CONFIG_SOC_ADC_MAX_CHANNEL_NUM = 10
const CONFIG_SOC_ADC_ATTEN_NUM = 4
const CONFIG_SOC_ADC_DIGI_CONTROLLER_NUM = 2
const CONFIG_SOC_ADC_PATT_LEN_MAX = 24
const CONFIG_SOC_ADC_DIGI_MIN_BITWIDTH = 12
const CONFIG_SOC_ADC_DIGI_MAX_BITWIDTH = 12
const CONFIG_SOC_ADC_DIGI_RESULT_BYTES = 4
const CONFIG_SOC_ADC_DIGI_DATA_BYTES_PER_CONV = 4
const CONFIG_SOC_ADC_DIGI_IIR_FILTER_NUM = 2
const CONFIG_SOC_ADC_DIGI_MONITOR_NUM = 2
const CONFIG_SOC_ADC_SAMPLE_FREQ_THRES_HIGH = 83333
const CONFIG_SOC_ADC_SAMPLE_FREQ_THRES_LOW = 611
const CONFIG_SOC_ADC_RTC_MIN_BITWIDTH = 12
const CONFIG_SOC_ADC_RTC_MAX_BITWIDTH = 12
const CONFIG_SOC_ADC_CALIBRATION_V1_SUPPORTED = 1
const CONFIG_SOC_ADC_SELF_HW_CALI_SUPPORTED = 1
const CONFIG_SOC_ADC_SHARED_POWER = 1
const CONFIG_SOC_APB_BACKUP_DMA = 1
const CONFIG_SOC_BROWNOUT_RESET_SUPPORTED = 1
const CONFIG_SOC_CACHE_WRITEBACK_SUPPORTED = 1
const CONFIG_SOC_CACHE_FREEZE_SUPPORTED = 1
const CONFIG_SOC_CPU_CORES_NUM = 2
const CONFIG_SOC_CPU_INTR_NUM = 32
const CONFIG_SOC_CPU_HAS_FPU = 1
const CONFIG_SOC_HP_CPU_HAS_MULTIPLE_CORES = 1
const CONFIG_SOC_CPU_BREAKPOINTS_NUM = 2
const CONFIG_SOC_CPU_WATCHPOINTS_NUM = 2
const CONFIG_SOC_CPU_WATCHPOINT_MAX_REGION_SIZE = 64
const CONFIG_SOC_SIMD_PREFERRED_DATA_ALIGNMENT = 16
const CONFIG_SOC_DS_SIGNATURE_MAX_BIT_LEN = 4096
const CONFIG_SOC_DS_KEY_PARAM_MD_IV_LENGTH = 16
const CONFIG_SOC_DS_KEY_CHECK_MAX_WAIT_US = 1100
const CONFIG_SOC_AHB_GDMA_VERSION = 1
const CONFIG_SOC_GDMA_NUM_GROUPS_MAX = 1
const CONFIG_SOC_GDMA_PAIRS_PER_GROUP = 5
const CONFIG_SOC_GDMA_PAIRS_PER_GROUP_MAX = 5
const CONFIG_SOC_AHB_GDMA_SUPPORT_PSRAM = 1
const CONFIG_SOC_GPIO_PORT = 1
const CONFIG_SOC_GPIO_PIN_COUNT = 49
const CONFIG_SOC_GPIO_SUPPORT_PIN_GLITCH_FILTER = 1
const CONFIG_SOC_GPIO_FILTER_CLK_SUPPORT_APB = 1
const CONFIG_SOC_GPIO_SUPPORT_RTC_INDEPENDENT = 1
const CONFIG_SOC_GPIO_SUPPORT_FORCE_HOLD = 1
const CONFIG_SOC_GPIO_VALID_GPIO_MASK = 0x1FFFFFFFFFFFF
const CONFIG_SOC_GPIO_IN_RANGE_MAX = 48
const CONFIG_SOC_GPIO_OUT_RANGE_MAX = 48
const CONFIG_SOC_GPIO_VALID_DIGITAL_IO_PAD_MASK = 0x0001FFFFFC000000
const CONFIG_SOC_GPIO_CLOCKOUT_BY_IO_MUX = 1
const CONFIG_SOC_GPIO_CLOCKOUT_CHANNEL_NUM = 3
const CONFIG_SOC_GPIO_SUPPORT_HOLD_IO_IN_DSLP = 1
const CONFIG_SOC_DEDIC_GPIO_OUT_CHANNELS_NUM = 8
const CONFIG_SOC_DEDIC_GPIO_IN_CHANNELS_NUM = 8
const CONFIG_SOC_DEDIC_GPIO_OUT_AUTO_ENABLE = 1
const CONFIG_SOC_I2C_NUM = 2
const CONFIG_SOC_HP_I2C_NUM = 2
const CONFIG_SOC_I2C_FIFO_LEN = 32
const CONFIG_SOC_I2C_CMD_REG_NUM = 8
const CONFIG_SOC_I2C_SUPPORT_SLAVE = 1
const CONFIG_SOC_I2C_SUPPORT_HW_CLR_BUS = 1
const CONFIG_SOC_I2C_SUPPORT_XTAL = 1
const CONFIG_SOC_I2C_SUPPORT_RTC = 1
const CONFIG_SOC_I2C_SUPPORT_10BIT_ADDR = 1
const CONFIG_SOC_I2C_SLAVE_SUPPORT_BROADCAST = 1
const CONFIG_SOC_I2C_SLAVE_SUPPORT_I2CRAM_ACCESS = 1
const CONFIG_SOC_I2C_SLAVE_CAN_GET_STRETCH_CAUSE = 1
const CONFIG_SOC_I2S_NUM = 2
const CONFIG_SOC_I2S_HW_VERSION_2 = 1
const CONFIG_SOC_I2S_SUPPORTS_XTAL = 1
const CONFIG_SOC_I2S_SUPPORTS_PLL_F160M = 1
const CONFIG_SOC_I2S_SUPPORTS_PCM = 1
const CONFIG_SOC_I2S_SUPPORTS_PDM = 1
const CONFIG_SOC_I2S_SUPPORTS_PDM_TX = 1
const CONFIG_SOC_I2S_PDM_MAX_TX_LINES = 2
const CONFIG_SOC_I2S_SUPPORTS_PDM_RX = 1
const CONFIG_SOC_I2S_PDM_MAX_RX_LINES = 4
const CONFIG_SOC_I2S_SUPPORTS_TDM = 1
const CONFIG_SOC_LEDC_SUPPORT_APB_CLOCK = 1
const CONFIG_SOC_LEDC_SUPPORT_XTAL_CLOCK = 1
const CONFIG_SOC_LEDC_TIMER_NUM = 4
const CONFIG_SOC_LEDC_CHANNEL_NUM = 8
const CONFIG_SOC_LEDC_TIMER_BIT_WIDTH = 14
const CONFIG_SOC_LEDC_SUPPORT_FADE_STOP = 1
const CONFIG_SOC_MCPWM_GROUPS = 2
const CONFIG_SOC_MCPWM_TIMERS_PER_GROUP = 3
const CONFIG_SOC_MCPWM_OPERATORS_PER_GROUP = 3
const CONFIG_SOC_MCPWM_COMPARATORS_PER_OPERATOR = 2
const CONFIG_SOC_MCPWM_GENERATORS_PER_OPERATOR = 2
const CONFIG_SOC_MCPWM_TRIGGERS_PER_OPERATOR = 2
const CONFIG_SOC_MCPWM_GPIO_FAULTS_PER_GROUP = 3
const CONFIG_SOC_MCPWM_CAPTURE_TIMERS_PER_GROUP = 1
const CONFIG_SOC_MCPWM_CAPTURE_CHANNELS_PER_TIMER = 3
const CONFIG_SOC_MCPWM_GPIO_SYNCHROS_PER_GROUP = 3
const CONFIG_SOC_MCPWM_SWSYNC_CAN_PROPAGATE = 1
const CONFIG_SOC_MMU_LINEAR_ADDRESS_REGION_NUM = 1
const CONFIG_SOC_MMU_PERIPH_NUM = 1
const CONFIG_SOC_PCNT_GROUPS = 1
const CONFIG_SOC_PCNT_UNITS_PER_GROUP = 4
const CONFIG_SOC_PCNT_CHANNELS_PER_UNIT = 2
const CONFIG_SOC_PCNT_THRES_POINT_PER_UNIT = 2
const CONFIG_SOC_RMT_GROUPS = 1
const CONFIG_SOC_RMT_TX_CANDIDATES_PER_GROUP = 4
const CONFIG_SOC_RMT_RX_CANDIDATES_PER_GROUP = 4
const CONFIG_SOC_RMT_CHANNELS_PER_GROUP = 8
const CONFIG_SOC_RMT_MEM_WORDS_PER_CHANNEL = 48
const CONFIG_SOC_RMT_SUPPORT_RX_PINGPONG = 1
const CONFIG_SOC_RMT_SUPPORT_RX_DEMODULATION = 1
const CONFIG_SOC_RMT_SUPPORT_TX_ASYNC_STOP = 1
const CONFIG_SOC_RMT_SUPPORT_TX_LOOP_COUNT = 1
const CONFIG_SOC_RMT_SUPPORT_TX_LOOP_AUTO_STOP = 1
const CONFIG_SOC_RMT_SUPPORT_TX_SYNCHRO = 1
const CONFIG_SOC_RMT_SUPPORT_TX_CARRIER_DATA_ONLY = 1
const CONFIG_SOC_RMT_SUPPORT_XTAL = 1
const CONFIG_SOC_RMT_SUPPORT_RC_FAST = 1
const CONFIG_SOC_RMT_SUPPORT_APB = 1
const CONFIG_SOC_RMT_SUPPORT_DMA = 1
const CONFIG_SOC_LCD_I80_SUPPORTED = 1
const CONFIG_SOC_LCD_RGB_SUPPORTED = 1
const CONFIG_SOC_LCD_I80_BUSES = 1
const CONFIG_SOC_LCD_RGB_PANELS = 1
const CONFIG_SOC_LCD_I80_BUS_WIDTH = 16
const CONFIG_SOC_LCD_RGB_DATA_WIDTH = 16
const CONFIG_SOC_LCD_SUPPORT_RGB_YUV_CONV = 1
const CONFIG_SOC_LCDCAM_I80_NUM_BUSES = 1
const CONFIG_SOC_LCDCAM_I80_BUS_WIDTH = 16
const CONFIG_SOC_LCDCAM_RGB_NUM_PANELS = 1
const CONFIG_SOC_LCDCAM_RGB_DATA_WIDTH = 16
const CONFIG_SOC_RTC_CNTL_CPU_PD_DMA_BUS_WIDTH = 128
const CONFIG_SOC_RTC_CNTL_CPU_PD_REG_FILE_NUM = 549
const CONFIG_SOC_RTC_CNTL_TAGMEM_PD_DMA_BUS_WIDTH = 128
const CONFIG_SOC_RTCIO_PIN_COUNT = 22
const CONFIG_SOC_RTCIO_INPUT_OUTPUT_SUPPORTED = 1
const CONFIG_SOC_RTCIO_HOLD_SUPPORTED = 1
const CONFIG_SOC_RTCIO_WAKE_SUPPORTED = 1
const CONFIG_SOC_LP_IO_CLOCK_IS_INDEPENDENT = 1
const CONFIG_SOC_SDM_GROUPS = 1
const CONFIG_SOC_SDM_CHANNELS_PER_GROUP = 8
const CONFIG_SOC_SDM_CLK_SUPPORT_APB = 1
const CONFIG_SOC_SPI_PERIPH_NUM = 3
const CONFIG_SOC_SPI_MAX_CS_NUM = 6
const CONFIG_SOC_SPI_MAXIMUM_BUFFER_SIZE = 64
const CONFIG_SOC_SPI_SUPPORT_DDRCLK = 1
const CONFIG_SOC_SPI_SLAVE_SUPPORT_SEG_TRANS = 1
const CONFIG_SOC_SPI_SUPPORT_CD_SIG = 1
const CONFIG_SOC_SPI_SUPPORT_CONTINUOUS_TRANS = 1
const CONFIG_SOC_SPI_SUPPORT_SLAVE_HD_VER2 = 1
const CONFIG_SOC_SPI_SUPPORT_CLK_APB = 1
const CONFIG_SOC_SPI_SUPPORT_CLK_XTAL = 1
const CONFIG_SOC_SPI_PERIPH_SUPPORT_CONTROL_DUMMY_OUT = 1
const CONFIG_SOC_MEMSPI_IS_INDEPENDENT = 1
const CONFIG_SOC_SPI_MAX_PRE_DIVIDER = 16
const CONFIG_SOC_SPI_SUPPORT_OCT = 1
const CONFIG_SOC_SPI_SCT_SUPPORTED = 1
const CONFIG_SOC_SPI_SCT_REG_NUM = 14
const CONFIG_SOC_SPI_SCT_BUFFER_NUM_MAX = 1
const CONFIG_SOC_SPI_SCT_CONF_BITLEN_MAX = 0x3FFFA
const CONFIG_SOC_MEMSPI_SRC_FREQ_120M = 1
const CONFIG_SOC_MEMSPI_SRC_FREQ_80M_SUPPORTED = 1
const CONFIG_SOC_MEMSPI_SRC_FREQ_40M_SUPPORTED = 1
const CONFIG_SOC_MEMSPI_SRC_FREQ_20M_SUPPORTED = 1
const CONFIG_SOC_SPIRAM_SUPPORTED = 1
const CONFIG_SOC_SPIRAM_XIP_SUPPORTED = 1
const CONFIG_SOC_SYSTIMER_COUNTER_NUM = 2
const CONFIG_SOC_SYSTIMER_ALARM_NUM = 3
const CONFIG_SOC_SYSTIMER_BIT_WIDTH_LO = 32
const CONFIG_SOC_SYSTIMER_BIT_WIDTH_HI = 20
const CONFIG_SOC_SYSTIMER_FIXED_DIVIDER = 1
const CONFIG_SOC_SYSTIMER_INT_LEVEL = 1
const CONFIG_SOC_SYSTIMER_ALARM_MISS_COMPENSATE = 1
const CONFIG_SOC_TIMER_GROUPS = 2
const CONFIG_SOC_TIMER_GROUP_TIMERS_PER_GROUP = 2
const CONFIG_SOC_TIMER_GROUP_COUNTER_BIT_WIDTH = 54
const CONFIG_SOC_TIMER_GROUP_SUPPORT_XTAL = 1
const CONFIG_SOC_TIMER_GROUP_SUPPORT_APB = 1
const CONFIG_SOC_TIMER_GROUP_TOTAL_TIMERS = 4
const CONFIG_SOC_LP_TIMER_BIT_WIDTH_LO = 32
const CONFIG_SOC_LP_TIMER_BIT_WIDTH_HI = 16
const CONFIG_SOC_TOUCH_SENSOR_VERSION = 2
const CONFIG_SOC_TOUCH_SENSOR_NUM = 15
const CONFIG_SOC_TOUCH_SUPPORT_SLEEP_WAKEUP = 1
const CONFIG_SOC_TOUCH_SUPPORT_WATERPROOF = 1
const CONFIG_SOC_TOUCH_SUPPORT_PROX_SENSING = 1
const CONFIG_SOC_TOUCH_PROXIMITY_CHANNEL_NUM = 3
const CONFIG_SOC_TOUCH_PROXIMITY_MEAS_DONE_SUPPORTED = 1
const CONFIG_SOC_TOUCH_SAMPLE_CFG_NUM = 1
const CONFIG_SOC_TWAI_CONTROLLER_NUM = 1
const CONFIG_SOC_TWAI_CLK_SUPPORT_APB = 1
const CONFIG_SOC_TWAI_BRP_MIN = 2
const CONFIG_SOC_TWAI_BRP_MAX = 16384
const CONFIG_SOC_TWAI_SUPPORTS_RX_STATUS = 1
const CONFIG_SOC_UART_NUM = 3
const CONFIG_SOC_UART_HP_NUM = 3
const CONFIG_SOC_UART_FIFO_LEN = 128
const CONFIG_SOC_UART_BITRATE_MAX = 5000000
const CONFIG_SOC_UART_SUPPORT_FSM_TX_WAIT_SEND = 1
const CONFIG_SOC_UART_SUPPORT_WAKEUP_INT = 1
const CONFIG_SOC_UART_SUPPORT_APB_CLK = 1
const CONFIG_SOC_UART_SUPPORT_RTC_CLK = 1
const CONFIG_SOC_UART_SUPPORT_XTAL_CLK = 1
const CONFIG_SOC_USB_OTG_PERIPH_NUM = 1
const CONFIG_SOC_SHA_DMA_MAX_BUFFER_SIZE = 3968
const CONFIG_SOC_SHA_SUPPORT_DMA = 1
const CONFIG_SOC_SHA_SUPPORT_RESUME = 1
const CONFIG_SOC_SHA_GDMA = 1
const CONFIG_SOC_SHA_SUPPORT_SHA1 = 1
const CONFIG_SOC_SHA_SUPPORT_SHA224 = 1
const CONFIG_SOC_SHA_SUPPORT_SHA256 = 1
const CONFIG_SOC_SHA_SUPPORT_SHA384 = 1
const CONFIG_SOC_SHA_SUPPORT_SHA512 = 1
const CONFIG_SOC_SHA_SUPPORT_SHA512_224 = 1
const CONFIG_SOC_SHA_SUPPORT_SHA512_256 = 1
const CONFIG_SOC_SHA_SUPPORT_SHA512_T = 1
const CONFIG_SOC_MPI_MEM_BLOCKS_NUM = 4
const CONFIG_SOC_MPI_OPERATIONS_NUM = 3
const CONFIG_SOC_RSA_MAX_BIT_LEN = 4096
const CONFIG_SOC_AES_SUPPORT_DMA = 1
const CONFIG_SOC_AES_GDMA = 1
const CONFIG_SOC_AES_SUPPORT_AES_128 = 1
const CONFIG_SOC_AES_SUPPORT_AES_256 = 1
const CONFIG_SOC_PM_SUPPORT_EXT0_WAKEUP = 1
const CONFIG_SOC_PM_SUPPORT_EXT1_WAKEUP = 1
const CONFIG_SOC_PM_SUPPORT_EXT_WAKEUP = 1
const CONFIG_SOC_PM_SUPPORT_WIFI_WAKEUP = 1
const CONFIG_SOC_PM_SUPPORT_BT_WAKEUP = 1
const CONFIG_SOC_PM_SUPPORT_TOUCH_SENSOR_WAKEUP = 1
const CONFIG_SOC_PM_SUPPORT_CPU_PD = 1
const CONFIG_SOC_PM_SUPPORT_TAGMEM_PD = 1
const CONFIG_SOC_PM_SUPPORT_RTC_PERIPH_PD = 1
const CONFIG_SOC_PM_SUPPORT_RC_FAST_PD = 1
const CONFIG_SOC_PM_SUPPORT_VDDSDIO_PD = 1
const CONFIG_SOC_PM_SUPPORT_MAC_BB_PD = 1
const CONFIG_SOC_PM_SUPPORT_MODEM_PD = 1
const CONFIG_SOC_CONFIGURABLE_VDDSDIO_SUPPORTED = 1
const CONFIG_SOC_PM_SUPPORT_DEEPSLEEP_CHECK_STUB_ONLY = 1
const CONFIG_SOC_PM_CPU_RETENTION_BY_RTCCNTL = 1
const CONFIG_SOC_PM_MODEM_RETENTION_BY_BACKUPDMA = 1
const CONFIG_SOC_PM_MODEM_PD_BY_SW = 1
const CONFIG_SOC_CLK_RC_FAST_D256_SUPPORTED = 1
const CONFIG_SOC_RTC_SLOW_CLK_SUPPORT_RC_FAST_D256 = 1
const CONFIG_SOC_CLK_RC_FAST_SUPPORT_CALIBRATION = 1
const CONFIG_SOC_CLK_XTAL32K_SUPPORTED = 1
const CONFIG_SOC_EFUSE_DIS_DOWNLOAD_ICACHE = 1
const CONFIG_SOC_EFUSE_DIS_DOWNLOAD_DCACHE = 1
const CONFIG_SOC_EFUSE_HARD_DIS_JTAG = 1
const CONFIG_SOC_EFUSE_DIS_USB_JTAG = 1
const CONFIG_SOC_EFUSE_SOFT_DIS_JTAG = 1
const CONFIG_SOC_EFUSE_DIS_DIRECT_BOOT = 1
const CONFIG_SOC_EFUSE_DIS_ICACHE = 1
const CONFIG_SOC_EFUSE_BLOCK9_KEY_PURPOSE_QUIRK = 1
const CONFIG_SOC_SECURE_BOOT_V2_RSA = 1
const CONFIG_SOC_EFUSE_SECURE_BOOT_KEY_DIGESTS = 3
const CONFIG_SOC_EFUSE_REVOKE_BOOT_KEY_DIGESTS = 1
const CONFIG_SOC_SUPPORT_SECURE_BOOT_REVOKE_KEY = 1
const CONFIG_SOC_FLASH_ENCRYPTED_XTS_AES_BLOCK_MAX = 64
const CONFIG_SOC_FLASH_ENCRYPTION_XTS_AES = 1
const CONFIG_SOC_FLASH_ENCRYPTION_XTS_AES_OPTIONS = 1
const CONFIG_SOC_FLASH_ENCRYPTION_XTS_AES_128 = 1
const CONFIG_SOC_FLASH_ENCRYPTION_XTS_AES_256 = 1
const CONFIG_SOC_MEMPROT_CPU_PREFETCH_PAD_SIZE = 16
const CONFIG_SOC_MEMPROT_MEM_ALIGN_SIZE = 256
const CONFIG_SOC_PHY_DIG_REGS_MEM_SIZE = 21
const CONFIG_SOC_MAC_BB_PD_MEM_SIZE = 192
const CONFIG_SOC_WIFI_LIGHT_SLEEP_CLK_WIDTH = 12
const CONFIG_SOC_SPI_MEM_SUPPORT_AUTO_WAIT_IDLE = 1
const CONFIG_SOC_SPI_MEM_SUPPORT_AUTO_SUSPEND = 1
const CONFIG_SOC_SPI_MEM_SUPPORT_AUTO_RESUME = 1
const CONFIG_SOC_SPI_MEM_SUPPORT_SW_SUSPEND = 1
const CONFIG_SOC_SPI_MEM_SUPPORT_OPI_MODE = 1
const CONFIG_SOC_SPI_MEM_SUPPORT_TIMING_TUNING = 1
const CONFIG_SOC_SPI_MEM_SUPPORT_CONFIG_GPIO_BY_EFUSE = 1
const CONFIG_SOC_SPI_MEM_SUPPORT_WRAP = 1
const CONFIG_SOC_MEMSPI_TIMING_TUNING_BY_MSPI_DELAY = 1
const CONFIG_SOC_MEMSPI_CORE_CLK_SHARED_WITH_PSRAM = 1
const CONFIG_SOC_SPI_MEM_SUPPORT_CACHE_32BIT_ADDR_MAP = 1
const CONFIG_SOC_COEX_HW_PTI = 1
const CONFIG_SOC_EXTERNAL_COEX_LEADER_TX_LINE = 1
const CONFIG_SOC_SDMMC_USE_GPIO_MATRIX = 1
const CONFIG_SOC_SDMMC_NUM_SLOTS = 2
const CONFIG_SOC_SDMMC_SUPPORT_XTAL_CLOCK = 1
const CONFIG_SOC_SDMMC_DELAY_PHASE_NUM = 4
const CONFIG_SOC_TEMPERATURE_SENSOR_SUPPORT_FAST_RC = 1
const CONFIG_SOC_WIFI_HW_TSF = 1
const CONFIG_SOC_WIFI_FTM_SUPPORT = 1
const CONFIG_SOC_WIFI_GCMP_SUPPORT = 1
const CONFIG_SOC_WIFI_WAPI_SUPPORT = 1
const CONFIG_SOC_WIFI_CSI_SUPPORT = 1
const CONFIG_SOC_WIFI_MESH_SUPPORT = 1
const CONFIG_SOC_WIFI_SUPPORT_VARIABLE_BEACON_WINDOW = 1
const CONFIG_SOC_WIFI_PHY_NEEDS_USB_WORKAROUND = 1
const CONFIG_SOC_BLE_SUPPORTED = 1
const CONFIG_SOC_BLE_MESH_SUPPORTED = 1
const CONFIG_SOC_BLE_50_SUPPORTED = 1
const CONFIG_SOC_BLE_DEVICE_PRIVACY_SUPPORTED = 1
const CONFIG_SOC_BLUFI_SUPPORTED = 1
const CONFIG_SOC_ULP_HAS_ADC = 1
const CONFIG_SOC_PHY_COMBO_MODULE = 1
const CONFIG_IDF_CMAKE = 1
const CONFIG_IDF_TOOLCHAIN = "gcc"
const CONFIG_IDF_TOOLCHAIN_GCC = 1
const CONFIG_IDF_TARGET_ARCH_XTENSA = 1
const CONFIG_IDF_TARGET_ARCH = "xtensa"
const CONFIG_IDF_TARGET = "esp32s3"
const CONFIG_IDF_INIT_VERSION = "5.4.2"
const CONFIG_IDF_TARGET_ESP32S3 = 1
const CONFIG_IDF_FIRMWARE_CHIP_ID = 0x0009
const CONFIG_APP_BUILD_TYPE_APP_2NDBOOT = 1
const CONFIG_APP_BUILD_GENERATE_BINARIES = 1
const CONFIG_APP_BUILD_BOOTLOADER = 1
const CONFIG_APP_BUILD_USE_FLASH_SECTIONS = 1
const CONFIG_BOOTLOADER_COMPILE_TIME_DATE = 1
const CONFIG_BOOTLOADER_PROJECT_VER = 1
const CONFIG_BOOTLOADER_OFFSET_IN_FLASH = 0x0
const CONFIG_BOOTLOADER_COMPILER_OPTIMIZATION_SIZE = 1
const CONFIG_BOOTLOADER_LOG_LEVEL_INFO = 1
const CONFIG_BOOTLOADER_LOG_LEVEL = 3
const CONFIG_BOOTLOADER_LOG_TIMESTAMP_SOURCE_CPU_TICKS = 1
const CONFIG_BOOTLOADER_FLASH_XMC_SUPPORT = 1
const CONFIG_BOOTLOADER_VDDSDIO_BOOST_1_9V = 1
const CONFIG_BOOTLOADER_REGION_PROTECTION_ENABLE = 1
const CONFIG_BOOTLOADER_WDT_ENABLE = 1
const CONFIG_BOOTLOADER_WDT_TIME_MS = 9000
const CONFIG_BOOTLOADER_RESERVE_RTC_SIZE = 0x0
const CONFIG_SECURE_BOOT_V2_RSA_SUPPORTED = 1
const CONFIG_SECURE_BOOT_V2_PREFERRED = 1
const CONFIG_SECURE_ROM_DL_MODE_ENABLED = 1
const CONFIG_APP_COMPILE_TIME_DATE = 1
const CONFIG_APP_RETRIEVE_LEN_ELF_SHA = 9
const CONFIG_ESP_ROM_HAS_CRC_LE = 1
const CONFIG_ESP_ROM_HAS_CRC_BE = 1
const CONFIG_ESP_ROM_HAS_MZ_CRC32 = 1
const CONFIG_ESP_ROM_HAS_JPEG_DECODE = 1
const CONFIG_ESP_ROM_UART_CLK_IS_XTAL = 1
const CONFIG_ESP_ROM_HAS_RETARGETABLE_LOCKING = 1
const CONFIG_ESP_ROM_USB_OTG_NUM = 3
const CONFIG_ESP_ROM_USB_SERIAL_DEVICE_NUM = 4
const CONFIG_ESP_ROM_HAS_ERASE_0_REGION_BUG = 1
const CONFIG_ESP_ROM_HAS_ENCRYPTED_WRITES_USING_LEGACY_DRV = 1
const CONFIG_ESP_ROM_GET_CLK_FREQ = 1
const CONFIG_ESP_ROM_HAS_HAL_WDT = 1
const CONFIG_ESP_ROM_NEEDS_SWSETUP_WORKAROUND = 1
const CONFIG_ESP_ROM_HAS_LAYOUT_TABLE = 1
const CONFIG_ESP_ROM_HAS_SPI_FLASH = 1
const CONFIG_ESP_ROM_HAS_ETS_PRINTF_BUG = 1
const CONFIG_ESP_ROM_HAS_NEWLIB = 1
const CONFIG_ESP_ROM_HAS_NEWLIB_NANO_FORMAT = 1
const CONFIG_ESP_ROM_HAS_NEWLIB_32BIT_TIME = 1
const CONFIG_ESP_ROM_NEEDS_SET_CACHE_MMU_SIZE = 1
const CONFIG_ESP_ROM_RAM_APP_NEEDS_MMU_INIT = 1
const CONFIG_ESP_ROM_HAS_FLASH_COUNT_PAGES_BUG = 1
const CONFIG_ESP_ROM_HAS_CACHE_SUSPEND_WAITI_BUG = 1
const CONFIG_ESP_ROM_HAS_CACHE_WRITEBACK_BUG = 1
const CONFIG_ESP_ROM_HAS_SW_FLOAT = 1
const CONFIG_ESP_ROM_HAS_VERSION = 1
const CONFIG_ESP_ROM_SUPPORT_DEEP_SLEEP_WAKEUP_STUB = 1
const CONFIG_ESP_ROM_HAS_OUTPUT_PUTC_FUNC = 1
const CONFIG_BOOT_ROM_LOG_ALWAYS_ON = 1
const CONFIG_ESPTOOLPY_FLASH_MODE_AUTO_DETECT = 1
const CONFIG_ESPTOOLPY_FLASHMODE_DIO = 1
const CONFIG_ESPTOOLPY_FLASH_SAMPLE_MODE_STR = 1
const CONFIG_ESPTOOLPY_FLASHMODE = "dio"
const CONFIG_ESPTOOLPY_FLASHFREQ_80M = 1
const CONFIG_ESPTOOLPY_FLASHFREQ = "80m"
const CONFIG_ESPTOOLPY_FLASHSIZE_2MB = 1
const CONFIG_ESPTOOLPY_FLASHSIZE = "2MB"
const CONFIG_ESPTOOLPY_BEFORE_RESET = 1
const CONFIG_ESPTOOLPY_BEFORE = "default_reset"
const CONFIG_ESPTOOLPY_AFTER_RESET = 1
const CONFIG_ESPTOOLPY_AFTER = "hard_reset"
const CONFIG_ESPTOOLPY_MONITOR_BAUD = 115200
const CONFIG_PARTITION_TABLE_SINGLE_APP = 1
const CONFIG_PARTITION_TABLE_CUSTOM_FILENAME = "partitions.csv"
const CONFIG_PARTITION_TABLE_FILENAME = "partitions_singleapp.csv"
const CONFIG_PARTITION_TABLE_OFFSET = 0x8000
const CONFIG_PARTITION_TABLE_MD5 = 1
const CONFIG_COMPILER_OPTIMIZATION_DEBUG = 1
const CONFIG_COMPILER_OPTIMIZATION_ASSERTIONS_ENABLE = 1
const CONFIG_COMPILER_ASSERT_NDEBUG_EVALUATE = 1
const CONFIG_COMPILER_FLOAT_LIB_FROM_GCCLIB = 1
const CONFIG_COMPILER_OPTIMIZATION_ASSERTION_LEVEL = 2
const CONFIG_COMPILER_HIDE_PATHS_MACROS = 1
const CONFIG_COMPILER_STACK_CHECK_MODE_NONE = 1
const CONFIG_COMPILER_DISABLE_DEFAULT_ERRORS = 1
const CONFIG_COMPILER_RT_LIB_GCCLIB = 1
const CONFIG_COMPILER_RT_LIB_NAME = "gcc"
const CONFIG_COMPILER_ORPHAN_SECTIONS_WARNING = 1
const CONFIG_APPTRACE_DEST_NONE = 1
const CONFIG_APPTRACE_DEST_UART_NONE = 1
const CONFIG_APPTRACE_UART_TASK_PRIO = 1
const CONFIG_APPTRACE_LOCK_ENABLE = 1
const CONFIG_TWAI_ERRATA_FIX_LISTEN_ONLY_DOM = 1
const CONFIG_EFUSE_MAX_BLK_LEN = 256
const CONFIG_ESP_TLS_USING_MBEDTLS = 1
const CONFIG_ESP_TLS_USE_DS_PERIPHERAL = 1
const CONFIG_ESP_COEX_ENABLED = 1
const CONFIG_ESP_ERR_TO_NAME_LOOKUP = 1
const CONFIG_GPTIMER_ISR_HANDLER_IN_IRAM = 1
const CONFIG_GPTIMER_OBJ_CACHE_SAFE = 1
const CONFIG_SPI_MASTER_ISR_IN_IRAM = 1
const CONFIG_SPI_SLAVE_ISR_IN_IRAM = 1
const CONFIG_USJ_ENABLE_USB_SERIAL_JTAG = 1
const CONFIG_ETH_ENABLED = 1
const CONFIG_ETH_USE_SPI_ETHERNET = 1
const CONFIG_ESP_EVENT_POST_FROM_ISR = 1
const CONFIG_ESP_EVENT_POST_FROM_IRAM_ISR = 1
const CONFIG_ESP_GDBSTUB_ENABLED = 1
const CONFIG_ESP_GDBSTUB_SUPPORT_TASKS = 1
const CONFIG_ESP_GDBSTUB_MAX_TASKS = 32
const CONFIG_ESPHID_TASK_SIZE_BT = 2048
const CONFIG_ESPHID_TASK_SIZE_BLE = 4096
const CONFIG_ESP_HTTP_CLIENT_ENABLE_HTTPS = 1
const CONFIG_ESP_HTTP_CLIENT_EVENT_POST_TIMEOUT = 2000
const CONFIG_HTTPD_MAX_REQ_HDR_LEN = 512
const CONFIG_HTTPD_MAX_URI_LEN = 512
const CONFIG_HTTPD_ERR_RESP_NO_DELAY = 1
const CONFIG_HTTPD_PURGE_BUF_LEN = 32
const CONFIG_HTTPD_SERVER_EVENT_POST_TIMEOUT = 2000
const CONFIG_ESP_HTTPS_OTA_EVENT_POST_TIMEOUT = 2000
const CONFIG_ESP_HTTPS_SERVER_EVENT_POST_TIMEOUT = 2000
const CONFIG_ESP32S3_REV_MIN_0 = 1
const CONFIG_ESP32S3_REV_MIN_FULL = 0
const CONFIG_ESP_REV_MIN_FULL = 0
const CONFIG_ESP32S3_REV_MAX_FULL = 99
const CONFIG_ESP_REV_MAX_FULL = 99
const CONFIG_ESP_EFUSE_BLOCK_REV_MIN_FULL = 0
const CONFIG_ESP_EFUSE_BLOCK_REV_MAX_FULL = 199
const CONFIG_ESP_MAC_ADDR_UNIVERSE_WIFI_STA = 1
const CONFIG_ESP_MAC_ADDR_UNIVERSE_WIFI_AP = 1
const CONFIG_ESP_MAC_ADDR_UNIVERSE_BT = 1
const CONFIG_ESP_MAC_ADDR_UNIVERSE_ETH = 1
const CONFIG_ESP_MAC_UNIVERSAL_MAC_ADDRESSES_FOUR = 1
const CONFIG_ESP_MAC_UNIVERSAL_MAC_ADDRESSES = 4
const CONFIG_ESP32S3_UNIVERSAL_MAC_ADDRESSES_FOUR = 1
const CONFIG_ESP32S3_UNIVERSAL_MAC_ADDRESSES = 4
const CONFIG_ESP_SLEEP_FLASH_LEAKAGE_WORKAROUND = 1
const CONFIG_ESP_SLEEP_MSPI_NEED_ALL_IO_PU = 1
const CONFIG_ESP_SLEEP_RTC_BUS_ISO_WORKAROUND = 1
const CONFIG_ESP_SLEEP_GPIO_RESET_WORKAROUND = 1
const CONFIG_ESP_SLEEP_WAIT_FLASH_READY_EXTRA_DELAY = 2000
const CONFIG_ESP_SLEEP_GPIO_ENABLE_INTERNAL_RESISTORS = 1
const CONFIG_RTC_CLK_SRC_INT_RC = 1
const CONFIG_RTC_CLK_CAL_CYCLES = 1024
const CONFIG_GDMA_CTRL_FUNC_IN_IRAM = 1
const CONFIG_GDMA_ISR_HANDLER_IN_IRAM = 1
const CONFIG_GDMA_OBJ_DRAM_SAFE = 1
const CONFIG_XTAL_FREQ_40 = 1
const CONFIG_XTAL_FREQ = 40
const CONFIG_ESP_SPI_BUS_LOCK_ISR_FUNCS_IN_IRAM = 1
const CONFIG_ESP_NETIF_IP_LOST_TIMER_INTERVAL = 120
const CONFIG_ESP_NETIF_TCPIP_LWIP = 1
const CONFIG_ESP_NETIF_USES_TCPIP_WITH_BSD_API = 1
const CONFIG_ESP_NETIF_REPORT_DATA_TRAFFIC = 1
const CONFIG_ESP_PHY_ENABLED = 1
const CONFIG_ESP_PHY_CALIBRATION_AND_DATA_STORAGE = 1
const CONFIG_ESP_PHY_MAX_WIFI_TX_POWER = 20
const CONFIG_ESP_PHY_MAX_TX_POWER = 20
const CONFIG_ESP_PHY_ENABLE_USB = 1
const CONFIG_ESP_PHY_RF_CAL_PARTIAL = 1
const CONFIG_ESP_PHY_CALIBRATION_MODE = 0
const CONFIG_PM_POWER_DOWN_CPU_IN_LIGHT_SLEEP = 1
const CONFIG_PM_RESTORE_CACHE_TAGMEM_AFTER_LIGHT_SLEEP = 1
const CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ_160 = 1
const CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ = 160
const CONFIG_ESP32S3_INSTRUCTION_CACHE_16KB = 1
const CONFIG_ESP32S3_INSTRUCTION_CACHE_SIZE = 0x4000
const CONFIG_ESP32S3_INSTRUCTION_CACHE_8WAYS = 1
const CONFIG_ESP32S3_ICACHE_ASSOCIATED_WAYS = 8
const CONFIG_ESP32S3_INSTRUCTION_CACHE_LINE_32B = 1
const CONFIG_ESP32S3_INSTRUCTION_CACHE_LINE_SIZE = 32
const CONFIG_ESP32S3_DATA_CACHE_32KB = 1
const CONFIG_ESP32S3_DATA_CACHE_SIZE = 0x8000
const CONFIG_ESP32S3_DATA_CACHE_8WAYS = 1
const CONFIG_ESP32S3_DCACHE_ASSOCIATED_WAYS = 8
const CONFIG_ESP32S3_DATA_CACHE_LINE_32B = 1
const CONFIG_ESP32S3_DATA_CACHE_LINE_SIZE = 32
const CONFIG_ESP32S3_TRACEMEM_RESERVE_DRAM = 0x0
const CONFIG_ESP_SYSTEM_PANIC_PRINT_REBOOT = 1
const CONFIG_ESP_SYSTEM_PANIC_REBOOT_DELAY_SECONDS = 0
const CONFIG_ESP_SYSTEM_RTC_FAST_MEM_AS_HEAP_DEPCHECK = 1
const CONFIG_ESP_SYSTEM_ALLOW_RTC_FAST_MEM_AS_HEAP = 1
const CONFIG_ESP_SYSTEM_MEMPROT_FEATURE = 1
const CONFIG_ESP_SYSTEM_MEMPROT_FEATURE_LOCK = 1
const CONFIG_ESP_SYSTEM_EVENT_QUEUE_SIZE = 32
const CONFIG_ESP_SYSTEM_EVENT_TASK_STACK_SIZE = 2304
const CONFIG_ESP_MAIN_TASK_STACK_SIZE = 3584
const CONFIG_ESP_MAIN_TASK_AFFINITY_CPU0 = 1
const CONFIG_ESP_MAIN_TASK_AFFINITY = 0x0
const CONFIG_ESP_MINIMAL_SHARED_STACK_SIZE = 2048
const CONFIG_ESP_CONSOLE_UART_DEFAULT = 1
const CONFIG_ESP_CONSOLE_SECONDARY_USB_SERIAL_JTAG = 1
const CONFIG_ESP_CONSOLE_USB_SERIAL_JTAG_ENABLED = 1
const CONFIG_ESP_CONSOLE_UART = 1
const CONFIG_ESP_CONSOLE_UART_NUM = 0
const CONFIG_ESP_CONSOLE_ROM_SERIAL_PORT_NUM = 0
const CONFIG_ESP_CONSOLE_UART_BAUDRATE = 115200
const CONFIG_ESP_INT_WDT = 1
const CONFIG_ESP_INT_WDT_TIMEOUT_MS = 300
const CONFIG_ESP_INT_WDT_CHECK_CPU1 = 1
const CONFIG_ESP_TASK_WDT_EN = 1
const CONFIG_ESP_TASK_WDT_INIT = 1
const CONFIG_ESP_TASK_WDT_TIMEOUT_S = 5
const CONFIG_ESP_TASK_WDT_CHECK_IDLE_TASK_CPU0 = 1
const CONFIG_ESP_TASK_WDT_CHECK_IDLE_TASK_CPU1 = 1
const CONFIG_ESP_DEBUG_OCDAWARE = 1
const CONFIG_ESP_SYSTEM_CHECK_INT_LEVEL_4 = 1
const CONFIG_ESP_BROWNOUT_DET = 1
const CONFIG_ESP_BROWNOUT_DET_LVL_SEL_7 = 1
const CONFIG_ESP_BROWNOUT_DET_LVL = 7
const CONFIG_ESP_SYSTEM_BROWNOUT_INTR = 1
const CONFIG_ESP_SYSTEM_BBPLL_RECALIB = 1
const CONFIG_ESP_IPC_TASK_STACK_SIZE = 1280
const CONFIG_ESP_IPC_USES_CALLERS_PRIORITY = 1
const CONFIG_ESP_IPC_ISR_ENABLE = 1
const CONFIG_ESP_TIME_FUNCS_USE_RTC_TIMER = 1
const CONFIG_ESP_TIME_FUNCS_USE_ESP_TIMER = 1
const CONFIG_ESP_TIMER_TASK_STACK_SIZE = 3584
const CONFIG_ESP_TIMER_INTERRUPT_LEVEL = 1
const CONFIG_ESP_TIMER_TASK_AFFINITY = 0x0
const CONFIG_ESP_TIMER_TASK_AFFINITY_CPU0 = 1
const CONFIG_ESP_TIMER_ISR_AFFINITY_CPU0 = 1
const CONFIG_ESP_TIMER_IMPL_SYSTIMER = 1
const CONFIG_ESP_WIFI_ENABLED = 1
const CONFIG_ESP_WIFI_STATIC_RX_BUFFER_NUM = 10
const CONFIG_ESP_WIFI_DYNAMIC_RX_BUFFER_NUM = 32
const CONFIG_ESP_WIFI_DYNAMIC_TX_BUFFER = 1
const CONFIG_ESP_WIFI_TX_BUFFER_TYPE = 1
const CONFIG_ESP_WIFI_DYNAMIC_TX_BUFFER_NUM = 32
const CONFIG_ESP_WIFI_STATIC_RX_MGMT_BUFFER = 1
const CONFIG_ESP_WIFI_DYNAMIC_RX_MGMT_BUF = 0
const CONFIG_ESP_WIFI_RX_MGMT_BUF_NUM_DEF = 5
const CONFIG_ESP_WIFI_AMPDU_TX_ENABLED = 1
const CONFIG_ESP_WIFI_TX_BA_WIN = 6
const CONFIG_ESP_WIFI_AMPDU_RX_ENABLED = 1
const CONFIG_ESP_WIFI_RX_BA_WIN = 6
const CONFIG_ESP_WIFI_NVS_ENABLED = 1
const CONFIG_ESP_WIFI_TASK_PINNED_TO_CORE_0 = 1
const CONFIG_ESP_WIFI_SOFTAP_BEACON_MAX_LEN = 752
const CONFIG_ESP_WIFI_MGMT_SBUF_NUM = 32
const CONFIG_ESP_WIFI_IRAM_OPT = 1
const CONFIG_ESP_WIFI_RX_IRAM_OPT = 1
const CONFIG_ESP_WIFI_ENABLE_WPA3_SAE = 1
const CONFIG_ESP_WIFI_ENABLE_SAE_PK = 1
const CONFIG_ESP_WIFI_SOFTAP_SAE_SUPPORT = 1
const CONFIG_ESP_WIFI_ENABLE_WPA3_OWE_STA = 1
const CONFIG_ESP_WIFI_SLP_DEFAULT_MIN_ACTIVE_TIME = 50
const CONFIG_ESP_WIFI_SLP_DEFAULT_MAX_ACTIVE_TIME = 10
const CONFIG_ESP_WIFI_SLP_DEFAULT_WAIT_BROADCAST_DATA_TIME = 15
const CONFIG_ESP_WIFI_STA_DISCONNECTED_PM_ENABLE = 1
const CONFIG_ESP_WIFI_GMAC_SUPPORT = 1
const CONFIG_ESP_WIFI_SOFTAP_SUPPORT = 1
const CONFIG_ESP_WIFI_ESPNOW_MAX_ENCRYPT_NUM = 7
const CONFIG_ESP_WIFI_MBEDTLS_CRYPTO = 1
const CONFIG_ESP_WIFI_MBEDTLS_TLS_CLIENT = 1
const CONFIG_ESP_WIFI_ENTERPRISE_SUPPORT = 1
const CONFIG_ESP_COREDUMP_ENABLE_TO_NONE = 1
const CONFIG_FATFS_VOLUME_COUNT = 2
const CONFIG_FATFS_LFN_NONE = 1
const CONFIG_FATFS_SECTOR_4096 = 1
const CONFIG_FATFS_CODEPAGE_437 = 1
const CONFIG_FATFS_CODEPAGE = 437
const CONFIG_FATFS_FS_LOCK = 0
const CONFIG_FATFS_TIMEOUT_MS = 10000
const CONFIG_FATFS_PER_FILE_CACHE = 1
const CONFIG_FATFS_USE_STRFUNC_NONE = 1
const CONFIG_FATFS_VFS_FSTAT_BLKSIZE = 0
const CONFIG_FATFS_LINK_LOCK = 1
const CONFIG_FATFS_DONT_TRUST_FREE_CLUSTER_CNT = 0
const CONFIG_FATFS_DONT_TRUST_LAST_ALLOC = 0
const CONFIG_FREERTOS_HZ = 100
const CONFIG_FREERTOS_CHECK_STACKOVERFLOW_CANARY = 1
const CONFIG_FREERTOS_THREAD_LOCAL_STORAGE_POINTERS = 1
const CONFIG_FREERTOS_IDLE_TASK_STACKSIZE = 1536
const CONFIG_FREERTOS_MAX_TASK_NAME_LEN = 16
const CONFIG_FREERTOS_USE_TIMERS = 1
const CONFIG_FREERTOS_TIMER_SERVICE_TASK_NAME = "Tmr Svc"
const CONFIG_FREERTOS_TIMER_TASK_NO_AFFINITY = 1
const CONFIG_FREERTOS_TIMER_SERVICE_TASK_CORE_AFFINITY = 0x7FFFFFFF
const CONFIG_FREERTOS_TIMER_TASK_PRIORITY = 1
const CONFIG_FREERTOS_TIMER_TASK_STACK_DEPTH = 2048
const CONFIG_FREERTOS_TIMER_QUEUE_LENGTH = 10
const CONFIG_FREERTOS_QUEUE_REGISTRY_SIZE = 0
const CONFIG_FREERTOS_TASK_NOTIFICATION_ARRAY_ENTRIES = 1
const CONFIG_FREERTOS_TASK_FUNCTION_WRAPPER = 1
const CONFIG_FREERTOS_TLSP_DELETION_CALLBACKS = 1
const CONFIG_FREERTOS_CHECK_MUTEX_GIVEN_BY_OWNER = 1
const CONFIG_FREERTOS_ISR_STACKSIZE = 1536
const CONFIG_FREERTOS_INTERRUPT_BACKTRACE = 1
const CONFIG_FREERTOS_TICK_SUPPORT_SYSTIMER = 1
const CONFIG_FREERTOS_CORETIMER_SYSTIMER_LVL1 = 1
const CONFIG_FREERTOS_SYSTICK_USES_SYSTIMER = 1
const CONFIG_FREERTOS_PORT = 1
const CONFIG_FREERTOS_NO_AFFINITY = 0x7FFFFFFF
const CONFIG_FREERTOS_SUPPORT_STATIC_ALLOCATION = 1
const CONFIG_FREERTOS_DEBUG_OCDAWARE = 1
const CONFIG_FREERTOS_ENABLE_TASK_SNAPSHOT = 1
const CONFIG_FREERTOS_PLACE_SNAPSHOT_FUNS_INTO_FLASH = 1
const CONFIG_FREERTOS_NUMBER_OF_CORES = 2
const CONFIG_HAL_ASSERTION_EQUALS_SYSTEM = 1
const CONFIG_HAL_DEFAULT_ASSERTION_LEVEL = 2
const CONFIG_HAL_WDT_USE_ROM_IMPL = 1
const CONFIG_HAL_SPI_MASTER_FUNC_IN_IRAM = 1
const CONFIG_HAL_SPI_SLAVE_FUNC_IN_IRAM = 1
const CONFIG_HEAP_POISONING_DISABLED = 1
const CONFIG_HEAP_TRACING_OFF = 1
const CONFIG_LOG_DEFAULT_LEVEL_INFO = 1
const CONFIG_LOG_DEFAULT_LEVEL = 3
const CONFIG_LOG_MAXIMUM_EQUALS_DEFAULT = 1
const CONFIG_LOG_MAXIMUM_LEVEL = 3
const CONFIG_LOG_DYNAMIC_LEVEL_CONTROL = 1
const CONFIG_LOG_TAG_LEVEL_IMPL_CACHE_AND_LINKED_LIST = 1
const CONFIG_LOG_TAG_LEVEL_CACHE_BINARY_MIN_HEAP = 1
const CONFIG_LOG_TAG_LEVEL_IMPL_CACHE_SIZE = 31
const CONFIG_LOG_TIMESTAMP_SOURCE_RTOS = 1
const CONFIG_LWIP_ENABLE = 1
const CONFIG_LWIP_LOCAL_HOSTNAME = "espressif"
const CONFIG_LWIP_TCPIP_TASK_PRIO = 18
const CONFIG_LWIP_DNS_SUPPORT_MDNS_QUERIES = 1
const CONFIG_LWIP_TIMERS_ONDEMAND = 1
const CONFIG_LWIP_ND6 = 1
const CONFIG_LWIP_MAX_SOCKETS = 10
const CONFIG_LWIP_SO_REUSE = 1
const CONFIG_LWIP_SO_REUSE_RXTOALL = 1
const CONFIG_LWIP_IP_DEFAULT_TTL = 64
const CONFIG_LWIP_IP4_FRAG = 1
const CONFIG_LWIP_IP6_FRAG = 1
const CONFIG_LWIP_IP_REASS_MAX_PBUFS = 10
const CONFIG_LWIP_ESP_GRATUITOUS_ARP = 1
const CONFIG_LWIP_GARP_TMR_INTERVAL = 60
const CONFIG_LWIP_ESP_MLDV6_REPORT = 1
const CONFIG_LWIP_MLDV6_TMR_INTERVAL = 40
const CONFIG_LWIP_TCPIP_RECVMBOX_SIZE = 32
const CONFIG_LWIP_DHCP_DOES_ARP_CHECK = 1
const CONFIG_LWIP_DHCP_DISABLE_VENDOR_CLASS_ID = 1
const CONFIG_LWIP_DHCP_OPTIONS_LEN = 68
const CONFIG_LWIP_NUM_NETIF_CLIENT_DATA = 0
const CONFIG_LWIP_DHCP_COARSE_TIMER_SECS = 1
const CONFIG_LWIP_DHCPS = 1
const CONFIG_LWIP_DHCPS_LEASE_UNIT = 60
const CONFIG_LWIP_DHCPS_MAX_STATION_NUM = 8
const CONFIG_LWIP_DHCPS_STATIC_ENTRIES = 1
const CONFIG_LWIP_DHCPS_ADD_DNS = 1
const CONFIG_LWIP_IPV4 = 1
const CONFIG_LWIP_IPV6 = 1
const CONFIG_LWIP_IPV6_NUM_ADDRESSES = 3
const CONFIG_LWIP_NETIF_LOOPBACK = 1
const CONFIG_LWIP_LOOPBACK_MAX_PBUFS = 8
const CONFIG_LWIP_MAX_ACTIVE_TCP = 16
const CONFIG_LWIP_MAX_LISTENING_TCP = 16
const CONFIG_LWIP_TCP_HIGH_SPEED_RETRANSMISSION = 1
const CONFIG_LWIP_TCP_MAXRTX = 12
const CONFIG_LWIP_TCP_SYNMAXRTX = 12
const CONFIG_LWIP_TCP_MSS = 1440
const CONFIG_LWIP_TCP_TMR_INTERVAL = 250
const CONFIG_LWIP_TCP_MSL = 60000
const CONFIG_LWIP_TCP_FIN_WAIT_TIMEOUT = 20000
const CONFIG_LWIP_TCP_SND_BUF_DEFAULT = 5760
const CONFIG_LWIP_TCP_WND_DEFAULT = 5760
const CONFIG_LWIP_TCP_RECVMBOX_SIZE = 6
const CONFIG_LWIP_TCP_ACCEPTMBOX_SIZE = 6
const CONFIG_LWIP_TCP_QUEUE_OOSEQ = 1
const CONFIG_LWIP_TCP_OOSEQ_TIMEOUT = 6
const CONFIG_LWIP_TCP_OOSEQ_MAX_PBUFS = 4
const CONFIG_LWIP_TCP_OVERSIZE_MSS = 1
const CONFIG_LWIP_TCP_RTO_TIME = 1500
const CONFIG_LWIP_MAX_UDP_PCBS = 16
const CONFIG_LWIP_UDP_RECVMBOX_SIZE = 6
const CONFIG_LWIP_CHECKSUM_CHECK_ICMP = 1
const CONFIG_LWIP_TCPIP_TASK_STACK_SIZE = 3072
const CONFIG_LWIP_TCPIP_TASK_AFFINITY_NO_AFFINITY = 1
const CONFIG_LWIP_TCPIP_TASK_AFFINITY = 0x7FFFFFFF
const CONFIG_LWIP_IPV6_MEMP_NUM_ND6_QUEUE = 3
const CONFIG_LWIP_IPV6_ND6_NUM_NEIGHBORS = 5
const CONFIG_LWIP_IPV6_ND6_NUM_PREFIXES = 5
const CONFIG_LWIP_IPV6_ND6_NUM_ROUTERS = 3
const CONFIG_LWIP_IPV6_ND6_NUM_DESTINATIONS = 10
const CONFIG_LWIP_ICMP = 1
const CONFIG_LWIP_MAX_RAW_PCBS = 16
const CONFIG_LWIP_SNTP_MAX_SERVERS = 1
const CONFIG_LWIP_SNTP_UPDATE_DELAY = 3600000
const CONFIG_LWIP_SNTP_STARTUP_DELAY = 1
const CONFIG_LWIP_SNTP_MAXIMUM_STARTUP_DELAY = 5000
const CONFIG_LWIP_DNS_MAX_HOST_IP = 1
const CONFIG_LWIP_DNS_MAX_SERVERS = 3
const CONFIG_LWIP_BRIDGEIF_MAX_PORTS = 7
const CONFIG_LWIP_ESP_LWIP_ASSERT = 1
const CONFIG_LWIP_HOOK_TCP_ISN_DEFAULT = 1
const CONFIG_LWIP_HOOK_IP6_ROUTE_NONE = 1
const CONFIG_LWIP_HOOK_ND6_GET_GW_NONE = 1
const CONFIG_LWIP_HOOK_IP6_SELECT_SRC_ADDR_NONE = 1
const CONFIG_LWIP_HOOK_NETCONN_EXT_RESOLVE_NONE = 1
const CONFIG_LWIP_HOOK_DNS_EXT_RESOLVE_NONE = 1
const CONFIG_LWIP_HOOK_IP6_INPUT_DEFAULT = 1
const CONFIG_MBEDTLS_INTERNAL_MEM_ALLOC = 1
const CONFIG_MBEDTLS_ASYMMETRIC_CONTENT_LEN = 1
const CONFIG_MBEDTLS_SSL_IN_CONTENT_LEN = 16384
const CONFIG_MBEDTLS_SSL_OUT_CONTENT_LEN = 4096
const CONFIG_MBEDTLS_SSL_KEEP_PEER_CERTIFICATE = 1
const CONFIG_MBEDTLS_PKCS7_C = 1
const CONFIG_MBEDTLS_CERTIFICATE_BUNDLE = 1
const CONFIG_MBEDTLS_CERTIFICATE_BUNDLE_DEFAULT_FULL = 1
const CONFIG_MBEDTLS_CERTIFICATE_BUNDLE_MAX_CERTS = 200
const CONFIG_MBEDTLS_CMAC_C = 1
const CONFIG_MBEDTLS_HARDWARE_AES = 1
const CONFIG_MBEDTLS_AES_USE_INTERRUPT = 1
const CONFIG_MBEDTLS_AES_INTERRUPT_LEVEL = 0
const CONFIG_MBEDTLS_GCM_SUPPORT_NON_AES_CIPHER = 1
const CONFIG_MBEDTLS_HARDWARE_MPI = 1
const CONFIG_MBEDTLS_MPI_USE_INTERRUPT = 1
const CONFIG_MBEDTLS_MPI_INTERRUPT_LEVEL = 0
const CONFIG_MBEDTLS_HARDWARE_SHA = 1
const CONFIG_MBEDTLS_ROM_MD5 = 1
const CONFIG_MBEDTLS_HAVE_TIME = 1
const CONFIG_MBEDTLS_ECDSA_DETERMINISTIC = 1
const CONFIG_MBEDTLS_SHA1_C = 1
const CONFIG_MBEDTLS_SHA512_C = 1
const CONFIG_MBEDTLS_TLS_SERVER_AND_CLIENT = 1
const CONFIG_MBEDTLS_TLS_SERVER = 1
const CONFIG_MBEDTLS_TLS_CLIENT = 1
const CONFIG_MBEDTLS_TLS_ENABLED = 1
const CONFIG_MBEDTLS_KEY_EXCHANGE_RSA = 1
const CONFIG_MBEDTLS_KEY_EXCHANGE_ELLIPTIC_CURVE = 1
const CONFIG_MBEDTLS_KEY_EXCHANGE_ECDHE_RSA = 1
const CONFIG_MBEDTLS_KEY_EXCHANGE_ECDHE_ECDSA = 1
const CONFIG_MBEDTLS_KEY_EXCHANGE_ECDH_ECDSA = 1
const CONFIG_MBEDTLS_KEY_EXCHANGE_ECDH_RSA = 1
const CONFIG_MBEDTLS_SSL_RENEGOTIATION = 1
const CONFIG_MBEDTLS_SSL_PROTO_TLS1_2 = 1
const CONFIG_MBEDTLS_SSL_ALPN = 1
const CONFIG_MBEDTLS_CLIENT_SSL_SESSION_TICKETS = 1
const CONFIG_MBEDTLS_SERVER_SSL_SESSION_TICKETS = 1
const CONFIG_MBEDTLS_AES_C = 1
const CONFIG_MBEDTLS_CCM_C = 1
const CONFIG_MBEDTLS_GCM_C = 1
const CONFIG_MBEDTLS_PEM_PARSE_C = 1
const CONFIG_MBEDTLS_PEM_WRITE_C = 1
const CONFIG_MBEDTLS_X509_CRL_PARSE_C = 1
const CONFIG_MBEDTLS_X509_CSR_PARSE_C = 1
const CONFIG_MBEDTLS_ECP_C = 1
const CONFIG_MBEDTLS_PK_PARSE_EC_EXTENDED = 1
const CONFIG_MBEDTLS_PK_PARSE_EC_COMPRESSED = 1
const CONFIG_MBEDTLS_ECDH_C = 1
const CONFIG_MBEDTLS_ECDSA_C = 1
const CONFIG_MBEDTLS_ECP_DP_SECP192R1_ENABLED = 1
const CONFIG_MBEDTLS_ECP_DP_SECP224R1_ENABLED = 1
const CONFIG_MBEDTLS_ECP_DP_SECP256R1_ENABLED = 1
const CONFIG_MBEDTLS_ECP_DP_SECP384R1_ENABLED = 1
const CONFIG_MBEDTLS_ECP_DP_SECP521R1_ENABLED = 1
const CONFIG_MBEDTLS_ECP_DP_SECP192K1_ENABLED = 1
const CONFIG_MBEDTLS_ECP_DP_SECP224K1_ENABLED = 1
const CONFIG_MBEDTLS_ECP_DP_SECP256K1_ENABLED = 1
const CONFIG_MBEDTLS_ECP_DP_BP256R1_ENABLED = 1
const CONFIG_MBEDTLS_ECP_DP_BP384R1_ENABLED = 1
const CONFIG_MBEDTLS_ECP_DP_BP512R1_ENABLED = 1
const CONFIG_MBEDTLS_ECP_DP_CURVE25519_ENABLED = 1
const CONFIG_MBEDTLS_ECP_NIST_OPTIM = 1
const CONFIG_MBEDTLS_ERROR_STRINGS = 1
const CONFIG_MBEDTLS_FS_IO = 1
const CONFIG_MQTT_PROTOCOL_311 = 1
const CONFIG_MQTT_TRANSPORT_SSL = 1
const CONFIG_MQTT_TRANSPORT_WEBSOCKET = 1
const CONFIG_MQTT_TRANSPORT_WEBSOCKET_SECURE = 1
const CONFIG_NEWLIB_STDOUT_LINE_ENDING_CRLF = 1
const CONFIG_NEWLIB_STDIN_LINE_ENDING_CR = 1
const CONFIG_NEWLIB_TIME_SYSCALL_USE_RTC_HRT = 1
const CONFIG_ESP_PROTOCOMM_SUPPORT_SECURITY_VERSION_0 = 1
const CONFIG_ESP_PROTOCOMM_SUPPORT_SECURITY_VERSION_1 = 1
const CONFIG_ESP_PROTOCOMM_SUPPORT_SECURITY_VERSION_2 = 1
const CONFIG_ESP_PROTOCOMM_SUPPORT_SECURITY_PATCH_VERSION = 1
const CONFIG_PTHREAD_TASK_PRIO_DEFAULT = 5
const CONFIG_PTHREAD_TASK_STACK_SIZE_DEFAULT = 3072
const CONFIG_PTHREAD_STACK_MIN = 768
const CONFIG_PTHREAD_DEFAULT_CORE_NO_AFFINITY = 1
const CONFIG_PTHREAD_TASK_NAME_DEFAULT = "pthread"
const CONFIG_MMU_PAGE_SIZE_64KB = 1
const CONFIG_MMU_PAGE_MODE = "64KB"
const CONFIG_MMU_PAGE_SIZE = 0x10000
const CONFIG_SPI_FLASH_BROWNOUT_RESET_XMC = 1
const CONFIG_SPI_FLASH_BROWNOUT_RESET = 1
const CONFIG_SPI_FLASH_HPM_AUTO = 1
const CONFIG_SPI_FLASH_HPM_ON = 1
const CONFIG_SPI_FLASH_HPM_DC_AUTO = 1
const CONFIG_SPI_FLASH_SUSPEND_TSUS_VAL_US = 50
const CONFIG_SPI_FLASH_ROM_DRIVER_PATCH = 1
const CONFIG_SPI_FLASH_DANGEROUS_WRITE_ABORTS = 1
const CONFIG_SPI_FLASH_YIELD_DURING_ERASE = 1
const CONFIG_SPI_FLASH_ERASE_YIELD_DURATION_MS = 20
const CONFIG_SPI_FLASH_ERASE_YIELD_TICKS = 1
const CONFIG_SPI_FLASH_WRITE_CHUNK_SIZE = 8192
const CONFIG_SPI_FLASH_VENDOR_XMC_SUPPORTED = 1
const CONFIG_SPI_FLASH_VENDOR_GD_SUPPORTED = 1
const CONFIG_SPI_FLASH_VENDOR_ISSI_SUPPORTED = 1
const CONFIG_SPI_FLASH_VENDOR_MXIC_SUPPORTED = 1
const CONFIG_SPI_FLASH_VENDOR_WINBOND_SUPPORTED = 1
const CONFIG_SPI_FLASH_VENDOR_BOYA_SUPPORTED = 1
const CONFIG_SPI_FLASH_VENDOR_TH_SUPPORTED = 1
const CONFIG_SPI_FLASH_SUPPORT_ISSI_CHIP = 1
const CONFIG_SPI_FLASH_SUPPORT_MXIC_CHIP = 1
const CONFIG_SPI_FLASH_SUPPORT_GD_CHIP = 1
const CONFIG_SPI_FLASH_SUPPORT_WINBOND_CHIP = 1
const CONFIG_SPI_FLASH_SUPPORT_BOYA_CHIP = 1
const CONFIG_SPI_FLASH_SUPPORT_TH_CHIP = 1
const CONFIG_SPI_FLASH_SUPPORT_MXIC_OPI_CHIP = 1
const CONFIG_SPI_FLASH_ENABLE_ENCRYPTED_READ_WRITE = 1
const CONFIG_SPIFFS_MAX_PARTITIONS = 3
const CONFIG_SPIFFS_CACHE = 1
const CONFIG_SPIFFS_CACHE_WR = 1
const CONFIG_SPIFFS_PAGE_CHECK = 1
const CONFIG_SPIFFS_GC_MAX_RUNS = 10
const CONFIG_SPIFFS_PAGE_SIZE = 256
const CONFIG_SPIFFS_OBJ_NAME_LEN = 32
const CONFIG_SPIFFS_USE_MAGIC = 1
const CONFIG_SPIFFS_USE_MAGIC_LENGTH = 1
const CONFIG_SPIFFS_META_LENGTH = 4
const CONFIG_SPIFFS_USE_MTIME = 1
const CONFIG_WS_TRANSPORT = 1
const CONFIG_WS_BUFFER_SIZE = 1024
const CONFIG_UNITY_ENABLE_FLOAT = 1
const CONFIG_UNITY_ENABLE_DOUBLE = 1
const CONFIG_UNITY_ENABLE_IDF_TEST_RUNNER = 1
const CONFIG_USB_HOST_CONTROL_TRANSFER_MAX_SIZE = 256
const CONFIG_USB_HOST_HW_BUFFER_BIAS_BALANCED = 1
const CONFIG_USB_HOST_DEBOUNCE_DELAY_MS = 250
const CONFIG_USB_HOST_RESET_HOLD_MS = 30
const CONFIG_USB_HOST_RESET_RECOVERY_MS = 30
const CONFIG_USB_HOST_SET_ADDR_RECOVERY_MS = 10
const CONFIG_USB_OTG_SUPPORTED = 1
const CONFIG_VFS_SUPPORT_IO = 1
const CONFIG_VFS_SUPPORT_DIR = 1
const CONFIG_VFS_SUPPORT_SELECT = 1
const CONFIG_VFS_SUPPRESS_SELECT_DEBUG_OUTPUT = 1
const CONFIG_VFS_SUPPORT_TERMIOS = 1
const CONFIG_VFS_MAX_COUNT = 8
const CONFIG_VFS_SEMIHOSTFS_MAX_MOUNT_POINTS = 1
const CONFIG_VFS_INITIALIZE_DEV_NULL = 1
const CONFIG_WL_SECTOR_SIZE_4096 = 1
const CONFIG_WL_SECTOR_SIZE = 4096
const CONFIG_WIFI_PROV_SCAN_MAX_ENTRIES = 16
const CONFIG_WIFI_PROV_AUTOSTOP_TIMEOUT = 30
const CONFIG_WIFI_PROV_STA_ALL_CHANNEL_SCAN = 1
const X__DARWIN_NSIG = 32
const X_ARM_SIGNAL_ = 1
const SIGHUP = 1
const SIGINT = 2
const SIGQUIT = 3
const SIGILL = 4
const SIGTRAP = 5
const SIGABRT = 6
const SIGEMT = 7
const SIGFPE = 8
const SIGKILL = 9
const SIGBUS = 10
const SIGSEGV = 11
const SIGSYS = 12
const SIGPIPE = 13
const SIGALRM = 14
const SIGTERM = 15
const SIGURG = 16
const SIGSTOP = 17
const SIGTSTP = 18
const SIGCONT = 19
const SIGCHLD = 20
const SIGTTIN = 21
const SIGTTOU = 22
const SIGIO = 23
const SIGXCPU = 24
const SIGXFSZ = 25
const SIGVTALRM = 26
const SIGPROF = 27
const SIGWINCH = 28
const SIGINFO = 29
const SIGUSR1 = 30
const SIGUSR2 = 31
const X__DARWIN_OPAQUE_ARM_THREAD_STATE64 = 0
const SIGEV_NONE = 0
const SIGEV_SIGNAL = 1
const SIGEV_THREAD = 3
const ILL_NOOP = 0
const ILL_ILLOPC = 1
const ILL_ILLTRP = 2
const ILL_PRVOPC = 3
const ILL_ILLOPN = 4
const ILL_ILLADR = 5
const ILL_PRVREG = 6
const ILL_COPROC = 7
const ILL_BADSTK = 8
const FPE_NOOP = 0
const FPE_FLTDIV = 1
const FPE_FLTOVF = 2
const FPE_FLTUND = 3
const FPE_FLTRES = 4
const FPE_FLTINV = 5
const FPE_FLTSUB = 6
const FPE_INTDIV = 7
const FPE_INTOVF = 8
const SEGV_NOOP = 0
const SEGV_MAPERR = 1
const SEGV_ACCERR = 2
const BUS_NOOP = 0
const BUS_ADRALN = 1
const BUS_ADRERR = 2
const BUS_OBJERR = 3
const TRAP_BRKPT = 1
const TRAP_TRACE = 2
const CLD_NOOP = 0
const CLD_EXITED = 1
const CLD_KILLED = 2
const CLD_DUMPED = 3
const CLD_TRAPPED = 4
const CLD_STOPPED = 5
const CLD_CONTINUED = 6
const POLL_IN = 1
const POLL_OUT = 2
const POLL_MSG = 3
const POLL_ERR = 4
const POLL_PRI = 5
const POLL_HUP = 6
const SA_ONSTACK = 0x0001
const SA_RESTART = 0x0002
const SA_RESETHAND = 0x0004
const SA_NOCLDSTOP = 0x0008
const SA_NODEFER = 0x0010
const SA_NOCLDWAIT = 0x0020
const SA_SIGINFO = 0x0040
const SA_USERTRAMP = 0x0100
const SA_64REGSET = 0x0200
const SIG_BLOCK = 1
const SIG_UNBLOCK = 2
const SIG_SETMASK = 3
const SI_USER = 0x10001
const SI_QUEUE = 0x10002
const SI_TIMER = 0x10003
const SI_ASYNCIO = 0x10004
const SI_MESGQ = 0x10005
const SS_ONSTACK = 0x0001
const SS_DISABLE = 0x0004
const MINSIGSTKSZ = 32768
const SIGSTKSZ = 131072
const PRIO_PROCESS = 0
const PRIO_PGRP = 1
const PRIO_USER = 2
const PRIO_DARWIN_THREAD = 3
const PRIO_DARWIN_PROCESS = 4
const PRIO_MAX = 20
const PRIO_DARWIN_BG = 0x1000
const PRIO_DARWIN_NONUI = 0x1001
const RUSAGE_SELF = 0
const RUSAGE_INFO_V0 = 0
const RUSAGE_INFO_V1 = 1
const RUSAGE_INFO_V2 = 2
const RUSAGE_INFO_V3 = 3
const RUSAGE_INFO_V4 = 4
const RUSAGE_INFO_V5 = 5
const RUSAGE_INFO_V6 = 6
const RU_PROC_RUNS_RESLIDE = 0x00000001
const RLIMIT_CPU = 0
const RLIMIT_FSIZE = 1
const RLIMIT_DATA = 2
const RLIMIT_STACK = 3
const RLIMIT_CORE = 4
const RLIMIT_AS = 5
const RLIMIT_MEMLOCK = 6
const RLIMIT_NPROC = 7
const RLIMIT_NOFILE = 8
const RLIM_NLIMITS = 9
const X_RLIMIT_POSIX_FLAG = 0x1000
const RLIMIT_WAKEUPS_MONITOR = 0x1
const RLIMIT_CPU_USAGE_MONITOR = 0x2
const RLIMIT_THREAD_CPULIMITS = 0x3
const RLIMIT_FOOTPRINT_INTERVAL = 0x4
const WAKEMON_ENABLE = 0x01
const WAKEMON_DISABLE = 0x02
const WAKEMON_GET_PARAMS = 0x04
const WAKEMON_SET_DEFAULTS = 0x08
const WAKEMON_MAKE_FATAL = 0x10
const CPUMON_MAKE_FATAL = 0x1000
const FOOTPRINT_INTERVAL_RESET = 0x1
const IOPOL_TYPE_DISK = 0
const IOPOL_TYPE_VFS_ATIME_UPDATES = 2
const IOPOL_TYPE_VFS_MATERIALIZE_DATALESS_FILES = 3
const IOPOL_TYPE_VFS_STATFS_NO_DATA_VOLUME = 4
const IOPOL_TYPE_VFS_TRIGGER_RESOLVE = 5
const IOPOL_TYPE_VFS_IGNORE_CONTENT_PROTECTION = 6
const IOPOL_TYPE_VFS_IGNORE_PERMISSIONS = 7
const IOPOL_TYPE_VFS_SKIP_MTIME_UPDATE = 8
const IOPOL_TYPE_VFS_ALLOW_LOW_SPACE_WRITES = 9
const IOPOL_TYPE_VFS_DISALLOW_RW_FOR_O_EVTONLY = 10
const IOPOL_SCOPE_PROCESS = 0
const IOPOL_SCOPE_THREAD = 1
const IOPOL_SCOPE_DARWIN_BG = 2
const IOPOL_DEFAULT = 0
const IOPOL_IMPORTANT = 1
const IOPOL_PASSIVE = 2
const IOPOL_THROTTLE = 3
const IOPOL_UTILITY = 4
const IOPOL_STANDARD = 5
const IOPOL_ATIME_UPDATES_DEFAULT = 0
const IOPOL_ATIME_UPDATES_OFF = 1
const IOPOL_MATERIALIZE_DATALESS_FILES_DEFAULT = 0
const IOPOL_MATERIALIZE_DATALESS_FILES_OFF = 1
const IOPOL_MATERIALIZE_DATALESS_FILES_ON = 2
const IOPOL_VFS_STATFS_NO_DATA_VOLUME_DEFAULT = 0
const IOPOL_VFS_STATFS_FORCE_NO_DATA_VOLUME = 1
const IOPOL_VFS_TRIGGER_RESOLVE_DEFAULT = 0
const IOPOL_VFS_TRIGGER_RESOLVE_OFF = 1
const IOPOL_VFS_CONTENT_PROTECTION_DEFAULT = 0
const IOPOL_VFS_CONTENT_PROTECTION_IGNORE = 1
const IOPOL_VFS_IGNORE_PERMISSIONS_OFF = 0
const IOPOL_VFS_IGNORE_PERMISSIONS_ON = 1
const IOPOL_VFS_SKIP_MTIME_UPDATE_OFF = 0
const IOPOL_VFS_SKIP_MTIME_UPDATE_ON = 1
const IOPOL_VFS_ALLOW_LOW_SPACE_WRITES_OFF = 0
const IOPOL_VFS_ALLOW_LOW_SPACE_WRITES_ON = 1
const IOPOL_VFS_DISALLOW_RW_FOR_O_EVTONLY_DEFAULT = 0
const IOPOL_VFS_DISALLOW_RW_FOR_O_EVTONLY_ON = 1
const IOPOL_VFS_NOCACHE_WRITE_FS_BLKSIZE_DEFAULT = 0
const IOPOL_VFS_NOCACHE_WRITE_FS_BLKSIZE_ON = 1
const WNOHANG = 0x00000001
const WUNTRACED = 0x00000002
const WCOREFLAG = 0200
const X_WSTOPPED = 0177
const WEXITED = 0x00000004
const WSTOPPED = 0x00000008
const WCONTINUED = 0x00000010
const WNOWAIT = 0x00000020
const WAIT_MYPGRP = 0
const X_QUAD_HIGHWORD = 1
const X_QUAD_LOWWORD = 0
const X__DARWIN_LITTLE_ENDIAN = 1234
const X__DARWIN_BIG_ENDIAN = 4321
const X__DARWIN_PDP_ENDIAN = 3412
const EXIT_FAILURE = 1
const EXIT_SUCCESS = 0
const RAND_MAX = 0x7fffffff
const ESP_OK = 0
const ESP_ERR_NO_MEM = 0x101
const ESP_ERR_INVALID_ARG = 0x102
const ESP_ERR_INVALID_STATE = 0x103
const ESP_ERR_INVALID_SIZE = 0x104
const ESP_ERR_NOT_FOUND = 0x105
const ESP_ERR_NOT_SUPPORTED = 0x106
const ESP_ERR_TIMEOUT = 0x107
const ESP_ERR_INVALID_RESPONSE = 0x108
const ESP_ERR_INVALID_CRC = 0x109
const ESP_ERR_INVALID_VERSION = 0x10A
const ESP_ERR_INVALID_MAC = 0x10B
const ESP_ERR_NOT_FINISHED = 0x10C
const ESP_ERR_NOT_ALLOWED = 0x10D
const ESP_ERR_WIFI_BASE = 0x3000
const ESP_ERR_MESH_BASE = 0x4000
const ESP_ERR_FLASH_BASE = 0x6000
const ESP_ERR_HW_CRYPTO_BASE = 0xc000
const ESP_ERR_MEMPROT_BASE = 0xd000
const X__ASSERT_FUNC = "??"
const X__bool_true_false_are_defined = 1
const True = 1
const False = 0
const SOC_ADC_SUPPORTED = 1
const SOC_UART_SUPPORTED = 1
const SOC_PCNT_SUPPORTED = 1
const SOC_PHY_SUPPORTED = 1
const SOC_WIFI_SUPPORTED = 1
const SOC_TWAI_SUPPORTED = 1
const SOC_GDMA_SUPPORTED = 1
const SOC_AHB_GDMA_SUPPORTED = 1
const SOC_GPTIMER_SUPPORTED = 1
const SOC_LCDCAM_SUPPORTED = 1
const SOC_LCDCAM_I80_LCD_SUPPORTED = 1
const SOC_LCDCAM_RGB_LCD_SUPPORTED = 1
const SOC_MCPWM_SUPPORTED = 1
const SOC_DEDICATED_GPIO_SUPPORTED = 1
const SOC_CACHE_SUPPORT_WRAP = 1
const SOC_ULP_SUPPORTED = 1
const SOC_ULP_FSM_SUPPORTED = 1
const SOC_RISCV_COPROC_SUPPORTED = 1
const SOC_BT_SUPPORTED = 1
const SOC_USB_OTG_SUPPORTED = 1
const SOC_USB_SERIAL_JTAG_SUPPORTED = 1
const SOC_CCOMP_TIMER_SUPPORTED = 1
const SOC_ASYNC_MEMCPY_SUPPORTED = 1
const SOC_SUPPORTS_SECURE_DL_MODE = 1
const SOC_EFUSE_KEY_PURPOSE_FIELD = 1
const SOC_EFUSE_SUPPORTED = 1
const SOC_SDMMC_HOST_SUPPORTED = 1
const SOC_RTC_FAST_MEM_SUPPORTED = 1
const SOC_RTC_SLOW_MEM_SUPPORTED = 1
const SOC_RTC_MEM_SUPPORTED = 1
const SOC_PSRAM_DMA_CAPABLE = 1
const SOC_XT_WDT_SUPPORTED = 1
const SOC_I2S_SUPPORTED = 1
const SOC_RMT_SUPPORTED = 1
const SOC_SDM_SUPPORTED = 1
const SOC_GPSPI_SUPPORTED = 1
const SOC_LEDC_SUPPORTED = 1
const SOC_I2C_SUPPORTED = 1
const SOC_SYSTIMER_SUPPORTED = 1
const SOC_SUPPORT_COEXISTENCE = 1
const SOC_TEMP_SENSOR_SUPPORTED = 1
const SOC_AES_SUPPORTED = 1
const SOC_MPI_SUPPORTED = 1
const SOC_SHA_SUPPORTED = 1
const SOC_HMAC_SUPPORTED = 1
const SOC_DIG_SIGN_SUPPORTED = 1
const SOC_FLASH_ENC_SUPPORTED = 1
const SOC_SECURE_BOOT_SUPPORTED = 1
const SOC_MEMPROT_SUPPORTED = 1
const SOC_TOUCH_SENSOR_SUPPORTED = 1
const SOC_BOD_SUPPORTED = 1
const SOC_CLK_TREE_SUPPORTED = 1
const SOC_MPU_SUPPORTED = 1
const SOC_WDT_SUPPORTED = 1
const SOC_SPI_FLASH_SUPPORTED = 1
const SOC_RNG_SUPPORTED = 1
const SOC_LIGHT_SLEEP_SUPPORTED = 1
const SOC_DEEP_SLEEP_SUPPORTED = 1
const SOC_LP_PERIPH_SHARE_INTERRUPT = 1
const SOC_PM_SUPPORTED = 1
const SOC_SIMD_INSTRUCTION_SUPPORTED = 1
const SOC_XTAL_SUPPORT_40M = 1
const SOC_ADC_RTC_CTRL_SUPPORTED = 1
const SOC_ADC_DIG_CTRL_SUPPORTED = 1
const SOC_ADC_ARBITER_SUPPORTED = 1
const SOC_ADC_DIG_IIR_FILTER_SUPPORTED = 1
const SOC_ADC_MONITOR_SUPPORTED = 1
const SOC_ADC_DMA_SUPPORTED = 1
const SOC_ADC_SAMPLE_FREQ_THRES_HIGH = 83333
const SOC_ADC_SAMPLE_FREQ_THRES_LOW = 611
const SOC_ADC_SHARED_POWER = 1
const SOC_BROWNOUT_RESET_SUPPORTED = 1
const SOC_CACHE_WRITEBACK_SUPPORTED = 1
const SOC_CACHE_FREEZE_SUPPORTED = 1
const SOC_CPU_CORES_NUM = 2
const SOC_CPU_INTR_NUM = 32
const SOC_CPU_HAS_FPU = 1
const SOC_HP_CPU_HAS_MULTIPLE_CORES = 1
const SOC_CPU_BREAKPOINTS_NUM = 2
const SOC_CPU_WATCHPOINTS_NUM = 2
const SOC_CPU_WATCHPOINT_MAX_REGION_SIZE = 64
const SOC_SIMD_PREFERRED_DATA_ALIGNMENT = 16
const SOC_GDMA_PAIRS_PER_GROUP = 5
const SOC_GDMA_PAIRS_PER_GROUP_MAX = 5
const SOC_AHB_GDMA_SUPPORT_PSRAM = 1
const SOC_GPIO_PIN_COUNT = 49
const SOC_GPIO_SUPPORT_PIN_GLITCH_FILTER = 1
const SOC_GPIO_FILTER_CLK_SUPPORT_APB = 1
const SOC_GPIO_IN_RANGE_MAX = 48
const SOC_GPIO_OUT_RANGE_MAX = 48
const SOC_MPU_CONFIGURABLE_REGIONS_SUPPORTED = 0
const SOC_MPU_REGIONS_MAX_NUM = 8
const SOC_MPU_REGION_RO_SUPPORTED = 0
const SOC_MPU_REGION_WO_SUPPORTED = 0
const SOC_RMT_TX_CANDIDATES_PER_GROUP = 4
const SOC_RMT_RX_CANDIDATES_PER_GROUP = 4
const SOC_RMT_CHANNELS_PER_GROUP = 8
const SOC_RMT_MEM_WORDS_PER_CHANNEL = 48
const SOC_RMT_SUPPORT_RX_PINGPONG = 1
const SOC_RMT_SUPPORT_RX_DEMODULATION = 1
const SOC_RMT_SUPPORT_TX_ASYNC_STOP = 1
const SOC_RMT_SUPPORT_TX_LOOP_COUNT = 1
const SOC_RMT_SUPPORT_TX_LOOP_AUTO_STOP = 1
const SOC_RMT_SUPPORT_TX_SYNCHRO = 1
const SOC_RMT_SUPPORT_TX_CARRIER_DATA_ONLY = 1
const SOC_RMT_SUPPORT_XTAL = 1
const SOC_RMT_SUPPORT_RC_FAST = 1
const SOC_RMT_SUPPORT_APB = 1
const SOC_RMT_SUPPORT_DMA = 1
const SOC_RTCIO_PIN_COUNT = 22
const SOC_RTCIO_INPUT_OUTPUT_SUPPORTED = 1
const SOC_RTCIO_HOLD_SUPPORTED = 1
const SOC_RTCIO_WAKE_SUPPORTED = 1
const SOC_LP_IO_CLOCK_IS_INDEPENDENT = 1
const SOC_SDM_GROUPS = 1
const SOC_SDM_CHANNELS_PER_GROUP = 8
const SOC_SDM_CLK_SUPPORT_APB = 1
const SOC_SPI_PERIPH_NUM = 3
const SOC_SPI_MAX_CS_NUM = 6
const SOC_SPI_MAXIMUM_BUFFER_SIZE = 64
const SOC_SPI_SUPPORT_DDRCLK = 1
const SOC_SPI_SLAVE_SUPPORT_SEG_TRANS = 1
const SOC_SPI_SUPPORT_CD_SIG = 1
const SOC_SPI_SUPPORT_CONTINUOUS_TRANS = 1
const SOC_SPI_SUPPORT_SLAVE_HD_VER2 = 1
const SOC_SPI_SUPPORT_CLK_APB = 1
const SOC_SPI_SUPPORT_CLK_XTAL = 1
const SOC_SPI_PERIPH_SUPPORT_CONTROL_DUMMY_OUT = 1
const SOC_MEMSPI_IS_INDEPENDENT = 1
const SOC_SPI_MAX_PRE_DIVIDER = 16
const SOC_SPI_SUPPORT_OCT = 1
const SOC_SPI_SCT_SUPPORTED = 1
const SOC_SPI_SCT_REG_NUM = 14
const SOC_SPI_SCT_CONF_BITLEN_MAX = 0x3FFFA
const SOC_MEMSPI_SRC_FREQ_120M = 1
const SOC_MEMSPI_SRC_FREQ_80M_SUPPORTED = 1
const SOC_MEMSPI_SRC_FREQ_40M_SUPPORTED = 1
const SOC_MEMSPI_SRC_FREQ_20M_SUPPORTED = 1
const SOC_SPIRAM_SUPPORTED = 1
const SOC_SPIRAM_XIP_SUPPORTED = 1
const SOC_SYSTIMER_COUNTER_NUM = 2
const SOC_SYSTIMER_ALARM_NUM = 3
const SOC_SYSTIMER_BIT_WIDTH_LO = 32
const SOC_SYSTIMER_BIT_WIDTH_HI = 20
const SOC_SYSTIMER_FIXED_DIVIDER = 1
const SOC_SYSTIMER_INT_LEVEL = 1
const SOC_SYSTIMER_ALARM_MISS_COMPENSATE = 1
const SOC_LP_TIMER_BIT_WIDTH_LO = 32
const SOC_LP_TIMER_BIT_WIDTH_HI = 16
const SOC_TWAI_CLK_SUPPORT_APB = 1
const SOC_TWAI_BRP_MIN = 2
const SOC_TWAI_BRP_MAX = 16384
const SOC_TWAI_SUPPORTS_RX_STATUS = 1
const SOC_EFUSE_DIS_DOWNLOAD_ICACHE = 1
const SOC_EFUSE_DIS_DOWNLOAD_DCACHE = 1
const SOC_EFUSE_HARD_DIS_JTAG = 1
const SOC_EFUSE_DIS_USB_JTAG = 1
const SOC_EFUSE_SOFT_DIS_JTAG = 1
const SOC_EFUSE_DIS_DIRECT_BOOT = 1
const SOC_EFUSE_DIS_ICACHE = 1
const SOC_EFUSE_BLOCK9_KEY_PURPOSE_QUIRK = 1
const SOC_SECURE_BOOT_V2_RSA = 1
const SOC_EFUSE_SECURE_BOOT_KEY_DIGESTS = 3
const SOC_EFUSE_REVOKE_BOOT_KEY_DIGESTS = 1
const SOC_SUPPORT_SECURE_BOOT_REVOKE_KEY = 1
const SOC_FLASH_ENCRYPTION_XTS_AES = 1
const SOC_FLASH_ENCRYPTION_XTS_AES_OPTIONS = 1
const SOC_FLASH_ENCRYPTION_XTS_AES_128 = 1
const SOC_FLASH_ENCRYPTION_XTS_AES_256 = 1
const SOC_MEMPROT_CPU_PREFETCH_PAD_SIZE = 16
const SOC_MEMPROT_MEM_ALIGN_SIZE = 256
const SOC_SDMMC_USE_GPIO_MATRIX = 1
const SOC_SDMMC_NUM_SLOTS = 2
const SOC_SDMMC_SUPPORT_XTAL_CLOCK = 1
const SOC_SDMMC_DELAY_PHASE_NUM = 4
const BIT31 = 0x80000000
const BIT30 = 0x40000000
const BIT29 = 0x20000000
const BIT28 = 0x10000000
const BIT27 = 0x08000000
const BIT26 = 0x04000000
const BIT25 = 0x02000000
const BIT24 = 0x01000000
const BIT23 = 0x00800000
const BIT22 = 0x00400000
const BIT21 = 0x00200000
const BIT20 = 0x00100000
const BIT19 = 0x00080000
const BIT18 = 0x00040000
const BIT17 = 0x00020000
const BIT16 = 0x00010000
const BIT15 = 0x00008000
const BIT14 = 0x00004000
const BIT13 = 0x00002000
const BIT12 = 0x00001000
const BIT11 = 0x00000800
const BIT10 = 0x00000400
const BIT9 = 0x00000200
const BIT8 = 0x00000100
const BIT7 = 0x00000080
const BIT6 = 0x00000040
const BIT5 = 0x00000020
const BIT4 = 0x00000010
const BIT3 = 0x00000008
const BIT2 = 0x00000004
const BIT1 = 0x00000002
const BIT0 = 0x00000001
const SOC_CLK_RC_FAST_FREQ_APPROX = 17500000
const SOC_CLK_RC_SLOW_FREQ_APPROX = 136000
const SOC_CLK_XTAL32K_FREQ_APPROX = 32768

type IntLeast8T c.Int8T
type IntLeast16T c.Int16T
type IntLeast32T c.Int32T
type IntLeast64T c.Int64T
type UintLeast8T c.Uint8T
type UintLeast16T c.Uint16T
type UintLeast32T c.Uint32T
type UintLeast64T c.Uint64T
type IntFast8T c.Int8T
type IntFast16T c.Int16T
type IntFast32T c.Int32T
type IntFast64T c.Int64T
type UintFast8T c.Uint8T
type UintFast16T c.Uint16T
type UintFast32T c.Uint32T
type UintFast64T c.Uint64T
type X__int8T c.Char
type X__uint8T c.Char
type X__int16T int16
type X__uint16T uint16
type X__int32T c.Int
type X__uint32T c.Uint
type X__int64T c.LongLong
type X__uint64T c.UlongLong
type X__darwinIntptrT c.Long
type X__darwinNaturalT c.Uint
type X__darwinCtRuneT c.Int

type X__mbstateT struct {
	X__mbstate8 [128]c.Char
}
type X__darwinMbstateT X__mbstateT
type X__darwinPtrdiffT c.Long
type X__darwinSizeT c.Ulong
type X__darwinVaList c.Pointer
type X__darwinWcharT c.Int
type X__darwinRuneT X__darwinWcharT
type X__darwinWintT c.Int
type X__darwinClockT c.Ulong
type X__darwinSocklenT X__uint32T
type X__darwinSsizeT c.Long
type X__darwinTimeT c.Long
type X__darwinBlkcntT X__int64T
type X__darwinBlksizeT X__int32T
type X__darwinDevT X__int32T
type X__darwinFsblkcntT c.Uint
type X__darwinFsfilcntT c.Uint
type X__darwinGidT X__uint32T
type X__darwinIdT X__uint32T
type X__darwinIno64T X__uint64T
type X__darwinInoT X__darwinIno64T
type X__darwinMachPortNameT X__darwinNaturalT
type X__darwinMachPortT X__darwinMachPortNameT
type X__darwinModeT X__uint16T
type X__darwinOffT X__int64T
type X__darwinPidT X__int32T
type X__darwinSigsetT X__uint32T
type X__darwinSusecondsT X__int32T
type X__darwinUidT X__uint32T
type X__darwinUsecondsT X__uint32T
type X__darwinUuidT [16]c.Char
type X__darwinUuidStringT [37]c.Char

type X__darwinPthreadHandlerRec struct {
	X__routine c.Pointer
	X__arg     c.Pointer
	X__next    *X__darwinPthreadHandlerRec
}

type X_opaquePthreadAttrT struct {
	X__sig    c.Long
	X__opaque [56]c.Char
}

type X_opaquePthreadCondT struct {
	X__sig    c.Long
	X__opaque [40]c.Char
}

type X_opaquePthreadCondattrT struct {
	X__sig    c.Long
	X__opaque [8]c.Char
}

type X_opaquePthreadMutexT struct {
	X__sig    c.Long
	X__opaque [56]c.Char
}

type X_opaquePthreadMutexattrT struct {
	X__sig    c.Long
	X__opaque [8]c.Char
}

type X_opaquePthreadOnceT struct {
	X__sig    c.Long
	X__opaque [8]c.Char
}

type X_opaquePthreadRwlockT struct {
	X__sig    c.Long
	X__opaque [192]c.Char
}

type X_opaquePthreadRwlockattrT struct {
	X__sig    c.Long
	X__opaque [16]c.Char
}

type X_opaquePthreadT struct {
	X__sig          c.Long
	X__cleanupStack *X__darwinPthreadHandlerRec
	X__opaque       [8176]c.Char
}
type X__darwinPthreadAttrT X_opaquePthreadAttrT
type X__darwinPthreadCondT X_opaquePthreadCondT
type X__darwinPthreadCondattrT X_opaquePthreadCondattrT
type X__darwinPthreadKeyT c.Ulong
type X__darwinPthreadMutexT X_opaquePthreadMutexT
type X__darwinPthreadMutexattrT X_opaquePthreadMutexattrT
type X__darwinPthreadOnceT X_opaquePthreadOnceT
type X__darwinPthreadRwlockT X_opaquePthreadRwlockT
type X__darwinPthreadRwlockattrT X_opaquePthreadRwlockattrT
type X__darwinPthreadT *X_opaquePthreadT
type UInt8T c.Char
type UInt16T uint16
type UInt32T c.Uint
type UInt64T c.UlongLong
type RegisterT c.Int64T
type UserAddrT UInt64T
type UserSizeT UInt64T
type UserSsizeT c.Int64T
type UserLongT c.Int64T
type UserUlongT UInt64T
type UserTimeT c.Int64T
type UserOffT c.Int64T
type SyscallArgT UInt64T
type X__darwinNlItem c.Int
type X__darwinWctransT c.Int
type X__darwinWctypeT X__uint32T
type FposT X__darwinOffT

type X__sbuf struct {
	X_base *c.Char
	X_size c.Int
}

type X__sFILEX struct {
	Unused [8]uint8
}

type X__sFILE struct {
	X_p       *c.Char
	X_r       c.Int
	X_w       c.Int
	X_flags   int16
	X_file    int16
	X_bf      X__sbuf
	X_lbfsize c.Int
	X_cookie  c.Pointer
	X_close   c.Pointer
	X_read    c.Pointer
	X_seek    c.Pointer
	X_write   c.Pointer
	X_ub      X__sbuf
	X_extra   *X__sFILEX
	X_ur      c.Int
	X_ubuf    [3]c.Char
	X_nbuf    [1]c.Char
	X_lb      X__sbuf
	X_blksize c.Int
	X_offset  FposT
}
type OffT X__darwinOffT
type IdtypeT c.Int

const (
	P_ALL  IdtypeT = 0
	P_PID  IdtypeT = 1
	P_PGID IdtypeT = 2
)

type PidT X__darwinPidT
type IdT X__darwinIdT
type SigAtomicT c.Int

type X__darwinArmExceptionState struct {
	X__exception X__uint32T
	X__fsr       X__uint32T
	X__far       X__uint32T
}

type X__darwinArmExceptionState64 struct {
	X__far       X__uint64T
	X__esr       X__uint32T
	X__exception X__uint32T
}

type X__darwinArmThreadState struct {
	X__r    [13]X__uint32T
	X__sp   X__uint32T
	X__lr   X__uint32T
	X__pc   X__uint32T
	X__cpsr X__uint32T
}

type X__darwinArmThreadState64 struct {
	X__x    [29]X__uint64T
	X__fp   X__uint64T
	X__lr   X__uint64T
	X__sp   X__uint64T
	X__pc   X__uint64T
	X__cpsr X__uint32T
	X__pad  X__uint32T
}

type X__darwinArmVfpState struct {
	X__r     [64]X__uint32T
	X__fpscr X__uint32T
}

type X__darwinArmNeonState64 struct {
	X__v    [32]X__uint128T
	X__fpsr X__uint32T
	X__fpcr X__uint32T
}

type X__uint128T struct {
	Unused [8]uint8
}

type X__darwinArmNeonState struct {
	X__v    [16]X__uint128T
	X__fpsr X__uint32T
	X__fpcr X__uint32T
}

type X__armPageinState struct {
	X__pageinError c.Int
}

type X__armLegacyDebugState struct {
	X__bvr [16]X__uint32T
	X__bcr [16]X__uint32T
	X__wvr [16]X__uint32T
	X__wcr [16]X__uint32T
}

type X__darwinArmDebugState32 struct {
	X__bvr      [16]X__uint32T
	X__bcr      [16]X__uint32T
	X__wvr      [16]X__uint32T
	X__wcr      [16]X__uint32T
	X__mdscrEl1 X__uint64T
}

type X__darwinArmDebugState64 struct {
	X__bvr      [16]X__uint64T
	X__bcr      [16]X__uint64T
	X__wvr      [16]X__uint64T
	X__wcr      [16]X__uint64T
	X__mdscrEl1 X__uint64T
}

type X__darwinArmCpmuState64 struct {
	X__ctrs [16]X__uint64T
}

type X__darwinMcontext32 struct {
	X__es X__darwinArmExceptionState
	X__ss X__darwinArmThreadState
	X__fs X__darwinArmVfpState
}

type X__darwinMcontext64 struct {
	X__es X__darwinArmExceptionState64
	X__ss X__darwinArmThreadState64
	X__ns X__darwinArmNeonState64
}
type McontextT *X__darwinMcontext64
type PthreadAttrT X__darwinPthreadAttrT

type X__darwinSigaltstack struct {
	SsSp    c.Pointer
	SsSize  X__darwinSizeT
	SsFlags c.Int
}
type StackT X__darwinSigaltstack

type X__darwinUcontext struct {
	UcOnstack  c.Int
	UcSigmask  X__darwinSigsetT
	UcStack    X__darwinSigaltstack
	UcLink     *X__darwinUcontext
	UcMcsize   X__darwinSizeT
	UcMcontext *X__darwinMcontext64
}
type UcontextT X__darwinUcontext
type SigsetT X__darwinSigsetT
type UidT X__darwinUidT

type Sigval struct {
	SivalPtr c.Pointer
}

type Sigevent struct {
	SigevNotify           c.Int
	SigevSigno            c.Int
	SigevValue            Sigval
	SigevNotifyFunction   c.Pointer
	SigevNotifyAttributes *PthreadAttrT
}

type X__siginfo struct {
	SiSigno  c.Int
	SiErrno  c.Int
	SiCode   c.Int
	SiPid    PidT
	SiUid    UidT
	SiStatus c.Int
	SiAddr   c.Pointer
	SiValue  Sigval
	SiBand   c.Long
	X__pad   [7]c.Ulong
}
type SiginfoT X__siginfo

type X__sigactionU struct {
	X__saHandler c.Pointer
}

type X__sigaction struct {
	X__sigactionU X__sigactionU
	SaTramp       c.Pointer
	SaMask        SigsetT
	SaFlags       c.Int
}

type Sigaction struct {
	X__sigactionU X__sigactionU
	SaMask        SigsetT
	SaFlags       c.Int
}

// llgo:type C
type SigT func(c.Int)

type Sigvec struct {
	SvHandler c.Pointer
	SvMask    c.Int
	SvFlags   c.Int
}

type Sigstack struct {
	SsSp      *c.Char
	SsOnstack c.Int
}

type Timeval struct {
	TvSec  X__darwinTimeT
	TvUsec X__darwinSusecondsT
}
type RlimT X__uint64T

type Rusage struct {
	RuUtime    Timeval
	RuStime    Timeval
	RuMaxrss   c.Long
	RuIxrss    c.Long
	RuIdrss    c.Long
	RuIsrss    c.Long
	RuMinflt   c.Long
	RuMajflt   c.Long
	RuNswap    c.Long
	RuInblock  c.Long
	RuOublock  c.Long
	RuMsgsnd   c.Long
	RuMsgrcv   c.Long
	RuNsignals c.Long
	RuNvcsw    c.Long
	RuNivcsw   c.Long
}
type RusageInfoT c.Pointer

type RusageInfoV0 struct {
	RiUuid             [16]c.Uint8T
	RiUserTime         c.Uint64T
	RiSystemTime       c.Uint64T
	RiPkgIdleWkups     c.Uint64T
	RiInterruptWkups   c.Uint64T
	RiPageins          c.Uint64T
	RiWiredSize        c.Uint64T
	RiResidentSize     c.Uint64T
	RiPhysFootprint    c.Uint64T
	RiProcStartAbstime c.Uint64T
	RiProcExitAbstime  c.Uint64T
}

type RusageInfoV1 struct {
	RiUuid                [16]c.Uint8T
	RiUserTime            c.Uint64T
	RiSystemTime          c.Uint64T
	RiPkgIdleWkups        c.Uint64T
	RiInterruptWkups      c.Uint64T
	RiPageins             c.Uint64T
	RiWiredSize           c.Uint64T
	RiResidentSize        c.Uint64T
	RiPhysFootprint       c.Uint64T
	RiProcStartAbstime    c.Uint64T
	RiProcExitAbstime     c.Uint64T
	RiChildUserTime       c.Uint64T
	RiChildSystemTime     c.Uint64T
	RiChildPkgIdleWkups   c.Uint64T
	RiChildInterruptWkups c.Uint64T
	RiChildPageins        c.Uint64T
	RiChildElapsedAbstime c.Uint64T
}

type RusageInfoV2 struct {
	RiUuid                [16]c.Uint8T
	RiUserTime            c.Uint64T
	RiSystemTime          c.Uint64T
	RiPkgIdleWkups        c.Uint64T
	RiInterruptWkups      c.Uint64T
	RiPageins             c.Uint64T
	RiWiredSize           c.Uint64T
	RiResidentSize        c.Uint64T
	RiPhysFootprint       c.Uint64T
	RiProcStartAbstime    c.Uint64T
	RiProcExitAbstime     c.Uint64T
	RiChildUserTime       c.Uint64T
	RiChildSystemTime     c.Uint64T
	RiChildPkgIdleWkups   c.Uint64T
	RiChildInterruptWkups c.Uint64T
	RiChildPageins        c.Uint64T
	RiChildElapsedAbstime c.Uint64T
	RiDiskioBytesread     c.Uint64T
	RiDiskioByteswritten  c.Uint64T
}

type RusageInfoV3 struct {
	RiUuid                      [16]c.Uint8T
	RiUserTime                  c.Uint64T
	RiSystemTime                c.Uint64T
	RiPkgIdleWkups              c.Uint64T
	RiInterruptWkups            c.Uint64T
	RiPageins                   c.Uint64T
	RiWiredSize                 c.Uint64T
	RiResidentSize              c.Uint64T
	RiPhysFootprint             c.Uint64T
	RiProcStartAbstime          c.Uint64T
	RiProcExitAbstime           c.Uint64T
	RiChildUserTime             c.Uint64T
	RiChildSystemTime           c.Uint64T
	RiChildPkgIdleWkups         c.Uint64T
	RiChildInterruptWkups       c.Uint64T
	RiChildPageins              c.Uint64T
	RiChildElapsedAbstime       c.Uint64T
	RiDiskioBytesread           c.Uint64T
	RiDiskioByteswritten        c.Uint64T
	RiCpuTimeQosDefault         c.Uint64T
	RiCpuTimeQosMaintenance     c.Uint64T
	RiCpuTimeQosBackground      c.Uint64T
	RiCpuTimeQosUtility         c.Uint64T
	RiCpuTimeQosLegacy          c.Uint64T
	RiCpuTimeQosUserInitiated   c.Uint64T
	RiCpuTimeQosUserInteractive c.Uint64T
	RiBilledSystemTime          c.Uint64T
	RiServicedSystemTime        c.Uint64T
}

type RusageInfoV4 struct {
	RiUuid                      [16]c.Uint8T
	RiUserTime                  c.Uint64T
	RiSystemTime                c.Uint64T
	RiPkgIdleWkups              c.Uint64T
	RiInterruptWkups            c.Uint64T
	RiPageins                   c.Uint64T
	RiWiredSize                 c.Uint64T
	RiResidentSize              c.Uint64T
	RiPhysFootprint             c.Uint64T
	RiProcStartAbstime          c.Uint64T
	RiProcExitAbstime           c.Uint64T
	RiChildUserTime             c.Uint64T
	RiChildSystemTime           c.Uint64T
	RiChildPkgIdleWkups         c.Uint64T
	RiChildInterruptWkups       c.Uint64T
	RiChildPageins              c.Uint64T
	RiChildElapsedAbstime       c.Uint64T
	RiDiskioBytesread           c.Uint64T
	RiDiskioByteswritten        c.Uint64T
	RiCpuTimeQosDefault         c.Uint64T
	RiCpuTimeQosMaintenance     c.Uint64T
	RiCpuTimeQosBackground      c.Uint64T
	RiCpuTimeQosUtility         c.Uint64T
	RiCpuTimeQosLegacy          c.Uint64T
	RiCpuTimeQosUserInitiated   c.Uint64T
	RiCpuTimeQosUserInteractive c.Uint64T
	RiBilledSystemTime          c.Uint64T
	RiServicedSystemTime        c.Uint64T
	RiLogicalWrites             c.Uint64T
	RiLifetimeMaxPhysFootprint  c.Uint64T
	RiInstructions              c.Uint64T
	RiCycles                    c.Uint64T
	RiBilledEnergy              c.Uint64T
	RiServicedEnergy            c.Uint64T
	RiIntervalMaxPhysFootprint  c.Uint64T
	RiRunnableTime              c.Uint64T
}

type RusageInfoV5 struct {
	RiUuid                      [16]c.Uint8T
	RiUserTime                  c.Uint64T
	RiSystemTime                c.Uint64T
	RiPkgIdleWkups              c.Uint64T
	RiInterruptWkups            c.Uint64T
	RiPageins                   c.Uint64T
	RiWiredSize                 c.Uint64T
	RiResidentSize              c.Uint64T
	RiPhysFootprint             c.Uint64T
	RiProcStartAbstime          c.Uint64T
	RiProcExitAbstime           c.Uint64T
	RiChildUserTime             c.Uint64T
	RiChildSystemTime           c.Uint64T
	RiChildPkgIdleWkups         c.Uint64T
	RiChildInterruptWkups       c.Uint64T
	RiChildPageins              c.Uint64T
	RiChildElapsedAbstime       c.Uint64T
	RiDiskioBytesread           c.Uint64T
	RiDiskioByteswritten        c.Uint64T
	RiCpuTimeQosDefault         c.Uint64T
	RiCpuTimeQosMaintenance     c.Uint64T
	RiCpuTimeQosBackground      c.Uint64T
	RiCpuTimeQosUtility         c.Uint64T
	RiCpuTimeQosLegacy          c.Uint64T
	RiCpuTimeQosUserInitiated   c.Uint64T
	RiCpuTimeQosUserInteractive c.Uint64T
	RiBilledSystemTime          c.Uint64T
	RiServicedSystemTime        c.Uint64T
	RiLogicalWrites             c.Uint64T
	RiLifetimeMaxPhysFootprint  c.Uint64T
	RiInstructions              c.Uint64T
	RiCycles                    c.Uint64T
	RiBilledEnergy              c.Uint64T
	RiServicedEnergy            c.Uint64T
	RiIntervalMaxPhysFootprint  c.Uint64T
	RiRunnableTime              c.Uint64T
	RiFlags                     c.Uint64T
}

type RusageInfoV6 struct {
	RiUuid                      [16]c.Uint8T
	RiUserTime                  c.Uint64T
	RiSystemTime                c.Uint64T
	RiPkgIdleWkups              c.Uint64T
	RiInterruptWkups            c.Uint64T
	RiPageins                   c.Uint64T
	RiWiredSize                 c.Uint64T
	RiResidentSize              c.Uint64T
	RiPhysFootprint             c.Uint64T
	RiProcStartAbstime          c.Uint64T
	RiProcExitAbstime           c.Uint64T
	RiChildUserTime             c.Uint64T
	RiChildSystemTime           c.Uint64T
	RiChildPkgIdleWkups         c.Uint64T
	RiChildInterruptWkups       c.Uint64T
	RiChildPageins              c.Uint64T
	RiChildElapsedAbstime       c.Uint64T
	RiDiskioBytesread           c.Uint64T
	RiDiskioByteswritten        c.Uint64T
	RiCpuTimeQosDefault         c.Uint64T
	RiCpuTimeQosMaintenance     c.Uint64T
	RiCpuTimeQosBackground      c.Uint64T
	RiCpuTimeQosUtility         c.Uint64T
	RiCpuTimeQosLegacy          c.Uint64T
	RiCpuTimeQosUserInitiated   c.Uint64T
	RiCpuTimeQosUserInteractive c.Uint64T
	RiBilledSystemTime          c.Uint64T
	RiServicedSystemTime        c.Uint64T
	RiLogicalWrites             c.Uint64T
	RiLifetimeMaxPhysFootprint  c.Uint64T
	RiInstructions              c.Uint64T
	RiCycles                    c.Uint64T
	RiBilledEnergy              c.Uint64T
	RiServicedEnergy            c.Uint64T
	RiIntervalMaxPhysFootprint  c.Uint64T
	RiRunnableTime              c.Uint64T
	RiFlags                     c.Uint64T
	RiUserPtime                 c.Uint64T
	RiSystemPtime               c.Uint64T
	RiPinstructions             c.Uint64T
	RiPcycles                   c.Uint64T
	RiEnergyNj                  c.Uint64T
	RiPenergyNj                 c.Uint64T
	RiSecureTimeInSystem        c.Uint64T
	RiSecurePtimeInSystem       c.Uint64T
	RiReserved                  [12]c.Uint64T
}
type RusageInfoCurrent RusageInfoV6

type Rlimit struct {
	RlimCur RlimT
	RlimMax RlimT
}

type ProcRlimitControlWakeupmon struct {
	WmFlags c.Uint32T
	WmRate  c.Int32T
}

type X_OSUnalignedU16 struct {
	X__val c.Uint16T
}

type X_OSUnalignedU32 struct {
	X__val c.Uint32T
}

type X_OSUnalignedU64 struct {
	X__val c.Uint64T
}

type Wait struct {
	WT struct {
		WTermsig  c.Uint
		WCoredump c.Uint
		WRetcode  c.Uint
		WFiller   c.Uint
	}
}
type CtRuneT X__darwinCtRuneT
type RuneT X__darwinRuneT
type WcharT X__darwinWcharT

type DivT struct {
	Quot c.Int
	Rem  c.Int
}

type LdivT struct {
	Quot c.Long
	Rem  c.Long
}

type LldivT struct {
	Quot c.LongLong
	Rem  c.LongLong
}
type MallocTypeIdT c.UlongLong

type X_mallocZoneT struct {
	Unused [8]uint8
}
type MallocZoneT X_mallocZoneT
type DevT X__darwinDevT
type ModeT X__darwinModeT
type EspErrT c.Int

type EspEtmChannelT struct {
	Unused [8]uint8
}
type EspEtmChannelHandleT *EspEtmChannelT

type EspEtmEventT struct {
	Unused [8]uint8
}
type EspEtmEventHandleT *EspEtmEventT

type EspEtmTaskT struct {
	Unused [8]uint8
}
type EspEtmTaskHandleT *EspEtmTaskT

/**
 * @brief ETM channel configuration
 */

type EspEtmChannelConfigT struct {
	Flags EtmChanFlags
}

type EtmChanFlags struct {
	Unused [8]uint8
}

// llgo:type C
type IntrHandlerT func(c.Pointer)

type IntrHandleDataT struct {
	Unused [8]uint8
}
type IntrHandleT *IntrHandleDataT
type EspIntrCpuAffinityT c.Int

const (
	ESP_INTR_CPU_AFFINITY_AUTO EspIntrCpuAffinityT = 0
	ESP_INTR_CPU_AFFINITY_0    EspIntrCpuAffinityT = 1
	ESP_INTR_CPU_AFFINITY_1    EspIntrCpuAffinityT = 2
)

type GpioNumT c.Int

const (
	GPIO_NUM_NC  GpioNumT = -1
	GPIO_NUM_0   GpioNumT = 0
	GPIO_NUM_1   GpioNumT = 1
	GPIO_NUM_2   GpioNumT = 2
	GPIO_NUM_3   GpioNumT = 3
	GPIO_NUM_4   GpioNumT = 4
	GPIO_NUM_5   GpioNumT = 5
	GPIO_NUM_6   GpioNumT = 6
	GPIO_NUM_7   GpioNumT = 7
	GPIO_NUM_8   GpioNumT = 8
	GPIO_NUM_9   GpioNumT = 9
	GPIO_NUM_10  GpioNumT = 10
	GPIO_NUM_11  GpioNumT = 11
	GPIO_NUM_12  GpioNumT = 12
	GPIO_NUM_13  GpioNumT = 13
	GPIO_NUM_14  GpioNumT = 14
	GPIO_NUM_15  GpioNumT = 15
	GPIO_NUM_16  GpioNumT = 16
	GPIO_NUM_17  GpioNumT = 17
	GPIO_NUM_18  GpioNumT = 18
	GPIO_NUM_19  GpioNumT = 19
	GPIO_NUM_20  GpioNumT = 20
	GPIO_NUM_21  GpioNumT = 21
	GPIO_NUM_26  GpioNumT = 26
	GPIO_NUM_27  GpioNumT = 27
	GPIO_NUM_28  GpioNumT = 28
	GPIO_NUM_29  GpioNumT = 29
	GPIO_NUM_30  GpioNumT = 30
	GPIO_NUM_31  GpioNumT = 31
	GPIO_NUM_32  GpioNumT = 32
	GPIO_NUM_33  GpioNumT = 33
	GPIO_NUM_34  GpioNumT = 34
	GPIO_NUM_35  GpioNumT = 35
	GPIO_NUM_36  GpioNumT = 36
	GPIO_NUM_37  GpioNumT = 37
	GPIO_NUM_38  GpioNumT = 38
	GPIO_NUM_39  GpioNumT = 39
	GPIO_NUM_40  GpioNumT = 40
	GPIO_NUM_41  GpioNumT = 41
	GPIO_NUM_42  GpioNumT = 42
	GPIO_NUM_43  GpioNumT = 43
	GPIO_NUM_44  GpioNumT = 44
	GPIO_NUM_45  GpioNumT = 45
	GPIO_NUM_46  GpioNumT = 46
	GPIO_NUM_47  GpioNumT = 47
	GPIO_NUM_48  GpioNumT = 48
	GPIO_NUM_MAX GpioNumT = 49
)

type GpioPortT c.Int

const (
	GPIO_PORT_0   GpioPortT = 0
	GPIO_PORT_MAX GpioPortT = 1
)

type GpioIntTypeT c.Int

const (
	GPIO_INTR_DISABLE    GpioIntTypeT = 0
	GPIO_INTR_POSEDGE    GpioIntTypeT = 1
	GPIO_INTR_NEGEDGE    GpioIntTypeT = 2
	GPIO_INTR_ANYEDGE    GpioIntTypeT = 3
	GPIO_INTR_LOW_LEVEL  GpioIntTypeT = 4
	GPIO_INTR_HIGH_LEVEL GpioIntTypeT = 5
	GPIO_INTR_MAX        GpioIntTypeT = 6
)

type GpioModeT c.Int

const (
	GPIO_MODE_DISABLE         GpioModeT = 0
	GPIO_MODE_INPUT           GpioModeT = 1
	GPIO_MODE_OUTPUT          GpioModeT = 2
	GPIO_MODE_OUTPUT_OD       GpioModeT = 6
	GPIO_MODE_INPUT_OUTPUT_OD GpioModeT = 7
	GPIO_MODE_INPUT_OUTPUT    GpioModeT = 3
)

type GpioPullupT c.Int

const (
	GPIO_PULLUP_DISABLE GpioPullupT = 0
	GPIO_PULLUP_ENABLE  GpioPullupT = 1
)

type GpioPulldownT c.Int

const (
	GPIO_PULLDOWN_DISABLE GpioPulldownT = 0
	GPIO_PULLDOWN_ENABLE  GpioPulldownT = 1
)

type GpioPullModeT c.Int

const (
	GPIO_PULLUP_ONLY     GpioPullModeT = 0
	GPIO_PULLDOWN_ONLY   GpioPullModeT = 1
	GPIO_PULLUP_PULLDOWN GpioPullModeT = 2
	GPIO_FLOATING        GpioPullModeT = 3
)

type GpioDriveCapT c.Int

const (
	GPIO_DRIVE_CAP_0       GpioDriveCapT = 0
	GPIO_DRIVE_CAP_1       GpioDriveCapT = 1
	GPIO_DRIVE_CAP_2       GpioDriveCapT = 2
	GPIO_DRIVE_CAP_DEFAULT GpioDriveCapT = 2
	GPIO_DRIVE_CAP_3       GpioDriveCapT = 3
	GPIO_DRIVE_CAP_MAX     GpioDriveCapT = 4
)

type PtrdiffT c.Long
type RsizeT c.Ulong
type MaxAlignT c.Double
type RtcGpioModeT c.Int

const (
	RTC_GPIO_MODE_INPUT_ONLY      RtcGpioModeT = 0
	RTC_GPIO_MODE_OUTPUT_ONLY     RtcGpioModeT = 1
	RTC_GPIO_MODE_INPUT_OUTPUT    RtcGpioModeT = 2
	RTC_GPIO_MODE_DISABLED        RtcGpioModeT = 3
	RTC_GPIO_MODE_OUTPUT_OD       RtcGpioModeT = 4
	RTC_GPIO_MODE_INPUT_OUTPUT_OD RtcGpioModeT = 5
)

type SocRootClkT c.Int

const (
	SOC_ROOT_CLK_INT_RC_FAST SocRootClkT = 0
	SOC_ROOT_CLK_INT_RC_SLOW SocRootClkT = 1
	SOC_ROOT_CLK_EXT_XTAL    SocRootClkT = 2
	SOC_ROOT_CLK_EXT_XTAL32K SocRootClkT = 3
)

type SocCpuClkSrcT c.Int

const (
	SOC_CPU_CLK_SRC_XTAL    SocCpuClkSrcT = 0
	SOC_CPU_CLK_SRC_PLL     SocCpuClkSrcT = 1
	SOC_CPU_CLK_SRC_RC_FAST SocCpuClkSrcT = 2
	SOC_CPU_CLK_SRC_INVALID SocCpuClkSrcT = 3
)

type SocRtcSlowClkSrcT c.Int

const (
	SOC_RTC_SLOW_CLK_SRC_RC_SLOW      SocRtcSlowClkSrcT = 0
	SOC_RTC_SLOW_CLK_SRC_XTAL32K      SocRtcSlowClkSrcT = 1
	SOC_RTC_SLOW_CLK_SRC_RC_FAST_D256 SocRtcSlowClkSrcT = 2
	SOC_RTC_SLOW_CLK_SRC_INVALID      SocRtcSlowClkSrcT = 3
)

type SocRtcFastClkSrcT c.Int

const (
	SOC_RTC_FAST_CLK_SRC_XTAL_D2  SocRtcFastClkSrcT = 0
	SOC_RTC_FAST_CLK_SRC_XTAL_DIV SocRtcFastClkSrcT = 0
	SOC_RTC_FAST_CLK_SRC_RC_FAST  SocRtcFastClkSrcT = 1
	SOC_RTC_FAST_CLK_SRC_INVALID  SocRtcFastClkSrcT = 2
)

type SocXtalFreqT c.Int

const (
	SOC_XTAL_FREQ_32M SocXtalFreqT = 32
	SOC_XTAL_FREQ_40M SocXtalFreqT = 40
)

type SocModuleClkT c.Int

const (
	SOC_MOD_CLK_CPU          SocModuleClkT = 1
	SOC_MOD_CLK_RTC_FAST     SocModuleClkT = 2
	SOC_MOD_CLK_RTC_SLOW     SocModuleClkT = 3
	SOC_MOD_CLK_APB          SocModuleClkT = 4
	SOC_MOD_CLK_PLL_F80M     SocModuleClkT = 5
	SOC_MOD_CLK_PLL_F160M    SocModuleClkT = 6
	SOC_MOD_CLK_PLL_D2       SocModuleClkT = 7
	SOC_MOD_CLK_XTAL32K      SocModuleClkT = 8
	SOC_MOD_CLK_RC_FAST      SocModuleClkT = 9
	SOC_MOD_CLK_RC_FAST_D256 SocModuleClkT = 10
	SOC_MOD_CLK_XTAL         SocModuleClkT = 11
	SOC_MOD_CLK_TEMP_SENSOR  SocModuleClkT = 12
	SOC_MOD_CLK_INVALID      SocModuleClkT = 13
)

type SocPeriphSystimerClkSrcT c.Int

const (
	SYSTIMER_CLK_SRC_XTAL    SocPeriphSystimerClkSrcT = 11
	SYSTIMER_CLK_SRC_DEFAULT SocPeriphSystimerClkSrcT = 11
)

type SocPeriphGptimerClkSrcT c.Int

const (
	GPTIMER_CLK_SRC_APB     SocPeriphGptimerClkSrcT = 4
	GPTIMER_CLK_SRC_XTAL    SocPeriphGptimerClkSrcT = 11
	GPTIMER_CLK_SRC_DEFAULT SocPeriphGptimerClkSrcT = 4
)

type SocPeriphTgClkSrcLegacyT c.Int

const (
	TIMER_SRC_CLK_APB     SocPeriphTgClkSrcLegacyT = 4
	TIMER_SRC_CLK_XTAL    SocPeriphTgClkSrcLegacyT = 11
	TIMER_SRC_CLK_DEFAULT SocPeriphTgClkSrcLegacyT = 4
)

type SocPeriphLcdClkSrcT c.Int

const (
	LCD_CLK_SRC_PLL160M SocPeriphLcdClkSrcT = 6
	LCD_CLK_SRC_PLL240M SocPeriphLcdClkSrcT = 7
	LCD_CLK_SRC_XTAL    SocPeriphLcdClkSrcT = 11
	LCD_CLK_SRC_DEFAULT SocPeriphLcdClkSrcT = 6
)

type SocPeriphRmtClkSrcT c.Int

const (
	RMT_CLK_SRC_APB     SocPeriphRmtClkSrcT = 4
	RMT_CLK_SRC_RC_FAST SocPeriphRmtClkSrcT = 9
	RMT_CLK_SRC_XTAL    SocPeriphRmtClkSrcT = 11
	RMT_CLK_SRC_DEFAULT SocPeriphRmtClkSrcT = 4
)

type SocPeriphRmtClkSrcLegacyT c.Int

const (
	RMT_BASECLK_APB     SocPeriphRmtClkSrcLegacyT = 4
	RMT_BASECLK_XTAL    SocPeriphRmtClkSrcLegacyT = 11
	RMT_BASECLK_DEFAULT SocPeriphRmtClkSrcLegacyT = 4
)

type SocPeriphTemperatureSensorClkSrcT c.Int

const (
	TEMPERATURE_SENSOR_CLK_SRC_RC_FAST SocPeriphTemperatureSensorClkSrcT = 12
	TEMPERATURE_SENSOR_CLK_SRC_DEFAULT SocPeriphTemperatureSensorClkSrcT = 12
)

type SocPeriphUartClkSrcLegacyT c.Int

const (
	UART_SCLK_APB     SocPeriphUartClkSrcLegacyT = 4
	UART_SCLK_RTC     SocPeriphUartClkSrcLegacyT = 9
	UART_SCLK_XTAL    SocPeriphUartClkSrcLegacyT = 11
	UART_SCLK_DEFAULT SocPeriphUartClkSrcLegacyT = 4
)

type SocPeriphMcpwmTimerClkSrcT c.Int

const (
	MCPWM_TIMER_CLK_SRC_PLL160M SocPeriphMcpwmTimerClkSrcT = 6
	MCPWM_TIMER_CLK_SRC_DEFAULT SocPeriphMcpwmTimerClkSrcT = 6
)

type SocPeriphMcpwmCaptureClkSrcT c.Int

const (
	MCPWM_CAPTURE_CLK_SRC_APB     SocPeriphMcpwmCaptureClkSrcT = 4
	MCPWM_CAPTURE_CLK_SRC_DEFAULT SocPeriphMcpwmCaptureClkSrcT = 4
)

type SocPeriphMcpwmCarrierClkSrcT c.Int

const (
	MCPWM_CARRIER_CLK_SRC_PLL160M SocPeriphMcpwmCarrierClkSrcT = 6
	MCPWM_CARRIER_CLK_SRC_DEFAULT SocPeriphMcpwmCarrierClkSrcT = 6
)

type SocPeriphI2sClkSrcT c.Int

const (
	I2S_CLK_SRC_DEFAULT  SocPeriphI2sClkSrcT = 6
	I2S_CLK_SRC_PLL_160M SocPeriphI2sClkSrcT = 6
	I2S_CLK_SRC_XTAL     SocPeriphI2sClkSrcT = 11
	I2S_CLK_SRC_EXTERNAL SocPeriphI2sClkSrcT = -1
)

type SocPeriphI2cClkSrcT c.Int

const (
	I2C_CLK_SRC_XTAL    SocPeriphI2cClkSrcT = 11
	I2C_CLK_SRC_RC_FAST SocPeriphI2cClkSrcT = 9
	I2C_CLK_SRC_DEFAULT SocPeriphI2cClkSrcT = 11
)

type SocPeriphSpiClkSrcT c.Int

const (
	SPI_CLK_SRC_DEFAULT SocPeriphSpiClkSrcT = 4
	SPI_CLK_SRC_APB     SocPeriphSpiClkSrcT = 4
	SPI_CLK_SRC_XTAL    SocPeriphSpiClkSrcT = 11
)

type SocPeriphSdmClkSrcT c.Int

const (
	SDM_CLK_SRC_APB     SocPeriphSdmClkSrcT = 4
	SDM_CLK_SRC_DEFAULT SocPeriphSdmClkSrcT = 4
)

type SocPeriphGlitchFilterClkSrcT c.Int

const (
	GLITCH_FILTER_CLK_SRC_APB     SocPeriphGlitchFilterClkSrcT = 4
	GLITCH_FILTER_CLK_SRC_DEFAULT SocPeriphGlitchFilterClkSrcT = 4
)

type SocPeriphTwaiClkSrcT c.Int

const (
	TWAI_CLK_SRC_APB     SocPeriphTwaiClkSrcT = 4
	TWAI_CLK_SRC_DEFAULT SocPeriphTwaiClkSrcT = 4
)

type SocPeriphAdcDigiClkSrcT c.Int

const (
	ADC_DIGI_CLK_SRC_APB       SocPeriphAdcDigiClkSrcT = 4
	ADC_DIGI_CLK_SRC_PLL_F240M SocPeriphAdcDigiClkSrcT = 7
	ADC_DIGI_CLK_SRC_DEFAULT   SocPeriphAdcDigiClkSrcT = 4
)

type SocPeriphAdcRtcClkSrcT c.Int

const (
	ADC_RTC_CLK_SRC_RC_FAST SocPeriphAdcRtcClkSrcT = 9
	ADC_RTC_CLK_SRC_DEFAULT SocPeriphAdcRtcClkSrcT = 9
)

type SocPeriphMwdtClkSrcT c.Int

const (
	MWDT_CLK_SRC_APB     SocPeriphMwdtClkSrcT = 4
	MWDT_CLK_SRC_DEFAULT SocPeriphMwdtClkSrcT = 4
)

type SocPeriphLedcClkSrcLegacyT c.Int

const (
	LEDC_AUTO_CLK        SocPeriphLedcClkSrcLegacyT = 0
	LEDC_USE_APB_CLK     SocPeriphLedcClkSrcLegacyT = 4
	LEDC_USE_RC_FAST_CLK SocPeriphLedcClkSrcLegacyT = 9
	LEDC_USE_XTAL_CLK    SocPeriphLedcClkSrcLegacyT = 11
	LEDC_USE_RTC8M_CLK   SocPeriphLedcClkSrcLegacyT = 9
)

type SocPeriphSdmmcClkSrcT c.Int

const (
	SDMMC_CLK_SRC_DEFAULT SocPeriphSdmmcClkSrcT = 6
	SDMMC_CLK_SRC_PLL160M SocPeriphSdmmcClkSrcT = 6
	SDMMC_CLK_SRC_XTAL    SocPeriphSdmmcClkSrcT = 11
)

type SocClkoutSigIdT c.Int

const (
	CLKOUT_SIG_PLL      SocClkoutSigIdT = 1
	CLKOUT_SIG_RC_SLOW  SocClkoutSigIdT = 4
	CLKOUT_SIG_XTAL     SocClkoutSigIdT = 5
	CLKOUT_SIG_PLL_F80M SocClkoutSigIdT = 13
	CLKOUT_SIG_RC_FAST  SocClkoutSigIdT = 14
	CLKOUT_SIG_INVALID  SocClkoutSigIdT = 255
)

type GlitchFilterClockSourceT SocPeriphGlitchFilterClkSrcT

type MultiHeapInfo struct {
	Unused [8]uint8
}
type MultiHeapHandleT *MultiHeapInfo

/** @brief Structure to access heap metadata via multi_heap_get_info */

type MultiHeapInfoT struct {
	TotalFreeBytes      c.SizeT
	TotalAllocatedBytes c.SizeT
	LargestFreeBlock    c.SizeT
	MinimumFreeBytes    c.SizeT
	AllocatedBlocks     c.SizeT
	FreeBlocks          c.SizeT
	TotalBlocks         c.SizeT
}

// llgo:type C
type MultiHeapWalkerCbT func(c.Pointer, c.SizeT, c.Int, c.Pointer) bool

// llgo:type C
type EspAllocFailedHookT func(c.SizeT, c.Uint32T, *c.Char)

/**
 * @brief Structure used to store heap related data passed to
 * the walker callback function
 */

type WalkerHeapInfo struct {
	Start c.IntptrT
	End   c.IntptrT
}
type WalkerHeapIntoT WalkerHeapInfo

/**
 * @brief Structure used to store block related data passed to
 * the walker callback function
 */

type WalkerBlockInfo struct {
	Ptr  c.Pointer
	Size c.SizeT
	Used bool
}
type WalkerBlockInfoT WalkerBlockInfo

// llgo:type C
type HeapCapsWalkerCbT func(WalkerHeapIntoT, WalkerBlockInfoT, c.Pointer) bool
