package soc

import _ "unsafe"

const EFUSE_WRITE_OP_CODE = 0x5a5a
const EFUSE_READ_OP_CODE = 0x5aa5
const EFUSE_RD_CHIP_VER_PKG_ESP32D0WDQ6 = 0
const EFUSE_RD_CHIP_VER_PKG_ESP32D0WDQ5 = 1
const EFUSE_RD_CHIP_VER_PKG_ESP32D2WDQ5 = 2
const EFUSE_RD_CHIP_VER_PKG_ESP32PICOD2 = 4
const EFUSE_RD_CHIP_VER_PKG_ESP32U4WDH = 4
const EFUSE_RD_CHIP_VER_PKG_ESP32PICOD4 = 5
const EFUSE_RD_CHIP_VER_PKG_ESP32PICOV302 = 6
const EFUSE_RD_CHIP_VER_PKG_ESP32D0WDR2V3 = 7
const EFUSE_CODING_SCHEME_VAL_NONE = 0x0
const EFUSE_CODING_SCHEME_VAL_34 = 0x1
const EFUSE_CODING_SCHEME_VAL_REPEAT = 0x2
