package soc

import _ "unsafe"

const RTC_I2C_SCL_LOW_PERIOD = 0x1FFFFFF
const RTC_I2C_SCL_LOW_PERIOD_V = 0x1FFFFFF
const RTC_I2C_SCL_LOW_PERIOD_S = 0
const RTC_I2C_SCL_STATE = 0x7
const RTC_I2C_SCL_STATE_V = 0x7
const RTC_I2C_SCL_STATE_S = 28
const RTC_I2C_MAIN_STATE = 0x7
const RTC_I2C_MAIN_STATE_V = 0x7
const RTC_I2C_MAIN_STATE_S = 25
const RTC_I2C_TIMEOUT = 0xFFFFF
const RTC_I2C_TIMEOUT_V = 0xFFFFF
const RTC_I2C_TIMEOUT_S = 0
const RTC_I2C_SLAVE_ADDR = 0x7FFF
const RTC_I2C_SLAVE_ADDR_V = 0x7FFF
const RTC_I2C_SLAVE_ADDR_S = 0
const RTC_I2C_SDA_DUTY = 0xFFFFF
const RTC_I2C_SDA_DUTY_V = 0xFFFFF
const RTC_I2C_SDA_DUTY_S = 0
const RTC_I2C_SCL_HIGH_PERIOD = 0xFFFFF
const RTC_I2C_SCL_HIGH_PERIOD_V = 0xFFFFF
const RTC_I2C_SCL_HIGH_PERIOD_S = 0
const RTC_I2C_SCL_START_PERIOD = 0xFFFFF
const RTC_I2C_SCL_START_PERIOD_V = 0xFFFFF
const RTC_I2C_SCL_START_PERIOD_S = 0
const RTC_I2C_SCL_STOP_PERIOD = 0xFFFFF
const RTC_I2C_SCL_STOP_PERIOD_V = 0xFFFFF
const RTC_I2C_SCL_STOP_PERIOD_S = 0
const RTC_I2C_CMD_REG_COUNT = 16
const RTC_I2C_VAL = 0
const RTC_I2C_VAL_V = 0x3FFF
const RTC_I2C_VAL_S = 0
