package soc

import _ "unsafe"

const RTCIO_GPIO36_CHANNEL = 0
const RTCIO_CHANNEL_0_GPIO_NUM = 36
const RTCIO_GPIO37_CHANNEL = 1
const RTCIO_CHANNEL_1_GPIO_NUM = 37
const RTCIO_GPIO38_CHANNEL = 2
const RTCIO_CHANNEL_2_GPIO_NUM = 38
const RTCIO_GPIO39_CHANNEL = 3
const RTCIO_CHANNEL_3_GPIO_NUM = 39
const RTCIO_GPIO34_CHANNEL = 4
const RTCIO_CHANNEL_4_GPIO_NUM = 34
const RTCIO_GPIO35_CHANNEL = 5
const RTCIO_CHANNEL_5_GPIO_NUM = 35
const RTCIO_GPIO25_CHANNEL = 6
const RTCIO_CHANNEL_6_GPIO_NUM = 25
const RTCIO_GPIO26_CHANNEL = 7
const RTCIO_CHANNEL_7_GPIO_NUM = 26
const RTCIO_GPIO33_CHANNEL = 8
const RTCIO_CHANNEL_8_GPIO_NUM = 33
const RTCIO_GPIO32_CHANNEL = 9
const RTCIO_CHANNEL_9_GPIO_NUM = 32
const RTCIO_GPIO4_CHANNEL = 10
const RTCIO_CHANNEL_10_GPIO_NUM = 4
const RTCIO_GPIO0_CHANNEL = 11
const RTCIO_CHANNEL_11_GPIO_NUM = 0
const RTCIO_GPIO2_CHANNEL = 12
const RTCIO_CHANNEL_12_GPIO_NUM = 2
const RTCIO_GPIO15_CHANNEL = 13
const RTCIO_CHANNEL_13_GPIO_NUM = 15
const RTCIO_GPIO13_CHANNEL = 14
const RTCIO_CHANNEL_14_GPIO_NUM = 13
const RTCIO_GPIO12_CHANNEL = 15
const RTCIO_CHANNEL_15_GPIO_NUM = 12
const RTCIO_GPIO14_CHANNEL = 16
const RTCIO_CHANNEL_16_GPIO_NUM = 14
const RTCIO_GPIO27_CHANNEL = 17
const RTCIO_CHANNEL_17_GPIO_NUM = 27
