package soc

import _ "unsafe"

const SDIO_SLAVE_SLOT0_IOMUX_PIN_NUM_CLK = 6
const SDIO_SLAVE_SLOT0_IOMUX_PIN_NUM_CMD = 11
const SDIO_SLAVE_SLOT0_IOMUX_PIN_NUM_D0 = 7
const SDIO_SLAVE_SLOT0_IOMUX_PIN_NUM_D1 = 8
const SDIO_SLAVE_SLOT0_IOMUX_PIN_NUM_D2 = 9
const SDIO_SLAVE_SLOT0_IOMUX_PIN_NUM_D3 = 10
const SDIO_SLAVE_SLOT0_FUNC = 0
const SDIO_SLAVE_SLOT1_IOMUX_PIN_NUM_CLK = 14
const SDIO_SLAVE_SLOT1_IOMUX_PIN_NUM_CMD = 15
const SDIO_SLAVE_SLOT1_IOMUX_PIN_NUM_D0 = 2
const SDIO_SLAVE_SLOT1_IOMUX_PIN_NUM_D1 = 4
const SDIO_SLAVE_SLOT1_IOMUX_PIN_NUM_D2 = 12
const SDIO_SLAVE_SLOT1_IOMUX_PIN_NUM_D3 = 13
const SDIO_SLAVE_SLOT1_FUNC = 4
