package soc

import _ "unsafe"

const SDMMC_SLOT0_IOMUX_PIN_NUM_CLK = 6
const SDMMC_SLOT0_IOMUX_PIN_NUM_CMD = 11
const SDMMC_SLOT0_IOMUX_PIN_NUM_D0 = 7
const SDMMC_SLOT0_IOMUX_PIN_NUM_D1 = 8
const SDMMC_SLOT0_IOMUX_PIN_NUM_D2 = 9
const SDMMC_SLOT0_IOMUX_PIN_NUM_D3 = 10
const SDMMC_SLOT0_IOMUX_PIN_NUM_D4 = 16
const SDMMC_SLOT0_IOMUX_PIN_NUM_D5 = 17
const SDMMC_SLOT0_IOMUX_PIN_NUM_D6 = 5
const SDMMC_SLOT0_IOMUX_PIN_NUM_D7 = 18
const SDMMC_SLOT0_FUNC = 0
const SDMMC_SLOT1_IOMUX_PIN_NUM_CLK = 14
const SDMMC_SLOT1_IOMUX_PIN_NUM_CMD = 15
const SDMMC_SLOT1_IOMUX_PIN_NUM_D0 = 2
const SDMMC_SLOT1_IOMUX_PIN_NUM_D1 = 4
const SDMMC_SLOT1_IOMUX_PIN_NUM_D2 = 12
const SDMMC_SLOT1_IOMUX_PIN_NUM_D3 = 13
const SDMMC_SLOT1_FUNC = 4
