package soc

import _ "unsafe"

const MSPI_FUNC_NUM = 1
const MSPI_IOMUX_PIN_NUM_CLK = 6
const MSPI_IOMUX_PIN_NUM_MISO = 7
const MSPI_IOMUX_PIN_NUM_MOSI = 8
const MSPI_IOMUX_PIN_NUM_HD = 9
const MSPI_IOMUX_PIN_NUM_WP = 10
const MSPI_IOMUX_PIN_NUM_CS0 = 11
const SPI_D2WD_PIN_NUM_MISO = 17
const SPI_D2WD_PIN_NUM_MOSI = 8
const SPI_D2WD_PIN_NUM_CLK = 6
const SPI_D2WD_PIN_NUM_CS = 16
const SPI_D2WD_PIN_NUM_WP = 7
const SPI_D2WD_PIN_NUM_HD = 11
const HSPI_FUNC_NUM = 1
const HSPI_IOMUX_PIN_NUM_MISO = 12
const HSPI_IOMUX_PIN_NUM_MOSI = 13
const HSPI_IOMUX_PIN_NUM_CLK = 14
const HSPI_IOMUX_PIN_NUM_CS = 15
const HSPI_IOMUX_PIN_NUM_WP = 2
const HSPI_IOMUX_PIN_NUM_HD = 4
const VSPI_FUNC_NUM = 1
const VSPI_IOMUX_PIN_NUM_MISO = 19
const VSPI_IOMUX_PIN_NUM_MOSI = 23
const VSPI_IOMUX_PIN_NUM_CLK = 18
const VSPI_IOMUX_PIN_NUM_CS = 5
const VSPI_IOMUX_PIN_NUM_WP = 22
const VSPI_IOMUX_PIN_NUM_HD = 21
