package soc

import _ "unsafe"

const UART_NUM_0_TXD_DIRECT_GPIO_NUM = 1
const UART_NUM_0_RXD_DIRECT_GPIO_NUM = 3
const UART_NUM_0_CTS_DIRECT_GPIO_NUM = 19
const UART_NUM_0_RTS_DIRECT_GPIO_NUM = 22
const UART_NUM_1_TXD_DIRECT_GPIO_NUM = 10
const UART_NUM_1_RXD_DIRECT_GPIO_NUM = 9
const UART_NUM_1_CTS_DIRECT_GPIO_NUM = 6
const UART_NUM_1_RTS_DIRECT_GPIO_NUM = 11
const UART_NUM_2_TXD_DIRECT_GPIO_NUM = 17
const UART_NUM_2_RXD_DIRECT_GPIO_NUM = 16
const UART_NUM_2_CTS_DIRECT_GPIO_NUM = 8
const UART_NUM_2_RTS_DIRECT_GPIO_NUM = 7
