package riscv

import _ "unsafe"

const PANIC_RSN_CACHEERR = 3
const MCAUSE_ILLIGAL_INSTRUCTION_ACCESS = 1
const MCAUSE_ILLEGAL_INSTRUCTION = 2
const MCAUSE_LOAD_ACCESS_FAULT = 5
const MCAUSE_INVALID_VALUE = 0xDEADC0DE
